### ISSUE TITLE
Play Store Whitescreen

### ISSUE THREAD

**Issue by nift4** [microg/GmsCore#1001]
Play Store (data deleted) first shows a loading circle and after reopen only a white screen until data is deleted again. Then the loading circle is back until you reopen it. So Play Store is unusable. Many of my paid apps stopped working because Play Store does not verify the purchase.
### Logs

    01-02 18:28:10.747 D/GmsHttpFormClient(2678): androidId=3eeeab3d3b1dfad7&app=com.android.vending&client_sig=38918a453d07199354f8b19af05ec6562ced5788&callerPkg=com.google.android.gms&callerSig=38918a453d07199354f8b19af05ec6562ced5788&device_country=de&Email=--REMOVED--&google_play_services_version=19420000&is_called_from_account_manager=1&_opt_is_called_from_account_manager=1&lang=de_DE&operatorCountry=de&sdk_version=29&service=oauth2%3Ahttps%3A%2F%2Fwww.googleapis.com%2Fauth%2Fgoogleplay&source=android&system_partition=1&Token=aas_et%2FAKppINYtVn7xss3ds-B61DTJqBXydQ6r2RAw7PjDxb8X5DMpEASd-JRDoYVYiqyWnueyuK-GHN6vCEb0uG-LLUoX0KRDIyVFVpUZw5AC4bAVPoy4goKrC3HQIdtUiPd-RQ%3D%3D
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 
    01-02 18:28:00.199 W/GmsAuthenticator(2678): java.io.IOException: Error=BadAuthentication
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 	at org.microg.gms.common.HttpFormClient.request(Unknown Source:344)
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 	at org.microg.gms.auth.AuthRequest.getResponse(Unknown Source:4)
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 	at org.microg.gms.auth.AuthManager.requestAuth(Unknown Source:150)
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 	at org.microg.gms.auth.loginservice.AccountAuthenticator.getAuthToken(Unknown Source:73)
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 	at android.accounts.AbstractAccountAuthenticator$Transport.getAuthToken(AbstractAccountAuthenticator.java:246)
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 	at android.accounts.IAccountAuthenticator$Stub.onTransact(IAccountAuthenticator.java:282)
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
    01-02 18:28:00.199 W/GmsAuthenticator(2678): 	at android.os.Binder.execTransact(Binder.java:994)

### System Information
UNOFFICAL LineageOS 17 (not for microG) from [@Sohamlad7](https://github.com/Sohamlad7) = Android 10
EdXposed 0.4.6.0.4771 with FakeGapps
microG 0.2.10

**Comment by selurvedu** [comment]
@nift4 did you try using Aurora Store with your Google Account? You will probably be able to download the paid apps. Though the app may try to check if it was really bought on your Google Account via Google Play Services, and that would probably fail. I can't say that for sure because I never tried this.

**Comment by nift4** [comment]
I can download the paid apps via Aurora Store but they cannot verify they were paid. If they don't verify someone can simply copy APK and have it without paying.

**Comment by selurvedu** [comment]
@nift4 OK, thanks for confirming.
