### ISSUE TITLE
Grammar

### ISSUE THREAD

**Issue by GummybearCanada** [microg/GmsCore#1002]
a connection, not an connection
![Screenshot_20200106-091646_microG_Services_Core](https://user-images.githubusercontent.com/48004998/71907472-1cd7f280-313a-11ea-8c05-e8ae3ad294b2.png)

**Comment by ofskymohsen** [comment]
Please explain more clearly. Do you mean this window remains for a long time?

**Comment by Pdevo** [comment]
I think the reference here is about the "an connection" instead of "a connection" in the message
