### ISSUE TITLE
Moia crashes when searching for addresses

### ISSUE THREAD

**Issue by Nesaijn** [microg/GmsCore#1026]
The ridesharing app Moia loads the map fine and selecting waypoints by draging the cursor to a spot seems to work fine too. But when searching for the destination address it crashes. 
Here is the logcat:
[moia-logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/4320139/moia-logcat.txt)

Device: Xperia XA2
OS: LineageOS 16
microG: 0.2.10.19420

**Comment by chris42** [comment]
I could not reproduce this with the latest microg (0.2.14.204215).
Adding payments also works.

I think this can be closed
