### ISSUE TITLE
MicroG Doesn't Pass SafetyNet

### ISSUE THREAD

**Issue by ghost** [microg/GmsCore#1037]
Well I'm Using A Samsung Galaxy S5 (klte) With Latest Stable Resurrection Remix (Pie),
MicroG Doesn't Pass SafetyNet , Even With Everything In The Check-List Checked !
I Installed MicroG Using MicroG Revived In Magisk ,
I Cant Get A LogCat Because I Formated My Phone

**Comment by Ajcford** [comment]
https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24#issue-451837206

**Comment by HaytamFrh** [comment]
> [microg/android_packages_apps_RemoteDroidGuard#24 (comment)](https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24#issue-451837206)

I Will See

**Comment by HaytamFrh** [comment]
> [microg/android_packages_apps_RemoteDroidGuard#24 (comment)](https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24#issue-451837206)

That Means That From Now On , MicroG Will Not Pass SafetyNet ?

**Comment by p4t44** [comment]
yep

**Comment by HaytamFrh** [comment]
> yep

So that means microg is now useful for C2DM and location services and showing that u don't pass safetynet , if this is what now it useful for , answer me and let me close this issue ;)
I like this project , I hope they can fix this issue someday

**Comment by p4t44** [comment]
no, microG does a lot more then that https://github.com/microg/android_packages_apps_GmsCore/wiki/Implementation-Status

**Comment by HaytamFrh** [comment]
> no, microG does a lot more then that https://github.com/microg/android_packages_apps_GmsCore/wiki/Implementation-Status

Well , that is awesome , having a list of what microg does !

**Comment by HaytamFrh** [comment]
so is there a possible way of passing safetynet ? i tried faking my fingerprint but it didnt do anything

**Comment by flawedworld** [comment]
@ghost theres 3 ways right now that are feasible:

**Comment by flawedworld** [comment]
@ghost The entire safetynet API has changed around June last year, and it will need the RemoteDroidGuard app to be updated at the least. If you need safetynet badly then its pretty much impossible to use microg. Progress is non existent when it comes to fixing it as far as i know.

you would need to use stock os OR rom + gapps + magisk OR compile with verified boot working + locked bl + safetynet patch on kernel currently from what I know in order to pass, with the 3rd one being the most ideal IMHO. Until MicroG is updated then option 3 is the most user controllable and safest if you need safetynet.

**Comment by b4nt0** [comment]
@flawedworld is there a way to reimplement safetynet client side to form a good request to google services with spoofed bootloader info?

**Comment by ArchangeGabriel** [comment]
SafetyNet is already re-implemented client-side in microG, but the actual issue is the binary component DroidGuard, and that one is using crypto IIRC. With hardware attestation being required nowadays, this means breaking TEE, and that will likely not be done.

**Comment by b4nt0** [comment]
@ArchangeGabriel does this mean that TEE will not only sign the result, but also perform the actual scan of the bootloader by itself?

**Comment by ArchangeGabriel** [comment]
@b4nt0 I don’t think so, this should still be DroidGuard, but DroidGuard. What I’m not sure of is whether you could place yourself between DroidGuard and the TEE.

**Comment by ale5000-git** [comment]
microG now pass SafetyNet
