### ISSUE TITLE
Install core GMS packages to use play store

### ISSUE THREAD

**Issue by timea-techgirl** [microg/GmsCore#1038]
Hello,

I'm using a Huawei P9 Lite running Android 7.0 stock ROM.
MicroG reports a check mark for all items and everything is running fine but when I tap on play store, I get this message "Install core GMS packages to use Google Play Store"

MicroG is installed to system.

Please tell me how to fix this.

**Comment by timeakesmarky** [comment]
Found the cause of the bug.
This issue occurs if you delete "GoogleLoginService.apk" from /system/priv-app
I tried a placeholder file but it didn't work.

Conclusion:
MicroG needs the original GoogleLoginService.apk for the play store to work on Huawei devices running EMUI. 
Tested only on EMUI 5.0

Play store still logs in via MicroG sign in prompt but it needs the GoogleLoginService.apk to be present.

Hope this can be fixed.

**Comment by chris42** [comment]
You could also use [Aurora Store](https://f-droid.org/de/packages/com.aurora.store/). It is working without problems for regular purchases stuff in your google account. Only In-App purchases will have issues.

**Comment by timeakesmarky** [comment]
> You could also use [Aurora Store](https://f-droid.org/de/packages/com.aurora.store/). It is working without problems for regular purchases stuff in your google account. Only In-App purchases will have issues.

Can I install paid apps that are free for a few hours? Will it be in the list of my purchases in my google account?
And does this need permissions to my google account?

**Comment by chris42** [comment]
I can't tell if you can test the apps, haven't used that and don't know how that works. You can probably ask at [their gitlab](https://gitlab.com/AuroraOSS/AuroraStore).

Yes of course you will need access to your google account, how else would you access your paid apps?
If you do not have paid apps and just want to use the play store for free apps, you can use an anonymous account from aurora store.

**Comment by bolimarvin323-sys** [comment]
Yoooo
