### ISSUE TITLE
[Enhancement] Trigger signature spoofing permission request for FakeStore as well

### ISSUE THREAD

**Issue by SebiderSushi** [microg/GmsCore#1042]
Because FakeStore has an activity for requesting its own signature spoofing permission since 2016-11-16, it could be nice if GmsCore was able to detect the presence of `com.android.vending.GrantFakeSignaturePermissionActivity` and launch it along with its own request (e.g. when triggering it in the Self-check) or display an independent button to trigger it for FakeStore.

This would streamline the setup process and one would no longer have to go the long route via the system permission settings.

**Comment by HaytamFrh** [comment]
Yeah it gonna be awesome!
One click to grant SignatureSpoofing For Fakestore Would Be A Good Feature To Add To MicroG , Bud You Have An Open Most nd

**Comment by SebiderSushi** [comment]
This feature has been silently implemented at some point and is currently present in [GmsCore v0.2.24.214816](https://github.com/microg/GmsCore/releases/tag/v0.2.24.214816)

Thanks a lot!
