### ISSUE TITLE
Gmail not working and force closing

### ISSUE THREAD

**Issue by Pokemetti** [microg/GmsCore#1052]
Hello, I use microg with Nanodroid on LineageOS 16 with microg (from lineage.microg.org) as well as stock TouchWiz Marshmallow on my S5 mini. On both phones Gmail force closes as soon as I try to start the app and occasionally force closes in the background. Gmail worked just fine before but since a few weeks it's been like that. The Gmail app is totally unusable like that, but there aren't any alternative apps I know of. I tried clearing data, giving it all permissions, didn't work. It seems to be related to some update. I'll maybe try since which version it doesn't work.

**Comment by Pokemetti** [comment]
I think that the latest working release is 2020.03.29.306383213.release

**Comment by NolfNolfer** [comment]
I'm having this problem too.

It started after I tried to flash a new firmware and a rom update. I reverted back to the old firmware and restored the backup, but even after restoring an backup of the Gmail app it still kept crashing.

**Comment by NolfNolfer** [comment]
> I think that the latest working release is 2020.03.29.306383213.release

BTW, tried that, it doesn't work for me that version.

**Comment by breversa** [comment]
I found solutions to several of my problems here : https://gitlab.com/Nanolx/NanoDroid#issues
You may be lucky and find the solution to yours too. :-)

**Comment by Pokemetti** [comment]
Sadly, seems to not be addressed there

**Comment by Axolord** [comment]
Can confirm, does not work for me either.
As a workaround for now I would promote using another mail client like fairemail for example, although it would be great having gmail itself fixed.

microG version: 0.2.10.200475-dirty via Nanodroid
OS: Havoc 3.3 with Android 10
Devices: Redmi Note 5 Pro

**Comment by Techwolf** [comment]
I upgraded to Android 10 via a fresh install of Havoc-OS 3.7 onto a Motorola G7 power. After installing gmail, it was doing the same as this issue, about three very quick flashes of the small window of app crash/forced closed. Using Titanuium Backup, I install an old backup, both app+data. After opening gmail, close it out and looked at notices, grant account access permission to gmail. Re-opened gmail and it just worked without issue. Gmail version 2019.04.14.246198419

**Comment by Pokemetti** [comment]
Well, as I stated, even version 2020.03.29.306383213 works which is newer than what you mentioned, so that is to be expected.

**Comment by Mrnofish** [comment]
After starting the app, I get a flashing "GMail keeps stopping" dialog.

Lineage with MicroG 20201014
MicroG 0.2.13.203915, update downloaded manually from microg.org
Modded Play Store from Nanolx
GMail 2020.09.20.334426683

**Comment by ale5000-git** [comment]
There is a crash loop, happens here: https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/auth/AccountContentProvider.java#L85

Relevant log:
```
[ 11-25 22:02:42.140  3271: 3289 D/GmsAuthProvider ]
Call from com.google.android.gm

[ 11-25 22:02:42.141  4960: 4960 W/Gmail    ]
AccountUtils:For b/73513912, load account content://com.google.android.gm.sapi/account.-2137146394 from MailAppProvider. Is account valid result: 1.

[ 11-25 22:02:42.154  4960: 4960 W/Gmail    ]
AccountUtils:For b/73513912, load account content://com.google.android.gm.email.provider/account.-437561172?suppress_combined%3Dtrue from MailAppProvider. Is account valid result: 1.

[ 11-25 22:02:42.181  3271: 3289 E/DatabaseUtils ]
Writing exception to parcel
java.lang.UnsupportedOperationException: Unsupported method call get_accounts(com.google.android.gm.exchange).
	at org.microg.gms.auth.AccountContentProvider.call(AccountContentProvider.java:85)
	at android.content.ContentProvider$Transport.call(ContentProvider.java:400)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:283)
	at android.os.Binder.execTransact(Binder.java:565)


[ 11-25 22:02:42.183  2365: 2771 W/AccountManagerService ]
  caller uid 10212 cannot access com.google accounts

...

[ 11-25 22:02:42.378  4960: 5086 E/Auth     ]
[GoogleAuthUtil] GoogleAuthUtil

[ 11-25 22:02:42.388  4960: 5117 E/aaqg     ]
Exception inside job [OnAccountsUpdated].
android.os.RemoteException: Accounts ContentProvider failed: Unsupported method call get_accounts(com.google.android.gm.exchange).
	at qvd.i(PG:12)
	at aatf.a(PG:2)
	at aaqc.c(PG)
	at aaqe.a(PG)
	at afov.a(Unknown Source)
	at bcps.a(PG:2)
	at bgsn.e(PG)
	at bgsp.run(PG:9)
	at bgue.execute(PG)
	at bgsl.r(PG:1)
	at bgsl.jz(PG:5)
	at bgsp.f(PG)
	at afoe.a(Unknown Source)
	at bcpq.a(PG:2)
	at bguj.a(PG:4)
	at bgwq.c(PG)
	at bgvq.run(PG:3)
	at bgws.run(PG)
	at bgum.run(PG:3)
	at bgue.execute(PG)
	at bgum.execute(PG:6)
	at bgsl.r(PG:1)
	at bgsl.n(PG:8)
	at bgsl.l(PG:2)
	at bguk.run(PG:2)
	at bgue.execute(PG)
	at bgsl.r(PG:1)
	at bgsl.jz(PG:5)
	at bguo.b(PG:10)
	at afoo.b(PG:1)
	at afot.a(Unknown Source)
	at bcps.a(PG:2)
	at bgsn.e(PG)
	at bgsp.run(PG:9)
	at bgue.execute(PG)
	at bgsl.r(PG:1)
	at bgsl.jz(PG:5)
	at bgsp.f(PG)
	at afpb.c(PG:9)
	at afpb.d(PG)
	at aaqf.a(PG:6)
	at aaqf.c(PG)
	at blrr.a(PG:2)
	at bliz.a(PG)
	at aaqg.g(PG)
	at aaqg.f(PG)
	at aaqg.h(PG)
	at aapn.a(PG:3)
	at blfs.e(PG:2)
	at blkt.run(PG:6)
	at bbrh.run(PG:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at bbpq.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:761)
```

**Comment by dimaryaz** [comment]
Haha, I have a fix that's so stupid I can't believe it actually worked:

```
--- a/play-services-core/src/main/java/org/microg/gms/auth/AccountContentProvider.java
+++ b/play-services-core/src/main/java/org/microg/gms/auth/AccountContentProvider.java
@@ -65,7 +65,7 @@ public class AccountContentProvider extends ContentProvider {
             if (getContext().checkCallingPermission(Manifest.permission.GET_ACCOUNTS) != PackageManager.PERMISSION_GRANTED)
                 throw new SecurityException("Access denied, missing GET_ACCOUNTS or EXTENDED_ACCESS permission");
         }
-        if (PROVIDER_METHOD_GET_ACCOUNTS.equals(method) && AuthConstants.DEFAULT_ACCOUNT_TYPE.equals(arg)) {
+        if (PROVIDER_METHOD_GET_ACCOUNTS.equals(method)) {
             Bundle result = new Bundle();
             AccountManager am = AccountManager.get(getContext());
             Account[] accounts = null;
```

Will send out a PR - hopefully, it's not actually breaking anything else.

**Comment by ale5000-git** [comment]
@mar-v-in: Is it possible to just log the error and return null or an empty Bundle in the case of unsupported operation?
I think it is better to have an app half working rathen then a crashing app (in this case loop crashing since the gmail sync will happen continuosly).
