### ISSUE TITLE
Safetynet API error

### ISSUE THREAD

**Issue by Persie11** [microg/GmsCore#1075]
I got LOS4MicroG v16 installed. I have in the MicroG settings Safetynet enabled. But everytime I check it says Safetynet API Error in Magisk.
I also installed Nanodroid manually but when I check with Magisk DroidGuard Helper apps crashes always.

**Comment by chris42** [comment]
Duplicate to https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24

**Comment by varistov** [comment]
Safetynet will always be broken even if you use custom ROM with relocked bootloader, not relevant to microG, it's google changed to safetynet API. use stock ROM with locked bootloader if you rely on apps that use safetynet API
https://www.nitter.net/topjohnwu/status/1278849731305672705

**Comment by ale5000-git** [comment]
microG now pass SafetyNet.
