### ISSUE TITLE
Permissions not requested

### ISSUE THREAD

**Issue by ploink** [microg/GmsCore#1100]
First, thank you very much for latest release! (v0.2.11.202414)
Even though I collected all the checkmarks in self-check, gmscore is still missing permissions ACCESS_FINE_LOCATION and READ_EXTERNAL_STORAGE. It does not request them.

One can check for ungranted permissions with:
`$  dumpsys package com.google.android.gms | grep granted=false`

For now I have granted the permissions manually:
`$ pm grant com.google.android.gms android.permission.ACCESS_FINE_LOCATION`
`$ pm grant com.google.android.gms android.permission.READ_EXTERNAL_STORAGE`

**Comment by patrickdrd** [comment]
I think I've got a similar problem,
location permission isn't granted and:

problems with google maps, after opening the app,
my location isn't detected

(I'm running google maps version 10.19.2 because of the message about google play services that needed to be updated..)

please @mar-v-in check and fix

**Comment by D3SOX** [comment]
For me background location is not working and granting doesn't work either. Using NanoDroid-22.9.20200910
![Screenshot_20201015-094640](https://user-images.githubusercontent.com/24937357/96092597-61fc3280-0ecb-11eb-881a-d0d3d8f0d56d.jpg)
![Screenshot_20201015-094621](https://user-images.githubusercontent.com/24937357/96092621-6a546d80-0ecb-11eb-80fa-b07b7053328e.jpg)

**Comment by ploink** [comment]
@D3SOX I noticed you have permission flag APPLY_RESTRICTION set to the background location permission. My phone does not have that:
`android.permission.ACCESS_BACKGROUND_LOCATION: granted=true, flags=[ SYSTEM_FIXED|GRANTED_BY_DEFAULT|USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED|RESTRICTION_INSTALLER_EXEMPT|RESTRICTION_SYSTEM_EXEMPT|RESTRICTION_UPGRADE_EXEMPT]`
Maybe your rom has some additional security features or you have some security app installed that causes this. Open app info for gmscore and see if you can change background location permissions there. 
You can also try deleting data for gmscore, that will wipe all permissions for the app so you can try assign them again.

**Comment by mar-v-in** [comment]
`ACCESS_BACKGROUND_LOCATION` is a hard restricted permission, which means that the decision if you can enable it is done by the app installing it (or if the app is part of the system image, the system decides this). Thus, this maybe is an issue of NanoDroid? @Nanolx

**Comment by drrossum** [comment]
* on Friday, 2020-10-16 09:41 +0000, Marvin W <notifications@github.com> wrote:

> `ACCESS_BACKGROUND_LOCATION` is a hard restricted permission, which means that the decision if you can enable it is done by the app installing it (or if the app is part of the system image, the system decides this). Thus, this maybe is an issue of NanoDroid? @Nanolx

Going through the list of requested permissions I see that there are two permissions not currently granted on my system:

ACCESS_BACKGROUND_LOCATION
ACCESS_COARSE_UPDATES

I guess these are both hard restricted permissions?

**Comment by D3SOX** [comment]
@ploink 

<details><summary>I already tried changing the permission from there but it has no option for it</summary>
<p>

![Screenshot_20201016-130118](https://user-images.githubusercontent.com/24937357/96251508-e1affd00-0fb0-11eb-84b4-a52e9da9e457.jpg)

</p>
</details>


<details><summary>When I tap on location settings it just takes me there</summary>
<p>

![Screenshot_20201016-131024](https://user-images.githubusercontent.com/24937357/96251595-fd1b0800-0fb0-11eb-92f7-19d7819de1b3.jpg)

</p>
</details>


The ROM is Paranoid Android, self compiled with [signature spoofing patch](https://github.com/microg/android_packages_apps_GmsCore/blob/master/patches/android_frameworks_base-P.patch)
(patch worked but I had to adjust the paths) and without Gapps

Deleting data didn't change anything

**Comment by Nanolx** [comment]
@mar-v-in likely. I've observed that installing NanoDroid directly into /system seems to always work, but depending on the ROM installing as Magisk may fail in this regard.

A temporary fix is to install uG as user app

`pm install -r /data/adb/modules/NanoDroid/system/priv-app/GmsCore/GmsCore.apk`

(or `NanoDroid_microG` instead of `NanoDroid`, depending on the module installed).

I'll investigate further, but may take a few days.

**Comment by Nanolx** [comment]
Yes, it's just like that. Installing NanoDroid into /system before booting the ROM the first time (just as one does with GApps) solves that issue. It also properly auto-grants all permissions to GmsCore (except `android.permission.FAKE_PACKAGE_SIGNATURE`), which is desireable, though.

Most A/B or S-A-R devices require /data to be clean when starting the first time (observed this on OnePlus 5T and OnePlus 6), thus installing NanoDroid as Magisk Module is always "dirty flashed". For one reason or another Android does deny `android.permission.ACCESS_BACKGROUND_LOCATION` even though it is properly privapp-whitelisted. Also all other should-be auto-granted permission need to be manually granted, as opposed to /system mode installation.

On older devices where you can flash ROM and Magisk in one go and sucessfully boot up, this does not happen. As mentioned before

`pm install -r /data/adb/modules/NanoDroid/system/priv-app/GmsCore/GmsCore.apk`

fixes the issue for Magisk Installations aswell.

I observed this on both Android 10 (AICP 15) and Android 11 (Syberia 4.1). Tomorrow I'll update the Magisk Modules's `service.sh` in order to silently auto-"userify" GmsCore, to workaround the issue.

Since no Magisk GApps package exists (until now I never thought about why that's the case) and given that privapps should be available right from the very first start, I suspect that behaviour is actually on purpose, so that proposed change to `service.sh` is likely the ultimate best I could come up with.

Unless someone can point me into a different direction.

**Comment by ploink** [comment]
@Nanolx 
>Unless someone can point me into a different direction.

One thing left to try is requesting the permission on behalf of the gmscore userId, similar to #1102 

On my phone the permission is granted, but when I try to revoke the permission as root, I get:
```
# pm revoke com.google.android.gms android.permission.ACCESS_BACKGROUND_LOCATION                                      
Security exception: Non-System UID cannot revoke system fixed permission android.permission.ACCESS_BACKGROUND_LOCATION for package com.google.android.gms
```

But using the app's system user id works:
```
#dumpsys package com.google.android.gms | grep userId=                                          
    userId=10174
    userId=10174
#pm revoke --user 10174 com.google.android.gms android.permission.ACCESS_BACKGROUND_LOCATION
```

So if you grant it with the "--user" option it might work too?

The permission on my phone:
```
      android.permission.ACCESS_BACKGROUND_LOCATION: restricted=true
        android.permission.ACCESS_BACKGROUND_LOCATION: granted=true, flags=[ 
SYSTEM_FIXED
|GRANTED_BY_DEFAULT
|USER_SENSITIVE_WHEN_GRANTED
|USER_SENSITIVE_WHEN_DENIED
|RESTRICTION_INSTALLER_EXEMPT
|RESTRICTION_SYSTEM_EXEMPT
|RESTRICTION_UPGRADE_EXEMPT]
```

I suppose different roms have different permission flags, the "RESTRICTION_SYSTEM_EXEMPT" makes it work with the "--user" option and "RESTRICTION_UPGRADE_EXEMPT" allows granting the permission on upgrading the apk. 

@D3SOX None of the exempt flags are set in your case, so I doubt any of these two methods work for you? Considering you rom is _Paranoid_ Android, this may be by design.

**Comment by Nanolx** [comment]
@ploink I've modified the `nanodroid-perm` script to do so.

For reference: https://gitlab.com/Nanolx/NanoDroid/-/commit/0437a12adf71a28b370fe0d3a92b92609ef1c038

**Comment by GitGangGuy** [comment]
Hi, I can't grant some permissions either (They also have `APPLY_RESTRICTION` activated):
```
android.permission.RECEIVE_SMS: granted=false, flags=[ USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED|APPLY_RESTRICTION]
android.permission.ACCESS_BACKGROUND_LOCATION: granted=false, flags=[ USER_SENSITIVE_WHEN_GRANTED|USER_SENSITIVE_WHEN_DENIED|APPLY_RESTRICTION]
```
I'm running ProtonAOSP (with Android 11) on a Pixel 5 using Magisk and the [microG installer revived](https://github.com/Magisk-Modules-Repo/microG_installer) module. 
I see that some workarounds for Nanodroid have been included, but what about other installation methods? How can I grant those permissions? Will I have to do a factory reset/wipe data?

**Comment by Nanolx** [comment]
The fix is to install microG not just as a priv-app, but also as a user-app, i. e. an update.

a) go to /data/adb/modules/microG_blabla/system/priv-app/GmsCore/GmsCore.apk and tap on the APK to install it as update
b) remove any runtime-permissions.xml from /data/users/*/
c) reboot
d) grant all permissions again

profit.

**Comment by xdevs23** [comment]
@Nanolx That's a very important step to take. I had GmsCore installed in priv-app but not as an user app and was facing the same issue. Now, being a priv-app and a user app it works.

I'll be looking into how to get location to work properly as apps don't seem to be able to get any location even though I have 3 network-based geolocation modules installed (do I need to also install address lookup modules?).

I'm using Android 11 (halogenOS)

**Comment by bugsyb** [comment]
@Nanolx  - thanks for details. Unfortunately even if did the steps, after reboot and re-opening MicroG - it shows all permissions in place and checking UI "Self-check" shows all checked (originally did check the last two remaining - Location in background and SMS access earlier, straight after installing User-level app following other steps).
runtime-permissions.xml has been removed afterwards, reboot, checked that all is still in place as allowed.

Waze still shows "Connecting to network" and nothing shows on map.

What to do now? Need to re-install MicroG or something?


> The fix is to install microG not just as a priv-app, but also as a user-app, i. e. an update.
> 
> a) go to /data/adb/modules/microG_blabla/system/priv-app/GmsCore/GmsCore.apk and tap on the APK to install it as update
> b) remove any runtime-permissions.xml from /data/users/*/
> c) reboot
> d) grant all permissions again
> 
> profit.

**Comment by bugsyb** [comment]
Reinstalled Waze, on launch got question about location access with only two options:
- when running
- deny

Nothing to select in background.

After accepting the only positive option of when running ap, got message "microG DroidGuard Helper keeps stopping".

Am on Android 10 (Unihertz Jelly 2).

**Comment by xdevs23** [comment]
Coming back to the location issue, I have been told (and observed) that simply waiting for a while (like 1-2 days) will help get location working. For me, now it works perfectly fine.
I have multiple location modules installed, although I don't know the exact usefulness of every single one of them.

Network-based geolocation modules:
- Déjà Vu Location Service
- GSM Location Service
- Mozilla Location Service
- Radiocells.org Unified Network Location Provider Backend
- WiFi Location Service

Address lookup modules:
- Nominatim

All of these are obtainable through F-Droid.

**Comment by bugsyb** [comment]
Found a workaround by logging in to old Waze account with email via _notifications_ and then all worked all of the sudden. Miserably it is gmail account :-O :-( 

Second observation is that at the time when problem persists, no search for places works well, first page of results shows up, but not extended where "Google, FourSquare" and others are.

Also additional observation is that there was no Terms & Conditions shown as normally is. Some something around some Google Services is going on or other sort of registration.

**Comment by ploink** [comment]
> I have multiple location modules installed, although I don't know the exact usefulness of every single one of them.
> 
> Network-based geolocation modules:
> 
> * Déjà Vu Location Service
> * GSM Location Service
> * Mozilla Location Service
> * Radiocells.org Unified Network Location Provider Backend
> * WiFi Location Service

Some of those may be outdated and I am not sure if they interfere with each other. I suggest you start with only one that is known to work before you try others, for example the [GSM Location Service fork from devee](https://f-droid.org/en/packages/org.fitchfamily.android.gsmlocation/). He continued the [original work from n76](https://github.com/n76/Local-GSM-Backend) and included some of the code from [my fork](https://github.com/ploink/Local-GSM-Backend/releases) to make it work with Android 10 and 4G/5G. Remember to go into the backend config and download the appropriate database for your region.

Nominatim is good, keep that.

**Comment by xdevs23** [comment]
@ploink thanks for your suggestion!

> [...] I suggest you start with only one that is known to work before you try others [...]

From my understanding, they do different things in different ways allowing combined location (WiFi, radio, etc.)

I will start disabling one after the other, seeing if they worsen location accuracy or speed.

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version so I close it for now.
Open a new issue if needed.
