### ISSUE TITLE
GmsMapMarker:showInfoWindow - Map markers not clickable

### ISSUE THREAD

**Issue by dicer** [microg/GmsCore#1149]
The app com.hcceg.veg.compassionfree shows markers on the map (icon upper right corner of the main screen). These markers should be clickable and show an info widget with the name of a restaurant and a link to the details.
On GmsCore 0.2.11.202414 the markers are not clickable and I get this Debug in the log:

08-25 11:38:24.665 10915 10915 D GmsMapMarker: unimplemented Method: showInfoWindow

**Comment by tiliaceae** [comment]
The application ch.publibike.app also does not show info popups when touching the map markers. The logcat shows 

12-04 13:46:53.740  2376  2376 D GmsMapMarker: unimplemented Method: showInfoWindow

**Comment by dh4** [comment]
Just adding another app to this. Same issue with com.samchristiansen.ioverlander.droid. Cannot click on the map markers. It makes the app difficult to use as that's a main feature of the app.

Logcat is the same:
```
2022-10-20 13:34:36.657 5780-5780/com.samchristiansen.ioverlander.droid D/GmsMapMarker: unimplemented Method: showInfoWindow
```

**Comment by fynngodau** [comment]
Info windows in maps are implemented since 0.2.28 / 0.2.29. Please check your favorite apps again with the latest version :)

**Comment by dicer** [comment]
Works for me in the mentioned app! Can be closed if others confirm as 
well

**Comment by ale5000-git** [comment]
The problem should be already fixed, if someone encounter it again with the latest version, then please open a new ticket.
