### ISSUE TITLE
Location from network provider problem

### ISSUE THREAD

**Issue by dogs-1985** [microg/GmsCore#1150]
I found that [LineageOS](https://build.lolinet.com/file/lineage/ginkgo/lineage-17.1-20200817-EXPERIMENTAL-ginkgo.zip) will not automatic change Dark Theme or Night Light based on Schedule (Turn on from sunset to sunrise). And I searched online, this requires fused location.

I installed the app [SatStat](https://www.f-droid.org/en/packages/com.vonglasow.michael.satstat/), which shows that I only have a red pin (GPS) and no blue pin (Network).

Sometime i will see the location access icon (AppleNlp/MozillaNlp/LocalGsmNLP/DejaVu) is running on status bar.

Installed:
MicroG 0.2.11, also put inside **/system/pri-app/**
Self-Check all tick, except **Play Store (Phonesky) installed**.
I have try either AppleNlp, MozillaNlp, LocalGsmNLP, DejaVu, and set location access to **Allowed All the time**

Not installed:
Open Gapps

My GPS is working, but I hope that AGPS can operate.
Can anyone solve my problem?

**Comment by ljl-covid** [comment]
@dogs-1985 this seems to be longstanding confusion, but A-GPS is *not* network location. I don't really know about this feature, but what it requires is most likely network location, not A-GPS, which is a range of features in a GNSS (or specifically GPS) receiver allowing it to get additional information to acquire a fix faster, whereas network location is a *different* source of (coarser than GPS) location that can work when GPS, and consequently A-GPS, is off.

**Comment by ArchangeGabriel** [comment]
> Self-Check all tick, except Play Store (Phonesky) installed.

That’s going to be an issue.

**Comment by dogs-1985** [comment]
> > Self-Check all tick, except Play Store (Phonesky) installed.
> 
> That’s going to be an issue.

Is that really need to install FakeStore to solve the problem? Because I thought is not related thing, so I didn't install the app.

I only install **GmsCore**, **GSF**, **DroidGuard**.

**Comment by dogs-1985** [comment]
> @dogs-1985 this seems to be longstanding confusion, but A-GPS is _not_ network location. I don't really know about this feature, but what it requires is most likely network location, not A-GPS, which is a range of features in a GNSS (or specifically GPS) receiver allowing it to get additional information to acquire a fix faster, whereas network location is a _different_ source of (coarser than GPS) location that can work when GPS, and consequently A-GPS, is off.

I really learn a lot of knowledge, thank you for your correction.

**Comment by ArchangeGabriel** [comment]
> Is that really need to install FakeStore to solve the problem? Because I thought is not related thing, so I didn't install the app.
>
> I only install GmsCore, GSF, DroidGuard.

Yes, it is required for μG to work properly. GSF and DroidGuard are not on the other hand.

**Comment by dogs-1985** [comment]
> > Is that really need to install FakeStore to solve the problem? Because I thought is not related thing, so I didn't install the app.
> > I only install GmsCore, GSF, DroidGuard.
> 
> Yes, it is required for μG to work properly. GSF and DroidGuard are not on the other hand.

Just now i try to installed **FakeStore**, and also put inside **/system/pri-app**, I still cannot see blue pin in [SatStat](https://www.f-droid.org/en/packages/com.vonglasow.michael.satstat/).
Currently I installed **LocalGsmNLP**, **DejaVu** in my phone. Self-Check **ALL** tick.

I have another question, can i install multiple nlp backend runs together? Will it cause a lot of battery?

**Comment by 2faraway2** [comment]
I do have the same issue on LOS4MicroG 17.1 for lavender ..
Unified NLP sees no network location (wifi or cell tower) .. tested with dejavu, mozilla, gsmlocation and wifi  NLP provider
I suppose it's an issue with the new 17.1 build-pipeline ?

**Comment by dogs-1985** [comment]
> I do have the same issue on LOS4MicroG 17.1 for lavender ..
> Unified NLP sees no network location (wifi or cell tower) .. tested with dejavu, mozilla, gsmlocation and wifi NLP provider
> I suppose it's an issue with the new 17.1 build-pipeline ?

I'm also feel helpless and don't know how to solve the problem.
I feel that these problems may come from Lineage itself, or it may be a problem with this latest version (0.2.11) of MicroG.
I don't remember clearly. When I used the Lineage GSI version and the old version (0.2.10) of MicroG before, I really saw that Network Location can operate.

**Comment by 2faraway2** [comment]
Well, the new version works perfectly on other devices with other roms, even with 17.1 roms.
Imho most likely it's an issue with LOS4MicroG 17.1 itself ...

**Comment by dogs-1985** [comment]
> Well, the new version works perfectly on other devices with other roms, even with 17.1 roms.
> Imho most likely it's an issue with LOS4MicroG 17.1 itself ...

I didn't use these kins of LOS4MicroG, I installed from FDroid MicroG.
I don't know if it's related to overlay problem (Like parameters fused location need to enable).

This is my another [post](https://github.com/erfanoabdi/android_device_xiaomi_ginkgo/issues/1).

**Comment by 2faraway2** [comment]
Which device do you use ? ginkgo ?
The reason why I ask is because @erfanoabdi is also the maintainer of LOS for lavender, which is the base for LOS4MicroG which I'm using ...  
OT: Who did you manage to get MicroG working without using a rom, that supports signature spoofing ? Or is signature spoofing in your mentioned 'experimental' LOS build already integrated ?

**Comment by dogs-1985** [comment]
> Which device do you use ? ginkgo ?
> The reason why I ask is because @erfanoabdi is also the maintainer of LOS for lavender, which is the base for LOS4MicroG which I'm using ...
> OT: How did you manage to get MicroG working without using a rom that supports signature spoofing ?
> Or is signature spoofing in your mentioned 'experimental' LOS build already integrated ?

Yes, Redmi Note 8 Ginkgo.
I execute this  [code](https://del.dog/hulycobanu.sh)  from my PC. I don't know who created this script, but its works for Signature Spoofing.

**Comment by Ratcav** [comment]
I am getting the same issue on the latest Lineage4microg for kuntao (Lenovo P2). Network location works perfectly after a reboot, but stops working after a while. I am also randomly seeing the location access icon (AppleNlp/MozillaNlp) running in the status bar.

**Comment by ale5000-git** [comment]
This should already be fixed, if you have other problems please open a new ticket.
