### ISSUE TITLE
Lidl Plus crashing

### ISSUE THREAD

**Issue by YigYag** [microg/GmsCore#1203]
Device: Xiaomi Mi A1
OS version: LineageOS 17.1 (Android 10)
microG version: 0.2.12.203315

Upon starting the app it asks you to select your Lidl store. Presumably this is meant to open a map where you can select the store but instead it results in a crash. Logcat file attached.

[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/5308763/logcat.txt)

**Comment by Romern** [comment]
App works for me, also your installation may be corrupt:
```
10-01 01:34:01.704 12226 12292 E dl.eci.lidlplu: Failed to open APK '/system/priv-app/GmsCore/GmsCore.apk' I/O error
10-01 01:34:01.704 12226 12292 E ResourcesManager: failed to add asset path /system/priv-app/GmsCore/GmsCore.apk
```
What does your self-check say?

**Comment by patrickdrd** [comment]
it crashes for me too, 
I didn't report it because I thought it was due to libraries missing etc,
anyway, thanks for reporting,
my self-check is absolutely fine

**Comment by YigYag** [comment]
@Romern I'm not sure why logcat gives those errors. Everything is checked in self-check (except background location but that seems to be a known issue). I receive push notifications and other apps that depend on Google Play Services work.

Anyway I installed mapsv1 through Magisk using the flashable zip provided in issue number 16 in the android_frameworks_mapsv1 repository and Lidl Plus is working fine now. I also did try the -vtm version. While it didn't crash the app it resulted in a blank map. I will leave this open but at least for now there is a workaround.

**Comment by patrickdrd** [comment]
I installed mapsv1 through Magisk using the flashable zip as well but it still doesn't work for me, I'll post logcat in a bit

**Comment by YigYag** [comment]
@patrickdrd I'm no expert but looking at your logcat it doesn't seem like the crash is related to missing maps API. Mine has clear references to **com.google.android.gms.maps**. In yours all errors seem to be **Error: java.io.FileNotFoundException** so I'd say it's unrelated to microG, but again, I'm no expert.

They also mention **LIDL I18N [PRO]** and l18n is internationalization (https://www.w3.org/International/questions/qa-i18n.en). Try changing system language to English and see if the app works. Or if you have (Ed)Xposed you can install the module called App Settings Reborn and change locale only for the Lidl App and see if it works with locale set to English.

I personally use microG without Google account so I use Aurora Store but I'm thinking maybe your Google Play Store could be using English locale so maybe the app doesn't pull the l18n files for your native language and then the app crashes because the Android OS is trying to load the app in your native language but the files are missing?

**Comment by drago333** [comment]
Works for me - I selected my Lidl store on the map without a crash.

**Comment by patrickdrd** [comment]
> Works for me - I selected my Lidl store on the map without a crash.

what map opened?
google maps? and what's your version please?

**Comment by drago333** [comment]
> what map opened? google maps?
The in-app map which is a google map that lets you select your store. No Google maps installed.
> and what's your version please?
You made me double check, I'm on v0.2.18.204714 (from 23 Feb). My setup is new so that's why it came as a surprise that I am not up to date. Guess I will report again with the latest version 
> also, what's your phone lang as @YigYag said?
Tested with both English UK and German locale.

**Comment by patrickdrd** [comment]
@drago333 0.2.22 was out a few days ago, did you update to it?
if so, could you post if the app is still working for you?

**Comment by drago333** [comment]
I confirm app behaves correctly on Android 11 "crdroid" with microG 0.2.22

Got through the whole setup activity (country, store, login promt) and toyed around with the main app activity. I can try log an account in if there's an issue with that.

Allowing/disallowing location access upon the initial map interaction didn't break it either – I tested both ways.

**Comment by drago333** [comment]
I've updated to Android 12 and the app still works. Can you guys please make sure that you have done the extra step in the [installation instructions](https://github.com/microg/GmsCore/wiki/Installation) for location support. I suspect that is the reason for your issues.

After you do it, reboot, redo the self-check in microG settings, reboot again. You might need to reset app data for lidl plus so make sure you back up any data you might lose, delete app data, and run it again.

**Comment by patrickdrd** [comment]
I checked again and it (finally) worked (I updated microg to 0.2.23 some days ago)

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version of microG so I close it for now.
Open a new issue if needed.
