### ISSUE TITLE
some mapbox apps are damn slow

### ISSUE THREAD

**Issue by 532910** [microg/GmsCore#1224]
While some apps using mapbox (club.rentmee.apps for example) works pretty fine, some other (youdrive.today, ru.urentbike.app) are so slow, so almost unusable. It's possible to book a car with youdrive, but it will take a long time and lots `Wait` answers for the `Youdrive isn't responding.` popup. There is nothing notable in logcat in my opinion. But I have an observation:
1. Rentmee has few cars.
2. In the spring, carshering was prohibited by government due to lockdown, so no cars were shown in Youdrive and it was fast at that time.
So looks like mapbox is slowed down by a large number of objects on it. But on another OP3t on the same Lineage  17.1 but with OpenGapps everything works fine.

**Comment by 532910** [comment]
Could anyone confirm this, or is this only affecting me?

**Comment by 532910** [comment]
Is any workaround here?

It's definitely depend on amount of objects (cars) shown on the map. If I chose few filters to show less than 200 cars it works fine. If I select all cars (more than 800) it freezes a lot.

**Comment by 532910** [comment]
```
# find /system /data -name "libmapbox-gl.so" -exec md5sum {} \;
4b0ce05c60f333d64d293c9690fefd43  /data/app/com.carshering-KYIzKvO-vFvq9KoZP52vqQ==/lib/arm64/libmapbox-gl.so
b2a47c2666a810e67e436f3ad13bd03a  /data/data/ru.urentbike.app/cache/.gmscore/lib/arm64-v8a/libmapbox-gl.so
f21abc0f473b93aca386d38f78a04299  /data/data/ru.belkacar.belkacar/lib-0/libmapbox-gl.so
b2a47c2666a810e67e436f3ad13bd03a  /data/data/youdrive.today/cache/.gmscore/lib/arm64-v8a/libmapbox-gl.so
b2a47c2666a810e67e436f3ad13bd03a  /data/media/0/Download/libmapbox-gl.so
```

Both `com.carshering` and `ru.belkacar.belkacar` that use own `libmapbox-gl.so` works fine. Both `youdrive.today` and `ru.urentbike.app` that use `libmapbox-gl.so` from GmsCore.apk (it extracted to downloads) works extremely slow.

**Comment by Bubu** [comment]
Maybe related to #969 ?

**Comment by 532910** [comment]
May be. BTW, I discovered that youdrive.today (carshering app) depends on number of cars shown on the map. It I filter out all cars (no cars are show on the map) the app is pretty fast, but if I choose all cars, the app is damn slow.

**Comment by Bubu** [comment]
That is consistent with the observations in #969. I've talked to marvin and added some thoughts to that issue.

**Comment by 532910** [comment]
This looks like a dup of #969
