### ISSUE TITLE
Corona Warn App is unable to find EXPOSURE_NOTIFICATION_API

### ISSUE THREAD

**Issue by ClundXIII** [microg/GmsCore#1242]
The German CWA fails to find the API provided by microG.

microG version: 0.2.13
CWA Version: 1.5.0
Fairphone 2 open OS

I am getting the error:
Nearby.EXPOSURE_NOTIFICATION_API is not available 

In the microG Settings I am told to open the App in order to activate the Exposure Notifications. Is this a hen-egg Problem I am experiencing here?

**Comment by chris42** [comment]
I installed that version combination just yesterday and normally you should get a popup that asks you to activate the exposure notification as soon as you open CWA the first time. Maybe it helps to reinstall and trigger that again?

**Comment by ClundXIII** [comment]
> I installed that version combination just yesterday and normally you should get a popup that asks you to activate the exposure notification as soon as you open CWA the first time. Maybe it helps to reinstall and trigger that again?

I tried reinstalling both CWA and microG. Nothing helped.

I have the exact same Problem for a few weeks now. I am using Fairphone Open OS. I read there were some problem with Bluetooth Chip not being compatible, but I think that should just mean more battery usage, right?

**Comment by ClundXIII** [comment]
>  normally you should get a popup that asks you to activate the exposure notification

That is my Problem. I am simply not getting this popup :(

**Comment by Dikay900** [comment]
Had the same problem. Solved it with the following steps.

- close / stop CWA
- disable GPS and bluetooth
- open CWA
- Activate exposure notification (you are getting asked to enable GPS and Bluetooth) 
- enable GPS and bluetooth
- Exposure notification is now active in CWA and microg

**Comment by ClundXIII** [comment]
Nope, no popup.

If I look into the Permission tab in my phone settings, I only see the "taking picture and videos" permission

**Comment by meisteredermeistereder-the-second** [comment]
I had a similar problem with 0.2.12 on LOS 17.1 (GSI on Fairphone 3) after I updated the Corona Warn App from 1.3.1 to 1.5. I had to go back to 1.3.1 (and loose all my stored contacts from the last few days).

**Comment by mar-v-in** [comment]
@ClundXIII 
Did you check that everything is fine according to microG Self-Check?

Fairphone 2 does not support BTLE Advertisements. This means you can't broadcast IDs to nearby devices or let others know that you've been diagnosed positively. However you can still use CWA to get notified if you've been in close contact with a positively diagnosed person.

**Comment by ClundXIII** [comment]
> Did you check that everything is fine according to microG Self-Check?
Yes, all the boxes are checked, except the 3 on top about signature spoofing/checking.

> Fairphone 2 does not support BTLE Advertisements. This means you can't broadcast IDs to nearby devices or let others know that you've been diagnosed positively. However you can still use CWA to get notified if you've been in close contact with a positively diagnosed person.
Yes, I read that somewhere in an issue. I was wondering if I could still broadcast with just heavy battery usage, but I guess no :(

**Comment by mar-v-in** [comment]
> except the 3 on top about signature spoofing/checking.

Well, they are required for microG to work.

> I was wondering if I could still broadcast with just heavy battery usage

No, BTLE and normal Bluetooth are largely different protocols that are not compatible with each other.

**Comment by ClundXIII** [comment]
> Well, they are required for microG to work.

Specifically for CWA? Because that is so far the only app where I had Problems with.

So the solution is to get a custom ROM?

**Comment by soberao** [comment]
> Had the same problem. Solved it with the following steps.
> 
>     * close / stop CWA
> 
>     * disable GPS and bluetooth
> 
>     * open CWA
> 
>     * Activate exposure notification (you are getting asked to enable GPS and Bluetooth)
> 
>     * enable GPS and bluetooth
> 
>     * Exposure notification is now active in CWA and microg

I can confirm that this solution works also for the Finnish official Covid-19 app. I had the same issue and now it is working after these steps.

**Comment by mar-v-in** [comment]
@ClundXIII 
> Specifically for CWA? Because that is so far the only app where I had Problems with.

Most features in microG require signature spoofing. Only a few apps can make use of push notifications and most apps will get network location without signature spoofing. But that's basically it.

> So the solution is to get a custom ROM?

There are multiple ways to patch existing ROMs for compatibility with microG. Easiest way probably is to use [Nanodroid](https://nanolx.org/nanolx/nanodroid) patcher.

**Comment by ClundXIII** [comment]
Okay, that explains why I had no Problems yet. I don't use push notifications.

> EDIT: Can you provide a screenshot of your Self-Check screen just to verify that this is really the issue?

Sure:
![grafik](https://user-images.githubusercontent.com/4571541/97090985-ae1c4500-1638-11eb-8705-c109864dd137.png)
![grafik](https://user-images.githubusercontent.com/4571541/97090989-b2e0f900-1638-11eb-8f4e-c419d9f8d668.png)

Also the Error message from CWA:
![grafik](https://user-images.githubusercontent.com/4571541/97091080-54684a80-1639-11eb-95f2-3fb9e568819b.png)

**Comment by mar-v-in** [comment]
@ClundXIII Alright. Yes, it's definitely the missing signature spoofing causing trouble here. SERVICE_INVALID is the play service client library indicating that the play services (and/or play store) installed is considered "invalid" because the signature does not match due to missing signature spoofing.

**Comment by ClundXIII** [comment]
Is there a way to patch the OS with nandroid with just Signature Spoofing? Because all the other features mentioned in the nandroid patcher are not really needed for the Fairphone open OS. I would like to stay as much vanilla as possible. (I already have root, the fdroid privileged extension and pretty much already minimal Android)

**Comment by mar-v-in** [comment]
Yes, the nanodroid-patcher package can do this, for details check https://gitlab.com/Nanolx/NanoDroid/-/blob/master/doc/microGsetup.md

**Comment by turion** [comment]
I believe I'm experiencing the same issue with a ShiftPhone 5me and Shift's Google-Free OS.

**Comment by f4814** [comment]
I am experiencing the same issue with signature spoofing enabled

**Comment by f4814** [comment]
Okay. I had to install FakeStore. Now it works.

**Comment by ClundXIII** [comment]
@mar-v-in 

I finally found some time and motivation to patch signature spoofing. I used tingle and everything works now!

Thank you very much :)
