### ISSUE TITLE
[Bird] Payment section does not open

### ISSUE THREAD

**Issue by purlupar** [microg/GmsCore#1255]
**Affected app**
Name: Bird
Package id: co.bird.android

**Describe the bug**
Payment section does not display.

**To Reproduce**
1. Tap "Payments" in the sidebar menu
2. Get a white screen

or:

1. After entering a scooter ID, tap "add PayPal" or "add Card".
2. Loading icon appears and stays animated with no effect.

**Expected behavior**
Payments section (input forms or a payment method option menu) should be displayed, I guess.

**System**
Android Version: 9
Custom ROM: lineage_cheeseburger-userdebug 9 (20201020)

**microG**
microG Core version: 0.2.13.203915
microG Self-Check results: All checked

**Comment by mar-v-in** [comment]
Is this still an issue with 0.2.14?

**Comment by purlupar** [comment]
No. It works now! Thank you!
