### ISSUE TITLE
G-suite accounts don't Login

### ISSUE THREAD

**Issue by gghhkm** [microg/GmsCore#1266]
**To Reproduce**
Try to login to G-suite accounts in YouTube or YouTube Vanced on a device using any form of MicroG.

**Expected behavior**
Login like normal

**Additional context**
Users of YTV have reported this issue https://github.com/YTVanced/Vanced/issues/115
This issue however is a upstream issue with MicroG according to KevinX8; one of the developers.

**Comment by SurycL** [comment]
I am also having this issue. My old gmail account works great, but I have my own domain for personal use and all my subscriptions and saved videos are in there, so I'm hoping that Youtube Vanced and microg can work with my account like all other apps I use do.

**Comment by niruhsa** [comment]
Having the same issue here: https://github.com/YTVanced/Vanced/issues/115

**Comment by pmcanseco** [comment]
Was this closed because it was fixed?

**Comment by ibilux** [comment]
Same problem here !
