### ISSUE TITLE
[New microG 0.2.13.203915] Several apps that ask to register for push notification crash at first startup if push notification is off

### ISSUE THREAD

**Issue by bege10** [microg/GmsCore#1276]
**Affected apps**
Name: DB Navigator, NABU Insektenwelt, NABU Vogelwelt and more
Package id: de.hafas.android.db, com.sunbirdimages.nabu_insects, com.sunbirdimages.nabu_birds

**Describe the bug**
After updating the system which contains the new microG version all apps that ask to register for push notification crashed. I don't use push notifications and thus have them disabled in microG settings. In the old version apps did not ask to register if push notifications where disabled in microG settings.

**To Reproduce**
1. Update LineageOS for microG
2. open apps that use push notification
3. The app crashes immediately (no app UI, just system popup that app has been stopped.)

**Workaround for most apps**
(DB Navigator and others)
1. activate push notifications in microG settings.
2. open app, it asks for registration
3. deny push registration
4. deactivate push notifications in microG settings
5. now apps don't ask nor crash any more at startup

This workaround does not work for  NABU Insektenwelt and NABU Vogelwelt 
They crash even if push notifications in microG settings is active
1. activate push notifications in microG settings
2. open app
3. immediate crash notification
4. leave the notification for a few seconds and you can see the app UI start behind the notification
5. tap anywhere on the screen and both the crash notification and the app UI vanish, so the app cannot be started.

**More testing**
I restored the system partition with the previous microG version and both apps work
Restored the new system and they crash again.
(Don't know for sure whether this is an issue with push notification or any other issue.)

**System**
Android Version: 9
Custom ROM: LineageOS for microG 16
Device: Samsung Galaxy S5 Plus (SM-G901F)

**microG**
microG Core version: [e.g. 0.2.13.203915]
microG Self-Check results: All ticked

**Comment by mar-v-in** [comment]
NABU apps crashing is unrelated to push notifications. The issue is fixed as of a83b677f469204b5b1714912cca2274917e6af6a.

I can't reproduce the DB Navigator issue. Can you provide a logcat?

**Comment by bege10** [comment]
Thank you for maintaining and fixing.
I will test DB Navigator on a fresh system and come back.

**Comment by ale5000-git** [comment]
@bege10: Have you retried with 0.2.15.204713?

**Comment by bege10** [comment]
I just updated my Samsung Galaxy S5 Plus (SM-G901F), LineageOS for microG 16 (Android 9), the microG version is 0.2.14.
I did not have the time yet to set up a fresh system.
In the updated system all apps that want to register are registered already, so I think the fact that they don't crash with push service deactivated doesn't say much. It may take a few weeks until I can setup a fresh system on this phone.

**Comment by ale5000-git** [comment]
You can take your time but be sure to use version 0.2.15 when you test it, trying with 0.2.14 isn't useful.

**Comment by bege10** [comment]
@ale5000-git Meanwhile I have installed /e/OS on my Samsung Galaxy S5 Plus (SM-G901F) and on my new Fairphone 3. /e/OS currently includes microG 0.2.17

If ask for registration is active apps don't register, if it is not active some apps register, some don't and I could not find out when they register and when not because the same app that has registered does not after new installation and vice versa.
Should this be considered here or at the /e/OS issue tracker?

**Comment by ale5000-git** [comment]
The integrated microG will always be old, you should always update manually before reporting.
Currently we are at v0.2.19.211515

If the problem is generic to microG should be reported here instead if it is specific to /e/ OS it should be reported at their bug tracker.

**Comment by bege10** [comment]
> 
> 
> The integrated microG will always be old, you should always update manually before reporting.
> Currently we are at v0.2.19.211515
> 
> If the problem is generic to microG should be reported here instead if it is specific to /e/ OS it should be reported at their bug tracker.
> A logcat will help.

I guess that the problem is a microG problem. But I cannot update microG through F-Droid because that version has a different signature from that that comes with /e/OS. Do you know whether I can use the apk download from github? And if so, how must it be installed on /e/OS?

> If you tried everything above and Cloud Messaging shows to be registered in microG, but no apps show up and the Push Notification Tester fails to register, try the following steps from this Reddit thread:
    disable both cloud messaging and Google device registration and reboot
    enable only Google device registration and reboot
    enable Cloud messaging and reboot

This does not work because after the first reboot Cloud Messaging is enabled again.

**Comment by bege10** [comment]
> 
> 
> The integrated microG will always be old, you should always update manually before reporting.
> Currently we are at v0.2.19.211515
> 
> If the problem is generic to microG should be reported here instead if it is specific to /e/ OS it should be reported at their bug tracker.
> A logcat will help.

This issue is now discussed in /e/ gitlab
https://gitlab.e.foundation/e/backlog/-/issues/3159
https://gitlab.e.foundation/e/backlog/-/issues/3165

Please, let me know whether to continue here or there.

**Comment by bege10** [comment]
Meanwhile it works with /e/OS. Thanks.

**Comment by ale5000-git** [comment]
@bege10: An issue that can cause problems with settings (possibly the cause of this issue) were fixed in v0.2.21.212158 (or later).

So I suggest to everyone that search for this issue to update microG (or wait ROM update if not possible).
