### ISSUE TITLE
Safetynet Invalid response

### ISSUE THREAD

**Issue by nerdunit** [microg/GmsCore#1277]
**Describe the bug**
SafetyNet will show the message "The response is invalid"

**To Reproduce**
Install an os without gapps (i.e. Lineage OS)
Apply SMALI patches (signature spoofing)
Install microg using nanodroid
Check Safetynet

**Expected behavior**
Safetynet should work

**System**
Android Version: 10
Custom ROM: LineageOS 17.1 (20201115)

**Comment by ale5000-git** [comment]
Latest microG GmsCore pass SafetyNet.
