### ISSUE TITLE
Sorry, there was a problem communicating with google servers when adding Google account

### ISSUE THREAD

**Issue by paulclou** [microg/GmsCore#1278]
After fresh install, when adding Google account to MicroG, authentication succeeds (with login notification sent to email), but fails to add account with the following message.
> Sorry, there was a problem communicating with google servers

**To Reproduce**
1. Fresh wipe
2. Open MicroG or Settings -> Accounts
3. Add Google account
4. Authenticate
5. Error

**Expected behavior**
Successfully add Google account to device

**System**
Device: Pixel 4 XL
Android Version: 10
Custom ROM: CalyxOS
MicroG version: 0.2.13.203915-5 (7786094)

**Comment by paulclou** [comment]
Workaround documented in this [issue](https://gitlab.com/CalyxOS/calyxos/-/issues/91) at Calyxos. One difference is the initial settings to disable device registration, cloud messaging, and safetynet didn't work, and needed to close and re-open the app to verify the settings are applied.

**Comment by AnshBhardwaj1** [comment]
I tried reinstalling with new version, that fixed the isseu
