### ISSUE TITLE
Standard and Vanced microg together on huawei devices.

### ISSUE THREAD

**Issue by michael1900** [microg/GmsCore#1279]
Last microg vanced version cannot be installed together this standard microg, but huawei users like me without google services need both mircog, standard and vanced. Ho w fix this?

**Comment by mar-v-in** [comment]
Vanced microG version is not needed for anything except the Vanced YouTube app which in itself can be replaced by open source software NewPipe which makes Vanced pretty much obsolete. Official microG works fine with normal YouTube app if you don't like NewPipe. So you have plenty of options to go without requiring Vanced. Vanced microG is in no way supported by microG developers.

Vanced breaking compatibility with official microG is an issue of Vanced. Vanced developers could just have merged the required parts of microG into the Vanced YouTube app, which would have made "Vanced microG" and the "Vanced installer" completely obsolete and would fix any compatibility issues.

**Comment by michael1900** [comment]
> Vanced microG version is not needed for anything except the Vanced YouTube app which in itself can be replaced by open source software NewPipe which makes Vanced pretty much obsolete. Official microG works fine with normal YouTube app if you don't like NewPipe. So you have plenty of options to go without requiring Vanced. Vanced microG is in no way supported by microG developers.
> 
> Vanced breaking compatibility with official microG is an issue of Vanced. Vanced developers could just have merged the required parts of microG into the Vanced YouTube app, which would have made "Vanced microG" and the "Vanced installer" completely obsolete and would fix any compatibility issues.

More or less Ok, but newpipe is not the same thing honestly, also for notifications btw i am starting to use it now.

But, when microg devs will solve this: https://github.com/microg/GmsCore/issues/1189

Because this "huawei signing fail" is the true problem for all of us with huawei devices w/o gms.

Thanks

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version (microG can now spoof another device) so I close it for now.
Open a new issue if needed.
