### ISSUE TITLE
Implement a way to backup and restore Exposure Notification keys

### ISSUE THREAD

**Issue by meisteredermeistereder-the-second** [microg/GmsCore#1287]
**Is your feature request related to a problem? Please describe.**
Changing the phone, changing the OS or maybe even upgrading to a major Android/LOS version leads to a loss if all the stored keys of Exposure Notification of the last two weeks as there is no backup/restore function.

**Describe the solution you'd like**
I would like to have an export/import (backup/restore) functionality, storing as a zip file or something else would be sufficient. That would be very helpful.

**Comment by chris42** [comment]
Duplicate to #1208 
Please use search before opening an issue.

**Comment by meisteredermeistereder-the-second** [comment]
You are absolutely right!
Problem seems to be me not switching language of screen keyboard which autocorrected "backup" to "Back APP" in the search. And then me not checking.
Anyway, you are right and sorry for the dupe!
