### ISSUE TITLE
FP3 November 12th update fails

### ISSUE THREAD

**Issue by Pratched** [microg/GmsCore#1289]
**Describe the bug**
I dont really know where else to report it and cannot find any other information. Everything worked quite fine when I migrated from the unofficial Lineage16 to the official version, except that It wiped the user data.
Anyway I reconfigured everything and used it mostly fine. Sometimes there are location issues but nothing serioues or longterm.
However the update from November 12th cannot be installed. Either it fails to install after downloading directly the update shows the same update after reboot again. I was able to reproduce the latter behaviour by clean installing with TWRP the .zip and upfront data wipe.

**To Reproduce**
1. Go to updater
2. Download
3. Install
4a. Installation fails -- Error
4.b Installation succeeds -- Reboot
5. Updater shows the update again.

**Expected behavior**
Plain simple updates.

**System**
Android Version:9
Custom ROM: LineageOS 16 for FP3

**Additional context**
Also it seems there isnt a newer version than the November build? 
I quite like microG and would love to continue using it.
If this is the wrong place to share this issue and you know better, please share.

**Comment by chris42** [comment]
This is the microg issue tracker, so not sure if you are correct here.

If you are looking for some lineageOS tracker you should probably look here https://wiki.lineageos.org/bugreport-howto.html and here https://gitlab.com/LineageOS/issues/android

For Fairphone probalbly here https://support.fairphone.com/hc/en-us

**Comment by Pratched** [comment]
All the above would be true, if it wouldnt be an issue with the images directly downloaded from lineage.microg.org, which would are different from the original lineageOS version.
The issue is regarding the update routine of this image.

**Comment by ArchangeGabriel** [comment]
Then it should be reported to LineageOS 4 microG, which is a independent (but of course related) project: https://github.com/lineageos4microg/l4m_website/issues.

**Comment by Pratched** [comment]
All right, my bad. Didnt realise that when following the Issue tree on lineage.microg.org.
If anybody can feel free to delete this issue.

**Comment by chris42** [comment]
If you would close it, that would already be enough...
