### ISSUE TITLE
Report no ble beacon advertised

### ISSUE THREAD

**Issue by kurt-by** [microg/GmsCore#1290]
Some diveces don't advertise contact notification beacons. Even if android is 6+
Example devices with lineageOS 14.1 or galaxy a3 2016 with lineageOS 17.1

Would be fine to get a warning about that.

**Comment by kurt-by** [comment]
Thank you f7190091af40e0387e5c9cf69003d2d7731f6250

**Comment by mar-v-in** [comment]
Warning is not yet there, but will be in next release

**Comment by mar-v-in** [comment]
0c321fd1eb54a2c923bf317d4f5bf255537b6e84 adds a warning to the settings screen.

**Comment by kurt-by** [comment]
@mar-v-in I can help testing, if I get a preview app.

**Comment by mar-v-in** [comment]
@kurt-n test build is at https://microg.org/dl/core-nightly.apk

**Comment by kurt-by** [comment]
![Screenshot_20201207-063443](https://user-images.githubusercontent.com/26526996/101313675-f42f1000-3856-11eb-8210-1804a32133b9.png)
