### ISSUE TITLE
SafetyNet not working

### ISSUE THREAD

**Issue by CountOmega** [microg/GmsCore#1308]
Hi all,

first of all, I really do appriciate your work. I cannot say how grateful I am for being able to run an de-googled OS.
I read about #526 . The safety net test yields signature fail. Has Google made it impossible to validate non-stock roms? If not, is there a way to get it up and running? It would be nice if it were working.

**System**
Android Version:  10
Custom ROM:  LineageOS 17.1
Phone: Pocophone F1

Cheers

CountOmega

**Comment by chris42** [comment]
wrong repository, SafetyNet belongs to RemoteDroidGuard. It's known not to work currently:

microg/RemoteDroidGuard#24

**Comment by CountOmega** [comment]
So I can forget about running it?

**Comment by chris42** [comment]
As the issue is unsolved, I guess so.

**Comment by CountOmega** [comment]
I read in #24 and #29 that one can try around to get it working. Any expirience on this?
