### ISSUE TITLE
de.corona.tracing crashes in oreo 8.0.0

### ISSUE THREAD

**Issue by dilbech** [microg/GmsCore#1312]
**Affected app**
Name: The oss corona app de.corona.tracing  1.7.1.2 (fdroid)
Package id: de.corona.tracing

**Describe the bug**
Installing the app causes the next reboot to bootloop.

**To Reproduce**

Do not install microg. I have disabled all gapps 
```
adb shell  pm disable-user --user 0 com.google.android.ext.services
adb shell  pm disable-user --user 0 com.google.android.partnersetup
adb shell  pm disable-user --user 0 com.google.android.ext.shared
adb shell  pm disable-user --user 0 com.android.vending
adb shell  pm disable-user --user 0 com.google.android.gms
adb shell  pm disable-user --user 0 com.google.android.gsf
adb shell  pm disable-user --user 0 com.google.android.inputmethod.latin
```

1. Install de.corona.tracing
2. accept and enable location/bluetooth
3. Everything seems OK
4. No errors reported
5. Now restart phone
6. The boots OK, once it reaches the lockscreen (like bootcomplete state), it just restarts... and go to restart again
7. Only way to rescue phone is:
`adb shell pm uninstall de.corona.tracing
`

**Log file **
https://codeberg.org/attachments/ee9397c0-97af-4107-a204-da06dd9b7ee6

**Expected behavior**
1. Stay fine

**Screenshots**

**System**
Android Version: 8.0.0
Custom ROM:  stock ROM - Cubot 

**microG**
microG Core version: the version bundled with de.corona.tracing  1.7.1.2 (fdroid)
microG Self-Check results: NOT installed.

**Additional context**

See https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/25

Any suggestions appreciated.

**Comment by kurt-by** [comment]
Same configuration, no problem. Only differences:
Uninstall -k instead of disable-usee
Samsung instead of chubot.

.. And maybe you should post in https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues - its' not really a GmsCore bug.

**Comment by mar-v-in** [comment]
The problem only happens on Android 8.0.0 when you don't exempt CCTG/microG from battery optimizations.
The issue is a bug in Android, [#65650999](https://issuetracker.google.com/issues/65650999).

I'll make sure we have a workaround for this in the next release.

**Comment by dilbech** [comment]
Thanks @mar-v-in 

@kurt-by 

> Same configuration, no problem. Only differences:
> Uninstall -k instead of disable-usee
> Samsung instead of chubot.

Do you mean 

`pm uninstall -k com.google.android.gms
`
May be I do not understand correctly. (a novice here)...
If I understand correctly, the above command (-k) will not stop/remove all from running original.google.services.

**Comment by kurt-by** [comment]
> Thanks @mar-v-in
> 
> @kurt-by
> 
> > Same configuration, no problem. Only differences:
> > Uninstall -k instead of disable-usee
> > Samsung instead of chubot.
> 
> Do you mean
> 
> `pm uninstall -k com.google.android.gms `
> May be I do not understand correctly. (a novice here)...
> If I understand correctly, the above command (-k) will not stop/remove all from running original.google.services.

https://forum.xda-developers.com/t/uninstall-any-apps-via-adb-no-root.3738105/

Make sure to disable device administrators to uninstall gms
