### ISSUE TITLE
[com.microsoft.skydrive] MS Onedrive crashes immediately

### ISSUE THREAD

**Issue by frank-bxl** [microg/GmsCore#1317]
**Affected app**
Name: MS Onedrive
Package id: com.microsoft.skydrive

**Describe the bug**
Onedrive aborts instantly after startup. Afterwards, the app continuously crashes even without an intended restart.

**To Reproduce**
1. Install the app (from Aurora store)
2. Click on start

**Expected behavior**
On first start: ask for account info, after this running in background

**Screenshots**
not available
**System**
Android Version: 10
Custom ROM: /e/ Q Vers. 0.13 Build: e_FP3-userdebug 10.QQ3A

**microG**
microG Core version: 0.2.14.204215-dirty
microG Self-Check results:  All ticked

**Additional context**
I attache a shortened bugreport
[bugreport_microG-Onedrive_excerpt.txt](https://github.com/microg/GmsCore/files/5702169/bugreport_microG-Onedrive_excerpt.txt)

**Comment by chris42** [comment]
Have you checked #1254 ?

**Comment by mar-v-in** [comment]
Updating to 0.2.15 should fix this.
