### ISSUE TITLE
Exposure Notification Framework Version 2

### ISSUE THREAD

**Issue by NovaMoon** [microg/GmsCore#1320]
I'm not sure how to properly tag this so please forgive me. 

There is going to be an update for the german "Corona Warn App" and its using a new version of the Exposure Notification Framework. 
https://www.coronawarn.app/de/blog/2020-12-16-corona-warn-app-version-1-9/

Just a headsup for potentional problems after the updates rolls out.

**Comment by mar-v-in** [comment]
What they call version 2 is known as ExposureWindow mode (in contrast to v1 mode) in Google documentation. It was already part of previous release (0.2.14) and will receive further bug fixes in next release (0.2.15, today or tomorrow). I've been testing ExposureWindow mode with CWA 1.8 preview releases (which for some reason CWA developers decided to ditch and directly jump to 1.9 instead).
