### ISSUE TITLE
Cloud Messaging Ping interval not saved

### ISSUE THREAD

**Issue by geromueller** [microg/GmsCore#1323]
**Describe the bug**
To get timely notifications (e.g. WhatsApp) I set the interval to 5mins. This value is reset to automatic after a short time. Maybe reconnect a network?

**To Reproduce**
Set interval to 5mins. Wait some time. Check again.
I will have a closer look.

**Expected behavior**
Ping interval stays at 5mins.

**System**
Android Version: 10
Custom ROM: Havoc 3.11

**Comment by mar-v-in** [comment]
https://github.com/microg/GmsCore/commit/c648883128eb0906e575bdf04d3801010832fb58 should fix this. Try again with https://microg.org/dl/core-nightly.apk
