### ISSUE TITLE
Upgrade 16.0 to 17.1 results in bootloop to recovery

### ISSUE THREAD

**Issue by JSUNFGH** [microg/GmsCore#1327]
Hello everyone,
I’ve been reading this GitHub for some time now, but never had problems with MicroG. So, first off, THANK YOU to the developers for doing a great job! But now I’m stuck for the first time and could use some advice from experienced users. I’m not sure if this belongs here. So please move this issue if it doesn’t or point me in the right direction for this issue. I also asked on XDA, but the reply didn’t help so far.

Until yesterday I used LOS for MicroG 16.0 with the lastest build (lineage-16.0-20200928) on my Samsung Galaxy S5 (klte) without major problems. Then I finally wanted to move on to 17.1. Unfortunately, there is no official documentation on how to do so. The homepage only speaks about upgrading from 15.1 to 16.0 (https://lineage.microg.org/). I searched around the internet and found an issue (https://github.com/microg/GmsCore/issues/1172) that suggested, dirty flashing would work. Also, that’s basically what the MicroG homepage says for upgrading from 15.1 to 16.0. Well, it didn’t work for me. LOS is loading to the turquoise loading symbol (moving dots), stays there for some time and reboots back into recovery. Rebooting the system from recovery ends the same way. Here is what I did:

a)
-	Upgrading TWRP to latest version (3.4.0.0)
-	Flashing latest LOS for MicroG (lineage-17.1-20201205) without wiping cache/dalvik
-	rebooting system
- 	resulted in boot loop to recovery (as described above)

b)
- 	in TWRP wiped cache + dalvik cache
- 	rebooting system
-	resulted in boot loop to recovery (as described above)

c)
- 	decided to restore phone to 16.0 with factory reset und restore of full backup from TWRP
- 	resulted in Odin/Fastboot bootloop, not able to properly boot to 16.0

d)
- 	decided to try 17.1 again and in TWRP flashed migration.zip first, then latest LOS for MicroG (lineage-17.1-20201205) with wiping cache/dalvik afterwards
- 	rebooting system
- 	resulted in boot loop to recovery (as described above)

e)
- 	hooked up phone to adb
- 	flashed latest LOS for MicroG (lineage-17.1-20201205) with adb sideload
- 	wiping cache/dalvik afterwards
- 	rebooting system
- 	resulted in boot loop to recovery (as described above)
- 	copied the recovery log from inside TWRP and attached it (see below)

What am I doing wrong? What is the right way to upgrade from 16.0 to 17.1? So, I would need help either to:

- 	finally upgrade from 16.0 to 17.1 without losing my apps and data or
- 	restore my phone to 16.0 without losing my apps and data.

Can anyone of you help me doing so? The phone is my daily driver and I need it usable asap. Thank you!

==========recovery-log==========================================

__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
Starting TWRP 3.4.0-0-13b07f8d on Wed Jan  1 01:11:23 2014
 (pid 214)
I:=> product model: 'SM-G900F'
I:=> using device id: 'SM-G900F'
TW_NO_REBOOT_BOOTLOADER := true
RECOVERY_SDCARD_ON_DATA := true
I:Lun file '/sys/devices/msm_dwc3/f9200000.dwc3/gadget/lun0/file'
TW_HAS_DOWNLOAD_MODE := true
TW_INCLUDE_CRYPTO := true
I:TW_BRIGHTNESS_PATH := /sys/devices/mdp.0/qcom,mdss_fb_primary.191/leds/lcd-backlight/brightness
I:Specified brightness file '/sys/devices/mdp.0/qcom,mdss_fb_primary.191/leds/lcd-backlight/brightness' not found.
I:Found brightness file at '/sys/devices/virtual/lcd/panel/panel/brightness'
I:TWFunc::Set_Brightness: Setting brightness control to 162
I:LANG: en
Starting the UI...
setting DRM_FORMAT_RGBX8888 and GGL_PIXEL_FORMAT_RGBX_8888
cannot find/open a drm device: No such file or directory
fb0 reports (possibly inaccurate):
  vi.bits_per_pixel = 32
  vi.red.offset   =  24   .length =   8
  vi.green.offset =  16   .length =   8
  vi.blue.offset  =   8   .length =   8
setting GGL_PIXEL_FORMAT_RGBX_8888
double buffered
framebuffer: 0 (1080 x 1920)
Using fbdev graphics.
I:TWFunc::Set_Brightness: Setting brightness control to 162
I:Loading package: splash (/twres/splash.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/splash.xml' directly
I:Checking resolution...
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page splash
I:Switching packages (splash)
=> Linking mtab
=> Processing /etc/recovery.fstab for SAR-detection
I:Reading /etc/recovery.fstab
I:Done processing fstab files
I:SAR-DETECT: SAR System detected
=> Processing /etc/recovery.fstab
I:Reading /etc/recovery.fstab
I:Processing '/modem'
I:Created '/modem' folder.
I:Processing '/firmware'
I:Created '/firmware' folder.
I:Processing '/boot'
I:Processing '/recovery'
I:Processing '/system'
I:Created '/system_root' folder.
I:Processing '/data'
I:Processing '/cache'
I:Processing '/efs'
I:Created '/efs' folder.
I:Processing '/modemst1'
I:Processing '/modemst2'
I:Processing '/external_sd'
I:Created '/external_sd' folder.
I:Processing '/usbstorage'
I:Created '/usbstorage' folder.
I:Processing '/misc'
I:Done processing fstab files
I:Setting up '/data' as data/media emulated storage.
I:Created '/sdcard' folder.
I:mount -o bind '/data/media' '/sdcard' process ended with RC=0
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
I:Trying wrapped key.
I:Unable to decrypt device
I:Setting up '/data' as data/media emulated storage.
I:mount -o bind '/data/media/0' '/sdcard' process ended with RC=0
I:Backup folder set to '/data/media/0/TWRP/BACKUPS/SM-G900F'
I:Settings storage is '/data/media/0'
I:Decrypt adopted storage starting
I:PageManager::LoadFileToBuffer loading filename: '/data/system/storage.xml' directly
I:successfully loaded storage.xml
Alternate GPT is invalid, using primary GPT.
I:type: '193d1ea4b3ca11e4b07510604b889dcf'
I:part: '6242243da92c4d8cbdfaec5bf34df90b'
I:Adopted_GUID '6242243da92c4d8cbdfaec5bf34df90b'
I:android_expand found
I:Detected adopted storage, disabling USB mass storage mode
I:key file is '/data/misc/vold/expand_6242243da92c4d8cbdfaec5bf34df90b.key', block device '/dev/block/mmcblk1p2'
E:Cannot remove dm-crypt device
I:Enabling support for allow_discards in dmcrypt.
I:Creating crypto dev "6242243da92c4d8cbdfaec5bf34df90b"; cipher=aes-cbc-essiv:sha256, keysize=16, real_dev=/dev/block/mmcblk1p2, len=127847611904, params="1 allow_discards"
I:target_type = crypt
I:real_blk_name = /dev/block/mmcblk1p2, extra_params = 1 allow_discards
I:adopted storage new block device: '/dev/block/dm-0'
I:Can't probe device /dev/block/mmcblk1
I:Unable to mount '/external_sd'
I:Actual block device: '/dev/block/mmcblk1', current file system: 'vfat'
I:Setting up '/external_sd' as data/media emulated storage.
I:Data backup size is 101887MB, free: 21181MB.
I:Data backup size is 91MB, free: 21181MB.
I:storage name from storage.xml is 'SD-Karte von SanDisk'
I:Internal storage is found on adopted storage 'SD-Karte von SanDisk'
I:Changing '/sdcard' to point to '/external_sd/media/0'
I:Data backup size is 91MB, free: 21181MB.
I:mount -o bind '/external_sd/media/0' '/sdcard' process ended with RC=0
Updating partition details...
I:Data backup size is 8709MB, free: 2514MB.
I:Data backup size is 91MB, free: 21181MB.
I:Unable to mount '/usbstorage'
I:Actual block device: '', current file system: 'vfat'
...done
/external_sd | /dev/block/dm-0 | Size: 121922MB Used: 91MB Free: 21181MB Backup Size: 91MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI Is_SubPartition Removable IsPresent Is_Encrypted Is_Decrypted Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Adopted_Storage 
   SubPartition_Of: /data
   Symlink_Path: /external_sd/media/0
   Symlink_Mount_Point: /sdcard
   Primary_Block_Device: /dev/block/mmcblk1p1
   Alternate_Block_Device: /dev/block/mmcblk1
   Decrypted_Block_Device: /dev/block/dm-0
   Display_Name: SD-Karte von SanDisk
   Storage_Name: SD-Karte von SanDisk
   Backup_Path: /external_sd
   Backup_Name: external_sd
   Backup_Display_Name: SD-Karte von SanDisk
   Storage_Path: /external_sd/media/0
   Current_File_System: f2fs
   Fstab_File_System: vfat
   Backup_Method: files
   MTP_Storage_ID: 65538

Updating partition details...
I:Data backup size is 8709MB, free: 2514MB.
I:Data backup size is 91MB, free: 21181MB.
I:Unable to mount '/usbstorage'
I:Actual block device: '', current file system: 'vfat'
...done
I:Unmounting main partitions...

Partition Logs:
/modem | /dev/block/mmcblk0p2 | Size: 63MB Used: 52MB Free: 11MB Backup Size: 52MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Has_SubPartition IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p2
   Alternate_Block_Device: /dev/block/platform/msm_sdcc.1/by-name/mdm
   Display_Name: Modem
   Storage_Name: Modem
   Backup_Path: /modem
   Backup_Name: modem
   Backup_Display_Name: Modem
   Storage_Path: /modem
   Current_File_System: vfat
   Fstab_File_System: vfat
   Backup_Method: files

/firmware | /dev/block/mmcblk0p1 | Size: 76MB Used: 8MB Free: 68MB Backup Size: 8MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Is_SubPartition IsPresent Mount_To_Decrypt Mount_Read_Only 
   SubPartition_Of: /modem
   Primary_Block_Device: /dev/block/mmcblk0p1
   Display_Name: firmware
   Storage_Name: firmware
   Backup_Path: /firmware
   Backup_Name: firmware
   Backup_Display_Name: firmware
   Storage_Path: /firmware
   Current_File_System: vfat
   Fstab_File_System: vfat
   Backup_Method: files
   Mount_Flags: 0, Mount_Options: context=u:object_r:firmware_file:s0

/boot | /dev/block/mmcblk0p15 | Size: 13MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p15
   Display_Name: Boot
   Storage_Name: boot
   Backup_Path: /boot
   Backup_Name: boot
   Backup_Display_Name: Boot
   Storage_Path: /boot
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/recovery | /dev/block/mmcblk0p16 | Size: 15MB
   Flags: Can_Be_Backed_Up IsPresent Can_Flash_Img 
   Primary_Block_Device: /dev/block/mmcblk0p16
   Display_Name: Recovery
   Storage_Name: recovery
   Backup_Path: /recovery
   Backup_Name: recovery
   Backup_Display_Name: Recovery
   Storage_Path: /recovery
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/system_root | /dev/block/mmcblk0p23 | Size: 2260MB Used: 1110MB Free: 1150MB Backup Size: 1110MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_Available_in_GUI IsPresent Can_Flash_Img Mount_Read_Only 
   Primary_Block_Device: /dev/block/mmcblk0p23
   Display_Name: System
   Storage_Name: System
   Backup_Path: /system_root
   Backup_Name: system
   Backup_Display_Name: System
   Storage_Path: /system_root
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/data | /dev/block/mmcblk0p26 | Size: 11936MB Used: 8709MB Free: 2514MB Backup Size: 8709MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI Has_SubPartition IsPresent Can_Be_Encrypted Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Settings_Storage 
   Symlink_Path: /data/media/0
   Primary_Block_Device: /dev/block/mmcblk0p26
   Crypto_Key_Location: footer
   Length: -16384
   Display_Name: Data
   Storage_Name: Internal Storage
   Backup_Path: /data
   Backup_Name: data
   Backup_Display_Name: Data
   Storage_Path: /data/media/0
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files
   MTP_Storage_ID: 65537

/cache | /dev/block/mmcblk0p24 | Size: 196MB Used: 4MB Free: 192MB Backup Size: 4MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p24
   Display_Name: Cache
   Storage_Name: Cache
   Backup_Path: /cache
   Backup_Name: cache
   Backup_Display_Name: Cache
   Storage_Path: /cache
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/efs | /dev/block/mmcblk0p12 | Size: 13MB Used: 4MB Free: 9MB Backup Size: 4MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Has_SubPartition IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p12
   Display_Name: EFS
   Storage_Name: EFS
   Backup_Path: /efs
   Backup_Name: efs
   Backup_Display_Name: EFS
   Storage_Path: /efs
   Current_File_System: ext4
   Fstab_File_System: ext4
   Backup_Method: files

/modemst1 | /dev/block/mmcblk0p13 | Size: 3MB
   Flags: Can_Be_Backed_Up Is_SubPartition IsPresent 
   SubPartition_Of: /efs
   Primary_Block_Device: /dev/block/mmcblk0p13
   Display_Name: modemst1
   Storage_Name: modemst1
   Backup_Path: /modemst1
   Backup_Name: modemst1
   Backup_Display_Name: modemst1
   Storage_Path: /modemst1
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/modemst2 | /dev/block/mmcblk0p14 | Size: 3MB
   Flags: Can_Be_Backed_Up Is_SubPartition IsPresent 
   SubPartition_Of: /efs
   Primary_Block_Device: /dev/block/mmcblk0p14
   Display_Name: modemst2
   Storage_Name: modemst2
   Backup_Path: /modemst2
   Backup_Name: modemst2
   Backup_Display_Name: modemst2
   Storage_Path: /modemst2
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

/external_sd | /dev/block/dm-0 | Size: 121922MB Used: 91MB Free: 21181MB Backup Size: 91MB
   Flags: Can_Be_Mounted Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI Is_SubPartition Removable IsPresent Is_Encrypted Is_Decrypted Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Adopted_Storage 
   SubPartition_Of: /data
   Symlink_Path: /external_sd/media/0
   Symlink_Mount_Point: /sdcard
   Primary_Block_Device: /dev/block/mmcblk1p1
   Alternate_Block_Device: /dev/block/mmcblk1
   Decrypted_Block_Device: /dev/block/dm-0
   Display_Name: SD-Karte von SanDisk
   Storage_Name: SD-Karte von SanDisk
   Backup_Path: /external_sd
   Backup_Name: external_sd
   Backup_Display_Name: SD-Karte von SanDisk
   Storage_Path: /external_sd/media/0
   Current_File_System: f2fs
   Fstab_File_System: vfat
   Backup_Method: files
   MTP_Storage_ID: 65538

/usbstorage |  | Size: 0MB Used: 0MB Free: 0MB Backup Size: 0MB
   Flags: Can_Be_Mounted Can_Be_Wiped Wipe_Available_in_GUI Removable Is_Storage 
   Primary_Block_Device: /dev/block/sda1
   Alternate_Block_Device: /dev/block/sda
   Display_Name: USB Storage
   Storage_Name: USB Storage
   Backup_Path: /usbstorage
   Backup_Name: usbstorage
   Backup_Display_Name: USB Storage
   Storage_Path: /usbstorage
   Current_File_System: vfat
   Fstab_File_System: vfat
   Backup_Method: files
   MTP_Storage_ID: 65539

/misc | /dev/block/mmcblk0p17 | Size: 13MB
   Flags: IsPresent 
   Primary_Block_Device: /dev/block/mmcblk0p17
   Display_Name: misc
   Storage_Name: misc
   Backup_Path: /misc
   Backup_Name: misc
   Backup_Display_Name: misc
   Storage_Path: /misc
   Current_File_System: emmc
   Fstab_File_System: emmc
   Backup_Method: dd

I:Loading package: TWRP (/data/media/0/TWRP/theme/ui.zip)
I:Loading zip theme
I:Loading package: TWRP (/twres/ui.xml)
I:Load XML directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/uk.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/tr.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sv.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/sk.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/ru.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pt_PT.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pt_BR.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/pl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/nl.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/it.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/hu.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/fr.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/es.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/el.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/de.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/cz.xml' directly
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
parsing languageFile
parsing languageFile done
I:PageManager::LoadFileToBuffer loading filename: '/twres/ui.xml' directly
I:Checking resolution...
I:Loading resources...
I:Failed to load image from indeterminate013, error -1
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Including file: /twres/portrait.xml...
I:PageManager::LoadFileToBuffer loading filename: '/twres/portrait.xml' directly
I:Loading resources...
I:Loading variables...
I:Loading mouse cursor...
I:Loading pages...
I:Loading page main
I:Loading page main2
I:Loading page install
I:Loading page flash_confirm
I:Loading page flash_zip
I:Loading page flash_done
I:Loading page flash_sleep_and_reboot
I:Loading page flashimage_confirm
I:Loading page clear_vars
I:Loading page reboot_system_routine
I:Loading page confirm_action
I:Loading page action_page
I:Loading page singleaction_page
I:Loading page action_complete
I:Loading page filecheck
I:Loading page rebootcheck
I:Loading page appcheck
I:Loading page wipe
I:Loading page advancedwipe
I:Loading page formatdata
I:Loading page formatdata_confirm
I:Loading page checkpartitionlist
I:Loading page partitionoptions
I:Loading page refreshfilesystem
I:Loading page selectfilesystem
I:Loading page backup
I:Loading page backup_options
I:Loading page backupname1
I:Loading page backupname2
I:Loading page backupencryption
I:Loading page backupencryption2
I:Loading page checkbackuppassword
I:Loading page backup_run
I:Loading page restore
I:Unable to open '/data/media/0/TWRP/BACKUPS/SM-G900F'
I:Loading page restore_read
I:Loading page restore_decrypt
I:Loading page try_restore_decrypt
I:Loading page restore_select
I:Loading page renamebackup
I:Loading page restore_run
I:Loading page mount
I:Loading page usb_mount
I:Loading page usb_umount
I:Loading page system_readonly_check
I:Loading page reboot
I:Loading page rebootapp
I:Loading page system_readonly
I:Loading page settings
I:Loading page settings_timezone
I:Loading page settings_screen
I:Loading page settings_vibration
I:Loading page settings_language
I:Loading page copylog
I:Loading page advanced
I:Loading page partsdcardsel
I:Loading page partsdcardcheck
I:Loading page partsdcard
I:Loading page htcdumlock
I:Loading page repackselect
I:Loading page repackconfirm
I:Loading page lock
I:Loading page filemanagerlist
I:Loading page filemanageroptions
I:Loading page choosedestinationfolder
I:Loading page filemanagerrenamefile
I:Loading page filemanagerrenamefolder
I:Loading page filemanagerchmod
I:Loading page filemanagerconfirm
I:Loading page filemanageraction
I:Loading page decrypt
I:Loading page decrypt_pattern
I:Loading page trydecrypt
I:Loading page terminalcommand
I:Loading page sideload
I:Loading page fixcontexts
I:Loading page slideout
I:Loading page select_storage
I:Loading page select_language
I:Loading page decrypt_users
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Switching packages (TWRP)
Boot command: boot-recovery
Got arguments from boot message
Startup Commands:  '--prompt_and_wipe_data' '--reason=RescueParty'RescueParty
 '--locale=de_DE'
ro.sf.lcd_density=480
ro.com.google.clientidbase=android-google
ro.com.android.wifi-watchlist=GoogleGuest
ro.url.legal=http://www.google.com/intl/%s/mobile/android/basic/phone-legal.html
ro.boot.emmc=true
ro.boot.sec_atd.tty=/dev/ttyHSL0
ro.boot.baseband=msm
ro.boot.hardware=qcom
ro.boot.revision=14
ro.boot.serialno=98cb9775
ro.boot.bootdevice=msm_sdcc.1
ro.boot.bootloader=G900FXXU1CPDF
ro.boot.debug_level=0x4f4c
ro.boot.warranty_bit=1
ro.boot.boot_recovery=1
ro.boot.emmc_checksum=3
ro.boot.nvdata_backup=0
ro.boot.cp_debug_level=0x55FF
ro.omni.device=klte
ro.omni.version=6.0.1-20200904-klte-HOMEMADE
ro.twrp.sar=true
ro.twrp.boot=1
ro.twrp.version=3.4.0-0
ro.wifi.channels=
ro.allow.mock.location=1
ro.board.platform=msm8974
ro.build.id=MOB31K
ro.build.date=Fri Sep  4 22:55:33 UTC 2020
ro.build.date.utc=0
ro.build.host=bfd035c5964a
ro.build.tags=test-keys
ro.build.type=eng
ro.build.user=jenkins
ro.build.flavor=omni_klte-eng
ro.build.display.id=omni_klte-eng 6.0.1 MOB31K 1 test-keys
ro.build.version.sdk=23
ro.build.version.base_os=
ro.build.version.release=6.0.1
ro.build.version.codename=REL
ro.build.version.incremental=1
ro.build.version.preview_sdk=
ro.build.version.all_codenames=REL
ro.build.version.security_patch=2016-11-05
ro.build.characteristics=default
ro.kernel.android.checkjni=1
ro.secure=0
ro.product.cpu.abi=armeabi-v7a
ro.product.cpu.abi2=armeabi
ro.product.cpu.abilist=armeabi-v7a,armeabi
ro.product.cpu.abilist32=armeabi-v7a,armeabi
ro.product.cpu.abilist64=
ro.product.name=kltexx
ro.product.board=MSM8974
ro.product.brand=samsung
ro.product.model=SM-G900F
ro.product.device=klte
ro.product.manufacturer=samsung
ro.baseband=msm
ro.bootmode=unknown
ro.hardware=qcom
ro.qualcomm.bt.hci_transport=smd
ro.revision=14
ro.serialno=98cb9775
ro.bootimage.build.date=Fri Sep 4 22:56:04 UTC 2020
ro.bootimage.build.date.utc=1599260164
ro.bootimage.build.fingerprint=samsung/omni_klte/klte:6.0.1/MOB31K/1:eng/test-keys
ro.bootloader=G900FXXU1CPDF
ro.debuggable=1
ro.modversion=OmniROM-6.0.1-20200904-klte-HOMEMADE
ro.setupwizard.enterprise_mode=1
ro.lcd_brightness=162
ro.lcd_min_brightness=0
dev.pm.dyn_samplingrate=1
fbe.data.wrappedkey=true
net.bt.name=Android
net.change=net.bt.name
sys.usb.config=mtp,adb
init.svc.adbd=stopping
init.svc.ueventd=running
init.svc.recovery=running
init.svc.set_permissive=stopped
twrp.crash_counter=0
twrp.action_complete=0
debug.sf.hw=1
debug.egl.hw=1
debug.atrace.tags.enableflags=0
debug.mdpcomp.logs=0
debug.mdpcomp.fallback=false
debug.mdpcomp.idletime=100
debug.composition.type=gpu
dalvik.vm.isa.arm.variant=krait
dalvik.vm.isa.arm.features=default
dalvik.vm.usejit=true
dalvik.vm.lockprof.threshold=500
dalvik.vm.dex2oat-filter=verify-at-runtime
dalvik.vm.stack-trace-file=/data/anr/traces.txt
dalvik.vm.image-dex2oat-filter=verify-at-runtime
persist.hwc.mdpcomp.enable=true
persist.sys.usb.config=mtp,adb
persist.sys.dalvik.vm.lib.2=libart
persist.sys.root_access=1
persist.fuse_sdcard=true
service.adb.root=1

Renaming regular /file_contexts -> /file_contexts.bak
Moving /prebuilt_file_contexts -> /file_contexts
SELinux contexts loaded from /file_contexts
Full SELinux support is present.
tw_get_context got selinux context: u:object_r:media_rw_data_file:s0
I:Got default contexts and file mode for storage files.
I:TWFunc::Fixup_Time: Pre-fix date and time: 2014-01-01--01-12-11
I:TWFunc::Fixup_Time: Setting time offset from file /sys/class/rtc/rtc0/since_epoch
I:TWFunc::Fixup_Time: will attempt to use the ats files now.
I:TWFunc::Fixup_Time: Setting time offset from file /data/time/ats_2, offset 1569397457119
I:TWFunc::Fixup_Time: Date and time corrected: 2019-09-25--08-56-27
I:Copied file /cache/recovery/log.gz to /cache/recovery/last_log.gz
I:Attempt to load settings from settings file...
I:InfoManager loading from '/data/media/0/TWRP/.twrps'.
I:Backup folder set to '/external_sd/media/0/TWRP/BACKUPS/SM-G900F'
I:Copied file /etc/recovery.fstab to /cache/recovery/recovery.fstab
I:Version number saved to '/cache/recovery/.version'
I:Unable to mount '/usbstorage'
I:Actual block device: '', current file system: 'vfat'
__bionic_open_tzdata: couldn't find any tzdata when looking for CET-1CEST,M3.5.0,M10.5.0!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
I:TWFunc::Set_Brightness: Setting brightness control to 102
I:PageManager::LoadFileToBuffer loading filename: '/twres/languages/en.xml' directly
parsing languageFile
parsing languageFile done
I:Translating partition display names
I:Backup folder set to '/external_sd/media/0/TWRP/BACKUPS/SM-G900F'
I:Starting MTP
I:[MTP] Starting MTP
I:sending message to add 65537 '/data/media/0' 'Internal Storage'
I:Message sent, add storage ID: 65537 '/data/media/0'
I:sending message to add 65538 '/external_sd/media/0' 'SD-Karte von SanDisk - Adopted Storage'
I:Message sent, add storage ID: 65538 '/external_sd/media/0'
MTP Enabled
I:Check_Lifetime_Writes result: '113'
I:Switching packages (TWRP)
I:Starting Adb Backup FIFO
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:[MTP] Using '/dev/mtp_usb' for MTP device.
I:[MTP] created new mtpserver object
I:[MTP] MtpServer::run fd: 20
I:[MTP] mtppipe add storage 65537 '/data/media/0'
I:[MTP] MtpStorage id: 65537 path: /data/media/0
I:[MTP] mtppipe add storage 65538 '/external_sd/media/0'
I:[MTP] MtpStorage id: 65538 path: /external_sd/media/0
I:TWFunc::Set_Brightness: Setting brightness control to 5
I:TWFunc::Set_Brightness: Setting brightness control to 0
I:TWFunc::Set_Brightness: Setting brightness control to 102
I:Set overlay: ''
I:Set page: 'advanced'
I:Set page: 'copylog'
I:Set page: 'action_page'
I:operation_start: 'Copy Log'

**Comment by chris42** [comment]
This definitely does not belong here. Install and upgrade issues of LineageOS should be in the LineageOS support forum or trackers. 
You seem to be in quite a difficult state and will probably need Lineage experts to fix it.

Out of my experience in AOSP major version jumps, I always needed to factory reset, hence wiping userdata. I do not know how LineageOS handles that and should only be attempted with a working and existent backup.

**Comment by JSUNFGH** [comment]
@chris42 Thank you for the quick reply! I just posted here because they couldn't help me on XDA so far and [https://github.com/microg/GmsCore/issues/1172](url) did raise a similar question and got an answer.

I did a factory reset before flashing 17.1 but this didn't help. And I have backup but restoring 16.0 didn't work. So... I don't know, it's just frustrating that both standard procedures failed on me.

**Comment by chris42** [comment]
Are you able to get an adb logcat from the boot? I am not sure how LOS is configured, hence if that is available to you. It normally shows quite well if there is a loop.

If not having logs and having backups, I would try a clean regular Lineage 17 (like you are flashing it for the first time) see if it boots up, then reflash with microg version.
Same when trying to restore the old 16 version. First get a clean 16 running than rewriting the backup over it.

**Comment by JSUNFGH** [comment]
I don't get any further than recovery or fastboot mode. When in recovery adb won't give me an logcat (logcat: not found). Or where/when would I obtain the logcat?

Tomorrow I will try the clean install of regular LineageOS 16.0, then MicroG 16.0, then restoring the 16.0 backup. Hope this helps. Thanks so far!

**Comment by chris42** [comment]
adb normally starts logging pretty quick after the "your device is unlocked" message. I thought you are getting to the lineageOS loading screen ("LOS is loading to the turquoise loading symbol (moving dots)")?
There you should get something via usb adb. However if LineageOS disabled adb via usb you won't see anything either way. I don't know enough about LineageOS to help with that.

**Comment by JSUNFGH** [comment]
That's right, I got to the lineageOS loading screen when dirty flashing the 17.1. But after all attempts (a to e, see above) failed, I decided to do factory reset and then try flashing 17.1, which worked. So I can't reproduce the original setting with the bootloop and provide an adb logcat since I'm not getting the bootloop anymore after clean install. I just can provide the recovery.log, which is attached above. I guess, I'm out of luck.

**Comment by chris42** [comment]
"do factory reset and then try flashing 17.1, which worked"
So you are now on a working 17.1?

**Comment by JSUNFGH** [comment]
Yes and no. I could be on a working clean install of 17.1 with not knowing if I can restore my data from a Titanium Backup due to a changed system (16.0 vs. 17.1). Later today I'm going your proposed road: clean install of LineageOS 16.0, install of LineageOS for MicroG 16.0, restoring my TWRP backup of 16.0. If this fails, I'm doing a clean install of 17.1 and try to restore my data from the Titatnium backup. I just need a working system with all my data, either 16.0 or 17.1, I don't care. Meanwhile, after reading other threads, I think the adopted storage I use might be the core of the problem.

**Comment by chris42** [comment]
If you have a running 17.1 I would test restore the most important apps with titanium backup. If you only choose data and not the app itself it should work. If that works you can stay on 17.1 and just restore data for all apps.

**Comment by JSUNFGH** [comment]
This would be my last resort. For this I would have to reformat the adopted storage, since 17.1 doesn't recognize it. First I try restoring 16.0 and hope it recognizes the adopted storage, so I can export app data from within the apps rather than relying on Titanium. Seems safer this way and working with 17.1 later is still possible.

**Comment by JSUNFGH** [comment]
I did succeed in restoring my phone back to its original condition by following your suggestion: clean install of LineageOS 16.0, install of LineageOS for MicroG 16.0, restoring my original TWRP backup of 16.0. Next on my agenda is the upgrade to 17.1 which I still have to figure out.

So I'm closing this issue. Thanks for your help @chris42!

**Comment by chris42** [comment]
No problem, glad that you at least got back to a working phone ;-). Out of my upgrade experiences, I guess your best bet is either to remove adopted storage beforehand (if that is even possible) or install fresh 17.1 and restore each apps data via titanium...
