### ISSUE TITLE
Can't cast screen from Redmi Note 7 (lavender)

### ISSUE THREAD

**Issue by fgianneschi** [microg/GmsCore#1331]
I've installed the lineageos 17.1 with microG for lavender (https://download.lineage.microg.org/lavender/lineage-17.1-20201205-microG-lavender.zip). Everything works quite well but I can't connect the phone screen to my chromecast using the usual system feature (home screen > drop down settings menu > Cast screen). It remains searching for available devices forever. See the attached picture.

![cast](https://user-images.githubusercontent.com/8987324/102912172-5f92f780-447d-11eb-8121-7d7642507370.jpg)

On the other hand, casting single media or streams using VLC works.

**Comment by i0r14** [comment]
Look at this:
https://github.com/microg/GmsCore/issues/79
It says "closed" but this functionality is still not working.

**Comment by fgianneschi** [comment]
Update: Still not working on LineageOS 18.1 + microG 0.2.24.214816

- VLC app works
- Amazon Prime video app shows the connection option and the Chromecast's device name, but isn't able to connect.

**Comment by ale5000-git** [comment]
Hi, the current Cast problem is common so I suggest to write on #580 instead of opening new issues.
