### ISSUE TITLE
Timestamp of ENF update differs from Corona-Warn-App 1.9.1 updated timestamp

### ISSUE THREAD

**Issue by Diapolo** [microg/GmsCore#1332]
## Technical details

- Device name: Fairphone 2
- Android version: Android 10 / LineageOS for microG ([lineage-17.1-20201203-microG-FP2.zip](https://download.lineage.microg.org/FP2/lineage-17.1-20201203-microG-FP2.zip))
- App version: 1.9.1
- ENF version: 204713000
- microG version: v0.2.16.204713

## Describe the bug

Note sure if this is a bug in microG or CWA - but CWA devs love to point to microG at first ;). I observed that the timestamps shown for ENF updates in the microG settings differs from the timestamp shown in Corona-Warn-App (CWA).

![Screenshot_20201222-120011_Corona-Warn](https://user-images.githubusercontent.com/1419649/102882010-02338200-444e-11eb-9fd3-a9204761aa3e.png)
![Screenshot_20201222-115945_microG_Services_Core](https://user-images.githubusercontent.com/1419649/102882016-0495dc00-444e-11eb-9974-f14875abb865.png)

## Steps to reproduce the issue

1. Open CWA, check the timestamp of "Aktualisiert:"
2. Open the microG ENF settings and check the timestamp of "Aktualisiert:"

## Additional information

I had installed the F-Droid version of 1.91 called "Corona Contact Tracing Germany" to verify if a previous error I observed (#1325) was related to CWA only (was fixed by microG update v0.2.16.204713). The app was installed in parallel to CWA and was removed 2 days ago. I hint that information just in case it could be relevant.

## Expected behaviour

Timestamps should be in sync.

**Comment by Diapolo** [comment]
Today I once more did an in-app-reset of CWA, because it moaned about not beeing updated for too long again. At least for now (directly after the reset and first update + scan) both timestamps are in sync.

**Comment by mar-v-in** [comment]
Can you please provide a logcat? I don't see this behavior on my CWA 1.9.1 or CCTG 1.9.1.6.

**Comment by Diapolo** [comment]
Well, I "solved" this by not only resetting CWA but by completely uninstalling and reinstalling the app. I now have CWA and CCTG installed in parallel and both show the same update timestamps, which match with microGs display.

Only thing I lost is the display, that tracing was active for 14 days - as this is just a display thing and the ENF data is there, I'm fine.
