### ISSUE TITLE
Rosetta Stone crash to startup

### ISSUE THREAD

**Issue by michael1900** [microg/GmsCore#1335]
I have same bug like here: https://github.com/microg/GmsCore/issues/1108 but no one fixed this yet.

Rosetta Stone appears to crash repeatedly during its startup screen, flashing a white screen every second or two and restarting the startup animation.

Huawei phone.

@mar-v-in

**Comment by michael1900** [comment]
Is there a fix for this?

**Comment by chris42** [comment]
Full duplicate to #1108 conversation should be continued over there

**Comment by Deadbeat13** [comment]
My "fix" involves opening Rosetta, waiting for the screen to dim (make sure it completely dims) then turning my screen back on resulting in a new scrolling wheel that eventually loads in Rosetta. No disabling anything, the whole process takes about 15 seconds.
