### ISSUE TITLE
[rki.coronawarnapp] Encounters aren't updated anymore on official CWA

### ISSUE THREAD

**Issue by nidico** [microg/GmsCore#1339]
**Affected app**
Name: Official Corona Warn App
Package id: rki.coronawarnapp

**Describe the bug**
Since upgrading official CWA from 1.7.1 to 1.9.1, encounters aren't updated anymore (last update: 2020-12-22).

This happened on GmsCore 0.2.15 as well as GmsCore 0.2.16.

On another device, the situation is similar, but slightly different - see issue #1338. This might therefore be a duplicate.

Same as on the other device, the Free [Corona Tracing Germany app](https://codeberg.org/corona-contact-tracing-germany/cwa-android) (installed via F-Droid) doesn't have this issue.

**System**
Android Version: 10
Custom ROM: LineageOS 17.1

**microG**
microG Core version: 0.2.16.204713
microG Self-Check results: All ticked

**Comment by Diapolo** [comment]
Perhaps related #1332?

**Comment by mar-v-in** [comment]
Can you please provide a logcat? I don't see this behavior on my CWA 1.9.1 or CCTG 1.9.1.6.

**Comment by nidico** [comment]
On this device, this appears to be working again since yesterday evening.
