### ISSUE TITLE
Unable to enable Exposure Notification after updating to 0.2.16

### ISSUE THREAD

**Issue by mvglasow** [microg/GmsCore#1341]
**Describe the bug**
After upgrading to 0.2.16 (or freshly installing it), Exposure Notification is no longer available—it it reported as Off, and the slider to enable it is grayed out.

**To Reproduce**
1. Install GmsCore 0.2.16.
2. Open settings, and check the Exposure Notification status.
3. Open the Exposure Notification setting.

**Expected behavior**
Exposure Notification is either enabled, or can be enabled.

**Screenshots**

**System**
Device: OnePlus One (bacon)
Android Version: 10
Custom distribution: LineageOS 17.1
microG installed as a system app through Magisk (microG Installer module)

**Additional context**
It does not seem to matter if GmsCore is updated from an earlier version or installed from scratch, or app data is cleared. 0.2.13 and 0.2.14 also seem affected. I have not recorded the version I used before; it was installed between November 1 and Dec 9, 2020, through Magisk.

**Comment by mvglasow** [comment]
Screenshots attached:
![Screenshot_20201226-160729_microG_Services_Core](https://user-images.githubusercontent.com/2377496/103152842-2bc11600-478c-11eb-97bc-c5c8642781bd.png)
![Screenshot_20201226-160741_microG_Services_Core](https://user-images.githubusercontent.com/2377496/103152849-37acd800-478c-11eb-8768-df31991639b8.png)

**Comment by kurt-by** [comment]
You should install a contact tracing app that uses the apple/google interface.

**Comment by mvglasow** [comment]
I have installed https://f-droid.org/en/packages/de.corona.tracing/ which originally showed up in the screen, but otherwise I got the exact same. I was unable to enable Exposure Notification from microG settings. The app (in version 1.9.1.4) gives me a dialog to launch microG settings so I can enable exposure notification, but tapping the button does nothing and the OK button is grayed out.

I worked around this whole thing by disabling the microG app, then uninstalling and reinstalling the Corona app, causing it to fall back to its bundled microG implementation, then re-enabling microG. (Btw, the bundled microG seems to have the same issue with Exposure Notification disabled and the button grayed out.)

**Comment by kurt-by** [comment]
F-droid version of cctg and microG don't fit well. I use microG with CoronaWarnApp on one phone and cctg without microG/GApps on another one without problems. Your bug should be reported in cctg issues.

**Comment by mvglasow** [comment]
Separating cctg from microG is not an option for me—I need microG for other things (UnifiedNLP), but I also want cctg on my phone (and I don’t carry multiple phones).

**Comment by mvglasow** [comment]
Update: I updated CCTG to 1.9.1.5 (1.9.1.4 has problems with bundled microG). Still no joy, unless I disable microG—then the bundled microG 0.2.16 works. However, if I re-enable microG system-wide, nothing works any more.

Right now that means there is a broken Exposure Notification provider on my device, which will prevent any contact tracing app from working, even if the app comes with a bundled version as a fallback.

If you are telling me a system-wide installation will not work, I suggest splitting exposure notification into a separate component, so I can still use the rest of microG (such as UnifiedNLP) without breaking contact tracing apps. (Right now I have the option between a working contact tracing app but no UnifiedNLP, or UnifiedNLP at the cost of not being able to use contact tracing, which is a huge bummer.)

**Comment by Ammako** [comment]
You are using microG just for UnifiedNLP? Why?

https://github.com/microg/UnifiedNlp/releases

**Comment by mar-v-in** [comment]
@mvglasow
The option to enable EN is never available in microG settings, it can only be used to disable EN.

However you should be able to enable EN in CCTG/CWA by touching the message about it being disabled at the top of the app or in its settings (called exposure logging or Risiko-Ermittlung).

**Comment by mvglasow** [comment]
@Ammako thanks for the pointer, will look into it.

@mar-v-in OK, now I’ve understood that, too—though it’s kinda non-obvious. The issue I am having, however, is that CCTG tells me it needs to be granted extra permissions, and when I tap the Grant button, nothing happens.

**Comment by mar-v-in** [comment]
@mvglasow have you checked that microG Self-Check has all fields ticked? Tried granting related permissions (location access) to CCTG and microG via system settings? When you select to remember the decision to deny a permission, the dialog will no longer show.

**Comment by mvglasow** [comment]
It definitely has location permission, and I tried granting each permission I could grant—to no avail. The only places where check marks are missing are:

* anything related to signatures (as I have no support for signature spoofing; however, microG is set up as a system app)
* Play Store (phonesky)
* permissions other than location (though, as above, I once tried granting everything I could, to no avail)

**Comment by mar-v-in** [comment]
- Make sure that you set location permission to "allow all the time". Also double-check you don't have location disabled system-wide. The missing permission is about location access, so this is probably the root cause. Does it say "microG services core needs additional permission" or "Corona Tracing needs additional permission"?
- Signature spoofing and Phonesky (FakeStore) are required to use CWA, but shouldn't be required to use CCTG.

**Comment by mvglasow** [comment]
All right, I upgraded to 0.2.15 again. As per System Settings, microG has location permission. When I tap it, it tells me:

> microG Services Core is a provider of location services for this device. Location access can be modified from location settings.

It does not let me make any settings here.

In the self-check, however, I see that microG has permission to access location in the foreground but not in the background. When I tap the entry to grant the permission, nothing happens (I don’t get a check mark).

**Comment by mvglasow** [comment]
Oh, and CCTG says:

> microG Services Core needs additional permissions.

I’m beginning to suspect that not being able to allow network location access is the error here, and everything else is a consequence of it.

**Comment by kurt-by** [comment]
There are so many broken or outdated microG installations around. I think best solution is a feature request in cctg to have a setting force use bundled api.

**Comment by mar-v-in** [comment]
@mvglasow as @kurt-by hinted, your installation of microG is corrupt. Exposure Notification API does not work without background location permission. See issue #1099 for some hints on how to solve this issue. And/or file an issue with whatever software you used to install microG.

**Comment by mvglasow** [comment]
One step further: as was pointed out to me in https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/65, I can update a system app by just dropping in a more recent APK, as long as package ID and signature match.

I installed a previous version (0.2.14, I believe) using the Magisk module, then dropped in the current APK from Github. Now I managed to enable background location services in microG. (Not sure what was wrong with the Magisk version, though—it must have had the official microG signature, else the update presumably would not have worked).

I then updated to CCTG 1.9.1.6 (had to clear all data to get it to work—note that you will lose existing exposure data) and was finally able to complete the sign-up process.

**Comment by kurt-by** [comment]
> Separating cctg from microG is not an option for me—I need microG for other things (UnifiedNLP), but I also want cctg on my phone (and I don’t carry multiple phones).

@mvglasow you are the SatStat developer? Can you make it work with android 10 and microG? It somehow fails to trigger NLP calculation.

**Comment by mvglasow** [comment]
@kurt-by I am indeed. Should work, though—I have it running here, with two backends, on LOS 17.1 (Android 10). I am getting two markers in the map—one for GPS, one for NLP. SatStat goes through all location providers it can find on the device and tries to get a location from them, no extra magic involved. If SatStat can’t get a location, it means other apps are going to have the same problem.

After doing the APK update, though, I did not get a network location until I rebooted. Seems to be an issue with microG, as the microG config/diagnostic app also did not show an address for the last location (backends installed and active being org.openbmap, GSM Location Service and Nominatim).

**Comment by Ammako** [comment]
> @Ammako thanks for the pointer, will look into it. EDIT: I see the latest release is from 2017, is standalone UnifiedNLP still being maintained?

Latest stable release would hopefully be good enough for most people, but actually, I'm not sure about Android 10.
For 2.0 alpha, I was under the impression that one would just have to build it themselves, but upon further inspection it seems it might not be that simple (?)

Either way, if you got microG GmsCore working, that's a lot easier, so don't worry about it.
