### ISSUE TITLE
Network based location

### ISSUE THREAD

**Issue by dogs-1985** [microg/GmsCore#1345]
I'm using Redmi Note 8 (Ginkgo), [LineageOS for MicroG](https://download.lineage.microg.org/ginkgo/lineage-17.1-20201204-microG-ginkgo.zip), current MicroG version 0.2.14.

I just want my LineageOS automatic change Dark Theme or Night Light based on Schedule (Turn on from sunset to sunrise). 

I installed [crDroid](https://forum.xda-developers.com/t/rom-10-0-crdroidandroid-v6-5-for-redmi-note-8-8t-unified-official.4082247/) and [CAF Android](https://forum.xda-developers.com/t/rom-11-0-stable-caf-android-11-for-rn8-8t-la-um-9-x-vanilla-gapps.4182317/) before, there is no problem at all with MicroG.

I have asked questions on the forum, but no one cares about me and the problem is not solved. I really don't know  whether problem from LineageOS or MicroG itself.

I hope someone can solve my problem.

**Comment by chris42** [comment]
Please be aware, that this is the issue tracker for issues related with microg and not a general support forum. So please consider closing this issue. If you feel this is a microg issue, please make sure you fill in a full bug report

A google search gives me this (I am not sure if this applies, but there is plenty of information out there, you just need to search): https://www.xda-developers.com/android-10-dark-mode-schedule/

**Comment by ale5000-git** [comment]
Have you tried a base LineageOS (without microG)?
Maybe the problem is in the base LineageOS, in that case onyìly them can fix it since LineageOS for MicroG is just plain LineageOS with minor changes.

**Comment by dogs-1985** [comment]
> Please be aware, that this is the issue tracker for issues related with microg and not a general support forum. So please consider closing this issue. If you feel this is a microg issue, please make sure you fill in a full bug report
> 
> A google search gives me this (I am not sure if this applies, but there is plenty of information out there, you just need to search): https://www.xda-developers.com/android-10-dark-mode-schedule/

Network based location not related to MicroG? I didn't know whose problem is, so I ask here.
This is my previous post.
https://github.com/microg/GmsCore/issues/1150

> Have you tried a base LineageOS (without microG)?
> Maybe the problem is in the plain LineageOS, in that case only them can fix it since LineageOS for microG is just plain LineageOS with minor changes.

I lazy reinstall the system again.
I tried to tag developer on xda to take a look at this post.

**Comment by chris42** [comment]
> 
> Network based location not related to MicroG? I didn't know whose problem is, so I ask here.
> This is my previous post.
> #1150
> 
For this issue (1345) I am seeing the following text, which is not related to network based location. So I am not sure if github is broken, or you mixed up issues:

> I'm using Redmi Note 8 (Ginkgo), LineageOS for MicroG, current MicroG version 0.2.14.
> 
> I just want my LineageOS automatic change Dark Theme or Night Light based on Schedule (Turn on from sunset to sunrise).
> 
> I installed crDroid and CAF Android before, there is no problem at all with MicroG.
> 
> I have asked questions on the forum, but no one cares about me and the problem is not solved. I really don't know whether problem from LineageOS or MicroG itself.
> 
> I hope someone can solve my problem.

**Comment by chris42** [comment]
I now get it. This is a full duplicate of #1150 and should be closed.

@dogs-1985 Why do you create a second issue with parts of information? This only confuses people that might be interested to help.

**Comment by dogs-1985** [comment]
> > Network based location not related to MicroG? I didn't know whose problem is, so I ask here.
> > This is my previous post.
> > #1150
> 
> For this issue (1345) I am seeing the following text, which is not related to network based location. So I am not sure if github is broken, or you mixed up issues:
> 
> > I'm using Redmi Note 8 (Ginkgo), LineageOS for MicroG, current MicroG version 0.2.14.
> > I just want my LineageOS automatic change Dark Theme or Night Light based on Schedule (Turn on from sunset to sunrise).
> > I installed crDroid and CAF Android before, there is no problem at all with MicroG.
> > I have asked questions on the forum, but no one cares about me and the problem is not solved. I really don't know whether problem from LineageOS or MicroG itself.
> > I hope someone can solve my problem.

Android dark theme / night light (auto schedule turn on, sunset to sunrise) based on network location. Except google, only MicroG supports network location.

> I now get it. This is a full duplicate of #1150 and should be closed.
> 
> @dogs-1985 Why do you create a second issue with parts of information? This only confuses people that might be interested to help.

I'm really sorry, I thought GitHub post like forum post. 
I thought the previous post was forgotten by developer, so I create new issue. 
I really don't know that what I did was create two same issue to developer.
Or someone help me merge these two posts together?

**Comment by chris42** [comment]
Just close this one, here is no information, that is not already in the original issue.

**Comment by dogs-1985** [comment]
Sorry, duplicate post.
