### ISSUE TITLE
Firefox / Fennec Crashes Tablet

### ISSUE THREAD

**Issue by Richard-Payne** [microg/GmsCore#1346]
**Affected app**
Name: 
  - Firefox (from Aurora)
  - Firefox-beta (from Aurora)
  - Firefox-nightly (from Aurora)
  - Fennec (from F-Droid)
Package id: 
  - org.mozilla.firefox
  - org.mozilla.firefox_beta
  - org.mozilla.fenix
  - org.mozilla.fennec_fdroid/

**Describe the bug**
Opening the app reboots the tablet

**To Reproduce**
1. Install app
2. open app

**Expected behavior**
App loads

**System**
Android Version: 9
Custom ROM: LineageOS 15.1

**microG**
microG Core version: 0.2.14.204215
microG Self-Check results: All ticked

**Additional context**
I'm fairly sure this is directly related to the microg build in LineageOS because I had previously installed the stock LineageOS 15.1 and Fennec loaded fine.  I can't compare Firefox because my previous install had neither GApps nor Microg.

**Comment by ale5000-git** [comment]
The bug is reported here: https://github.com/mozilla-mobile/fenix/issues/5663
The fix is here: https://github.com/LineageOS/android_kernel_cyanogen_msm8974/commit/f44b4b19da1541fce8440ffa1e59cdb722cf10b5

It is a bug in LineageOS but one LineageOS may be affeccted and one another may not, just contact the developers of your ROM.

**Comment by Richard-Payne** [comment]
ok.  So 15.1 is no longer supported so they're not going to back port it and they've dropped support for pollux_windy on later versions of LineageOS.

I know this isn't really a microg issue anymore, but I'd like to ask your advice as a more experienced LineageOS user.  I'm pretty new to this.  
Is this how they operate? Just drop support and start forcing you to build source code to get a version that works on your device?
I thought, and please correct me if I'm wrong, that LineageOS was aimed at all users, not just developers.

**Comment by chris42** [comment]
If I see that correctly, it is a Sony Xperia Tablet Z, hence around 7 years old. You were probably lucky to be able to use it that long. My experience is for most mobile things you get 5 years for the blockbuster devices and around 3-4 years for less popular ones.

It is less forcing you to do anything, other than there is no one left to do the work for you as they have limited resources. Most people maintain devices as a hobby and gift for others. If for a new version there is no one volunteering to do the work, the device gets unsupported. So they operate on a best effort not on a negative strategic basis.

**Comment by Richard-Payne** [comment]
Yeah, I get the lack of maintenance.  Maybe my question was poorly framed.  What caught me off guard was the lack of downloadable binary for 15.1.  They had it, but removed it.  I tried following the build instructions and ended up with some obscure compilation error.  There's a reason I don't do c/c++ unless I have no other choice!  ;)

I downloaded the binary I'm testing from the microg version.  Do you guys lose the binaries some set period after upstream does, or do you hold on to them for longer?

**Comment by chris42** [comment]
The Microg LineageOS versions? I am not involved in the builds, hence can't say how long they stay.

**Comment by Richard-Payne** [comment]
ok, np.  Thanks.

**Comment by ale5000-git** [comment]
You should look at: https://forum.xda-developers.com/

For example for Samsung Galaxy SII that started with Android 2.3.3, it is now still developed and can run Android 11 (obviously unofficially).
