### ISSUE TITLE
Push notifications not working at all when MicroG main configuration app is closed

### ISSUE THREAD

**Issue by Yuri6037** [microg/GmsCore#1348]
**Describe the bug**
When the MicroG main configuration app is closed no notifications are received on any apps supporting push notifications

**To Reproduce**
1. Install FDroid
2. Install MicroG repo in FDroid
3. Install GMS Core from MicroG and enable all permissions including run in background, activate device registration and cloud messaging. The only option to leave not enabled is SafetyNet as there's no way to get it to work on LineageOS 17.1
4. Enable Root adb
5. Run adb root to install the UnififiedNLP NetworkLocation.apk (real pain to do but doable)
6. Install Aurora Store from FDroid (because FDroid is a peace of s*** unable to install proper version of certain apps)
7. Run Aurora Store in anonymous mode
8. Change install settings to force native installer (for some reasons the default method is broken)
9. Install Google Maps from Aurora Store
10. Check if maps works if it does then MicroG works fine otherwise something bad happened in the NetworkLocation.apk install (ignore maps asking you to install google play services, believe me it does not need it)
11. Install Nextcloud and Nextcloud talk from Aurora Store (FDroid versions are f***** up)
12. Run Nextcloud and connect it to your account, do the same with Nextclould talk
13. Now open Nextcloud on your computer (like desktop linux)
14. Shutdown all apps on your phone
15. Send a message from another nextcloud account from your desktop computer
16. Enjoy notification not received on the phone
17. Now open MicroG main configuration app on your phone
18. Repeat step 15
19. Enjoy notification properly received on the phone

**Expected behavior**
MicroG should not require neither background annoying permanent notification or to be keps open in order to receive anything !

**Screenshots**
No screenshot are needed

**System**
Android Version: Android 10
Custom ROM: LineageOS 17.1

**Additional context**
The phone is an old OnePlus 6. The desktop computer is running PopOS 20.10.

The push notifications enabled apps are of course shown in the list in the main MicroG app, if it's not listed then make sure you installed them from Aurora Store (FDroid decided to on purpose f*** up apps that uses push notifications)

EDIT 2: Randomly it will work. You might need to reboot the phone multiple times to cause it to fail. Another option is to lock the screen.

**Comment by Sam-arch99** [comment]
Same here, I've noticed that "microG Services Core" will end up in reboot loop (shown via active apps) if you close the config app via launcher, which results in non working push notifications.
I'm using the latest los4microg build on my S5 plus (16.0-20210112-microG-kccat6, Services Core 0.2.16.204713) with the default Trebuchet launcher.

As a workaround I've hidden the microG config app via launcher and if I need access to the app I do it via Settings >> System >> Advanced >> microG-Settings. It's is kinda annoying but at least it doesn't break the push notifications.

I hope this is getting fixed soon... (could also be an LOS related bug/problem).

**Comment by Sapiosenses** [comment]
@Sam-arch99 

I've had problems with the microG configuration app if I enable the newish setting "Cloud Messaging/Advanced/"Confirm new apps".

Have you tried turning that off, by chance, and see if the app keeps crashing?

**Comment by Yuri6037** [comment]
I have been testing recently the microG for Lineage OS image directly. No more issues to be observed for now.

**Comment by ale5000-git** [comment]
This should be fixed, if there are other problems please open a new issue.
