### ISSUE TITLE
microG randomly loses GCM connection (LineageOS 17.1, OnePlus 3T, microG 0.2.16.204713)

### ISSUE THREAD

**Issue by deesnook** [microg/GmsCore#1359]
**Describe the bug**
After some time, microG loses GCM connection, supposedly when entering doze mode. Logically, push notifications then do not work anymore. Turning on and off device registration and/or cloud messaging in the microG settings does not help, the status remains disconnected. Rebooting the phone does help, though. Usually the GCM connection is then established upon startup (and accordingly push notifications are delivered). 

All self-checks are OK, battery optimization is turned off for both microG Services Core and microG Services Framework Proxy. So far I have set the ping interval to automatic

**To Reproduce**
Steps to reproduce the behavior: set up microG, use phone for a certain period of time, leaving the phone untouched for a while (probably until it goes into doze mode). 

**Expected behavior**
microG should not lose GCM connection, or if it does, it should automatically reconnect

**Screenshots**
Not necessary

**System**
microG: 0.2.16.204713
Android Version: 10
Custom ROM: LineageOS 17.1-20201206-microG-oneplus3 (recent clean install)
OnePlus 3T

**Additional context**
There might be / probably is a relation to the following issues; however, both are slightly different from my experience:
https://github.com/microg/GmsCore/issues/1011 - but I wasn't able to reproduce the issue the way described there
https://github.com/microg/GmsCore/issues/1340 - slightly different error behavior. I don't experience frequent disconnections. However, when I kill the microG settings and restart the app, the connection seems to have been reestablished because the minute count starts from the beginning

**Comment by LeVraiRoiDHyrule** [comment]
I'm having the same issue. I'm on the latest MicroG, Redmi Note 8T (willow) on MSM Xtended XR (official) V4. It's an Android 11 rom.

**Comment by deesnook** [comment]
OK, so today I randomly discovered that the connection loss happens when trying to access mtalk.google.com because I had blocked access to this site using Blokada. Since allowing access again this morning, it seems to have worked without any issues. When blocking mtalk.google.com I even had done some research what it is about, but all I found was that it was used for Google Hangouts, so I didn't draw the conclusion that it also had to do with the functioning of push notifications in general.

@mar-v-in : Can you confirm that GCM needs access to mtalk.google.com? If that's the case, there's probably no bug at all (at least in my case)

**Comment by LeVraiRoiDHyrule** [comment]
I am not using Hangout, my disconnection issues appear right after clean flashing my rom, and installing Microg. I already have connection issues and it can't register apps for GCM.

**Comment by chris42** [comment]
@deesnook Yes, it does: https://github.com/microg/GmsCore/wiki/Helpful-Information (4th point on the list)

**Comment by deesnook** [comment]
@LeVraiRoiDHyrule 
I'm not using Hangouts either, that's why I was surprised that mtalk apparently has to do with push notifications. 
If apps don't register, you have a different problem than I have. 

@chris42 
Oh yes. I didn't see this. I wish I had before :) Thanks for pointing it out. My issue is closed now :)
