### ISSUE TITLE
Adding support for com.google.android.gms.net / Cronet

### ISSUE THREAD

**Issue by dimaryaz** [microg/GmsCore#1360]
Looks like more and more apps (well, Google's apps for now) are requiring Cronet:
- Books (https://github.com/microg/GmsCore/issues/1248)
- Maps (https://github.com/microg/GmsCore/issues/1252)
- Google Fi 
- (probably others)

What would it take to implement it? I.e., is it a matter of adding an existing library (https://chromium.googlesource.com/chromium/src/+/master/components/cronet/ I'm guessing?), or would it require re-implementing everything from scratch?

Is anyone already working on this? If not, I will give it a try.

**Comment by alexdonh** [comment]
Got me S10+ upgraded to Android 11 and some Google's apps just keep crashing with the exact error.

`The bidirectional stream API is not supported by the Java implementation of Cronet Engine`

Google Drive to the list too!

**Comment by dylangerdaly** [comment]
Any updates on this?

**Comment by kolAflash** [comment]
> Google Drive to the list too!

This version is working for me.
https://www.apkmirror.com/apk/google-inc/drive/drive-2-18-152-01-release/
I'm using this APK:
https://www.apkmirror.com/apk/google-inc/drive/drive-2-18-152-01-release/google-drive-2-18-152-01-46-android-apk-download/

**Comment by mstarostik** [comment]
Family Link is affected as well

**Comment by dimaryaz** [comment]
I decided to actually give it a try - except that I'm not an Android developer, so don't know what I'm doing. Made some progress - but got stuck, and hoping that someone here could provide some help.

What I've done so far:
- Built Cronet for Android, using [these instructions](https://chromium.googlesource.com/chromium/src/+/refs/tags/63.0.3236.1/components/cronet/android/build_instructions.md)
- Added out/Debug/cronet/*.jar, out/Debug/cronet/libs/arm64-v8a/libcronet.92.0.4495.0.so to GmsCore
- Added a "com.google.android.gms.cronet_dynamite" module descriptor to GmsCore

Here are [my changes](https://github.com/microg/GmsCore/compare/master...dimaryaz:cronet).

Now, when I run the [Cronet Sample](https://github.com/GoogleChromeLabs/cronet-sample) app, I get the following exception:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.samples.cronet_sample/com.google.samples.cronet_sample.MainActivity}: java.lang.ClassCastException: class org.chromium.net.impl.NativeCronetEngineBuilderImpl cannot be cast to org.chromium.net.ICronetEngineBuilder
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	...
Caused by: java.lang.ClassCastException: class org.chromium.net.impl.NativeCronetEngineBuilderImpl cannot be cast to org.chromium.net.ICronetEngineBuilder
	at java.lang.Class.asSubclass(Class.java:2482)
	at com.google.android.gms.net.PlayServicesCronetProvider.createBuilder(Unknown Source:15)
	at org.chromium.net.CronetEngine$Builder.createBuilderDelegate(CronetEngine.java:333)
	at org.chromium.net.CronetEngine$Builder.<init>(CronetEngine.java:75)
	at com.google.samples.cronet_sample.ViewAdapter.getCronetEngine(ViewAdapter.java:175)
	at com.google.samples.cronet_sample.ViewAdapter.<init>(ViewAdapter.java:53)
	at com.google.samples.cronet_sample.MainActivity.loadItems(MainActivity.java:65)
	at com.google.samples.cronet_sample.MainActivity.onCreate(MainActivity.java:55)
	at android.app.Activity.performCreate(Activity.java:7824)
	....
```

`NativeCronetEngineBuilderImpl` is in fact implementing the `ICronetEngineBuilder` interface, so this shouldn't happen.

My hypothesis is: the sample app relies on the "com.google.android.gms:play-services-cronet:16.0.0" client library which contains its own copy of `ICronetEngineBuilder`. When it loads `NativeCronetEngineBuilderImpl` from GmsCore, that object uses GmsCore's copy of `ICronetEngineBuilder` - which comes from a different class loader, so it's a physically different class, even if it has the same name and the same contents.

I even tried removing `ICronetEngineBuilder` from GmsCore - but that causes `NativeCronetEngineBuilderImpl` to fail to be resolved.

Does anyone know how any of this is supposed to work? @mar-v-in ?

**Comment by mar-v-in** [comment]
The current dynamite loader does not support merging class loaders. This was not required so far, but apparently is in this case.
I've mostly implemented it now, and this does seem to make it work together with @dimaryaz changes. I'll clean things up and hope to get this up and running tomorrow. We then still have to package this properly with multi-arch support and so on.

**Comment by dimaryaz** [comment]
Oh wow, can't wait to try it.

A few questions about packaging Cronet properly:

- How should Cronet be built? A few solutions I can see:
  * Add it to GmsCore build system. Not very practical: it takes 32GB of space and hours to build just one arch.
  * Check in pre-built .jars and .so
  * Add a config option for location of pre-built libraries, and expect the user to build those separately
  * Build it as a separate .apk? Don't know if it's supported by dynamite.
- Should it be an optional dependency?
  * Building Cronet is a pain - but other than that, I can't think of good reasons to exclude it. Also, `./gradlew assembleWithMapboxWithNearbyWithCronetRelease` might be too much.
- Is a single project good enough here? Or should e.g. `cronet_api.jar` be moved to `play-services-cronet-api`?

**Comment by mar-v-in** [comment]
@dimaryaz I pushed the changes in 5d50ae375fd969e587bbdbcee1461f36b7349736. The only thing that needs to be changed to get your work running is to add a `public static final boolean MERGE_CLASS_LOADER = true;` to the `ModuleDescriptor`.

Regarding your questions:
- I would prefer to not have pre-built binaries in the GmsCore repository. My suggestion would be to create a script/tool that allows to build Cronet from source, package it in an `.aar` including the native `.so` for each architecture, and then upload this `.aar` to Maven Central. We can then reference that `.aar` in the `play-services-cronet-core` module in GmsCore. We already do something similar for the patched conscrypt library: https://github.com/microg/conscrypt-gmscore
- No need to make it optional for now. (although multi-architecture builds might turn out a little big, but the solution for this should be to split apk per architecture).
- Would be great to have a split `play-services-cronet-api` module so we could provide a microG version of `play-services-cronet` client library should we ever want to.

**Comment by dimaryaz** [comment]
Nice!

Well, the good news is, it makes Cronet Sample and even Google Maps work. The bad news is: it breaks Google Hangouts. (Ok, maybe not the most useful app these days, but still...)

This is the error:

```
W le.android.tal: Found duplicate classes, falling back to extracting from APK : /data/app/com.google.android.gms-NlHTgaQz9RfOKDMAbV2dOA==/base.apk
W le.android.tal: NOTE: This wastes RAM and hurts startup performance.
W le.android.tal: Found duplicated class when checking oat files: 'LJ/N;' in /data/app/com.google.android.talk-Xpka5V3AB-RCkAHGQoFiEA==/base.apk and /data/app/com.google.android.gms-NlHTgaQz9RfOKDMAbV2dOA==/base.apk
W le.android.tal: 
E gnf     : Babel_App: Uncaught exception in background thread Thread[Hangouts Concurrent Service Network Thread 3,5,main]
E gnf     : Babel_App: java.lang.NoSuchMethodError: No direct method <init>(Lorg/chromium/net/impl/CronetEngineBuilderImpl;)V in class Lorg/chromium/net/impl/CronetUrlRequestContext; or its super classes (declaration of 'org.chromium.net.impl.CronetUrlRequestContext' appears in base.apk)
E gnf     : 	at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(NativeCronetEngineBuilderImpl.java:32)
E gnf     : 	at org.chromium.net.ExperimentalCronetEngine$Builder.build(PG:1)
E gnf     : 	at nhy.a(Unknown Source:334)
E gnf     : 	at osz.a(PG:1)
E gnf     : 	at lcg.a(Unknown Source:12)
E gnf     : 	at osz.a(PG:1)
E gnf     : 	at est.s(PG:1)
E gnf     : 	at nhu.a(PG:4)
E gnf     : 	at gen_binder.root.RootModule$Generated.b(PG:220)
E gnf     : 	at jzk.w(PG:10)
E gnf     : 	at jzk.c(PG:2)
E gnf     : 	at jzk.b(PG:2)
E gnf     : 	at jwc.x(PG:23)
E gnf     : 	at jvu.a(PG:4)
E gnf     : 	at fcc.a(PG:9)
E gnf     : 	at jwc.r(PG:2)
E gnf     : 	at fcl.n(PG:1)
E gnf     : 	at fnl.co(PG:2)
E gnf     : 	at fja.e(PG:13)
E gnf     : 	at bsd.call(Unknown Source:1)
E gnf     : 	at fnb.a(PG:1)
E gnf     : 	at bse.run(PG:9)
E gnf     : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E gnf     : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E gnf     : 	at bsi.run(PG:3)
E gnf     : 	at java.lang.Thread.run(Thread.java:919)
```

Google Hangouts comes with its own version of Cronet (libcronet.89.0.4389.23.so), and our version breaks it.

Now, here's where it gets weird... If you run `dexdump classes2.dex` on the Hangouts apk, you'll see that its version of `CronetUrlRequestContext` has a no-argument constructor:

```
    #1              : (in Lorg/chromium/net/impl/CronetUrlRequestContext;)
      name          : '<init>'
      type          : '(Lptb;)V'
      access        : 0x10001 (PUBLIC CONSTRUCTOR)
      code          -
      registers     : 30
      ins           : 2
      outs          : 16
      insns size    : 297 16-bit code units
```

while our version of `CronetUrlRequestContext` takes a single argument, `CronetEngineBuilderImpl`. So that explains the error. But, I was trying to figure out which version of Cronet introduced the breaking change... and, actually, `CronetUrlRequestContext` has never had a constructor with no arguments. I've literally looked through the whole history of that class. How did Hangouts end up with it? Is it using some non-public, never released version of Cronet?

In any case... is there some way for us to detect that our version is incompatible and shouldn't be used? Hangout's Cronet also has `MODULE_VERSION = 1`, so that does't help. Just blacklist incompatible apps?

**Comment by dimaryaz** [comment]
I misread the method signature. It's not a no-argument constructor - it still has one argument, but the type `CronetEngineBuilderImpl` has been obfuscated as `ptb`. I took apart OpenGApps; it's similarly obfuscated, but has different type names, so apparently they don't have to match.

This looks like a different class loader bug. The sequence of calls is:

- `ExperimentalCronetEngine.Builder.build(...)` from Hangouts
- `NativeCronetEngineBuilderImpl.build(...)` from GmsCore (in fact, Hangouts doesn't have that class at all)
- `new CronetUrlRequestContext(...)` from Hangouts - **but this should have been from GmsCore**

I'm guessing the interface classes (`ICronetEngineBuilder`, etc.) should only be loaded once and shared, but each apk should have its own version of the implementation classes?

**Comment by mar-v-in** [comment]
I added a bit of filtering logic to the class loader, so that the module can configure which classes to merge.
However, just merging the full `org.chromium.net` package seems to not work properly. I excluded some classes, resulting in the following `ModuleDescriptor` configuration:
```
    public static final List<String> MERGED_PACKAGES = Arrays.asList("org.chromium.net");
    public static final List<String> MERGED_CLASSES = Arrays.asList(
            "!org.chromium.net.AndroidNetworkLibrary",
            "!org.chromium.net.NetworkChangeNotifier",
            "!org.chromium.net.NetworkChangeNotifierAutoDetect",
            "!org.chromium.net.ProxyChangeListener",
            "!org.chromium.net.X509Util"
    );
```
This seems to work with a few apps I tested, but further adjustments might be needed. Maybe there is something we can do about the cronet implementation such that these excludes wouldn't be needed, but for now I guess that would be a hack we can work with.

**Comment by dimaryaz** [comment]
That didn't quite work for me - still caused Hangouts to crash... But I think I *almost* figured everything out.

All of the "shared" classes come from `cronet_api.jar`, which actually makes sense. In fact, `cronet_api.jar` should not be included in GmsCore at all - as long as we're using a merged class loader, its classes should be loaded from the client apk. And OpenGApps does not seem to include those classes.

That means, we shouldn't even need the `FilteredClassLoader`... but, for some reason, I still can't get it working without it. I'm sure there's something trivial I'm missing.

For now, I added all classes from `cronet_api.jar` to `MERGED_CLASSES` and removed `cronet_api.jar` itself.

I've [updated my branch](https://github.com/microg/GmsCore/compare/master...dimaryaz:cronet). (Also replaced the binaries with release versions, but that didn't seem to affect anything.)

**Comment by mar-v-in** [comment]
The `FilteredClassLoader` should stay. Without it, classes in the apk using cronet can cause random side effects in cronet itself. I'm also sure that something similar is original Google implementation.
Indeed using a whitelist sounds like a better idea. If the API is sufficiently stable, this should be manageable effort to maintain. I don't think it's wrong to include cronet API with our GmsCore package. If it's really not needed, ProGuard will take care of it. Also this allows us to use cronet ourselves should we ever want to.

**Comment by dimaryaz** [comment]
Ok, makes sense.

Everything works for me in my branch. I meant, Hangouts was crashing when I tried `MERGED_PACKAGES` and `MERGED_CLASSES` from your comment - but it works fine for me with the whitelist. (I have Hangouts 37.0.367279857, LineageOS 10.)

Also, I tried bringing back `cronet_api.jar` ([different branch](https://github.com/microg/GmsCore/compare/master...dimaryaz:cronet-api)) - somehow, that breaks Cronet Sample, even though Google Maps and Hangouts still work. Of course this shouldn't be possible, since the whitelist contains every class from `cronet_api.jar`... I have no idea what's going on. I'll get to the bottom of that eventually, but I guess it's not very important.

I'll try adding a build script for Cronet now.

**Comment by dimaryaz** [comment]
Just created a repo with Cronet build scripts: https://github.com/dimaryaz/cronet/ . I haven't figured out yet how to package the results - create .aar, etc. The scripts aren't perfect; I've tried using your `checkout()` function and split git dir and work tree - but I'm pretty sure that's incompatible with Google's `depot_tools`.

There isn't really a way to fully automate it, so here are the instructions. This requires Linux, btw.

- Run `checkout.sh`: that downloads `depot_tools`, then `chromium` and its dependencies; about 32GB.
- Install build dependencies. Chromium repo has a script for Ubuntu: `chromium/src/build/install-build-deps-android.sh`. I've manually installed everything in Fedora - things like gcc, ninja, gtk3-devel (cause why wouldn't an Android networking library depend on Gtk3?)
- Run `build.sh`. You'll probably run into missing build dependencies here. If it succeeds, you'll have 4 build directories, `chromium/src/out/Release-{arm,arm64,x86,x64}/cronet/`.

I'm guessing this should be in a separate repo, like `conscrypt-gmscore`? If you create one, I can send a PR. Or feel free to just copy/paste and edit my build scripts.

**Comment by dimaryaz** [comment]
Noticed some exceptions in adb log (when opening GMail, I think). Nothing appears to have broken, but still...
```
Caused by: java.lang.UnsatisfiedLinkError: Shared library "/data/app/com.google.android.gms-T9hP_Ov1FyMnKfoi0_h4lw==/base.apk!/lib/arm64-v8a/libcronet.92.0.4495.0.so" already opened by ClassLoader 0x277(dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.android.gms-T9hP_Ov1FyMnKfoi0_h4lw==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-T9hP_Ov1FyMnKfoi0_h4lw==/lib/arm64, /data/app/com.google.android.gms-T9hP_Ov1FyMnKfoi0_h4lw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]]); can't open in ClassLoader 0x7432a6762c(dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.google.android.gms-T9hP_Ov1FyMnKfoi0_h4lw==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-T9hP_Ov1FyMnKfoi0_h4lw==/lib/arm64, /data/app/com.google.android.gms-T9hP_Ov1FyMnKfoi0_h4lw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]])
	at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
	at java.lang.System.loadLibrary(System.java:1667)
	at org.chromium.net.impl.CronetLibraryLoader.ensureInitialized(CronetLibraryLoader.java:71)
	at org.chromium.net.impl.CronetUrlRequestContext.<init>(CronetUrlRequestContext.java:154)
	at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(NativeCronetEngineBuilderImpl.java:32)
	at org.chromium.net.ExperimentalCronetEngine$Builder.build(PG:2)
```

Should the classloader only be created once, and cached?

**Comment by dimaryaz** [comment]
Well, looks like this is officially fixed!

(Whatever is left - figuring why cronet-api is causing problems - should probably be a different issue.)
