### ISSUE TITLE
For huawei

### ISSUE THREAD

**Issue by mandoof1** [microg/GmsCore#1369]
now i know we all hate huawei for locking there bootloader but lets not screw the people that use them over by add a hauwei option in micro g so we can use google services on unrooted my idea is inspired from micro g vanced

**Comment by fareszr** [comment]
you need support for signature spoofing.
which requires root or a custom rom.

vanced micro g works because the main app is designed for it.

**Comment by DarkPhoenix2704** [comment]
Signature Spoofing is required for complete functionality of what MicroG provides. The dev can't do anything & Can @mandoof1 you close this Issue

**Comment by ale5000-git** [comment]
The latest version of microG GmsCore can now spoof another device so it can avoid the ban.
To be able to use the apps that need Google Play Services with microG without signature spoofing you have to patch the apps themself to remove the signature check.
