### ISSUE TITLE
microG settings crash without location permission

### ISSUE THREAD

**Issue by steelman** [microg/GmsCore#1376]
**Describe the bug**
microG settings crash without location permission with [LocalGsmNlpBackend](https://f-droid.org/packages/org.fitchfamily.android.gsmlocation/) installed.

**To Reproduce**
1. Install [LocalGsmNlpBackend](https://f-droid.org/packages/org.fitchfamily.android.gsmlocation/)
2. Go to microG settings
3. Click on "Location modules"
4. Bang! (the app crashes)

**Expected behavior**
List of location modules appears

**System**
Android Version: 10
Custom ROM: LineageOS 17.1

**Workaround**
1. Go to System settings → Applications →microG services → Permissions
2. Enable Location permission

**Comment by WikiBayer** [comment]
I have on CRDroid (Android 11) the self problem

**Comment by herrdeh** [comment]
Still exists 26.09.2024. But easily solvable.

**Comment by ale5000-git** [comment]
The latest version of microG no longer support backends so this issue no longer exist.

@herrdeh
If you have a similar issue in the latest version please open a new ticket with your specific case.
