### ISSUE TITLE
[com.busuu.android.enc] <App Login doesn't work>

### ISSUE THREAD

**Issue by jarnnk** [microg/GmsCore#1378]
**Affected app**
Name: [Busuu]
Package id: [com.busuu.android.enc]

**Describe the bug**
The app login loads infinite. I found no way to work around this.
Also reached the support but I seem to be the only one with this issue.

**To Reproduce**
Install Busuu app
Open and login with a valid account

**Expected behavior**
The login actually happens

**System**
Android Version: 10
Custom ROM: LineageOS 17.1 for microg
Magisk 20.4
Magisk 21.4 (but shouldnt matter)

**microG**
microG Core version: [e.g. 0.2.17.204714]
microG Self-Check results: [All ticked]

**Comment by Oizaro** [comment]
@janniku-kun Unfortunately the login of every app, updated from January, doesn't work anymore.

Have tou tried to login with an old version, and after update it to last one? Working with YouTube (at least).

**Comment by janniku-kun** [comment]
Tried it but same issue till app versions of august.

**Comment by AinzTheSupremeOne** [comment]
Probably related to #1373

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version so I close it for now.
Open a new issue if needed.
