### ISSUE TITLE
Microg 

### ISSUE THREAD

**Issue by WWEANDFURBYYT** [microg/GmsCore#1379]
The vanced microg is not showing me signed in I can't sign in to YT Vanced please fix
![Screenshot_20210127-181905](https://user-images.githubusercontent.com/78121049/106071549-2a0caa00-60cc-11eb-93a1-afb539c19c8c.jpg)

**Comment by gghhkm** [comment]
Bruh close this.

https://github.com/microg/GmsCore/issues/1373

**Comment by ale5000-git** [comment]
Vanced isn't supported by microG, ask in their project => https://github.com/YTVanced/VancedMicroG/issues
PS: If you are also using official microG GmsCore update it to the latest version.
