### ISSUE TITLE
[com.firstrowria.pushnotificationtester] Can not get Cloud Messaging to work at all

### ISSUE THREAD

**Issue by sicherist** [microg/GmsCore#1382]
[2021-01-29-16-32-31.txt](https://github.com/microg/GmsCore/files/5894754/2021-01-29-16-32-31.txt)
**Affected app**
Name: All apps using Cloud Messaging [e.g. pushnotificationtester]
Package id: [e.g. com.firstrowria.pushnotificationtester]

**Describe the bug**
On my Sony Xperia Z5 compact with LineageOS 18.1 I have all the boxes checked in microG self-test but cloud messaging isn't working. Google device registration is enabled, Cloud messaging is enabled, and seems to connect fine.

There are no apps registered and newly installed apps won't even ask for push-permission. The "confirm new apps" setting doesn't change it.

The app "Push Notification Tester" from aurora-store fails in step one with a red X at "register for Push notifications".

I read in some threads that could try to dial #*#*CHECKIN#*#* to enable cloud messaging but this didn't change anything.

One thing I noticed is that every time i reboot "google device registration is off".

I also downgraded to a LineageOS 14.1 ROM but same behaviour.

I tried both manual and Nanodroid installation. No difference.

I do not use Magisk

I do not have a google-account. Is this a problem?

**System**
Android Version: 7
Custom ROM: LineageOS 14.1

**microG**
microG Core version: [e.g. 0.2.17.204714]
microG Self-Check results: All ticked

**Additional context**
Logcat attached.

**Comment by chris42** [comment]
You do not need a google account for this.

Few things you should check:
- See that you have per app registration turned off
- after using the CHECKIN command you need to reinstall the app again

**Comment by sicherist** [comment]
Thanks for clarification that a google account is not necessary. I had already tried both settings.
After downgrading gms core to 0.2.15.204713 as suggested in #1329 cloud messaging now works flawlessly.

**Comment by maxcco** [comment]
I can reproduce the problem on Lineage 18.1 and fix the same way downgrade to 0.2.15.204713

same setup as sicherist :
xperia z5c

System
Android Version: 11
Custom ROM: LineageOS 18.1

microG
microG Core version: [e.g. 0.2.17.204714]
microG Self-Check results: All ticked

**Comment by mrtndwrd** [comment]
I have the exact same problem with `microg` version `0.2.17.204714` on Lineage 17.1 (`lineage-17.1-20210126-microG-cheeseburger.zip` to be precise)

**Comment by Master0ne** [comment]
Issue confirmed with microG Services Core Version `0.2.17.204714` and `0.2.16.204713` on ArrowOS 11 on a POCO X3 NFC, as well as the fix by downgrading to to `0.2.15.204713`.

**Comment by mrtndwrd** [comment]
I managed to downgrade to microg 2.14 by building the magisk module for an [older version](https://github.com/Magisk-Modules-Repo/microG_installer/commit/1f63cf7fd95f971d12a60d89ab8b997a325bf2f1). I'll attach it to this message if it helps anyone.

I can confirm that after downgrading I can register for push messages and they work in the Push Notification Tester app. *Then* I can upgrade microg to the newest version and push messages still works. This makes me think that the Google Device Registration is the thing that's broken in the newest version.

**Comment by NateTheSage** [comment]
@mrtndwrd Thanks for that. That Magisk module worked for me too, and keeps working as long as I blacklist GmsCore's updates on F-Droid, which is good enough for now but undesirable long-term.

However, for my situation, upgrading to the latest version of GmsCore causes the same issue where it appears device registration continually fails. I'm running SuperiorOS Android 11 on payton.

I also have another, most likely unrelated issue where GmsCore does not get to access background location or SMS, and trying to flip these permissions on in System Settings presents no change. But I am able to connect to FCM, so for me this is a nonissue.

**Comment by chris42** [comment]
I just set up a new device. For me device registration was deactivating when trying to set the first time. Had to reactivate it, only then push notification registration would work.

**Comment by Frivolous2** [comment]
Same issue, LOS 17.1.

**Comment by Master0ne** [comment]
> I also have another, most likely unrelated issue where GmsCore does not get to access background location or SMS, and trying to flip these permissions on in System Settings presents no change. But I am able to connect to FCM, so for me this is a nonissue.

I had [the same issue](https://github.com/nift4/microg_installer_revived/issues/16) with the microG Installer Revived Magisk Module but could not help the developer analyze that problem as I already have moved on to manual installation. You may want to have a look and help @nift4 to fix the issue.

**Comment by mrtndwrd** [comment]
> I also have another, most likely unrelated issue where GmsCore does not get to access background location or SMS, and trying to flip these permissions on in System Settings presents no change. But I am able to connect to FCM, so for me this is a nonissue.

I actually have this issue as well, but I haven't noticed anything not working yet (apart from the self-check checkmarks). I'll check the issue MasterOne linked to above and see if it helps, or if I can provide more logs.

**Comment by Mrnofish** [comment]
A simple workaround is linked in issue #1408.

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version so I close it for now.
Open a new issue if needed.
