### ISSUE TITLE
Connection with chromecast 

### ISSUE THREAD

**Issue by vmct92** [microg/GmsCore#1387]
I can't use youtube Vance with chromecast in the last update. 
The app can't find the chromecast, but in YouTube app and another app can do

![Screenshot_2021-02-02-11-38-21-549_com vanced android youtube](https://user-images.githubusercontent.com/78432275/106624261-d70f7880-654b-11eb-849e-89e202a27962.jpg)
![Screenshot_2021-02-02-11-38-31-791_com vanced android youtube](https://user-images.githubusercontent.com/78432275/106624269-db3b9600-654b-11eb-83b4-8ecf6c08b41e.jpg)

**Comment by i0r14** [comment]
Look at this:
https://github.com/microg/GmsCore/issues/79
It says "closed" but this functionality is still not working.

**Comment by ale5000-git** [comment]
Cast is currently not working but I'm closing this ticket in favor of #580
