### ISSUE TITLE
Unable to log in to the App with MicroG

### ISSUE THREAD

**Issue by Vstory** [microg/GmsCore#1388]
**Describe the bug**
[AppSales](https://play.google.com/store/apps/details?id=net.tsapps.appsales) Cannot log in with MicroG.

**To Reproduce**
After installing MicroG, click login in AppSales, but no response.

**Expected behavior**
After installing MicroG, click Login in AppSales to log in normally.

**Screenshots**

![QQ图片20210203112808](https://user-images.githubusercontent.com/20795557/106694151-f45b4a00-6612-11eb-9e4c-d07c32a68fa2.jpg)

![QQ图片20210203113013](https://user-images.githubusercontent.com/20795557/106694297-397f7c00-6613-11eb-9ab8-3ce012ea859b.png)

**System**
Android Version: 9
Custom ROM: MIUI 12 20.6.18

**Comment by gghhkm** [comment]
#1373

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version of microG GmsCore so I close it for now.
Open a new issue if needed.
