### ISSUE TITLE
Vanced stopped recognizing my Google account

### ISSUE THREAD

**Issue by Lyzder** [microg/GmsCore#1390]
Just yesterday, I created a brand account and transfered my channel there. After the process was complete, YT Vanced stopped recognizing my Google account: it says I have to login, but it doesn't list any accounts.
I tried deleting and adding my account again, through MicroG and Vanced, to no avail. The official YT app recognizes my account without problem.
My device is a Huawei Y7

**Comment by Ammako** [comment]
microG is not responsible for Vanced, you'll have to ask them

https://github.com/YTVanced/VancedMicroG/issues
https://github.com/YTVanced/Vanced/issues

**Comment by Ammako** [comment]
#1373 may be related

**Comment by ale5000-git** [comment]
Vanced isn't supported by microG, ask in their project.
PS: If you are also using official microG GmsCore update it to the latest version.
