### ISSUE TITLE
MicroG Status "not connected"

### ISSUE THREAD

**Issue by tgaertner** [microg/GmsCore#1392]
**Describe the bug**
MicroG shown not connected all the time.
No MicroG Service is working.
The check shows all boxes checked.

**System**
Phone: Motorola MotoG7
Android Version: 10
Custom ROM: LineageOS 17.1

**Additional context**
Used the Rom from https://lineage.microg.org/

Installed the "Signature Spoofing Checker" App from F-Droid - and it says that signature spoofing is disabled - maybe this info helps.

I realized that on my wifes Phone (BQ AquarisX2 - with LineageOS 16) has the same problem.

If you need further information I'm glad to help to dig deeper into it.

**Comment by Ammako** [comment]
> Installed the "Signature Spoofing Checker" App from F-Droid - and it says that signature spoofing is disabled - maybe this info helps.

Lineage for microG only grants signature spoofing permissions to priv-apps. Therefore, user apps like this signature spoofing checker can't be granted the permission to check for it. If the self-check says it's working, then you don't have to worry.

If you're referring to cloud messaging, try entering *#*#2432546#*#* in your dialer and see if it helps.

**Comment by tgaertner** [comment]
Thanks for investigating.
Yea I saw the dialer thing in some help topics and tried about 10 times - no difference.

BUT Yesterday and today in the morning I got some push notification from a registered app - so I looked into the microG settings and it showed "connected" - sadly after 40 seconds it went back to "not connected". Is this maybe a problem with "the other side" - google API or whatever? I used microG on my old Aquaris X for some years - without any problems...

With the current situation its sadly absolutely useless. 

Also trying to enable "Mozilla Location Service" does not work. The switch turns back to off emidiately and it looks like the notification bar swipes down - or some shadow - but I don't see any error or so. Could this be related? (btw. on my wifes phone its possible to enable the Mozilla Location Service)

**Comment by tgaertner** [comment]
Feedback on this: So randomly 2 or 3 times a day it connects and all the old push notifications come in. After about 15seconds it disconnect again and no push notifications coming in. Am I the only one having this issue?

**Comment by tgaertner** [comment]
Finally I found the issue...
I realized that when I'm not connected to my home wlan it works...so searching for what was blocking it I realized that my pihole was blocking mtalk.google.com ....

Whitelised that Domain and voila... it works now smooth.
Thanks for all investigation on that.

**Comment by maribu** [comment]
In case someone else stumbles upon this after installing LineageOS 20 with microG: By default both GSM Core and F-Droid have internet access disabled in the apps settings (at least on a dirty install).

1. Settings -> Apps -> See all <number> apps
2. Select "mircoG Services Core"
3. Open "Mobile data and Wi-Fi"
4. Enable "Allow network access"

(Same for F-Droid.)
