### ISSUE TITLE
microG gms core crashed

### ISSUE THREAD

**Issue by WanderMax** [microg/GmsCore#1400]
Here is the log as below

02-22 10:01:42.063: D/GmsDummySvc(32408):  onBind: Intent { act=com.google.android.gms.usagereporting.service.START pkg=com.google.android.gms }
02-22 10:01:42.171: D/GmsDummySvc(32408):  bound by: GetServiceRequest{serviceId=USAGE_REPORTING, gmsVersion=10298000, packageName='com.gh4a', extras=Bundle[{}]}
02-22 10:02:16.834: W/AccTypeManager(11798):  Skipping extension package com.google.android.gms ( com.google) because it doesn't have the CONTACTS_STRUCTURE metadata
02-22 10:03:37.526: D/BoostFramework(1774):  perfHint : hint: 0x1081 pkg_name(userDataStr): com.google.android.gms:ui duration(userData1): 2000 type(userData2): 1
02-22 10:03:37.532: I/ActivityManager(1774):  START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.google.android.gms/org.microg.gms.ui.SettingsActivity bnds=[106,1630][413,2060]} from uid 10098 pid 3107
02-22 10:03:37.561: D/ANDR-PERF-ACT-TRIG(1774):  start activity com.google.android.gms/org.microg.gms.ui.SettingsActivity/204714034
02-22 10:03:37.561: D/ActivityTrigger(1774):  activityStartTrigger: Activity is Triggerred in full screen ApplicationInfo{270744b com.google.android.gms}
02-22 10:03:37.561: E/ActivityTrigger(1774):  activityStartTrigger: not whiteListedcom.google.android.gms/org.microg.gms.ui.SettingsActivity/204714034
02-22 10:03:37.561: D/ActivityTrigger(1774):  activityResumeTrigger: The activity in ApplicationInfo{270744b com.google.android.gms} is now in focus and seems to be in full-screen mode
02-22 10:03:37.568: D/ActivityTrigger(1774):  activityResumeTrigger: The activity in ApplicationInfo{270744b com.google.android.gms} is now in focus and seems to be in full-screen mode
02-22 10:03:37.587: I/ActivityManager(1774):  Start proc 10446:com.google.android.gms:ui/u0a61 for activity com.google.android.gms/org.microg.gms.ui.SettingsActivity
02-22 10:03:37.587: D/BoostFramework(1774):  perfHint : hint: 0x1081 pkg_name(userDataStr): com.google.android.gms:ui duration(userData1): -1 type(userData2): 3
02-22 10:03:37.631: V/StorageRedirectInject(10446):  nativeForkAndSpecialize: package=com.google.android.gms, uid=10061
02-22 10:03:37.631: V/StorageRedirectInject(10446):  install hook: package=com.google.android.gms, user=0
02-22 10:03:37.663: D/InputDispatcher(1774):  setFocus: AppWindowToken{9f2171f token=Token{1c9611a ActivityRecord{4d7d3c5 u0 com.google.android.gms/org.microg.gms.ui.SettingsActivity t11402}}}
02-22 10:03:37.716: I/RecentsTaskLoadPlan(2130):  task(11402,com.google.android.gms,false)
02-22 10:03:37.895: I/zygote64(10446):    at void org.microg.gms.ui.SettingsActivity.onCreate(android.os.Bundle) (SettingsActivity.java:29)
02-22 10:03:37.895: I/zygote64(10446):  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/lib/arm64, /data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
02-22 10:03:37.895: I/zygote64(10446):    at void org.microg.gms.ui.SettingsActivity.onCreate(android.os.Bundle) (SettingsActivity.java:29)
02-22 10:03:37.896: I/zygote64(10446):    at void org.microg.gms.ui.SettingsActivity.onCreate(android.os.Bundle) (SettingsActivity.java:29)
02-22 10:03:37.896: I/zygote64(10446):  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/lib/arm64, /data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
02-22 10:03:37.896: I/zygote64(10446):    at void org.microg.gms.ui.SettingsActivity.onCreate(android.os.Bundle) (SettingsActivity.java:29)
02-22 10:03:37.897: I/zygote64(10446):    at void org.microg.gms.ui.SettingsActivity.onCreate(android.os.Bundle) (SettingsActivity.java:29)
02-22 10:03:37.897: I/zygote64(10446):  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/system/framework/com.android.location.provider.jar", zip file "/data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/lib/arm64, /data/app/com.google.android.gms-HI_nqenrnqiLeMyInotPwQ==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
02-22 10:03:37.897: I/zygote64(10446):    at void org.microg.gms.ui.SettingsActivity.onCreate(android.os.Bundle) (SettingsActivity.java:29)
02-22 10:03:38.102: I/System.out(10446):  [xxx]:packageName=com.google.android.gms
02-22 10:03:38.222: D/InputMethodManagerService(1774):  Switching to client com.google.android.gms(10446), IME=com.baidu.input_huawei/.ImeService
02-22 10:03:38.274: I/ActivityManager(1774):  Displayed com.google.android.gms/org.microg.gms.ui.SettingsActivity: +704ms
02-22 10:03:38.366: D/ULocClient(10446):  Binding to Intent { act=org.microg.nlp.service.UnifiedLocationService pkg=com.google.android.gms }
02-22 10:03:38.368: D/ULocService(32408):  onBind: Intent { act=org.microg.nlp.service.UnifiedLocationService pkg=com.google.android.gms }
02-22 10:03:38.373: D/ULocClient(10446):  Connected to ComponentInfo{com.google.android.gms/org.microg.nlp.service.UnifiedLocationServiceEntryPoint}
02-22 10:03:38.405: D/ULocService(32408):  registerLocationCallback[com.google.android.gms]
02-22 10:03:38.407: D/ULocService(32408):  setUpdateInterval[com.google.android.gms] interval: 0
02-22 10:03:38.414: D/ULocClient(10446):  Binding to Intent { act=org.microg.nlp.service.UnifiedLocationService pkg=com.google.android.gms }
02-22 10:03:38.416: D/ULocService(32408):  onBind: Intent { act=org.microg.nlp.service.UnifiedLocationService pkg=com.google.android.gms }
02-22 10:03:38.417: D/ULocClient(10446):  Connected to ComponentInfo{com.google.android.gms/org.microg.nlp.service.UnifiedLocationServiceEntryPoint}
02-22 10:03:38.419: D/ULocService(32408):  registerLocationCallback[com.google.android.gms]
02-22 10:03:38.419: D/ULocService(32408):  setUpdateInterval[com.google.android.gms] interval: 0
02-22 10:03:39.136: I/RecentsTaskLoadPlan(2130):  task(11402,com.google.android.gms,false)
02-22 10:03:39.430: I/RecentsTaskLoadPlan(2130):  task(11402,com.google.android.gms,false)
02-22 10:03:39.586: I/RecentsTaskLoadPlan(2130):  task(11402,com.google.android.gms,false)
02-22 10:04:06.269: W/ContextImpl(3058):  Failed to ensure /data/user/0/com.google.android.gms/shared_prefs: mkdir failed: EACCES (Permission denied)
02-22 10:04:49.860: I/RecentsTaskLoadPlan(2130):  task(11402,com.google.android.gms,false)
02-22 10:04:50.037: I/RecentsTaskLoadPlan(2130):  task(11402,com.google.android.gms,false)
02-22 10:04:50.801: I/ActivityManager(1774):  Killing 10446:com.google.android.gms:ui/u0a61 (adj 900): remove task
02-22 10:04:50.803: I/ActivityManager(1774):  Killing 5401:com.google.android.gms:persistent/u0a61 (adj 800): remove task
02-22 10:04:50.837: W/InputDispatcher(1774):  channel '5de98a5 com.google.android.gms/org.microg.gms.ui.SettingsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-22 10:04:50.837: E/InputDispatcher(1774):  channel '5de98a5 com.google.android.gms/org.microg.gms.ui.SettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-22 10:04:50.837: I/WindowManager(1774):  WINDOW DIED Window{5de98a5 u0 com.google.android.gms/org.microg.gms.ui.SettingsActivity}
02-22 10:04:50.837: W/InputDispatcher(1774):  Attempted to unregister already unregistered input channel '5de98a5 com.google.android.gms/org.microg.gms.ui.SettingsActivity (server)'
02-22 10:04:50.843: W/ActivityManager(1774):  Scheduling restart of crashed service com.google.android.gms/org.microg.gms.gcm.PushRegisterService in 1000ms
02-22 10:04:50.879: D/HtcAppOpsGuardDog:au(2952):   check Process: [runIn=0] uid=10061, pid=32408, package=com.google.android.gms, process=com.google.android.gms, importance=IMPORTANCE_FOREGROUND: {100 (0x64)}, processState=PROCESS_STATE_BOUND_FOREGROUND_SERVICE: {3 (0x3)} ...
02-22 10:04:50.879: D/HtcAppOpsGuardDog:HtcAutoStartGuardService(2952):   [2952/3121][user:0/0/0/1000/1000]:  the package is running. (uid=10061, pkg=com.google.android.gms).
02-22 10:04:50.883: D/HtcAppOpsGuardDog:au(2952):   check Process: [runIn=0] uid=10061, pid=32408, package=com.google.android.gms, process=com.google.android.gms, importance=IMPORTANCE_FOREGROUND: {100 (0x64)}, processState=PROCESS_STATE_BOUND_FOREGROUND_SERVICE: {3 (0x3)} ...
02-22 10:04:50.883: D/HtcAppOpsGuardDog:HtcAutoStartGuardService(2952):   [2952/3121][user:0/0/0/1000/1000]:  the package is running. (uid=10061, pkg=com.google.android.gms).
02-22 10:04:51.844: W/ActivityManager(1774):  Scheduling restart of crashed service com.google.android.gms/org.microg.gms.gcm.PushRegisterService in 1000ms
02-22 10:04:52.865: I/ActivityManager(1774):  Start proc 10501:com.google.android.gms:persistent/u0a61 for service com.google.android.gms/org.microg.gms.gcm.PushRegisterService
02-22 10:04:52.904: V/StorageRedirectInject(10501):  nativeForkAndSpecialize: package=com.google.android.gms, uid=10061
02-22 10:04:52.904: V/StorageRedirectInject(10501):  install hook: package=com.google.android.gms, user=0
02-22 10:04:53.012: E/AndroidRuntime(10501):  Process: com.google.android.gms:persistent, PID: 10501
02-22 10:04:53.012: E/AndroidRuntime(10501):  java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@c742e77 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference
02-22 10:04:53.012: E/AndroidRuntime(10501):  	at org.microg.gms.gcm.PushRegisterService.onStartCommand(PushRegisterService.kt:115)
02-22 10:04:53.018: E/ActivityManager(1774):  App crashed! Process: com.google.android.gms:persistent
02-22 10:04:53.037: I/ActivityManager(1774):  Showing crash dialog for package com.google.android.gms u0
02-22 10:04:54.926: I/ActivityManager(1774):  Killing 10501:com.google.android.gms:persistent/u0a61 (adj 0): crash
02-22 10:04:54.962: D/InputDispatcher(1774):  Touched window was removed: Window{de07f87 u0 Application Error: com.google.android.gms}
02-22 10:04:54.970: D/HtcAppOpsGuardDog:au(2952):   check Process: [runIn=0] uid=10061, pid=32408, package=com.google.android.gms, process=com.google.android.gms, importance=IMPORTANCE_FOREGROUND: {100 (0x64)}, processState=PROCESS_STATE_BOUND_FOREGROUND_SERVICE: {3 (0x3)} ...
02-22 10:04:54.970: D/HtcAppOpsGuardDog:HtcAutoStartGuardService(2952):   [2952/3121][user:0/0/0/1000/1000]:  the package is running. (uid=10061, pkg=com.google.android.gms).

**Comment by mar-v-in** [comment]
Should be fixed as of ecfe3da3f7573e3d66a1ad9c12e8a08bbeae307b
