### ISSUE TITLE
Whatsapp doesn't sync messages

### ISSUE THREAD

**Issue by aka56kg** [microg/GmsCore#1406]
**Affected app**
Name: [e.g. WhatsApp]
Package id: [e.g. com.whatsapp]

**Describe the bug**
Can't sync whatsapp messages, when clicking on sync, it shows that i need to add an google account, when i add account, it shows that google account already exists 

**To Reproduce**
1. Install Whatsapp
2. Click on agree and continue
3. Login with phone number
4. Click on continue (Message backup with Google Drive)
5. Click on give permission
6. Click on add account
7. Click on sign in
8. Enter your email and click next
9. It shows that my google account is already exists on this device

**Expected behavior**
Expected to sync whatsapp messages

**System**
Android Version: [e.g. 10]
Custom ROM: [e.g. iodéOS]

**microG**
microG Core version: [e.g. 0.2.15.204713-iode.7]
microG Self-Check results: [e.g. All ticked]

**Comment by 1Maxnet1** [comment]
I can confirm this behaviour on my System:

System
Android Version: 9
Custom ROM: unofficial LineageOS

microG
microG Core version: 0.2.17.204714
microG Self-Check results: All ticked

@SnusVeteranus Make sure to fill out the complete Template to help the developers ;)

**Comment by jimbob88** [comment]
Just had this problem too, in order to fix it:

`Android Settings -> Accounts -> Google -> Account Preferences -> Allow apps to find accounts (enable)`

This allowed me to install and get google backup working with WhatsApp (Android 9.0 [CR-7.0])

**Comment by Milor123** [comment]
@jimbob88 Thank you very much !!! its works for me in the 2021!!!

**Comment by mhl787156** [comment]
> Just had this problem too, in order to fix it:
> 
> `Android Settings -> Accounts -> Google -> Account Preferences -> Allow apps to find accounts (enable)`
> 
> This allowed me to install and get google backup working with WhatsApp (Android 9.0 [CR-7.0])


Just wanted to add for future people, this currently works for me too in 2022 - BUT my `allow apps to find accounts` was already enabled. I had to disable and re-enable and then it started working! 

Running Iode 3.1, microg 0.2.24.214816-iode.20
