### ISSUE TITLE
Device Registration and SafetyNet reverting to Off after every reboot; push notifications not working

### ISSUE THREAD

**Issue by Mrnofish** [microg/GmsCore#1408]
## Observed behavior

After every reboot, Device Registration and SafetyNet revert to off. GCM is stuck on On and cannot be disabled. Push notifications do not work.

**To Reproduce**
1. Install MicroG
2. Enter MicroG Settings
3. Switch Device Registration, Cloud Messaging and SafetyNet ON.
4. Reboot
5. Enter MicroG Settings
6. Verify Device Registration and SafetyNet are now OFF
7. Check Cloud Messaging and verify there are ZERO apps registered.

## Expected behavior
The settings should be preserved and Cloud Messaging should work

## System
Android Version: 10
Custom ROM: LineageOS 17.1

## Workaround
[A workaround for this issue has been reported on r/MicroG](https://www.reddit.com/r/MicroG/comments/kuhgse/device_registration_and_push_notifications/girx53t) and I have verified it to work.

In my case, disabling Cloud Messaging wasn't possible as it was stuck on ON, but otherwise the procedure worked flawlessly and restored operation as intended.

**Comment by Mrnofish** [comment]
Related issues: #1382 and #1329. See this issue for a workaround that doesn't involve downgrading.

**Comment by famo** [comment]
FTR, these are the steps as posted on reddit:
> I disabled BOTH device registration and GCM and rebooted.
> Then I only enabled device registration and rebooted.
> Then I enabled GCM too and rebooted.
> Aaaand now it works.

In my case, I also couldn't disable GCM, so I just rebooted, enabled device registration rebooted, then installed signal and it registered with GCM.

However, I wasn't able to make Telegram (FOSS) register with GCM, even after re-install...

**Comment by Mrnofish** [comment]
I have Telegram in my Work Profile managed by Shelter and it is registered and receiving messages. Notifications are not being triggered, but this might be a different issue, not sure.

OTOH, I've been having issues with Firefox.

MicroG claims the app is registered, but in the details, 0 messages have been received. I can confirm that the Send to Tab feature, which relies on Cloud Messaging, does not work, except when the app is restarted.

**Comment by Kaleb-Reid** [comment]
> However, I wasn't able to make Telegram (FOSS) register with GCM, even after re-install...

Telegram-FOSS wont register because it doesn't have FCM/GCM support

**Comment by MrNessuno** [comment]
Same behaviour, every reboot Device registration goes Off with SafetyNet and also apps can't register to GCM, like Whatsapp for example so I can't receive notifications.

Android 11
FakeGApps + EdExposed
MicroG: 2.18.204714.204714036

**Comment by Redsandro** [comment]
Same behavior, but __I cannot turn device registration on.__ Workaround does _not_ work. Device registration and GMC suddenly turns __on after 6 hours.__ With a reboot, everything reverts to none (not on, not off, but nothing). Wait six hours; working again.

Android 11
OmniROM 11 20210523-raphael-MICROG
MicroG 0.2.19.21515

**Comment by RobertoWa** [comment]
issue #1329 post by jkehne from 21. march solves the problem switches turn off after reboot.

i recommend to wipe data of gms core on any issue after updating to newer version and edit the config file of gms mentioned by jkehne. after reboot gms works as it should be.

**Comment by q1nt** [comment]
Found a way to completely reset GMS prefs BUT only if you have root

   1) go to /data/data/com.google.android.gms/shared_prefs
   2) back up com.google.android.gms_preferences.xml
   3) delete the file, which will rebuild after reboot

This method is based on nanodroid-util, which includes
`reset_gms_data () { if [ -z ${1} ]; then find /data/data/*/shared_prefs -name com.google.android.gms.*.xml -delete`

**Comment by ale5000-git** [comment]
The bug should already been fixed, just update to v0.2.22.212658

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version so I close it for now.
Open a new issue if needed.
