### ISSUE TITLE
Deny/Allow App Registration popup comes up blank

### ISSUE THREAD

**Issue by Mrnofish** [microg/GmsCore#1410]
**Describe the bug**
When Confirm New App is Enabled in Cloud Messaging, the Deny/Allow popup is blank, and not showing the name of the app trying to register.

**To Reproduce**
1. In MicroG Settings > Cloud Messaging > Advanced, enable Confirm New App
2. Install any application that uses Cloud Messaging
3. When the application tries to register, a popup will be displayed

**Expected behavior**
The popup should show the name of the app trying to register for Cloud Messaging.

**System**
Android Version: 10
Custom ROM: LineageOS 17.1 nightly 21-02-28

**Comment by mar-v-in** [comment]
Should be fixed via 91b0f6893f9848354af7654b3cebc842615bcd7f.

**Comment by mar-v-in** [comment]
0.2.19 is released and is available in microG F-Droid repository or via [GitHub release page](https://github.com/microg/GmsCore/releases/tag/v0.2.19.211515).
