### ISSUE TITLE
[com.google.android.gms] GmsCore (0.2.17.204714) frequent crashes

### ISSUE THREAD

**Issue by token0** [microg/GmsCore#1419]
**Affected app**
Name: GmsCore
Package id: com.google.android.gms

**Describe the bug**
GmsCore crashes

from the logcat:

> java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@fd809f1 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference

**To Reproduce**
1. Nothing, it crashes on it's own

**System**
Android Version: 7.1.2
Stock ROM: Sony Xperia Z5 Compact E5823 32.4.A.1.54

**microG**
microG Core version: 0.2.17.204714
microG Self-Check results: All ticked

**Additional context**
[system_app_crash@1615376764715.txt](https://github.com/microg/GmsCore/files/6115758/system_app_crash%401615376764715.txt)

**Comment by token0** [comment]
Same for 0.2.**18**.204714

> java.lang.RuntimeException: Unable to start service org.microg.gms.gcm.PushRegisterService@e6162b1 with null: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Intent.getIntExtra(java.lang.String, int)' on a null object reference*

**Comment by mar-v-in** [comment]
Should be fixed as of ecfe3da3f7573e3d66a1ad9c12e8a08bbeae307b
