### ISSUE TITLE
[com.meteociel.fr] Crash in org.microg.gms.gcm.RegisterRequest.extraParams

### ISSUE THREAD

**Issue by bellegarde-c** [microg/GmsCore#1424]
**Affected app**
Name: Meteociel
Package id: com.meteociel.fr
https://play.google.com/store/apps/details?id=com.meteociel.fr&hl=fr&gl=US

**Describe the bug**
App crash on startup

**To Reproduce**

[meteociel.txt](https://github.com/microg/GmsCore/files/6134959/meteociel.txt)

**System**
Android Version: 10
Custom ROM: LineageOS 17.1

**microG**
microG Core version:  0.2.18
microG Self-Check results: All ticked

**Comment by chris42** [comment]
You probably should update to the latest version of microg and verify, that the bug is still existent. 
Preview release is already at 0.2.18

**Comment by bellegarde-c** [comment]
Sorry, I use last version com.google.android.gms-204714036.apk

**Comment by bellegarde-c** [comment]
Just found that the application servers are down since https://twitter.com/olesovhcom/status/1369478732247932929

Should be related, sorry for noise.

**Comment by Ammako** [comment]
Still, microG could probably handle these kinds of cases more gracefully, rather than letting apps crash.
