### ISSUE TITLE
No sound in latest lineage+microg for harpia

### ISSUE THREAD

**Issue by aldonogueira** [microg/GmsCore#1431]
**Describe the bug**
The latest OTA update broke sound in every application. Even in system settings, no sound is reproduced either through the speakers or using a headphone. Some applications like a metronome crash and others say they can't reproduce sound

**To Reproduce**
1. You have a perfectly working Moto G4 Play (harpia) using [lineage+microg 17.1-20210201](https://download.lineage.microg.org/harpia/lineage-17.1-20210201-microG-harpia.zip)
2. Update the system to [lineage+microg 17.1-20210328](https://download.lineage.microg.org/harpia/lineage-17.1-20210328-microG-harpia.zip)
3. Sound is gone

**System**
Android Version: 10
Custom ROM: LineageOS 17.1

**Additional context**
I tried to revert to the previous build, but then I couldn't even unlock the phone that something crashed

**Please remove the latest OTA update as soon as possible**
I tried to talk to the people behind lineage+microg, but it's extremely difficult to find any contact. This is maybe not the proper place to talk about this, but I hope you guys know how to contact them

**Comment by JonnyTech** [comment]
This is the incorrect place to report lineageos bugs, please close this idsue and post one with them.

**Comment by aldonogueira** [comment]
Where? I tried really hard to find the right place to report it.  

If you guys don't help me, this bug will be forgotten. I can easily solve my problem installing other ROM, but I'm trying to help the project and other users as well

**Comment by JonnyTech** [comment]
According to [their bug reporting template](https://lineage.microg.org#bugreporting), either at [gitlab issues](https://gitlab.com/LineageOS/issues/android) or the [xda thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/)

**Comment by aldonogueira** [comment]
Thanks, JonnyTech.  

I'm sending a message in the XDA forum so they remove the update as soon as possible, but I'm also trying to report the bug in the appropriate project.
