### ISSUE TITLE
Among us not working online

### ISSUE THREAD

**Issue by MijoHuer** [microg/GmsCore#1432]
I have Google Auth fail when tried to log in and the online game doesnt work (the gane tries to search a match but doesn't found any)

![Screenshot_20210331-204304_Among_Us](https://user-images.githubusercontent.com/78889806/113224433-d4868200-9261-11eb-9321-e5ebcfcf4477.png)

Using microg 2.18.204714

**Comment by MijoHuer** [comment]
Nevermind, it was a error of the game itself

**Comment by Axolord** [comment]
If the issue is resolved, please close

**Comment by rednaz1337** [comment]
How did you fix this? I have the same error.

**Comment by sricks** [comment]
I'm able to join online lobbies, but when the game starts, it's a black screen (can still hear audio). No clue if it's GSF/MicroG problem or not. No error message.

Using CalyxOS with Pixel 4a
