### ISSUE TITLE
[com.urbandroid.sleep] "Update Google Play Services" / cannot update or run v20210403

### ISSUE THREAD

**Issue by Mrnofish** [microg/GmsCore#1438]
**Affected app**
Name: Sleep as Android
Package id: com.urbandroid.sleep

**Describe the bug**
Since the last update has been pushed to the Play Store, I'm getting the following notification consistently:

>**Update Google Play services**
>Sleep won't run unless you update Google Play Services

When I first updated the application manually, I was given a message that the update could not succeed because Google Play Services needed to be updated.

The previous version ran without detectable problems on my end.

**To Reproduce**
1. Install Sleep as Android

It might be necessary to install an older version (apparently the last production which works with MicroG might be [20210312 prod](https://sleep.urbandroid.org/wp-content/uploads/release/sleep-20210312-prod-release.apk)) as the most current might not install at all.

All production and beta versions can be download from this page: https://sleep.urbandroid.org/more/download/

**Expected behavior**
Sleep as Android should be able to update and run as previously.

**System**
Android Version: 10
Custom ROM: LineageOS 17.1

**microG**
microG Core version: 0.2.18 preview
microG Self-Check results: All ticked

**Additional context**
[According to the Release Notes from the developer](https://docs.sleep.urbandroid.org/general/release_notes.html), they are transitioning some system in order to take advantage of "new Google Sleep API"

Release notes for 20210226 already mentioned integration with "new Google Sleep API", but upgrades still worked and the app didn't complain.

There is no entry detailing the changes for 20210312.

**Comment by mar-v-in** [comment]
The warning message is gone with https://github.com/microg/GmsCore/commit/a173d268973dac2386504d96419d513ecc45b90c, I haven't verified all functionality of sleep tracking though, from the release notes I guess the sleep time estimates and automatic sleep tracking might be not working as good as it would with original Google services.

**Comment by Mrnofish** [comment]
Thank you very much. 

I'd like to provide feedback, if at all possible, is there any way I can test the patched version without waiting for either a preview or stable download?

**Comment by mar-v-in** [comment]
0.2.19 is released and is available in microG F-Droid repository or via [GitHub release page](https://github.com/microg/GmsCore/releases/tag/v0.2.19.211515).
