### ISSUE TITLE
Grid of collected contact Ids does not show details / wrong row header

### ISSUE THREAD

**Issue by di-sc** [microg/GmsCore#1441]
**Bug description**
As shown in the picture below there are contacts collected (**4**) but these are not marked in the grid below.
I would expect that the contacts are marked in the calendar grid in a different color.

Additionally or related to the issue: instead of showing the month in the row header the current minutes are shown.

**To Reproduce**
1. Install the CCTG
2. Have some contacts with people who also have installed the CCTG or CWA
3. Open the "Begegnungen" view

**Expected behavior**
Show detailed information of collected Ids in the calendar grid
Show a correct row header

**Screenshots**
![image](https://user-images.githubusercontent.com/54937900/114271085-f1fcde00-9a0f-11eb-989d-b641fb0371ed.png)

**System**
ZTE Blade L8
Android Version: 9
Custom ROM: ?

**Comment by fynngodau** [comment]
Just 4 collected IDs is definitely too low in case you were at any place at which you'd expect to find someone who also has the app.

Here's the code the matrix graph uses to determine the format that it uses for the column description:

https://github.com/microg/GmsCore/blob/91b0f6893f9848354af7654b3cebc842615bcd7f/play-services-nearby-core-ui/src/main/kotlin/org/microg/gms/nearby/core/ui/DotChartView.kt#L41-L46

From the documentation, it looks like `DATE_FORMAT` is supposed to be one of these values (or maybe also something similar that is appropriate) depending on your locale: `mm/dd/yyyy`, `dd/mm/yyyy`, `yyyy/mm/dd`

This is then used with `SimpleDateFormat` by microG (unless the string is empty), which is incorrect, because `mm` in `SimpleDateFormat` means "Minute in hour", whereas `MM` means "Month in year". Nice find @di-sc!

**Comment by fynngodau** [comment]
I opened PR #1443 to address the issue I described above.

I'm wondering what is up with the chart in the screenshot, as normally, the first and last box are moved according to the current time (I noticed that the screenshot was recorded in the middle of the day). Compare it to this screenshot to see what I mean (12-hour time format): 
![image](https://user-images.githubusercontent.com/16943720/108603224-083ed400-73a7-11eb-8a40-3c73285ce1ea.png)

**Comment by di-sc** [comment]
> Just 4 collected IDs is definitely too low in case you were at any place at which you'd expect to find someone who also has the app. This might mean that the app is not collecting IDs correctly.

Yes that is a bit strange but may be correct because I didn't had much contacts after restarting the app. When it worked for some days I have had 82 collected Ids but the grid looked the same.

**Comment by di-sc** [comment]
> I'm wondering what is up with the chart in the screenshot, as normally, the first and last box are moved according to the current time (I noticed that the screenshot was recorded in the middle of the day). Compare it to this screenshot to see what I mean (12-hour time format):

I think this is related to  #1443.

The start date is parsed and formatted with the same wrong format string:

`47           val lowest = dateFormat.parse(dateFormat.format(date))?.time ?: date.time`

and used later to calculate the bullets for day 0 and 14:

```
62          for (hour in 0..((min - lowest) / 1000 / 60 / 60).toInt()) {
63              displayData[0]?.second?.set(hour, displayData[0]?.second?.get(hour) ?: -1)
64          }
65          for (hour in ((min - lowest) / 1000 / 60 / 60).toInt() until 24) {
66              displayData[14]?.second?.set(hour, displayData[14]?.second?.get(hour) ?: -1)
67          }
```

So this may also be fixed if the date issue  is fixed #1443.

**Comment by fynngodau** [comment]
You're right, I can reproduce this happening. `lowest` is supposed to be the lowest timestamp of the day, it seems. This would have worked more elegantly with Java 8 time methods but those are not available without some odd desugarify tweaks.

**Comment by di-sc** [comment]
I installed the latest version of the CCTG 2.03 on my mobile but the error still exists.
May be the installation does not update the microg library!?

**Comment by fynngodau** [comment]
@di-sc There hasn't been a microG update since the issue was fixed.
