### ISSUE TITLE
[de.rki.coronawarnapp] Corona-Warn-App: Can't use microg's exposure API

### ISSUE THREAD

**Issue by aanno** [microg/GmsCore#1447]
**Affected app**
Name: Corona-Warn-App
Package id: de.rki.coronawarnapp
Version: 1.15.2

**Describe the bug**
Exposure Notifications activation fails. (Dialog: 'microG Services Core benötigt zusätzliche Berechtigungen', Button 'ERTEILEN' could be pressed - but nothing happens.)

**Expected behavior**
Pressing 'ERTEILEN' should lead to a dialog for giving the app the rights to use the exposure API.

**System**
Android Version: 11
Custom ROM: Lineage4MicroG 18.1-20210411-microG-oneplus3
Hardware: Oneplus 3t (A3003)

**microG**
microG Core version: 0.2.18.204714
microG Self-Check results:
All checked, _except_ for 'background location services' and 'receive SMS' (both Checkboxes are _disabled_ and hence can't be selected).

**Additional context**
In Lineage4MicroG 17.1, de.rki.coronawarnapp has worked as expected.
I also tried the app Corona-Tracing (de.corona.tracing, Version 1.15.1.0) with the same result.

**Comment by Axolord** [comment]
You should be able to click on the two mentioned fields and microG should ask for its permissions. If this does not work, can you grant the permission manually in the system settings?
The CWA issue is quite sure just because of the two boxes.

**Comment by Axolord** [comment]
Connected with this issue:
https://github.com/microg/GmsCore/issues/1440

**Comment by aanno** [comment]
Well, on the android permission details of [de.rki.coronawarnapp] Corona-Warn-App, there is 'Camera' allowed, but no permissions denied (no idea how to add arbitrary permissions here).

I can do the same for microG itself. Android permission details of microG show:
* allowed: files and media, contacts, location (_but_ 'only while the app is used'), and phone
* denied: SMS

I tried to change the SMS permission: The is a dialog for allowing the permission, but it seems _not_ to be stored. Trying to change the location permission leads to a alert box with:

> Achtung
> microG Services Core ist ein Anbieter von Standortdiensten für dieses Gerät. Die Berechtigenungen für den Zugriff auf deinen Standord kannst du in den Standorteinstellungen ändern.
> 
(Translation: Attention, microG services core is a provider of location services for this device. The permissions for accessing your location could be changed in the location settings of the device.)

_But_ going to the android location settings does not help. I simply have no idea how to change the location permissions from 'only while the app is used' to 'background/permanent' for microG.

For other apps there are changes allowed (i.e. for Mozilla UnifiedNlp Backend, I could switch between 'only while the app is used', 'ask every time' and 'deny'). But there seems no way to change between 'only while the app is used' and 'background/permanent'...

**Comment by Axolord** [comment]
Then we have to wait for a fix. It is the same issue as #1440

**Comment by fynngodau** [comment]
I am not certain to what extend microG can help here. The location permission needs to be set to Allow all the time for microG. If this is not possible to do like seen in the screenshot I attached, that sounds like a platform bug to me.

![microG](https://i.imgur.com/CoshODU.png)

**Comment by aanno** [comment]
Problem is still there for:

Custom ROM: Lineage4MicroG 18.1-20210509-microG-oneplus3

Name: Corona-Warn-App
Package id: de.rki.coronawarnapp
Version: 2.1.2

**Comment by ale5000-git** [comment]
Have you tried with this version? https://microg.org/dl/core-nightly.apk

**Comment by aanno** [comment]
Yes! This works! Thank you very much! 
MicroG Services Core Version 0.2.19.211515-1 (e42f684)
