### ISSUE TITLE
Maps broken after upgrade to Lineage OS 18.1

### ISSUE THREAD

**Issue by minarofaeil** [microg/GmsCore#1455]
I have Pixel 2 working with LineageOS-microG on version 17.1, Google Maps was working fine, once I updated to LineageOS-microg 18.1, maps stopped working. Google Maps is showing blank area in place of maps, other apps that use maps (like Waze) do the same thing.

I don't know where I can debug this or if this is a bug in the latest version.

**Comment by mina-medixin** [comment]
Removing the registered Google account solves the issue.

**Comment by minarofaeil** [comment]
Removing the registered Google account solves the issue.
