### ISSUE TITLE
Any plans to move from MapBox to its FOSS fork MapLibre?

### ISSUE THREAD

**Issue by token0** [microg/GmsCore#1463]
MapLibre project is an open source alternative to Mapbox’s proprietary 2.0 update.
Is there any plans to move?

https://github.com/MapLibre
https://twitter.com/maplibre

**Comment by mar-v-in** [comment]
Probably, yes. For now we can stick with the older version we already have.

**Comment by huuhaa** [comment]
@mar-v-in Now when time has flies after latest comment, are there any news about this?

**Comment by Atemu** [comment]
I don't see a reason to switch to MapLibre. They haven't added any interesting features for this use-case. Their major changes were for iOS, QT and other platforms.

For our use-case, it's about the same as the old MapBox version currently in use.

**Comment by ildar** [comment]
I see @token0 made a Pull Request (#1865) for this. Is it regression-free?
@mar-v-in could you please make an alpha release with that so we can test
it beforehands? Thanks
Thank you all guys for this!
