### ISSUE TITLE
[Corona-Warn-App] v2.2.1 requires an update of Google Play-services (microG missing preConsent authorization?)

### ISSUE THREAD

**Issue by Diapolo** [microg/GmsCore#1469]
## Technical details

- Device name: Fairphone 2
- Android version: 10, LineageOS + microG version 0.2.19.211515
- App version: 2.2.1

## Describe the bug

I just tried to do the necessary steps for "Testergebnis abrufen" to learn any new workflows (I do this after each CWA update). When clicking on "Einverstanden" I now get an error message reading "Google Play-Dienste aktualisieren: Corona-Warn wird nur ausgeführt, wenn du die Google Play-Dienste aktualisierst". This was not the case with app version 2.1.2.

A CWA dev raised the idea, that my "microG version is **not supporting the preConsent authorization** introduced by Google 2 month ago". See: https://github.com/corona-warn-app/cwa-app-android/issues/3163#issuecomment-840470972

## Steps to reproduce the issue

![CWA1](https://user-images.githubusercontent.com/1419649/118021652-c1d09400-b35b-11eb-826e-b59f61ea12cf.png)
![CWA2](https://user-images.githubusercontent.com/1419649/118021666-c5641b00-b35b-11eb-901f-34574682dcf4.png)
![CWA3](https://user-images.githubusercontent.com/1419649/118021671-c72dde80-b35b-11eb-83f0-da1cf9fe8926.png)

## Expected behaviour

Open the QR-Code reader.

## Possible Fix

When tapping the error message the QR-Code reader opens. Not sure if registering a test would work, as I have none available to scan.

## Additional context

I'm using LineageOS for microG, microG version 0.2.19.211515 (https://github.com/microg/GmsCore/releases/tag/v0.2.19.211515)

For reference, this is the issue in the CWA repo:
https://github.com/corona-warn-app/cwa-app-android/issues/3163

**Comment by mar-v-in** [comment]
Thanks for reporting. Indeed we can do something about this on microG-side (although CWA could have also had proper handling of this error on their side).

You might want to consider migrating to CCTG which is much better tested with microG and thus doesn't have this issue. See https://codeberg.org/corona-contact-tracing-germany/cwa-android#how-to-migrate-from-cwa on how to migrate.

**Comment by Diapolo** [comment]
Thanks for fixing this :), is there any nightly or test-build available for verifying yet?

**Comment by mar-v-in** [comment]
@Diapolo https://microg.org/dl/core-nightly.apk
