### ISSUE TITLE
Is "NoGoolag" your official support medium?

### ISSUE THREAD

**Issue by freshgum-bubbles** [microg/GmsCore#1495]
Apologies for the inconvenient location, however I feel the microG project may be the subject of impersonation (a la [Bromite](https://github.com/bromite/bromite/discussions/1186)).

There is a room on Telegram named https://t.me/microGsupport, which claims https://t.me/joinchat/nMOOE4YJPDFhZjZk is the official support room for the microG project. I am unable to find anything from the microG project which confirms this.

See below screenshots of this room:

https://user-images.githubusercontent.com/85623267/122550145-3f5a8480-d02b-11eb-868c-dbfdfb44c433.png
https://user-images.githubusercontent.com/85623267/122550295-66b15180-d02b-11eb-9701-9b875c167e14.png
https://user-images.githubusercontent.com/85623267/122550336-716be680-d02b-11eb-9ed6-1b10675285f5.png
https://user-images.githubusercontent.com/85623267/122550467-982a1d00-d02b-11eb-852a-2b049de3ddab.png
https://user-images.githubusercontent.com/85623267/122550566-bd1e9000-d02b-11eb-8710-87789de11884.png

**Comment by mar-v-in** [comment]
There is no official microG support room on Telegram.

**Comment by Ammako** [comment]
I don't see anywhere on that link that claims this to be any kind of *official* support group, though. It just says that it's a support group. Or am I missing something? They're not there to impersonate as far as I can tell.

**Comment by Ammako** [comment]
@FriendlyNeighborhoodShane may have a thing or two to say about this, though.

https://github.com/FriendlyNeighborhoodShane/MinMicroG/commit/c826a347f0ff1690c2f0ab5f3eabe3df14a7277f

**Comment by FriendlyNeighborhoodShane** [comment]
Yep, it isn't official in any sense, and doesn't seem to claim to be, so I don't really think it counts as impersonation?

And yep, there has recently been a bit of infighting and fallout in the mod team over it essentially becoming an asinine antivax crank channel. 3/10, would not reccommend to anyone.

**Comment by Sapiosenses** [comment]
There is a better alternative on Telegram. (I can expand if there is interest, don't want to hijack.)

**Comment by freshgum-bubbles** [comment]
I assumed it was an official channel as the NoGoolag user stated it was official not too long ago. In hindsight I should have grabbed a screenshot, sorry about that. Messages are deleted weekly for reasons unknown.

> asinine antivax crank channel

I've seen enough to know this is true! :sweat_smile: 

Anyway, thanks for confirming there is no affiliation between microG and NoGoolag.
