### ISSUE TITLE
[com.instagram.android] Instagram does not register for push notifications

### ISSUE THREAD

**Issue by ArnVollebregt** [microg/GmsCore#1498]
**Affected app**
Name: Instagram
Package id: [com.instagram.android](https://play.google.com/store/apps/details?id=com.instagram.android)

**Describe the bug**
Instagram does not receive push notifications.

**To Reproduce**
1. Install *Instagram*.
2. Authenticate with account.
3. Wait for push notification on other phone(s) with same account.
4. Notice push notification is not received on this phone.

**Expected behavior**
I expect a push notification from the Instagram app, similar to other installed applications (such as *Push Notification Tester* and *Discord*).

**System**
Android Version: 11
Custom ROM: [lineageos_pro1_userdebug 11 RQ2A.210505.003 d40645ea7e](https://download.lineageos.org/pro1)

**Additional context**
Installed application(s) version(s):
- [Magisk v23.0 (23000)](https://github.com/topjohnwu/Magisk/releases)
- [Riru v25.4.4.r426.05ec94](https://github.com/RikkaApps/Riru/releases)
- [Riru - LSPosed vv1.4.5 (5767)](https://github.com/LSPosed/LSPosed/releases)
- [FakeGApps (Apr 7)](https://github.com/whew-inc/FakeGApps/releases)
- microG [Services Core v0.2.19.211515](https://github.com/microg/GmsCore/releases)
- microG [Services Framework Proxy v0.1.0]()
- microG [Store (FakeStore release) v0.0.2](https://github.com/microg/Phonesky)
- [Push Notification Tester v2.9](https://play.google.com/store/apps/details?id=com.firstrowria.pushnotificationtester)
- [Instagram (June 14, 2021)](https://play.google.com/store/apps/details?id=com.instagram.android)

Could be related to [[ch.protonmail.android] Protonmail does not register for push notifications #1494](https://github.com/microg/GmsCore/issues/1494), as this sounds similar. Perhaps a different/altered push notification implementation in Android?

**Comment by RobertoWa** [comment]
u installed this app over playstore?

my experience is on android 11, some apps only work with push if they are installed over playstore.

**Comment by ArnVollebregt** [comment]
> u installed this app over playstore?

I downloaded it with [APK Downloader](https://apps.evozi.com/apk-downloader/), but did not install it directly from the Playstore; my goal is to deGoogle as much as possible, and *microG* is a concession in order to receive push notifications.

As an experiment I temporary added a google account to the phone (without any additional software installation), but to no avail.

**Comment by RobertoWa** [comment]
since i use android 11 (los 18.1) i have to use the patched playstore by nanodroid to get signal messenger working with push. i dont know why. but that is why i mentioned it here...maybe the same behavior.

**Comment by 4n0nym0u53** [comment]
> Could be related to [[ch.protonmail.android] Protonmail does not register for push notifications #1494](https://github.com/microg/GmsCore/issues/1494), as this sounds similar. Perhaps a different/altered push notification implementation in Android?

The issue seems to have fixed itself for me for ProtonMail. ProtonMail is now registered and I'm receiving push notifications. Maybe it's because my ROM got updated yesterday, which upgraded microG from version 0.2.18.204714 to version 0.2.19.211515, but I don't think so since that's the version the author of #1494 had problems with too.

**Comment by 4n0nym0u53** [comment]
> Could be related to [[ch.protonmail.android] Protonmail does not register for push notifications #1494](https://github.com/microg/GmsCore/issues/1494), as this sounds similar. Perhaps a different/altered push notification implementation in Android?

The issue seems to have fixed itself for me with ProtonMail. ProtonMail is now registered and I'm receiving push notifications. Maybe it's because my ROM got updated yesterday, which upgraded microG from version 0.2.18.204714 to version 0.2.19.211515, but I don't think so since that's the version the author of #1494 had problems with too.

**Comment by 4n0nym0u53** [comment]
> since i use android 11 (los 18.1) i have to use the patched playstore by nanodroid to get signal messenger working with push. i dont know why. but that is why i mentioned it here...maybe the same behavior.

That's strange, I use Signal on LOS 18.1 (the microG version, but Signal isn't registered for GCM) and notifications work fine for me. I got Signal from Aurora Store.

**Comment by ArnVollebregt** [comment]
> As an experiment I temporary added a google account to the phone (without any additional software installation), but to no avail.

So this is where it gets interesting: adding the google account (and reinstalling *Instagram*, flushing cache/data) actually **did** (temporarily) result in push notifications, although it did not appear under *Cloud messaging* in *microG Settings*.

The behavior was not consistent though, after trying to replicate it: at first it seemed *Instagram* had to be started after fresh device boot before notifications showed up in tandem with the other phone. During testing to determine the limits/rules of this behavior the notifications ceased to appear though, although no settings/applications changed.

Any way I can aid in debugging to hunt down the cause for this behavior?

**Comment by ArnVollebregt** [comment]
> Any way I can aid in debugging to hunt down the cause for this behavior?

Debugging got a bit harder as _Push Notification Tester_ [cannot connect to the server anymore](https://github.com/bbindreiter/PushNotificationTester_App/issues/9) because [it was removed from Google Play](https://github.com/bbindreiter/PushNotificationTester_App/issues/8).

**Comment by ArnVollebregt** [comment]
Instead of rolling my own I've just installed [the build for my phone](https://download.lineage.microg.org/pro1/lineage-18.1-20210621-microG-pro1-recovery.img) of [LineageOS for microG](https://lineage.microg.org/) and that worked out of the box.

Closing this ticket: most likely this was [PEBCAK](https://en.wiktionary.org/wiki/PEBCAK) ;)

P.S.: I had the same issue with [Signal](https://play.google.com/store/apps/details?id=org.thoughtcrime.securesms) as @RobertoWa [encountered](https://github.com/microg/GmsCore/issues/1498#issuecomment-864825978), which has now also been resolved.
