### ISSUE TITLE
GmsCore force closes when Magisk Hide is activated. 

### ISSUE THREAD

**Issue by RomainGranata** [microg/GmsCore#1499]
Hello,

The issue is in the title : whenever I activate Magisk hide (in order to use certain apps that do not allow rooted devices), the Gms Core app doesn't work properly, and force closes in a loop. The issue resolves itself as soon as I deactivate Magisk Hide and reboot my device. To be clear, the issue appears even if I am not hiding root to the gms app.

I am running on Lineage OS 18.1, that I manually patched for it to allow signature spoofing. 

Has anyone noticed a similar issue ?

**Comment by Sapiosenses** [comment]
Yes, this is a known issue.

The following may be of interest:

https://github.com/topjohnwu/Magisk/issues/3559

https://github.com/microg/GmsCore/issues/1363#issuecomment-767032780
