### ISSUE TITLE
[com.google.android.youtube] YouTube chromecasting doesn't work

### ISSUE THREAD

**Issue by ghost** [microg/GmsCore#1502]
**Describe the bug**
After requests a chromecast playback on one of latest YouTuve versions (for example 16.20.35), a notification about a needed Play Services update is shown.

System
Android Version: 11
Custom ROM: OneUI 3.1

microG
microG Core version: 0.2.19.211515
microG Self-Check results: All ticked

**Comment by luciph0r** [comment]
Seconded, and the fork implementers say the fix has to come from upstream.

**Comment by hannad4** [comment]
I can confirm that I am having the same issue. I updated the Vanced micro g (fork of micro g) from the Vanced Manager on my phone and now casting does not work anymore, even though it worked previously. I looked it up and can also confirm they are saying this needs to be fixed upstream

**Comment by javiims** [comment]
When will it be fixed? It's annoying!

**Comment by f3nyx** [comment]
Same issue here. Updating Google Play does nothing. It even keeps asking to update it.

**Comment by ale5000-git** [comment]
Cast is currently not working but I'm closing this ticket in favor of #580
