### ISSUE TITLE
Maps crashes instantaneously

### ISSUE THREAD

**Issue by drrossum** [microg/GmsCore#1506]
**Describe the bug**
Maps v10.24.3 crashes instantaneously upon launch.  This version used to work on Microg v0.2.19.  Upgraded to v10.38.3 to make sure this is not a random maps bug, but that version also crashes immediately.

MicroG version: d8e50cb341569e32e09c783517356fecebedf8a7

**System**
Android Version: 11
Custom ROM: LineageOS 18.1

**Additional context**
Was working with microg v0.2.19

[debug.log](https://github.com/microg/GmsCore/files/6748437/debug.log)

**Comment by ale5000-git** [comment]
There is a know issue in the latest version of microG, have you tried with tihs? https://microg.org/dl/core-nightly.apk

**Comment by drrossum** [comment]
This happens using a self-built apk from the latest commit in the repo:
d8e50cb3 (HEAD, origin/master, origin/HEAD) Cronet: Use updated version

**Comment by mar-v-in** [comment]
Have you tried with a more recent version of Google Maps (10.57.1 seems to be the latest version)?

**Comment by drrossum** [comment]
Success!

v10.57.1 does not crash
v10.47.1 still crashed

**Comment by mar-v-in** [comment]
Looks like older versions of Maps might expect some older version of Cronet which we are not compatible with.

**Comment by drrossum** [comment]
I do get a message saying "Update Google Play services.  Maps won't run unless you update Google Play services" using this v10.57.1...

**Comment by drrossum** [comment]
I tried versions before v10.57.1 but I guess this version really is also the earliest (as well as the latest, as you said).  Apart from the warning message all functionality seems to be there.

**Comment by mar-v-in** [comment]
10.**75**.1 is the latest version, not 10.**57**.1
