### ISSUE TITLE
Slack doesn't register for push notifications

### ISSUE THREAD

**Issue by miquecg** [microg/GmsCore#1512]
**Describe the bug**
I've ran the notifications test on Slack application and it doesn't work. I remember at some point before it was listed on Cloud Messaging applications but it's no longer the case, even though I've tried `*#*#CHECKIN#*#*` workaround.

This application runs on a separated work profile but that doesn't seem to cause any problems to other apps that do have working notifications. On the main profile I also miss some apps that were registered before, probably something is going on.

**System**
Android Version: 11
Custom ROM: LineageOS 18.1
GmsCore version: 0.2.21.212158

**Additional context**
Autocheck diagnosis passes.
I don't have enabled Google device registration. Apparently I must have turned it off long time ago and it was never a problem

**Comment by miquecg** [comment]
It looks like cloud connection could be somehow unreliable. When I check it reports connected just few seconds ago very often, like if it was not able to survive.

**Comment by Sapiosenses** [comment]
If you haven't already enabled device registration you should enable it, that should be a prerequisite for push messaging.

Explanation here:

https://github.com/microg/GmsCore/issues/1508#issuecomment-876269198

If the socket keeps getting closed you may have a firewall problem somewhere between you and the Google servers that need to be communicated-with to make push messaging work.

**Comment by miquecg** [comment]
Thanks for the help. After enabling device registration all missing apps came back, Slack included :slightly_smiling_face:

What I've observed about GCM connection is that almost every time, when I close settings the connection is lost until next time I open microG again. Keeping it opened creates a persistent connection. All autodiagnosis checks are marked and battery optimization for microG is not even available.

**Comment by miquecg** [comment]
Closing because issue description is no longer valid. Slack is now registered and GCM connection *seems* to last, at least a few hours last time I checked. What remains valid is that sometimes GCM last connection time gets reset after re-opening GsmCore.
