### ISSUE TITLE
CardDAV sync does not work

### ISSUE THREAD

**Issue by aanno** [microg/GmsCore#1525]
**Describe the bug**
All Contacts Apps that I tried (Google Contacts, Simple Contacts, and the Contacts App that comes with LineageOS) do _not_ work for CardDAV synchronization (with DAVx5). However, CalDAV synchronization does work as expected.

**To Reproduce**

Preliminaries:
1. CardDAV/CalDAV synchronization app (here: DAVx5, but I expect that the bug is not related to the sync app used)
2. Contacts App of your choice (here: Google Contacts, but I expect that the bug is not related to contacts app used)
3. A working CardDAV/CalDAV account configured in DAVx5 (i.e. the account from your own nextcloud server)

Steps to reproduce the behavior (i.e. with Google Contacts):
1. Open 'Google Contacts'
2. App shows the 'loading contacts' animation for long time, finally displaying 'no contacts yet'.
3. menu -> settings (this will also take some time) -> accounts <br/>
    Interestingly, the expected 'DAVx5' account is _not_ listed.

**Expected behavior**
Both CardDAV and CalDAV synchronization should work.

**System**
Android Version: 11
Custom ROM: https://lineage.microg.org/ 18.1 of July, 4th, 2021
Device: OnePlus 3t 
microg version: 0.2.21.212158

**Additional context**
Perhaps related to #1476 (?)

**Comment by aanno** [comment]
With the 'simple contacts app' you could try the add a new contact. At the very button of the form, you could normally select which storage to use. However, there is only on choice: 'device storage'. I would expect to see DAVx5 (or something similiar) as well.

For me, it looks like that all the 'contacts apps' fail to find the appropriate 'storage backends' (like DAVx5).

**Comment by chris42** [comment]
Are you sure this is related to microg? 
The Contacts setup with CalDAV does not need google components to work, hence not microg. Using that combination of stock contacts with DAVx5 on AOSP phones with and without microg without issues.

**Comment by aanno** [comment]
Fair point. And I'm not sure. I'm not into the technical details but maybe it's because the https://lineage.microg.org/ team has removed something from LineageOS that is related to contacts (storage/provider/rights) but not related to sync to google contacts (which would be in microg, or not?). Any suggestions were to report the problem?

**Comment by chris42** [comment]
I am not sure, if the microg team of lineageos removed something. Normally they should just be adding a prebuilt microg, but never looked in detail on what they do. Would probably search the lineage help if anyone has issues with DAVx5

**Comment by aanno** [comment]
Dear @chris42, I guess you are right: This report is _invalid_. If there is someone with the same problem who steps upon this: **You need a factory reset to get your device to work again** (and yes, this is unfortunate!).

In my case, the problem was (probably) triggered by installing https://lineage.microg.org/ on the stock firmware _without deleting the apps (i.e. without formatting the data partition)_.
