### ISSUE TITLE
Notifications never work when phone in Battery Saver mode

### ISSUE THREAD

**Issue by TheLastGimbus** [microg/GmsCore#1527]
**Describe the bug**
I never get notifications when my phone is in Power Saver. I have all checks form self-test passed, gms core as well as gsf proxy 's .apks are copied to `/system/priv-app` to make them system, and battery optimizations are disabled for them

Also, when I open the app, it often says "connected since N minutes" - even tho notifications are not coming :disappointed: 

**To Reproduce**
1. Turn on battery saver
2. Wait a while for it to kick in
3. Send message/call yourself on Signal/Messenger/Whatsapp
4. No profit

**Expected behavior**
Notifications should work thanks to disabling battery optimization

**System**
Android Version: 10
Custom ROM: LineageOS 17.1
Installation: Magisk->EdXposed->FakeGApps
MicroG version: 0.2.21.212158 (from GH Releases)

**Comment by Fox2Code** [comment]
Android also need the correct xmls to be placed in `/system/etc/permission/` for priv apps permissions.

MicroG need the `android.permission.CHANGE_DEVICE_IDLE_TEMP_WHITELIST` permission to work correctly with the android battery saver, this allow MicroG to disable battery saver on apps receiving cloud messages for a short period of time.

Code: 
https://github.com/microg/GmsCore/blob/a830b5dd5de71fa53f9d037c210a81fb38ea3321/play-services-core/src/main/java/org/microg/gms/gcm/McsService.java#L189

**Comment by Fox2Code** [comment]
This Magisk module should install MicroG correctly with the correct xmls files.
https://github.com/Magisk-Modules-Repo/microG_installer

**Comment by TheLastGimbus** [comment]
Woo-hoo! I `adb push`ed `/system/etc/sysconfig/org.microG.xml` and `/system/etc/permissions/privapp-permissions-org.microG.xml`, and looks like this works!!! 

Please tell me this will persist over OTA updates :pray:

**Comment by Ammako** [comment]
> Please tell me this will persist over OTA updates pray

It won't, unless you also put something in addon.d to backup and restore the files every time. Note that this also applies to the apks you moved to priv-app.
