### ISSUE TITLE
MicroG on LineageOS 18.1 does not work

### ISSUE THREAD

**Issue by Dadoode** [microg/GmsCore#1531]
Corona-Warn-App
I get the following error:

**Describe the bug**
The Signature Spoofing does not worg right.

**To Reproduce**
https://download.lineageos.org/flame
lineage-18.1-20210711-nightly-flame-signed
Install OS
C:\Users\User\Downloads>adb sideload C:\Users\User\Downloads\lineage-18.1-20210711-nightly-flame-signed.zip
Reboot
Then install Magisk
C:\Users\User\Downloads>adb sideload C:\Users\User\Downloads\Magisk-v23.0.zip
reboot
Get Root in Magisk
install "Riru" and "Riru - LSPosed" in Magisk (https://github.com/microg/GmsCore/wiki/Signature-Spoofing)
Download and install FakeGApps (https://github.com/whew-inc/FakeGApps/releases)
C:\Users\User\Downloads>adb install C:\Users\User\Downloads\app-release.apk
Performing Streamed Install
Success

install All MicroG Moduls (https://microg.org/download.html)
C:\Users\User\Downloads>adb install C:\Users\User\Downloads\com.google.android.gms-212158042.apk
Performing Streamed Install
Success

C:\Users\User\Downloads>adb install C:\Users\User\Downloads\com.google.android.gsf-8.apk
Performing Streamed Install
Success

C:\Users\User\Downloads>adb install C:\Users\User\Downloads\com.android.vending-16.apk
Performing Streamed Install
Success

C:\Users\User\Downloads>adb install C:\Users\User\Downloads\FakeStore-v0.1.0.apk
Performing Streamed Install
Success

C:\Users\User\Downloads>adb install C:\Users\User\Downloads\LegacyNetworkLocation.apk
Performing Streamed Install
Success

C:\Users\User\Downloads>adb install C:\Users\User\Downloads\org.microg.gms.droidguard-4.apk
Performing Streamed Install
Success

Install CWA-App

Tick all Boxes in  LSPosed

Reboot

Check Self Test in Micro G (give Permissions)
--> All ticked

Start CWA 
--> Error 3 No API found

**Expected behavior**
The CWA schould work with no error

**Screenshots**
![Screenshot_20210815-153831_Magisk](https://user-images.githubusercontent.com/56791165/129480577-fac5a135-eadc-453b-9565-11d1a42cdbc4.png)
![Screenshot_20210815-153836_LSPosed](https://user-images.githubusercontent.com/56791165/129480581-2a283c47-a919-47c3-a2f2-baceb360c5c5.png)
![Screenshot_20210815-153841_LSPosed](https://user-images.githubusercontent.com/56791165/129480583-bb1fea76-548a-4bf3-8327-b16dc5d6476b.png)
![Screenshot_20210815-153849_LSPosed](https://user-images.githubusercontent.com/56791165/129480584-e6e4b214-c47d-47b5-9a90-b32905cf7c28.png)
![Screenshot_20210815-153906_microG_Services_Core](https://user-images.githubusercontent.com/56791165/129480587-475e12b0-c28b-4cfd-afd3-095ca998e9b0.png)
![Screenshot_20210815-153912_microG_Services_Core](https://user-images.githubusercontent.com/56791165/129480589-85d86c90-2e4f-4272-9cfd-638a736e3c48.png)
![Screenshot_20210815-153915_microG_Services_Core](https://user-images.githubusercontent.com/56791165/129480595-90ee0a6d-7317-4a74-8e47-c64811baec04.png)
![Screenshot_20210815-152305_Corona-Warn](https://user-images.githubusercontent.com/56791165/129480597-022c792a-7440-40b8-9c92-ac6ce321ce42.png)

**System**
Android Version: e.g. 11
Custom ROM: LineageOS 18.1
Pixel 4 (flame)

**microG**
microG Core version:  212158042
microG Self-Check results:  All ticked

**Comment by Dev0110** [comment]
Got the same issue... See #1532

**Comment by Dadoode** [comment]
Solved with https://github.com/nift4/microg_installer_revived
