### ISSUE TITLE
MicroG isn't detected by apps

### ISSUE THREAD

**Issue by Dev0110** [microg/GmsCore#1532]
**Describe the bug**
Hello there ! I've set up MicroG from LOS18.1 and signature spoofing with Magisk, LSPosed and FakeGapps from whew-inc. But no apps can detect MicroG. Uber app says that google play services are not installed and many other apps too. MicroG self check is OK. What is the problem? Thanks for your help!

**To Reproduce**
1. Install official LOS18.1
2. Root with Magisk
3. Install Riru and LSPosed
4. Install FakeGapps from whew-inc
5. Install the 4 MicroG packages from their FDroid repo.
6. Tick all the boxes on MicroG self check
7. Launch Uber app
8. It says that Google Play Services isn't installed (in fact, true but MicroG should replace it)

**Expected behavior**
App should work

**System**
Android Version: 11
Custom ROM: LineageOS 18.1

**Comment by RobertoWa** [comment]
try to install microg by using https://github.com/FriendlyNeighborhoodShane/MinMicroG or https://github.com/nift4/microg_installer_revived

**Comment by Dev0110** [comment]
Thanks !
I tried already nift4 installer without sucess.
I will try MMG when I got a computer under my hand to build it

**Comment by RobertoWa** [comment]
no need to build mmg, there are some ready pakets to download.

i have only one app not recognising microg, but when i install it by patched google playstore (included inside nanodroid) it works.

**Comment by ShubhamPatilsd** [comment]
Do I have to factory reset my ROM for this? I'm using LOS 18.1 (unofficial) and I used the same method @Dev0110 used to install microG.

**Comment by ShubhamPatilsd** [comment]
Ok update: I used nift4 and it was successful. Although in the self-check, I cannot give access to use location in the background or the permission to receive SMS. Is this fine?

**Comment by Iey4iej3** [comment]
Is it related to this bug: https://github.com/microg/GmsCore/issues/1513 and try the solution at https://github.com/microg/GmsCore/issues/1513#issuecomment-882053298

**Comment by Dev0110** [comment]
Thanks !
It worked with nift4.
But I would like to update Microg components with fdroid but the signature aren't matching between the package ans the fdroid release...
