### ISSUE TITLE
Microg is failing to login to a google account.

### ISSUE THREAD

**Issue by einekratzekatze** [microg/GmsCore#1546]
When trying to add an account to microg I get this Error:
![image](https://user-images.githubusercontent.com/48450457/131220845-a011cf41-053b-49d1-bfc1-bcd26ef43add.png)
English: 
Sorry...
A problem occurred during the communication with the google servers. 
Please try again later.

System:
Android Version: 11
Custom ROM: Stock Android 11 with a LineageOS 18.1 gsi
Phone: Samsung Galaxy M31

**Comment by mrbad25** [comment]
Same

**Comment by dacechavez** [comment]
Try the workaround here
#https://github.com/microg/GmsCore/issues/1425#issuecomment-882024446

**Comment by einekratzekatze** [comment]
xenon205s solution worked 👍
