### ISSUE TITLE
Chromecast

### ISSUE THREAD

**Issue by PeterKW** [microg/GmsCore#1565]
Are there any updates on why the Chromecast microG bug exists which blocks casting? From what I can gather it might work with particular applications but not others or something? Is it known which area of code to work on causes this problem? 

Also, is there an active issue of post to follow updates on this on?

![Screenshot_20210912-210636.png](https://user-images.githubusercontent.com/13779157/133001293-236bef5a-72e9-4580-acae-fddcf4d504f3.png)

**Comment by Sacerdoss** [comment]
As far as I can see Chromecast implementation is in a dummy state where necessary functions exist but do nothing. I couldn't find a implementation that would communicate with the chromecast. I can imagine that there is a lot more work to be done before it will work.

**Comment by am2222** [comment]
But I was using the same app and it was working fine and suddenly after an update it stopped working

**Comment by phrogg** [comment]
> For anyone looking for an alternative if its just about a single TV: I have now ditched my Chromecast and put a Raspberry Pi in its place. I installed Kodi on it and use Kore as a remote from my smartphone. Its a little bit more initial configuration work to do but using that you can hit share from Youtube/Netflix... Videos and start "casting" like that. Works like a charm.

Really for Netflix as well? Also in HD?

**Comment by nnuel** [comment]
> This is probably because of an update in the Chromecast Api. The old API (v1 I think) worked for a long time although v2 was already out. But Apps are switching from v1 to v2 and I think v1 already doesn't work anymore fully. Also v1 probably did work with MicroG and v2 doesn't (yet)

What would be needed to make v2 work under microG?

**Comment by BugInACode** [comment]
I've just started using _lineageos for microg_ and have noticed the lack of support for casting, including native casting. VLC doesn't even seem to have a casting button for me.

There was a question earlier on whether there is a thread about ongoing works, and there seems to be a couple of them but none seem to truly fix the problem.

To add to the above, Netflix seems to show the casting button but only shows "phone" as the possible connections. Spotify does not show devices except for other devices using my account.

Going forward I'd like to make a more formal thread focussed on fixing the casting issue, be it implementing VLC's supposed google-api-less method, or reverse engineering the api and making it work. If no one can point to a formal thread/issue by Monday, I will open one and start looking into the problem. 

Give this comment a thumbs up of you'd like to be mentioned in the thread once it's found/created and I will do so if you're not already on it.

**Comment by ale5000-git** [comment]
Cast is currently not working but I'm closing this ticket in favor of #580
