### ISSUE TITLE
[```fr.smarquis.fcm```] FCM toolbox shows ```MISSING_INSTANCEID_SERVICE```

### ISSUE THREAD

**Issue by StephanoGeorge** [microg/GmsCore#1573]
**Affected app**
Name: [FCM toolbox](https://github.com/SimonMarquis/FCM-toolbox/)
Package id: `fr.smarquis.fcm`

**Describe the bug**
FCM toolbox shows `MISSING_INSTANCEID_SERVICE` in titlebar

**To Reproduce**
1. Open FCM toolbox
2. See error

**Expected behavior**
FCM toolbox show token in titlebar

**Screenshots**

**System**
Android Version: 11
Custom ROM: crDroid 7.6

**microG**
microG Core version: 0.2.22.212658
microG Self-Check results: All ticked

**Additional context**
Check https://github.com/SimonMarquis/FCM-toolbox/issues/10

**Comment by mar-v-in** [comment]
What is the status of device registration and cloud messaging in microG settings?

**Comment by StephanoGeorge** [comment]
Thanks Reply

![Screenshot_20210930-182610195](https://user-images.githubusercontent.com/20573568/135439009-44eb7de1-92b6-4fb1-8a59-4bb6be3cf878.jpg)
![Screenshot_20210930-182624552](https://user-images.githubusercontent.com/20573568/135439017-2d18a7bb-5960-4879-9f6e-26e4d694d26d.jpg)

**Comment by ale5000-git** [comment]
Have you tried the latest version (v0.2.23.214816)?

**Comment by StephanoGeorge** [comment]
I tried. Installed the microg and restarted. But the behavior is still the same

**Comment by Qufyy** [comment]
I had the same issue, I managed to solve it by installing MicroG through Magisk using [this](https://github.com/nift4/microg_installer_revived). Maybe MicroG needs to be installed as a system app? Previously I had it installed through F-Droid.

**Comment by cheadrian** [comment]
I've tested this and can say it works, there's no issues, I get token and I can ping app.
MicroG on Huawei Matepad 10.4, HarmonyOS 2.0, no root, locked bootloader.
Device registered as Motorola Moto G. Google Account signed in.

**Comment by StephanoGeorge** [comment]
Sorry, I don't use MicroG anymore, you can open a new issue.
