### ISSUE TITLE
Exposure Notifications need permission changes for Android 12

### ISSUE THREAD

**Issue by Bubu** [microg/GmsCore#1591]
Something in Android 12 changed with how you access the bluetooth scanning functionality[1] and the migration works poorly currently:

https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/169

Haven't yet done much investogation,

[1]: https://www.xda-developers.com/android-12-location-scan-nearby-bluetooth-devices/

**Comment by Bubu** [comment]
Also broken for new installs.

**Comment by Bubu** [comment]
A short update: Adding `android.permission.BLUETOOTH_ADVERTISE`, `android.permission.BLUETOOTH_SCAN` to the to be requested permission list on Android 12 makes it work again for new installs. I was hoping to get rid of the need for location permissions via https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location but haven't been able to get CCTG to target Android 12 and thus test this idea. (my currently "working" flow of having the app ask for location access, then nearby access, and then location background access is pretty confusing and inconvenient... we could probably reorder the nearby one at the start to have this make some more sense... but you still need like a manual to correctly grant all permissions :(.)

We'll also need to add a notification that permissions need to be updated for people who do the initial setup on Android 11 and then updating to Android 12.

**Comment by ale5000-git** [comment]
While you are at it have you looked at this? #1598
It could cause big troubles.

**Comment by Bubu** [comment]
On November 9, 2021 9:53:19 AM GMT+01:00, ale5000 ***@***.***> wrote:
>While you are at it have you looked at this? #1598
>It could cause big troubles.
>

Do you specifically mean for exposure notifications or generally for standalone microg?

(Haven't read the article yet, will do later)

**Comment by ale5000-git** [comment]
It probably need to be in both (standalone microg and all apps using exposure notifications), otherwise scan may break unexpectedly when this change will be enabled on all devices.
