### ISSUE TITLE
Exposure Notification + NZ Covid tracer app doesn't work.

### ISSUE THREAD

**Issue by eliotb** [microg/GmsCore#1603]
_Note: maybe this is a matter of my misunderstanding of how the microG exposure notification API works.  I am assuming it will work with any app that works with the Google official EN API, without modifying the app.
If this is not the case, is there somewhere I can learn how to find out what is going wrong or what needs to be modified to make an app compatible with microG EN_

Opening the NZ Covid Tracer app.  (nz.govt.health.covidtracer) it has a section "TRACE YOUR ENCOUNTERS" in the dashboard. This says "Bluetooth Tracing is unavailable, your device may  not be supported"

**To Reproduce**
* Open NZ covid tracer
* See bluetooth tracing is unavailable

**System**
Device: Samsung S9+ SM-G965F
Android Version: 10
Custom ROM:  /e/ 0.19-20211027
microG: 0.2.21.212158-144  self check all ☑

**Additional context**
I know that EN works on my device because I have installed "Corona Contact  Tracing Germany" app from F-Droid.
I know that this is the open source version that may have special code to use microG EN functions(?)

NZ Covid Tracer app
* Play store: https://play.google.com/store/apps/details?id=nz.govt.health.covidtracer
* Source https://github.com/minhealthnz/nzcovidtracer-app

**Comment by mar-v-in** [comment]
This is probably because the app requires SafetyNet.

Best you can do is inform the authors that the use of SafetyNet to block users is actually discouraged by Google and that Google acknowledges that SafetyNet is not a suitable abuse protection, see https://android-developers.googleblog.com/2017/11/10-things-you-might-be-doing-wrong-when.html
> By blocking users solely on their attestation results, you might be missing abusive users that don't fail attestations. Furthermore, you might also be blocking legitimate, loyal customers who fail attestations for reasons other than abuse.

**Comment by eliotb** [comment]
I wasn't clear that the app basically works. I scans QR codes and records diary entries, receives notifications etc. The only part that doesn't work is using the EN service.
Can safetynet stop part of an app from working like this?

**Comment by mar-v-in** [comment]
According to [their documentation](https://github.com/minhealthnz/nzcovidtracer-app/blob/main/src/features/verification/README.md), the SafetyNet verification is only required for uploading exposure keys after infection and would not be required for warning you. However the current codebase seems to run into an error when trying to verify the safetynet state, resulting in it assuming that your device does not support EN.

Maybe you can try to file a bug report with them so that they at least allow you to use the app to receive warnings even if they don't want to allow to upload exposure keys (probably in fear of abuse).

**Comment by eliotb** [comment]
Thanks for the detailed reply, and the time and effort it took from you.
I'll take it up with the authors.

**Comment by robinpaulson** [comment]
I'm getting the same problem, although my device will not successfully scan QR codes. @eliotb If you contact the MoH, do let me know, I'll use the same contact method to file a similar bug report.

I have a suspicion their response will be "we do not support microG", despite the bug being a more fundamental flaw, as pointed out by Marvin.

**Comment by eliotb** [comment]
@robinpaulson I sent this to help@covidtracer.min.health.nz

> The covid app tells me "Bluetooth Tracing is unavailable", however I know that BlueTooth tracing can work because
> I installed the Corona Contact Germany tracer android app, and this correctly gathers BT exposure data.
> 
> I have further technical information about why the NZ Covid app is incorrectly disabling exposure tracking,
> so if your developers want to get in touch about that I'm happy to provide it.

**Comment by robinpaulson** [comment]
Ah, that is nicely worded. I shall ponder and send something supporting to the same address.

Do you think it would help to explicitly reference you/your message, so the two are linked; are you OK with me doing so?

Cheers

**Comment by eliotb** [comment]
On 3/11/21 14:21, robinpaulson wrote:
> Ah, that is nicely worded. I shall ponder and send something supporting to the same address.
> 
> Do you think it would help to explicitly reference you/your message, so the two are linked; are you OK with me doing so?

yes, no problem if you want to.

**Comment by robinpaulson** [comment]
I updated to the latest version of gms core today, bluetooth tracing in the nz covid app and exposure notifications now works!

**Comment by ale5000-git** [comment]
The latest version of microG has fixed SafetyNet, so it will certainly works.
But it isn't sure it will still works in the case it breaks again.

**Comment by robinpaulson** [comment]
>  But it isn't sure it will still works in the case it breaks again.

Well sure, for that matter, every part of microg *might* break. I'm not sure what point you're making.

**Comment by ale5000-git** [comment]
Quote:

> According to their documentation, the SafetyNet verification is only required for uploading exposure keys after infection and would not be required for warning you. However the current codebase seems to run into an error when trying to verify the safetynet state, resulting in it assuming that your device does not support EN.

The fact that `current codebase seems to run into an error when trying to verify the safetynet state, resulting in it assuming that your device does not support EN` is the major bug here.

**Comment by eliotb** [comment]
Just dropping in with confirmation that /e/ OS 0.22 upgraded microG to v 0.2.24, and the BT EN functionality of NZ Covid Tracer app is now working. Thanks.
