### ISSUE TITLE
Mapbox not displaying

### ISSUE THREAD

**Issue by UnderSampled** [microg/GmsCore#1604]
I only get the "won't run without Google Play Services" message. It worked on this phone before I updated it (the update required that I format data). Not quite sure how to diagnose.

MicroG version: 0.2.22.212658
Phone: Poco X3 NFC (surya)
Android version: 11
ROM/Build: Arrow OS 2021-10-08

**Comment by ale5000-git** [comment]
It is possible that previously you have used the signature spoofing patch, and updating has reverted it.

**Comment by UnderSampled** [comment]
The "update" required a full wipe, so anything would have to be done from scratch. Last time I think I installed through an ota zip; this time I used the magisk installer.

On November 2, 2021 10:28:01 AM EDT, ale5000 ***@***.***> wrote:
>It is possible that previously you have used the signature spoofing patch, and updating has reverted it.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/microg/GmsCore/issues/1604#issuecomment-957696537
Sincerely,
Stephen Christie

**Comment by UnderSampled** [comment]
Here's a screenshot of the self-checker.
![Uploading Screenshot_20211102-111615.png…]()

**Comment by UnderSampled** [comment]
Here's a screenshot of the self checker:

![Uploading Screenshot_20211102-111615.png…]()

It seems to get the cloud messaging requests.

**Comment by ale5000-git** [comment]
The image is pretty clear: `Phonesky doesn't have the correct signature`
Both GmsCore and Phonesky need the signature spoofing permission and you haven't granted it to Phonesky.

**Comment by UnderSampled** [comment]
Huh. I expected since it sounded like a replacement for the play store and not the services that it wasn't necessary for operation. I have found where to allow it to spoof, and it seems to work. Thanks

**Comment by ale5000-git** [comment]
The Google library (inside apps) expect both to be present and have correct signature even if they don't do anything.
