### ISSUE TITLE
ENF: don't return encounter matches older than 14 days.

### ISSUE THREAD

**Issue by Bubu** [microg/GmsCore#1614]
Currently recorded exposures are kept up to 15 days and are then cleaned out of the database. This leads to microG reporting too old matching encounters to CWA/CCTG and leading to this confusing display problem:

![image](https://user-images.githubusercontent.com/105185/142232134-3a6171c5-7a99-4ce9-9439-485d036473bc.png)

**Comment by Bubu** [comment]
CCTG issue: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/159

**Comment by Bubu** [comment]
Heh, is seems that this can happen via google ENF as well: https://github.com/corona-warn-app/cwa-app-android/issues/4407#issuecomment-977725175

Which makes this strictly a CWA bug... I think? :thinking: :shrug:

**Comment by ale5000-git** [comment]
@Bubu
Isn't this already fixed by this PR? https://github.com/corona-warn-app/cwa-app-android/pull/4618

**Comment by Bubu** [comment]
I haven't really been keeping up with cwa things recently. It might very well be fixed, yes.

**Comment by fynngodau** [comment]
Yes, upstream fixed this quite a while back already
