### ISSUE TITLE
GmsCore.apk keeps disappearing from /system/priv-app on each reboot

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [microg/GmsCore#1615]
I do as the documentation suggests and do:
`adb push GmsCore.apk /system/priv-app/GmsCore/` but after I reboot, the folder disappears

**Comment by JonnyTech** [comment]
Seems like you have Magisk installed.

**Comment by 1-minute-to-midnight** [comment]
Yeah.....is that a problem? Do I have to get microg from the microg-installer-revived module? But you see it comes with droid guard installed which is proprietary and I don't want it on my system

**Comment by JonnyTech** [comment]
I am not a magisk user but I believe that it creates an overlay to the system partition so is not writing the gmscore apk to the actual system partition. Try copying the apk there from recovery.

**Comment by 1-minute-to-midnight** [comment]
That worked. Thanks.
