### ISSUE TITLE
Implement snapshot feature in maps API

### ISSUE THREAD

**Issue by mar-v-in** [microg/GmsCore#1617]
The current implementation of the maps API lacks support for the snapshot() functionality.

https://github.com/microg/GmsCore/blob/master/play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt#L483

This is a requirement for location sharing in Signal messenger.

**Comment by khao-soi** [comment]
Is there an easy way to test this function? Last night I tried to implement this method, but I lack experience in kotlin and android development.

**Comment by mar-v-in** [comment]
You can try out most maps features (including the snapshot feature) in the maps api demo app: https://github.com/googlemaps/android-samples/releases/tag/v1.6.0

**Comment by khao-soi** [comment]
So, I tried a few things here. When I connect my phone (LOS + microG) and attacht the debugger to its com.google.android.gms process it doesn't seem to hit any breakpoint. 
When I create a virtual device (Nexus 6 for no specific reason) based on the Android 10.0 microG Image and start the maps demo app I get "Maps SDK for Android Demos (Kotlin) won't run without Google Play Services". Self-Check has everything besides Phonesky and GSF.

Any ideas?

**Comment by mar-v-in** [comment]
For using microG in Android Emulator, check https://github.com/microg/GmsCore/wiki/Development-Tools#using-the-emulator

For debugging apps that use Maps API, you need to attach the debugger to the app using Maps, not com.google.android.gms.

**Comment by fynngodau** [comment]
Snapshots are now implemented:

https://github.com/microg/GmsCore/blob/d56b6a088fab43397be4f2cec65f12a90dde7187/play-services-maps-core-mapbox/src/main/kotlin/org/microg/gms/maps/mapbox/GoogleMap.kt#L477-L500
