### ISSUE TITLE
How to uninstall microG from huawei?

### ISSUE THREAD

**Issue by A7madshareef** [microg/GmsCore#1623]
How do I remove microG from huawei, I downloaded it and uninstalled it and when try downloading another version it either says (you already have a newer version of this app) or ( package signature doesn't match the installed app, try uninstalling the current version)
I DON'T have it my apps list in settings.
And I checked system apps and it is not there.
Please help. ❤️🙏

**Comment by fynngodau** [comment]
Are Google Play services installed on your device?

**Comment by A7madshareef** [comment]
> Are Google Play services installed on your device?

No, my device is huawei y9a, it doesn't have Google play services.

**Comment by Iey4iej3** [comment]
It seems impossible to unlock bootloaders for Huawei devices, and MicroG does not seem to be installable there.

**Comment by AlexanderCormi4** [comment]
Maybe @A7madshareef has YouTube Vanced? Afaik, you need their implementation of microG before being able to sign-in to your Google account

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version (microG can now spoof another device) so I close it for now.
Open a new issue if needed.
