### ISSUE TITLE
[be.belfius.directmobile.android] <scanning function of app not working>

### ISSUE THREAD

**Issue by antio789** [microg/GmsCore#1625]
**Affected app**
Name: Belfius Mobile
Package id: [be.belfius.directmobile.android]

**Describe the bug**
when using the app the scanning function doesn't work and I receive this message: impossible to load the necessary data for scanning. update the Google Playstore or try later.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch the app
2. Click on Scan my debit card (to login) / same behaviour if logged in when trying a mobile payment 
3. See error

**System**
Android Version: [10]
Custom ROM: [/e/OS 0.20-20211215151800]

**microG**
microG Core version: [e.g. 0.2.22.212658-158]
microG Self-Check results: [Permission to find accounts on the Device, Permission to receive text messages SMS not ticked]

**Additional context**
app version 21.4.0 used to work on previous build
google play store is not installed, fake store 0.1.0 installed

**Comment by redfast00** [comment]
This still does not work on the latest version of the Belfius app and microG, I'm available to give more debugging information if needed.

**Comment by redfast00** [comment]
Since @mar-v-in and @lfxgroove wrote the code for the Vision Barcode API (https://github.com/microg/GmsCore/commit/5e39818a20032d261215420fc72e05efad4202b5), maybe they have some clue about how to debug or even fix this?

**Comment by redfast00** [comment]
It now seems to work :D I think this issue can be closed @antio789

**Comment by ArchangeGabriel** [comment]
@redfast00 Was there any change that made it work?

**Comment by redfast00** [comment]
I don't recall having to do anything, might have to do with a Belfius app update?

**Comment by rmelotte** [comment]
I can confirm that in my case it started working after a Belfius app update (unfortunately I have no information on what version specifically).
