### ISSUE TITLE
[com.ting.dashboard] Ting (no account needed) 

### ISSUE THREAD

**Issue by Maxwell175** [microg/GmsCore#1632]
**Affected app**
Name: Ting
Package id: com.ting.dashboard

**Describe the bug**
When trying to log in, app says "Please check your Email and Password" and the following appears in logcat:
```
01-04 17:09:22.316  7640 12145 I TingAPI : Added ACCEPT: application/json
01-04 17:09:22.317  7640 12145 I TingAPI : Posting feed: https://m.ting.com/mobile/v2/get_access_token
01-04 17:09:22.429  7640 12145 I TingAPI : Got result: {"token":"<snip>
01-04 17:09:22.507 12309 12309 D GmsSafetyNetAttest: Payload: SafetyNetData{nonce=[size=169 text=<snip>…], packageName=com.ting.dashboard, signatureDigest=[[hex=<snip>]], fileDigest=[hex=<snip>], gmsVersionCode=212658000, seLinuxState=SELinuxState{supported=true, enabled=true}, currentTimeMs=1641334162458}
01-04 17:09:04.164  1395  1395 W NotificationHistory: Attempted to add notif for locked/gone/disabled user 0
01-04 17:09:22.516  1395  4615 W ActivityManager: Unable to start service Intent { act=org.microg.gms.droidguard.REMOTE pkg=org.microg.gms.droidguard } U=0: not found
01-04 17:09:22.558 12309 12309 E AndroidRuntime: FATAL EXCEPTION: main
01-04 17:09:22.558 12309 12309 E AndroidRuntime: Process: com.google.android.gms, PID: 12309
01-04 17:09:22.558 12309 12309 E AndroidRuntime: java.lang.RuntimeException: Status: 14, error:null
01-04 17:09:22.558 12309 12309 E AndroidRuntime:        at org.microg.gms.droidguard.ConnectorDroidGuardResultCreator$getResult$$inlined$suspendCoroutine$lambda$1.run(DroidGuardResultCreator.kt:48)
01-04 17:09:22.558 12309 12309 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:923)
01-04 17:09:22.563  1395 12416 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
```

**To Reproduce**
1. Open app.
2. Login. It seems error still appears in logcat even if invalid login is used.

**Expected behavior**
It is expected that the app would login normally.

**Screenshots**
N/A

**System**
Android Version: 11
Custom ROM: microg LineageOS 18.1

**microG**
microG Core version: 0.2.22.212658
microG Self-Check results: All Checked

**Additional context**
N/A

**Comment by ale5000-git** [comment]
The problem seems to be related to SafetyNet.
The solution is to update microG GmsCore to 0.2.23.214816 and enable SafetyNet.

**Comment by Maxwell175** [comment]
Confirming that this works after updating to latest microG and following the steps I mentioned in a reddit post to get SafetyNet to pass:
https://www.reddit.com/r/MicroG/comments/shmpng/confirmed_safetynet_passing_on_lineageos_microg/
