### ISSUE TITLE
com.vanced.android.youtube: Chromecast streaming not working on non root version of YT Vanced due to MicroG ?

### ISSUE THREAD

**Issue by Holguitar** [microg/GmsCore#1643]
**Affected app**
Name: YouTube Vanced non root
Package id: com.vanced.android.youtube

**Describe the bug**
Streaming to Chromecast is not possible with the non root version of YT Vanced, developers say due MicroG:
![IMG_20220125_152409](https://user-images.githubusercontent.com/18100580/151001452-eaeaca66-31c5-4091-b433-202f1e1f44cc.jpg)

**To Reproduce**
1. Start latest YouTube Vanced non root version
2. Click on the streaming icon.

**Expected behavior**
Streaming to Chromecast should start.

**System**
Android Version: 11
Device: Xiaomi Mi 9T
Firmware: Miui 12.1.1 global
Stock firmware

**microG**
microG Core version: 0.2.22.212658

**Additional context**
Older versions of YouTube Vanced with the build number 16.02.35 and earlier are working with latest MicroG.

**Comment by nnuel** [comment]
Does chromecast support work in MicroG in general? That to me is not really clear if I am able to cast on a degoogled tablet on LineageOS.

**Comment by Sapiosenses** [comment]
As far as I know microG has never claimed full/stable support for casting.

https://github.com/microg/GmsCore/wiki/Implementation-Status

**Comment by Sapiosenses** [comment]
Also, Vanced has been shutdown after legal threats by Google, so the whole issue may be moot at this point.

https://www.nasdaq.com/articles/youtube-vanced-to-shut-down-due-to-legal-reasons

**Comment by zekiz774** [comment]
@Sapiosenses Now there's a successor.

**Comment by ale5000-git** [comment]
Chromecast support in microG currenctly doesn't work correctly and also Vanced microG isn't microG.

Also Vanced microG was shutdown, if you use its successor you should report the proble to them.
