### ISSUE TITLE
Security alert: Use of private SafetyNet / Android device verification API key in `SafetyNetPreferencesFragment`

### ISSUE THREAD

**Issue by scottyab** [microg/GmsCore#1644]
Hi @mar-v-in  I'm tagging you as it looks as if my API key was added by you in this [commit](https://github.com/microg/GmsCore/commit/fd8ce71a836c8bf8ac9786d6ce0f58807a4a23c5#diff-7ecc83b144dcc9fc3995357aff03a35830f6cb9baa124f3d3201041d284617caR98) 

Google Cloud sent me a Suspicious Activity Alert as they spotted the use of my private API key for SafetyNet / Android device verification in this repository See [SafetyNetPreferencesFragment Line:98](https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/kotlin/org/microg/gms/ui/SafetyNetPreferencesFragment.kt#L98). The API key is specifically for the  [safetynet sample app](https://play.google.com/store/apps/details?id=com.scottyab.safetynet.sample) in the Play store that I created as a demo of SafetyNet aTest Verification that people have found useful. 

**I'm not clear how and why this API key has been used here and compromised by this repo?**  

I also don't understand the use of the `com.scottyab.safetynet.sample` here in the [Attestation](https://github.com/microg/GmsCore/blob/4a5c98491bcfe4754b3efcfed20f3ada75a6ebec/play-services-safetynet-core/src/main/java/org/microg/gms/safetynet/Attestation.java) I'd be grateful for some more context. 

These device verification Google Cloud API calls are free if the usage stays low. However I'm not able to guarantee this anymore given the API key is public. Therefore *I'm planning to revoke the API key* but before I do I wanted to get some more context from you. To resolve you'll need to sign up to Google Cloud console and create your own API credential to use.

**Comment by mar-v-in** [comment]
Hi.

The motivation of having the API key in there is to allow users to test a verification as if it was performed by your app for test reasons. If you feel uncomfortably with your app being used as a the emulated app (I expected you to be fine with that as your app is specifically about testing SafetyNet), I can obviously change this to any other app, but the motivation is to test as if it was a real app, not a simulated one.

Also be aware that your key is not compromised in this repository and was public since the public release of your app as it is the public API key bundled with your app.

**Comment by mar-v-in** [comment]
microG is an alternative, open-source implementation of Play Services, providing the same functions to apps as the Google implementation.

The settings screen has a section where users can enable/disable the SafetyNet API and there is a button to test the SafetyNet functionality. This button is currently simulating the behavior of a user pressing the test button in your SafetyNet test app.

> I'm not sure I see that as being quite the same as the key in plain text in this repository

I personally don't really see the difference. If someone was making an effort to use someone else's API key, they can always do so. With the right tools, extracting the API key from the APK is really only a two click thing.

As far as I know, Google requires you to enter the package name and certificate hash. As such, no abuse of the API key is possible for anyone not having access to your app signing key.

> Is there something prohibiting you or this project from using your own Google Cloud API key?

Technically any key could be used, but for reasons™, I don't have a Google account available to do so.
I contacted another app developer and will be using a key of them.

Sorry for the inconvenience.

**Comment by mar-v-in** [comment]
Close via af28974d979d07a7d9f914dda0281b0b24f5ef3f
