### ISSUE TITLE
Apps using PlayServices for location cannot get location using GPS

### ISSUE THREAD

**Issue by ibex107** [microg/GmsCore#1648]
**Describe the bug**
Certain apps seem to be dependant on PlayServices for location. These apps fail to get the GPS position from microg but have no problem getting location based on networks arround it. In other words when a certain location module is enabled, it gets location based on it (the accuracy is obviously very low). But when all location modules are disabled the apps don't get any location at all. Again, only those apps that require PlayServices for location have a problem. For example GPSTest or My Location (both apps from FDroid) don't have this problem and are able to get GPS coordinates without any issue. This is proved by the fact that when apps that don't require PlayServices for location get their position, they appear in settings as the only app that requested location during the usage time frame. On the other hand apps that need PlayServices for location appear in the location history together with MicroG to have requested location at the same time. After about 30 seconds both apps stop requesting location.

**To Reproduce**
1. Switch off all location modules in microG
2. Use an app that requires PlayServices for location (can be Mapy.cz, found on google play)
3. Try and get location
4. No location is found 

**System**
Android Version: 10
Custom ROM: LineageOS 17.1 (microg fork)
Device: Ginkgo (Xiaomi Redmi Note 8)

**Additional context**
The issue was already disscussed [here](https://github.com/microg/UnifiedNlp/issues/230) but it was in the wrong repo.
The part about being dependant on PlayServices for location might be wrong. It might be a completely different issue but to meet it seems like it.

**Comment by drago333** [comment]
Mapy.cz works for me. Can you please make sure that you have done the extra step in the [installation instructions](https://github.com/microg/GmsCore/wiki/Installation)  for location support. I suspect that is the reason for your issues.

After you do it, reboot, redo the self-check in microG settings, reboot again. You might need to reset app data for Mapy.cz so make sure you back up any data you might lose, delete app data, and run it again.

**Comment by ibex107** [comment]
The issue didn't appear again. I have no idea what caused the issue but it's fixed so there is no need to solve anything. It might have been LineageOS for microg but that's honestly just a guess.

**Comment by g-a-b** [comment]
This issue should be reopened since the problem isn't fixed. 

I face this very precise problem. Sometimes Google Maps can only display _Network Location_ whereas sometimes it succeeds in displaying _GPS Location_. I found two workarounds so far: a reboot of the device or a forced stop of Microg process.

This issue may have been fixed by [24b0bfa](https://github.com/microg/GmsCore/commit/24b0bfa998a23ace0851e5181cf5f3c13db28b5c) as mentionned in #1517 but I can't test it since /e/ does not embbeds `v0.2.27.223616` so far.

Android Version: 12
Custom ROM: /e/ 1.8.1
Device: beyondlte0 (Samsung S10e)

**Comment by g-a-b** [comment]
> You can simply install this version to test (system apps could be updated via installing an updated apk, say, via F-Droid).

Its on the phone I use daily. I don't want to break anything doing things I don't understand. And indeed I don't really understand all that underlying stuff.

**Comment by Iey4iej3** [comment]
> I don't want to break anything doing things I don't understand.

This is undo-able, and in general, it makes sense to keep apps up to date.

**Comment by skbnoqtrjf** [comment]
> Mapy.cz works for me. Can you please make sure that you have done the extra step in the [installation instructions](https://github.com/microg/GmsCore/wiki/Installation) for location support. I suspect that is the reason for your issues.
> 
> After you do it, reboot, redo the self-check in microG settings, reboot again. You might need to reset app data for Mapy.cz so make sure you back up any data you might lose, delete app data, and run it again.

could you tell me how to install that "additional patch"?
![image](https://github.com/microg/GmsCore/assets/143573917/86d8e9ba-d0af-4139-921e-526e81233f58)
