### ISSUE TITLE
Can't upgrade with F-droid

### ISSUE THREAD

**Issue by stemy2** [microg/GmsCore#1649]
**Describe the bug**
I try to upgrade GMScore with F-droid, the installation failed for an "unknown reason" (sic).

**To Reproduce**
1. Upgrade GMScore

**Expected behavior**
The upgrade succeed

**System**
Android Version: 8.1.0
Custom ROM: /e/ v0.19

**Comment by ale5000-git** [comment]
If I'm not wrong /e/ ships with a modified version of microG GmsCore (it imply that it also has a different signature) so you can't update it with the official microG GmsCore but you have to use the version provided by them.

**Comment by ale5000-git** [comment]
@stemy2: Alternatively if you have root you can replace the file in the system partition.

**Comment by ale5000-git** [comment]
The microG update for /e/ is here: https://gitlab.e.foundation/e/os/GmsCore/-/releases

**Comment by ale5000-git** [comment]
@stemy2
The microG update for /e/ is here: https://gitlab.e.foundation/e/os/GmsCore/-/releases
