### ISSUE TITLE
profiles feature doesn't work on Honor play 20(Huawei honor 20i)

### ISSUE THREAD

**Issue by GDWGH** [microg/GmsCore#1651]
**Describe the bug**
Login and pop up message: ”Sorry... There was a problem communicating with Google servers. Try again later”. 

**To Reproduce**
1. login
2. See error

**Screenshots**
![Screenshot_20220129_121210.jpg](https://s2.loli.net/2022/01/29/w7StElGIFzgJ2LX.jpg)

**System**
Android Version: 10
Custom ROM: Magic UI 4.0

**microG**
microG Core version: 0.2.23.214816
microG Self-Check results: not All ticked
![Screenshot_20220129_121624.jpg](https://s2.loli.net/2022/01/29/cfP9IFDjbrliG17.jpg)

**Comment by GDWGH** [comment]
the Firebase Cloud Messaging look like dosen't work either
![Screenshot_20220129_122248.jpg](https://s2.loli.net/2022/01/29/ep3Ct4wzBEgduLV.jpg)![Screenshot_20220129_121013.jpg](https://s2.loli.net/2022/01/29/CQgmyJ49oPZ1s7X.jpg)

**Comment by JonnyTech** [comment]
Without signature spoofing support then nothing will work. Is your ROM capable of doing so? Did you copy both `GMSCore` and `FakeStore` to `/system/priv-app/`?

**Comment by GDWGH** [comment]
> 

i can't move them to /system/priv-app/ and signature spoofing 
because Magic UI is base on Huawei's EMUI(12) and my phone use unisoc(i can't find anythink to root my phone)

**Comment by GDWGH** [comment]
> ‎如果没有签名欺骗支持，则一切都不起作用。您的ROM是否能够做到这一点？您是否同时复制了和到 ？‎`GMSCore``FakeStore``/system/priv-app/`

i can't move them to /system/priv-app/ and signature spoofing 
because Magic UI is base on Huawei's EMUI(12) and my phone use unisoc(i can't find anything to root my phone)

**Comment by JonnyTech** [comment]
Sorry, then you cannot use microG. If you can unlock bootloader then maybe you can install a custom rom or magisk. But this is not the place to ask. Mabe try at [XDA](https://forum.xda-developers.com/).

**Comment by ale5000-git** [comment]
@GDWGH

Push Notification Tester has been discontinued by its author so it will never works again, se here: https://github.com/bbindreiter/PushNotificationTester_App/issues/8
(at least until someone fork it and republish on Play Store)

**Comment by GDWGH** [comment]
> @GDWGH
> 
> **Push Notification Tester** has been discontinued by its author so it will never works again, see here: https://github.com/bbindreiter/PushNotificationTester_App/issues/8
> (at least until someone fork it and republish on Play Store)

oh I found it at apkpure

**Comment by ale5000-git** [comment]
@GDWGH: It doesn't matter, the server backend was disabled.

Quote:

> Of course. Source code is available for everyone to use.
> 
> Problem is on server side though. Backend is not available anymore as I took it offline.

**Comment by serrj-sv** [comment]
I found a solution:
- disable wifi/data
- re-install (or force stop + clear data/cache) microG service core
- open microG settings, choose profile
- force stop microG
- enable wifi/data
- go to microG settings and disable/enable google cloud registration (make sure it is registered)
- go login with your account

**Comment by GDWGH** [comment]
> I found a solution:
> - disable wifi/data
> - re-install (or force stop + clear data/cache) microG service core
> - open microG settings, choose profile
> - force stop microG
> - enable wifi/data
> - go to microG settings and disable/enable google cloud registration (make sure it is registered)
> - go login with your account

still not work and I need to use an app to register cloud massage       it said 0 app registed![Screenshot_20220204_124658.jpg](https://user-images.githubusercontent.com/57795156/152473661-2cc9211d-29ad-444d-9136-f9ff535b13b5.jpg)

**Comment by ale5000-git** [comment]
@GDWGH
If you don't have signature spoofing most apps will refuse microG, there is nothing to do.
The only thing is patch the apps itself to ignore signature.

**Comment by GDWGH** [comment]
> @GDWGH If you don't have signature spoofing most apps will refuse microG, there is nothing to do. The only thing is patch the apps itself to ignore signature.

so where can i "patch"  the app

**Comment by erik9012** [comment]
> > @GDWGH If you don't have signature spoofing most apps will refuse microG, there is nothing to do. The only thing is patch the apps itself to ignore signature.
> 
> so where can i "patch" the app

With a bit luck luckypatcher(https://www.luckypatchers.com/download/) could help you with patching apps from prevent checks related to signature. Good luck

**Comment by GDWGH** [comment]
this solution is work on my phone
reinstall that version --- login --- see error --- uninstall then install v0.2.23.214816   ----- login --- work
~~(may GSM is work beacuse i saw the apps is register)~~

**Comment by GDWGH** [comment]
> Sorry, then you cannot use microG. If you can unlock bootloader then maybe you can install a custom rom or magisk. But this is not the place to ask. Mabe try at [XDA](https://forum.xda-developers.com/).

![Screenshot_20220209_142050.jpg](https://user-images.githubusercontent.com/57795156/153133474-4a95d55f-d865-422c-842a-455d5d9b74ff.jpg)![Screenshot_20220209_141926.jpg](https://user-images.githubusercontent.com/57795156/153133478-684c7622-2316-4089-8fb6-2d19c73dc629.jpg)


work & it can be use

**Comment by itoledo** [comment]
> I found a solution:
> 
> * disable wifi/data
> * re-install (or force stop + clear data/cache) microG service core
> * open microG settings, choose profile
> * force stop microG
> * enable wifi/data
> * go to microG settings and disable/enable google cloud registration (make sure it is registered)
> * go login with your account

Confirmed working on P40 Pro, could login. It still wouldnt show any accounts on Google maps etc. but at least login from microg settings do work.
