### ISSUE TITLE
ENF: RSSI 0 dBm

### ISSUE THREAD

**Issue by transistortim** [microg/GmsCore#1655]
Hey,

I'm using microG included in CCTG. On 2022-01-27 in the evening, I upgraded CCTG to 2.14.1.2, which according to the info screen uses microG version 18214816000.
As can be seen in the plot below, after the update there are many encounters with an RSSI of 0 dBm in exposure.db. In the days before the upgrade everything seems fine.

Looking at recent changes to the ENF code, I stumbled upon https://github.com/microg/GmsCore/commit/110157dab8097bc6c6589c950483731f4175320d and marked durations of 0 as `x` and durations unequal 0 as `o`. The plot indicates only encounters with a duration of 0 are stored with a valid RSSI.
![2022-01-30 exposuredb](https://user-images.githubusercontent.com/26510865/151720070-54378d20-fdce-4653-9237-67fe9293af98.png)

Device: Motorola Moto G7 Play (channel) with stock Android 10 (Google Play services are installed)

Can anybody reproduce this? Python code to create the plot:
```Python
import datetime

import matplotlib.pyplot as plt
import matplotlib.dates as md
from matplotlib.lines import Line2D
import sqlite3


file_name = "2022-01-30 exposure.db"

plt.figure()
plt.ylabel("RSSI / dBm")
ax=plt.gca()
xfmt = md.DateFormatter("%Y-%m-%d %H:%M:%S")
ax.xaxis.set_major_formatter(xfmt)
plt.grid()

with sqlite3.connect(file_name) as db_conn:
    data = db_conn.execute("SELECT timestamp, rssi, duration FROM advertisements ORDER BY timestamp;")
    for entry in data:
        x = datetime.datetime.fromtimestamp(int(entry[0]/1000))
        y = entry[1]
        if entry[2] == 0:
            plt.plot(x, y, marker="x")
        else:
            plt.plot(x, y, marker="o")

legend_elements = [Line2D([], [], linestyle="None", color="k", marker="x", label="duration == 0"),
                   Line2D([], [], linestyle="None", color="k", marker="o", label="duration $\\neq$ 0",)]
ax.legend(handles=legend_elements)
plt.show()

```

**Comment by transistortim** [comment]
In my opinion the error is caused by the introduction of MIN in https://github.com/microg/GmsCore/commit/110157dab8097bc6c6589c950483731f4175320d.
We have `rssi = (a + r*b)/c`.
`c` is `MAX(duration, t-timestamp)`.
If `t < timestamp` (“timestamps in database are newer than reported system time”) => `t-timestamp < duration`. So MAX correctly yields `duration` as fallback.
`b` is `MIN(0, t-timestamp-duration)`.
As `t-timestamp < duration` (see above), `t-timestamp-duration` evaluates to a negative number, which is smaller than 0 and hence yielded by MIN. This causes `r*b` to have a different sign then `a` and may finally lead to 0 in the numerator.
Using MAX instead would yield 0 and discard the new rssi reading `r`, which corresponds to the intention of "ignoring new measurements of the same RPI when they are seemingly older than a previous measurement".

So MIN should be changed to MAX.

**Comment by mar-v-in** [comment]
Thanks for looking into this. Your assessment is 100% correct. This unfortunately leads to wrong risk calculations (see https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/223#issuecomment-364044). I'll prepare and push an update today.
