### ISSUE TITLE
changing NLP backend does not work

### ISSUE THREAD

**Issue by vincentvidal** [microg/GmsCore#1657]
When trying to change the NLP backend in microG settings, nothing happens: the previously selected one remains active and the new one does not activate. In this logcat (https://pastebin.com/TNu91KdX), grepped by 'backend', Mozilla NLP backend was initially selected. Then Apple NLP backend has been selected, Mozilla has been unselected, and all the way Mozilla NLP is triggered by microG and Apple NLP never.

This runs under iodéOS, which is based on LineageOS 18.1, with a self-compiled microG, with all commits from v0.2.23.214816 as of today.

**Comment by mar-v-in** [comment]
Fixed via https://github.com/microg/UnifiedNlp/commit/bdda930c87e7813c361ff00f17fa03e376d48b7f

**Comment by vincentvidal** [comment]
Tested. Many thanks
