### ISSUE TITLE
Missing Implementation of com.google.gms.common.GooglePlayServicesUtil

### ISSUE THREAD

**Issue by the1nine** [microg/GmsCore#1679]
**Is your feature request related to a problem? Please describe.**

Multiple applications recently reference this class and will crash upon startup when not installed. 

**Describe the solution you'd like**

A simple implementation would likely allow those apps to start up. [Reference](https://developers.google.com/android/reference/com/google/android/gms/common/GooglePlayServicesUtil)

**Describe alternatives you've considered**

Only the original GMS package would fix the issue.

**Additional context**

It looks like the developer page also shows a newer GoogleApiAvailability class with replacements for these calls.
[Reference](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability#showErrorDialogFragment(android.app.Activity,%20int,%20int,%20android.content.DialogInterface.OnCancelListener))

**Comment by wzuo** [comment]
+1, ecountered the same problem

**Comment by wzuo** [comment]
looks like this is implemented: https://github.com/microg/GmsCore/blob/ad12bd5de4970a6607a18e37707fab9f444593a7/play-services-base/src/main/java/com/google/android/gms/common/GooglePlayServicesUtil.java
did you manage to fix the issue @the1nine ?

**Comment by the1nine** [comment]
Looks like it isn't throwing exceptions for the missing class.
