### ISSUE TITLE
[<com.rapido.passenger>] <Rapido won't run without Google Play services, which are not supported by your device. >

### ISSUE THREAD

**Issue by whatanerdguy** [microg/GmsCore#1684]
**Affected app**
Name: [e.g. Rapido]
Package id: [e.g. com.rapido.passenger]

**Describe the bug**
In my opinion, this isn't a bug, the app doesn't work without Google Play services, that is why I installed **MicroG Services**, but the result was same even after installing MicroG

**To Reproduce**
1. Go to Playstore or Aurora Store
2. Search for Rapido
3. Download and install the app

**Expected behavior**
A popup error showing **Rapido won't run without Google Play services, which are not supported by your device. **

**Screenshots**
Below is the screenshot of the error
![Rapido](https://user-images.githubusercontent.com/101058137/156973990-c2fa69ee-d0fa-44a7-aad5-4c2f3b0c219b.jpg)

**System**
Android Version: [e.g. 11]
Custom ROM: [e.g. LineageOS 18.1]

**microG**
microG Core version: [e.g. 0.2.24.214816]
microG Self-Check results: [e.g. All ticked]

**Comment by Dev0110** [comment]
See #1695

**Comment by ale5000-git** [comment]
This seems to be an installation issue.
I suppose you have already fixed it as of now, if not the case please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and then if the issue still apply write it here.
