### ISSUE TITLE
Self-test is fully checked - but "... needs Google Play services" still shows up?

### ISSUE THREAD

**Issue by IngwiePhoenix** [microg/GmsCore#1695]
**Describe the bug**
I installed Lineage OS 18.1 way before reading about microG, which inherently means that I never installed the LineageOS distribution with microG pre-installed. I kinda regret that, but due to dodgy USB on my phone and having a pretty good setup right now, I don't feel like nuking the entire installation. If possible, that is.

In order to install microG, I used:
- Magisk + Zygisk
- LSPosed via Zygisk
- [whew-inc fork of FakeGApps](https://github.com/whew-inc/FakeGApps)
- Aurora Store via F-Droid with Root Installation method

Within the microG settings, all checks are set. But no matter which app I open - Discord, Spotify, Paypal or other random games like progressbar98 - they all tell me that "Google Play Services is not installed". Huh? O.o

**To Reproduce**
Steps to reproduce the behavior, shortened:
1. Install LineageOS 18.1 on Razer Phone 2
2. Install F-Droid, Aurora Store
3. Install Magisk, LSPosed, whew-inc FakeGApps
4. Select "System Framework" and "MicroG Core Services"
5. Install an app (i.e. Discord) via Aurora Store
6. Open said app. Chances are you see the notification of missing Google Play services.

**Expected behavior**
I just want to get my notifications from the apps I use - Discord being the most important one.

**Screenshots**
Because I will post a lot of them, I decided to put them into a summary.

<details>
<summary>Screenshots</summary>

![Screenshot_20220320-225447_Shell](https://user-images.githubusercontent.com/2893716/159187872-7c7d8f8d-1f48-485c-ae7f-c73e985a9b39.png)

![Screenshot_20220320-225516_Shell](https://user-images.githubusercontent.com/2893716/159187873-1c046b1b-9c43-4135-a1c4-2fa97059ec89.png)

![Screenshot_20220320-225706_Magisk](https://user-images.githubusercontent.com/2893716/159187875-62ba4c08-0629-443c-b0c7-59777ac08090.png)

![Screenshot_20220320-225716_Magisk](https://user-images.githubusercontent.com/2893716/159187876-c8e81efd-895d-4c7d-ab96-66d96cd0ffc8.png)

![Screenshot_20220320-225310_Discord](https://user-images.githubusercontent.com/2893716/159187878-4ec6c766-a575-44b2-9234-f378a4feb61b.png)

![Screenshot_20220320-225419_Shell](https://user-images.githubusercontent.com/2893716/159187879-9c834ad6-ddb3-40ca-9243-0899f5a37341.png)

</details>

**System**
Android Version: 11
Custom ROM: LineageOS 18.1 (NOT "microG for Lineage")
Device: Razer Phone 2 (aura)
Magisk: 24.3
LSPosed Zygisk: 1.7.2
FakeGApps: 3.0 via whew-inc

**Additional context**
I do have a SeedVault backup. If possible, I'd like to avoid a full reinstall because accessibility during the setup wizard is useable but quite hard. I am visually impaired and using a phone as a magnifier for another phone to poke through setup is *not* fun ^^;

**Comment by IngwiePhoenix** [comment]
Just spotted this:

```
03-21 13:05:45.821  1917  1917 W Discord : Fetching FCM registration token failed
03-21 13:05:45.821  1917  1917 W Discord : java.io.IOException: MISSING_INSTANCEID_SERVICE
03-21 13:05:45.821  1917  1917 W Discord :      at b.i.c.s.n.b(com.google.firebase:firebase-iid@@21.0.0:60)
03-21 13:05:45.821  1917  1917 W Discord :      at com.google.firebase.iid.FirebaseInstanceId.m(com.google.firebase:firebase-iid@@21.0.0:16)
03-21 13:05:45.821  1917  1917 W Discord :      at b.i.c.s.i.a(Unknown Source:6)
03-21 13:05:45.821  1917  1917 W Discord :      at b.i.a.f.n.m.run(com.google.android.gms:play-services-tasks@@17.2.1:3)
03-21 13:05:45.821  1917  1917 W Discord :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-21 13:05:45.821  1917  1917 W Discord :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-21 13:05:45.821  1917  1917 W Discord :      at b.i.a.f.e.o.j.b.run(com.google.android.gms:play-services-basement@@17.6.0:2)
03-21 13:05:45.821  1917  1917 W Discord :      at java.lang.Thread.run(Thread.java:923)
```

(used `adb logcat | grep -i discord` for that but it feels incomplete)

I also did see FakeGApps giving Discord the fake signature a little further up.

Anything I can do here?

**Comment by IngwiePhoenix** [comment]
I figured it out and I am quite awestuck and have NO IDEA why this worked.

I used https://github.com/nift4/microg_installer_revived to install microG and somehow, *that* worked. I was immediately asked, even for already-installed apps, if I wanted to allow notifications.

I am truely confused. Why does a system install through magisk work, but a F-Droid install does not?

**Comment by msdhedhi** [comment]
Google SDK stub seems to be checking if the app was indeed installed via PlayStore app.
Try editing the file "/data/system/packages.xml" once your package is installed. Look for your desired package in this file and set the following 2 attributes to "com.android.vending"
installer="com.android.vending" 
installInitiator="com.android.vending"
Then reboot your device and see if the error message still occurs.

**Comment by Rakesh3929** [comment]
@msdhedhi I can confirm that changing the above made the apps like Rapido and Uber work seamlessly. In case of Ola, the only problem was the maps didn't appear to select "to" and "fro" but i could input it manually and book a ride. Thanks for this trick.

**Comment by ale5000-git** [comment]
This seems to be an installation issue.
I suppose you have already fixed it as of now, if not the case please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and then if the issue still apply write it here.

@Rakesh3929: If you still have the problem after updating to the latest nightly build, please open a separate ticket.
