### ISSUE TITLE
[com.paypal.android.p2pmobile] PayPal Crash

### ISSUE THREAD

**Issue by TheLastProject** [microg/GmsCore#1710]
**Affected app**
Name: PayPal
Package id: com.paypal.android.p2pmobile
Version: 8.16.0

**Describe the bug**
Crashes on startup

**To Reproduce**
1. Open the app
2. Wait

**Expected behavior**
No crash on startup

**Screenshots**
Not applicable

**System**
Android Version: 11
Custom ROM: LineageOS for microG 18.1

**microG**
microG Core version: 0.2.24.214816
microG Self-Check results: All ticked

**Additional context**
Crash log (collected with Scoop):
```
FATAL EXCEPTION: main
Process: com.paypal.android.p2pmobile, PID: 30271
java.lang.RuntimeException: Unable to create application o.syb: java.lang.ArithmeticException: divide by zero
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6724)
	at android.app.ActivityThread.access$1300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.ArithmeticException: divide by zero
	at o.xjm.h(Unknown Source:500)
	at o.yfv.a(:54)
	at o.xjm.b(:75)
	at com.paypal.android.p2pmobile.common.app.BasePayPalApplication.k(:2438)
	at com.paypal.android.p2pmobile.common.app.BasePayPalApplication.K(:835)
	at com.paypal.android.p2pmobile.common.app.BasePayPalApplication.onCreate(:615)
	at o.szg.onCreate(:43)
	at o.syb.onCreate(:8)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6719)
	... 8 more
```

**Comment by luke-jr** [comment]
FWIW, getting this same crash with LineageOS + MindTheGapps

**Comment by RobertoWa** [comment]
i am on a rooted android 10 stock (floyd v7) with microg, paypal working well.

**Comment by CoLdIcE42** [comment]
I am on also LineageOS for microG 18.1 and paypal is crashing

**Comment by craeckor** [comment]
I had the same Issues so I searched a little bit so I found a reddit and this guys had the same Issues but it's turned out that LineageOS is not the Problem. It's PayPal itself who create this Problems.
A Solution is to Download an older Version of PayPal: Version 8.12.1 https://paypal.de.uptodown.com/android/download/4511718

**Comment by Jan200101** [comment]
It appears downgrading is no longer possible, the app prompts the user to update blocking them from using the app.

**Comment by PiJ82** [comment]
Just tried the current version of Paypal, 8.31.0. This one does work on my phone again. With the previous version it didn't work.
So if the crash is really fixed now, the crash occurred in the version range [>8.12.1 <8.31.0]. Maybe someone could verify that?

**Comment by craeckor** [comment]
Lineage user here, I can confirm it's now starting without problems

**Comment by TheLastProject** [comment]
I no longer use the app. Given 2 people say it's fixed I'll close this, someone else can create a new issue if they care.

**Comment by Rastopapola** [comment]
@PiJ82 @TheLastProject @Jan200101 

Hey all, I happily detected that 8.31 worked back in December 2022. Naive as I was, I simply re enabled automatic updates again on the play store just to realize the latest version (~8.33) is broken again and won't start properly.

Especially interesting for @Jan200101 : I was able to reinstall the previous version using the [aurora store ](https://auroraoss.com/). In here you are able to look for a specific version of an app using the app detail page as described in [here](https://community.e.foundation/t/paypal-suddenly-nonfunctional/39973/14). The needed version code can be found on various apk databases. I used [apkmirror](https://www.apkmirror.com/uploads/?appcategory=paypal) and the corresponding version code for 8.31 which is _1150078402_ .

Works like a charm this way. Whoever has some online reach like a blog or vlog: Spread the word and help our lost souls out there. 

Love and out.

**Comment by Jan200101** [comment]
> Especially interesting for @Jan200101 : I was able to reinstall the previous version using the [aurora store ](https://auroraoss.com/).

Yeah, I found this version to be working too when it initially came out, but thanks for the heads up.

Lets hope this one won't be disabled so quickly again.
