### ISSUE TITLE
[com.google.android.apps.chromecast.app] Google Home does not launch

### ISSUE THREAD

**Issue by binex-dsk** [microg/GmsCore#1722]
**Affected app**
Name: Google Home
Package id: [com.google.android.apps.chromecast.app]

**Describe the bug**
Upon launching the app, it fails, with an error of "Home won't run without Google Play services, which are not supported by your device."

**To Reproduce**
1. Install Google Home
2. open it

**Expected behavior**
The app should launch

**Screenshots**
![IMG_20220518_174849.jpg](https://user-images.githubusercontent.com/65276418/169161548-a578c47e-5e59-4c20-8bb9-784dc22623de.jpg)

**System**
Android Version: 12
Custom ROM: GrapheneOS

**microG**
microG Core version: 0.2.24.214816
microG Self-Check results: I don't have signature spoofing, so those boxes aren't ticked. I also don't have most of the permissions, nor GSF.

**Additional context**
I don't have a logged in Google account

**Comment by ale5000-git** [comment]
> microG Self-Check results: I don't have signature spoofing, so those boxes aren't ticked. I also don't have most of the permissions, nor GSF.

You already have the answer, apps will never see microG without signature spoofing.

**Comment by binex-dsk** [comment]
> > microG Self-Check results: I don't have signature spoofing, so those boxes aren't ticked. I also don't have most of the permissions, nor GSF.
> 
> You already have the answer, apps will never see microG without signature spoofing.

Then how do I enable signature spoofing on GrapheneOS? Been searching for hours yet have found nothing on it

**Comment by ale5000-git** [comment]
I will say it in short, it is just based on discussion found over the internet so don't take it for granted.
GrapheneOS developers doesn't particularly like microG and they wouldn't do anything to simplify its installation, you can patch the ROM for signature spoofing but the patches that are simple to apply are less secure.

The simpler way is to choose a ROM that ship with a safe signature spoofing built-in.
