### ISSUE TITLE
Why isn't micro able to pretend to be play services without signature spoofing?

### ISSUE THREAD

**Issue by gohanko** [microg/GmsCore#1724]
As far as I know, when an application is installed, it's signature is pinned and subsequent updates needs to be signed with the same keys.

On a system without Play Services installed prior, isn't it possible to just use microg named and branded as play services? Why isn't it possible to install microg pretending to be play services without signature spoofing? Is there a built in feature in android that authenticates play services?

**Comment by ale5000-git** [comment]
Apps that use Google libraries bundle that library with them, so every apps check indipendently that the signature is from Google, so they only ways are patch the ROM or path all user apps (only the one that use Play Services).
