### ISSUE TITLE
Android Auto / Navigation via touchscreen of car

### ISSUE THREAD

**Issue by starbrights** [microg/GmsCore#1733]
**Is your feature request related to a problem? Please describe.**
My experience is that Android Auto doesn't work. It seems to recognise microG as a non or old Playservice.

**Describe the solution you'd like**
My car supports Android Auto, so it seems a good way to use the bigger display instead of the screen of mobile. I am using LOS and microG for years now and only in rare cases I run into problems. So for me the idea of using touchscreen of the car sound perfect, but I runs only with gapps, which I don't like in terms of sharing data. I don't need the full featured AA (phone, messanger, audio), just navigation would be fine. MicroG can handle  that in standalone navigation apps.

Please just let me know if there is hope to get something like that working. Otherwise maybe I need a second phone with just Android Auto running.

Anyhow, thanks for the great work in the last few years!

**Comment by ArchangeGabriel** [comment]
https://github.com/microg/GmsCore/issues/897

**Comment by starbrights** [comment]
Thanks, so it seem not completly impossible.  I will post further on in your linked main thread. Sorry that I miss that.
