### ISSUE TITLE
CTS profile match failed

### ISSUE THREAD

**Issue by GEkuL** [microg/GmsCore#1737]
**Affected app**
Name: microG Services Core

**Describe the bug**
Hi there, I'm using Xiaomi Redmi K20Pro/Mi 9T Pro (raphael) and I'm on Custom ROM with microG installed.
I can't get the SafetyNet check pass, even though I have all the required steps accomplished.
If I use GApps instead of microG Services everything works fine, yet when it comes to microG troubles arise. :(

**To Reproduce**
1. Set up Zygissk in Magisk
2. Install [safetynet-fix](https://github.com/kdrag0n/safetynet-fix/releases/v2.1.1), LSposed modules into Magisk
3. Install FakeGapps for LSposed
4. Do all the Self-Check in microG gms
5. Try to Test SafetyNet (both via microG and via SafetyNet Checker)
6. The test fails: `CTS profile match **Failed**`

**Expected behavior**
I must say that with GApps the safetynet passes, while microG don't give the same result :(
I guess this can probably be due to outdated droidguard setup inside the microG gms.

**System**
Android Version: 12L
Custom ROM: Project Blaze 1.1
Device: Xiaomi Redmi K20 Pro (raphael)

**microG**
microG Core version: 0.2.24.21.48.16
microG Self-Check results: All ticked

**Additional context**
Please, help me with the issue, I don't want to go back to google..

**Comment by WikiBayer** [comment]
This is not a microG Bug.
I have this error with other many ROMs.

You can fix it with ih8sn on thw most ROMs



The microG magisk module is better.

**Comment by GEkuL** [comment]
@WikiBayer could you share the links, pls?

**Comment by GEkuL** [comment]
@WikiBayer I've tried the solutions with official G.Play Services and with microG. It worked perfectly fine for official ones. So I guess the trouble is in microG :(

**Comment by GEkuL** [comment]
@Atemu I've solved the problem with microG magisk module. The trouble was that the spoofing supported by LineageOS/crDroid is only available on `/system/priv` installed apps, aka default system apps. So microG needs to be installed in that location.

**Comment by iTrooz** [comment]
(This feature should probably be closed as it's resolved)
