### ISSUE TITLE
Intent filter verification service / com.android.statementservice regularly crashing on LineageOS for microg

### ISSUE THREAD

**Issue by starbrights** [microg/GmsCore#1740]
I am aware this is a very unclear specification of a bug. 
It is not clear who and what is responsible for this - can be also Android12 (LOS).
But it seems to be that the combination of LOS and microG causes most of problems - from what I found in net.

**Describe the bug**
This message pops up from time to time. It seems not to harm anything, but is of course annoying.
Try to identify anything in log, but it's all very unclear to me.

**To Reproduce**
Right now I don't find a way to trigger it reliably.

**Expected behavior**
It should not pop up this message

**System**
Los  19 for microG, S10e  (Android 12)

**Additional context**
https://forum.xda-developers.com/t/com-android-statementservice-regularly-crashing-on-lineageos-for-microg.4452499/
I found some bug reports in telegram support channel for my ROM too, while maintainer means this is not device specific (which the above link confirms).

**Comment by maloo1** [comment]
As @starbrights mentioned this looks like it was also an issue with CalyxOS and they have "fixed" this by just hiding the error.

https://review.calyxos.org/c/CalyxOS/vendor_calyx/+/7976

I currently have CalyxOS 3.6.0 (android 12) installed on a Pixel 4a5g. I was originally having issues on Lineage for microg with this message appearing every 30sec to 1 minute while using the phone. The number of incidents did appear to grow as time went on and there did not appear to be anything the user was doing to trigger it (seemed random when using the phone, or watching it).

I can provide some more logs from CalyxOS if that would help (I assume it would still be logged just not displayed, but havent looked tbh).
There are some logs attached to the XDA link posted above when I was experiencing this on LOS 19 for microg...

**Comment by starbrights** [comment]
No Calyx for Samsung. Thought about /e/ but the fancy security stuff there is not even FOSS. 
The hack seems to me just a workaround. Would be curious what (or which app) exactly triggers that.

**Comment by johnfocker0** [comment]
Same issue on enchilada (OnePlus 6) on the latest LineageOS for microG build.

**Comment by wiryfuture** [comment]
I also have this on blueline/pixel 3. Annoying, hope it's not wasting too much battery life.

**Comment by starbrights** [comment]
The popups have been disappeard after some time. 
Lately I installed BetterBatteryStats and Magisk V25  (and few other things I don't remember) and it came back ?!?
Anyone else some more experience with that?

**Comment by Estebiu** [comment]
Same experience, Mi10T with los4microg.

**Comment by AwesomeFTW** [comment]
Same thing with LineageOS19 for microg, Samsung S10 
On my end, this seems to have something to do with Firefox nightly, using mpv as an external player, since the error completely stopped showing up when I quit those apps, even though the error was still showing up previously when restarting the entire device without stopping said apps.

**Comment by PEPSIMANTR** [comment]
I also have same thing on arowos with microg installed. Uninstalled the statementservice package by `pm uninstall -k --user 0 com.android.statementservice` command as a workaround and no more problems yet.

**Comment by flipreverse** [comment]
Hi folks!
This seems to be a bug in AOSP: https://android.googlesource.com/platform/frameworks/base/+/4978d1ad10293900e9b5feea349abd09ceb6e710
The LOS repo `android_frameworks_base` does not have this commit at the moment. I'll cherry-pick that one, and give it a try.

**Comment by ale5000-git** [comment]
The fix is now also in the LOS repo: https://github.com/LineageOS/android_frameworks_base/commit/fce1b15db00aae4447456359ac1c16bf773bbb26
