### ISSUE TITLE
[2.6.2-0] microG installer revived fails to install GMSCore

### ISSUE THREAD

**Issue by rogue-agent** [microg/GmsCore#1744]
**Affected app**
Name: GMSCore
Package id: com.google.android.gms-214816048.apk

**Describe the bug**
No play services app works. I tried installing the apk, I tried installing it via ADB AppControl but also failed. I tried via the Magisk module but it also fails. 

**To Reproduce**
1. Root
2. install Magisk modules Riru and Lposed restart inbetween
3. Install FakeGapps restart
4. Install MicroG magisk module
5. `Installing microG GmsCore Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification result]`

**Expected behavior**
Success of installation

**Log**
```
`- Copying zip to temp directory
- Installing microG_Installer_Revived.zip
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
**************************
 microG Installer Revived 
 by nift4 
**************************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: CHANGELOG
  inflating: customize.sh
  inflating: module.prop
  inflating: README.md
   creating: system/
   creating: system/etc/
   creating: system/etc/permissions/
  inflating: system/etc/permissions/privapp-permissions-org.microG.xml
  inflating: system/etc/permissions/com.google.android.maps.xml
   creating: system/etc/sysconfig/
  inflating: system/etc/sysconfig/org.microG.xml
   creating: system/etc/default-permissions/
  inflating: system/etc/default-permissions/permissions-com.google.android.gms.xml
   creating: system/priv-app/
   creating: system/priv-app/GsfProxy/
  inflating: system/priv-app/GsfProxy/GsfProxy.apk
   creating: system/priv-app/Phonesky/
  inflating: system/priv-app/Phonesky/Phonesky.apk
   creating: system/priv-app/GmsCore/
  inflating: system/priv-app/GmsCore/GmsCore.apk
   creating: system/framework/
  inflating: system/framework/com.google.android.maps.jar
- Installing microG GmsCore
Failure [INSTALL_FAILED_VERSION_DOWNGRADE: Package Verification Result]
- Done`
```

**System**
Android Version: 12
Custom ROM: stock, self root

**microG**
microG Core version: Revived 2.6.2-0
microG Self-Check results: 

**Additional context**
How am I to stop the G service apps from crashing all the time? How should I install GMSCore?

**Comment by ale5000-git** [comment]
Hi,
this isn't the right place.
You should report problems of microG installer revived here: https://github.com/nift4/microg_installer_revived/issues
