### ISSUE TITLE
gradle sync fails with fork because of no git tags 

### ISSUE THREAD

**Issue by iTrooz** [microg/GmsCore#1752]
**Describe the bug**

When cloning the repository, we can't make a gradle sync because git doesn't find any tag (github doesn't seem to copy them to the fork). Command failing : https://github.com/microg/GmsCore/blob/36d62fde7b75ebea2d238e3d8fc11721bda4ae43/build.gradle#L63

**To Reproduce**
- Create a fork of GmsCore
- run `./gradlew`
- Get the error 'Process 'command 'git'' finished with non-zero exit value 128'

**Other information**
Quick fix for this : create a tag locally, for example with `git tag -a v1.0`

**Comment by mar-v-in** [comment]
If your fork does not have the tags, you can fetch them from the main repository like this:
```sh
git fetch https://github.com/microg/GmsCore.git 'refs/tags/*:refs/tags/*'
```
