### ISSUE TITLE
Add Google Account: no network connection & Google device registration: not registered

### ISSUE THREAD

**Issue by fabian-thomas** [microg/GmsCore#1762]
**Describe the bug**
Trying to add an google account in the microG Settings leaves me on a "no network connection" screen (see below).
Enabling Google device registration leaves the Status "not registered".

**To Reproduce**
1. microG Settings app
2. Click Account
3. Click sign in

or:
1. microG Settings app
2. Click Google device registration
3. Select profile: automatic (resolves to native for me)
4. Tick on

**Expected behavior**
Google Account registration gives a prompt for mail address.
Google device registration says registered and GCM works.

**Screenshots**
[no connection screen](https://user-images.githubusercontent.com/4995833/185104486-b174a0e6-49a0-4075-a9bb-a53eb17f811d.png)

**System**
Android Version: 12
Custom ROM: LineageOS + microG 19.1 (19-20220804-microG-bramble)
GmsCore: 0.2.24.214816
Everything is ticked in self check
Device: bramble / Pixel 4a 5G

Note that I switched from LineageOS 19.1 (plain, no gapps nor microg) to LineageOS + microG 19.1 by applying it as update in LineageOS recovery.

**Fixes I tried**
I tried all the tricks from https://github.com/microg/GmsCore/wiki/Helpful-Information. So, calling trick, rebooting in between. Rebooting with device registration on/off, etc. Nothing worked.
I also tried to switch private DNS to off, like stated [here](https://github.com/microg/GmsCore/issues/1513#issuecomment-877783448).

I confirmed that I can ping `mtalk.google.com`, so no blocking is in the way I guess. Note that I did not configure anything in that direction manually.

**Additional context**
If I enable device registration the logs are full of:
```
08-17 13:22:04.133  1696  2198 D ConnectivityService: Replacing NetworkRequest [ LISTEN id=130887, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10253 RequestorUid: 10253 RequestorPkg: com.google.android.gms] ] with NetworkRequest [ LISTEN id=130888, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10253 RequestorUid: 10253 RequestorPkg: com.google.android.gms] ] because their intents matched.
08-17 13:22:04.134  1696  2198 D ConnectivityService: NetReassign [no changes]
08-17 13:22:04.134  1696  2198 D ConnectivityService: Sending PendingIntent{75b7b48: PendingIntentRecord{f7fbe80 com.google.android.gms broadcastIntent}}
08-17 13:22:04.138  1696  2198 D ConnectivityService: Replacing NetworkRequest [ LISTEN id=130888, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10253 RequestorUid: 10253 RequestorPkg: com.google.android.gms] ] with NetworkRequest [ LISTEN id=130889, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10253 RequestorUid: 10253 RequestorPkg: com.google.android.gms] ] because their intents matched.
08-17 13:22:04.138  1696  2198 D ConnectivityService: NetReassign [no changes]
08-17 13:22:04.138  1696  2198 D ConnectivityService: Sending PendingIntent{b6331c7: PendingIntentRecord{f7fbe80 com.google.android.gms broadcastIntent}}
08-17 13:22:04.138  1696  1696 D ConnectivityService: Finished sending PendingIntent{75b7b48: PendingIntentRecord{f7fbe80 com.google.android.gms broadcastIntent}}
08-17 13:22:04.141  1696  2198 D ConnectivityService: Replacing NetworkRequest [ LISTEN id=130889, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10253 RequestorUid: 10253 RequestorPkg: com.google.android.gms] ] with NetworkRequest [ LISTEN id=130890, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10253 RequestorUid: 10253 RequestorPkg: com.google.android.gms] ] because their intents matched.
08-17 13:22:04.141  1696  2198 D ConnectivityService: NetReassign [no changes]
08-17 13:22:04.141  1696  1696 D ConnectivityService: Finished sending PendingIntent{b6331c7: PendingIntentRecord{f7fbe80 com.google.android.gms broadcastIntent}}
08-17 13:22:04.141  1696  2198 D ConnectivityService: Sending PendingIntent{adf7d92: PendingIntentRecord{f7fbe80 com.google.android.gms broadcastIntent}}
08-17 13:22:04.144  1696  1696 D ConnectivityService: Finished sending PendingIntent{adf7d92: PendingIntentRecord{f7fbe80 com.google.android.gms broadcastIntent}}
08-17 13:22:04.145  1696  2198 D ConnectivityService: Replacing NetworkRequest [ LISTEN id=130890, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10253 RequestorUid: 10253 RequestorPkg: com.google.android.gms] ] with NetworkRequest [ LISTEN id=130891, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&NOT_VCN_MANAGED Uid: 10253 RequestorUid: 10253 RequestorPkg: com.google.android.gms] ] because their intents matched.
08-17 13:22:04.145  1696  2198 D ConnectivityService: NetReassign [no changes]
```

When I click on sign in when adding an account I don't get any meaningful information in logcat.

**Comment by fabian-thomas** [comment]
Fixed by reinstalling micro g apk as noted in #1734:
Download gmscore apk from microg website. Then:
```
adb root
adb install com.google.android.gms-214816048.apk
```

**Comment by marvinwankersteen** [comment]
I had exactly the same problem after the upgrade from LineageOS 18 to LineageOS 19 and tried everything, but nothing worked.

For me, reinstalling the microg core as described by @fabian-thomas also helped.

I was afraid I was going to have to wipe my device ;)

**Comment by AtomToast** [comment]
unfortunately reinstalling did nothing for me :/ Notable is that on lineage 20 I get like a crossed out globe icon in my statusbar whenever I open the microg settings
