### ISSUE TITLE
When next Lemonadep Release? How to go from LineageOS (220816) to MicroG (220806)?

### ISSUE THREAD

**Issue by enoironline** [microg/GmsCore#1763]
Hello, when will the next update for Lemonadep be uploaded? The actual version is the 20220806.

I mistakenly installed the latest LineageOS version (20220816) instead of the latest from MicroG (20220806). Once the new MicroG version is available, I can do a dirty install. What else can I do to revert back to MicroG? Only a new installation? Do I have to follow the LineageOS instructions (https://wiki.lineageos.org/devices/lemonadep/install) for this, or is there an easier way?

**Comment by ale5000-git** [comment]
microG is NOT LineageOS for microG.
You should ask here: https://github.com/lineageos4microg/docker-lineage-cicd

**Comment by enoironline** [comment]
Thank you for the hint and the link.
