### ISSUE TITLE
Has microG considered applying for the FUTO grant program?

### ISSUE THREAD

**Issue by ronidee** [microg/GmsCore#1765]
I recently learned about FUTO which is a company with the goal to fight big tech (and got the financial power to do so). The creator is a developer/billionaire with love for FOSS as far as I understand.

Now they give out grants to projects that "fight tech tyranny" and microG was the first to come to my mind. The application is closed for this summer but the website says there'll be more in the future.

Is this something microG (or you, @mar-v-in ) is considering and could it help finance the project?

https://futo.org/grants/futo-fellows-program

**Comment by elevenfive** [comment]
Looks like they are already a recipient!  https://futo.org/grants/legendary-grants/
![Screenshot from 2022-10-06 20-13-30](https://user-images.githubusercontent.com/1291596/194460267-9c946729-54e1-44a1-9614-2c95b7b20525.png)

**Comment by mar-v-in** [comment]
Indeed. :)
