### ISSUE TITLE
Google account failed to login / sign-in

### ISSUE THREAD

**Issue by ghost** [microg/GmsCore#1793]
**Describe the bug**
Title is enough ig

**To Reproduce**
N/A

**Expected behavior**
It should login

**Screenshots**
Bruh
![Screenshot_20220926_235655](https://user-images.githubusercontent.com/86816436/192325039-b62b82b0-cfa3-4d5a-a977-322525593b62.jpg)

**System**
Android Version: 10
Custom ROM: EMUI 10.1

**Additional context**
I'm fuc- pissed off at this, I've been trying so sign-in for the whole day but it doesn't really work. Some fork does work though but they are outdated ( last commit 2020 ).

**Comment by ale5000-git** [comment]
There are mainly some know problems:
- If the account file got corrupted, then add account will always files, to fix it delete all the account files, restard the device and retry; the file to delete are listed here: https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/files/bin/minutil.sh#L41
- You have 2-Step verification enabled, the only fix is to disable it.

**Comment by ale5000-git** [comment]
You need to be root, or inside the recovery.

**Comment by ale5000-git** [comment]
The only thing that I can suggest without root is to do a factory reset and then retry from the start.
