### ISSUE TITLE
[com.google.android.apps.*] GMail, Google productivity apps "Add account" misbehaviour

### ISSUE THREAD

**Issue by ildar** [microg/GmsCore#1799]
**Affected app**
Name: Google ____(whatever)____
Package id: com.google.android.apps.*

**Describe the bug**
Apps fail to see the Google account, asking to Add a new one.

**To Reproduce**
1. Launch an app
2. See "Add account" view of MicroG
3. adding gets you back to 2

**Expected behavior**
Should use existing account

**System**
Android Version: 12
Custom ROM: LineageOS 19.1

**microG**
microG Core version:  v0.2.24.214816 Latest
microG Self-Check results: All ticked

**Additional context**
Seems that gapps framework updated, MicroG doesn't workaround it yet.

**Comment by ildar** [comment]
related bugs already reported: https://github.com/microg/GmsCore/issues/888, https://github.com/microg/GmsCore/issues/995, https://github.com/microg/GmsCore/issues/1701

**Comment by ildar** [comment]
WORKAROUND: install older apps that still work (more or less):

1. GMail version 2022.05.01.449051655 (63266744)
2. Drive version 2.21.497.3.90 (212657450)
3. Sheets version 1.21.502.02.40 (2150202440)
4. Docs version 1.21.502.02.40 (2150202440)
5. Presentations version 5.21.481.03.40 (214810340)
6. Keep version 5.21.481.03.40 (214810340)
7. Translator version 6.37.27.452667103.6-release (697732350)
8. Photo 5.79.0.432507389 (42470611)

The version code in `()` can be used for Manual installing with Aurora store.

**Comment by ale5000-git** [comment]
Have you tried recently with the latest [nightly build](https://microg.org/dl/core-nightly.apk)?
I have the latest version of Drive and it is working fine.

**Comment by ildar** [comment]
nope. Just installed and tried.
1. manually gave the permission to Contacts
2. launched the fresh new.
It doesn't show the cloud contents and asks Goo permissions again and again.

**Comment by ildar** [comment]
argh!
reinstalled the old version of Drive and it misbehaves as above. Seems it's
the Nightly MicroG's fault.

**Comment by ildar** [comment]
FakeStore 0.1.0log:
```
10-06 14:41:13.856  2913 29089 D GmsAuthManager: token present, but expired
10-06 14:41:13.865  2913 29089 D GmsHttpFormClient: -- Request --
10-06 14:41:13.865  2913 29089 D GmsHttpFormClient:
androidId=xxx&app=com.google.android.apps.docs&client_sig=xxxxxx&callerPkg=com.google.android.gms&callerSig=xxx&device_country=kz&Email=xxx.xxx%
40gmail.com
&google_play_services_version=223616000&is_called_from_account_manager=1&_opt_is_called_from_account_manager=1&lang=ru_KZ&operatorCountry=kz&sdk_version=32&service=oauth2%3Ahttps%3A%2F%
2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fdrive.file%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fdrive.metadata.readonly%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fdrive.readonly%20https%3A%2F%2Fdocs.google.com
%2Ffeeds%20https%3A%2F%2Fdocs.googleusercontent.com%20https%3A%2F%
2Fspreadsheets.google.com%2Ffeeds%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Factivity%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fcloudprint%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fdiscussions%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fdocs%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fdrive.apps%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fdrive.categories.readonly%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fmemento%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fnotifications%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fspreadsheets%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fvouchers%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fgmail.readonly%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fsubscriptions%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fpeopleapi.readonly%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fdrive.activity.readonly%20https%3A%2F%2Fwww.googleapis.com
%2Fauth%2Fpeopleapi.readwrite%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud_search.query&source=android&Token=aas_et%xxx-xxx-xxx-xxx
xxx-c%3D
10-06 14:41:14.486  2913 29089 D GmsHttpFormClient: -- Response --
10-06 14:41:14.486  2913 29089 D GmsHttpFormClient: Error=ServiceDisabled
10-06 14:41:14.487  2913 29089 W GmsHttpFormClient: Response line
'Error=ServiceDisabled' not processed
10-06 14:41:14.502 17170 17790 W DriveCore: [io-21]
[Service][Jni][user=e43868ff][HttpCallTransport] Auth error getting auth
token for CelloHttpCall{method=GET , url=
https://www.googleapis.com/drive/v2internal/about?fields=rootFolderId&reason=304&openDrive=false&syncType=2&featureLabel=android-sync-native,
hasRequestBody=false, acceptHttpResponseGzipEncoding=true,
failOnNonHttpsUrl=false, failOnCleartextPermitted=false,
contextRequestHeaders=Host : www.googleapis.com,user-agent :
Cakemix/2.21.497.03.90x (phhgsi_arm64_ab SP2A.220505.002)
Google.Drive/2.21.497.03.90x
(OS=Android;OSVer=12;Manufacturer=unknown;Model=Phh-Treble
vanilla;SyncEngine=Cello) Mozilla/5.0 (Linux; U; Android 12; ru-kz;
Phh-Treble vanilla Build/SP2A.220505.002) AppleWebKit/525.10+ (KHTML, like
Gecko) Version/3.0.4 Mobile Safari/523.12.2,Accept-Encoding : gzip,
additionalHeaders=}
10-06 14:41:14.502 17170 17790 W DriveCore: java.lang.Exception:
android.accounts.AuthenticatorException: evj
```

**Comment by ale5000-git** [comment]
Could you please send the complete log?

**Comment by ale5000-git** [comment]
It is possible that the app check if it is installed from Play Store.
If you used "microG unofficial installer" you can run `adb shell minutil -i com.google.android.apps.docs` to reinstall the package as if it were installed from Play Store even if Play Store isn't installed.

**Comment by ildar** [comment]
would be great if someone could confirm the Nightly+Drive working on
non-"microG unofficial installer" case

**Comment by ale5000-git** [comment]
My installer include also a configuration xml that is needed to make it working correctly: https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/files/etc/sysconfig/google.xml
Do you have it?

**Comment by ildar** [comment]
I installed everything under the files/etc . Didn't help either :-(

**Comment by Kenajcrap** [comment]
have you enabled account discovery in the google account that was registered through microG? You can check by going to Settings > Accounts > [Google Account Name] > Account preferences > "Allow apps to find accounts"

**Comment by ildar** [comment]
Surely it's on

**Comment by mar-v-in** [comment]
Are you using a regular/personal google account or a work/managed account?

**Comment by ildar** [comment]
пт, 21 окт. 2022 г., 15:18 Marvin W :

> Are you using a regular/personal google account or a work/managed account?
>
Personal

**Comment by ale5000-git** [comment]
@ildar
Could you please try to update microG to v0.2.26.223616 and then uninstall and reinstall the apps that have problems?

**Comment by ildar** [comment]
@ale5000 ,
I installed as you suggested and it now works. Thanks a lot!
Then I'll close the issue...
