### ISSUE TITLE
getCallingPackage called without parameter

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#1811]
[getCallingPackage](https://github.com/microg/GmsCore/blob/master/play-services-base-core/src/main/java/org/microg/gms/common/PackageUtils.java#L168) expect a context parameter but [here](https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/org/microg/gms/auth/AccountContentProvider.java#L59) is called without it.

Is it intended?

**Comment by mar-v-in** [comment]
That is `ContentProvider.getCallingPackage()`, not the one from `PackageUtils`.
