### ISSUE TITLE
Cannot Select Google Drive Account On Whatsapp

### ISSUE THREAD

**Issue by orkninos2** [microg/GmsCore#1824]
**Describe the bug**
When you try to select a google account to backup your data it will give you the sign in option rather than the select account option. 

**To Reproduce**
1. Go to Whatssapp
2. Click on settings
3. Select chats
4. Select chat backup
5. Select google account option

**Expected behavior**
Select google account option.

**Screenshots**

**System**
Android Version: [12]
Custom ROM: [LineageOS 19]

**Additional context**
When you click on sign in and enter you email it says: "This account already exsists on your device."![Screenshot_20221111-161340_microG Services Core.png](https://user-images.githubusercontent.com/82326430/201347776-fd3ed5da-4849-4d1f-8c4b-229f32e3e783.png)

**Comment by ale5000-git** [comment]
What is the version of microG GmsCore?

**Comment by orkninos2** [comment]
Microg Version:0.2.25.223616

**Comment by ale5000-git** [comment]
Do you see the account in other apps?

**Comment by orkninos2** [comment]
> Do you see the account in other apps?

Yes only on whatsapp that happens to me

**Comment by ale5000-git** [comment]
Did you grant Contacts permission to WhatsApp?

**Comment by orkninos2** [comment]
> Did you grant Contacts permission to WhatsApp?

Yes

**Comment by orkninos2** [comment]
I fixed it via allowing apps to see my accounts without prior authorization.
Go to settings
Tap on accounts
Select google account
Tap on personal info and privacy
And enable apps to find accounts

**Comment by SODDINGIT** [comment]
This is the solution:
https://github.com/microg/GmsCore/issues/1988#issuecomment-1910083365

**Comment by Aquind** [comment]
I'm having the same issue with WhatsApp (some other apps) and microG 0.3.9 in /e/OS 3.2 (android 14)

Login Loop and then getting the, "Account already exists on this device" when trying to connect to a google account.  

Under MicroG Services>>Google Accounts: "allow apps to find accounts", "trust google for app permissions", and "Authenticate with device registration" are all enabled.

**Comment by Panelgamer** [comment]
Having the same issue that Aquind is having now. Did y'all found a solution?
