### ISSUE TITLE
Unable to log in an account

### ISSUE THREAD

**Issue by BigmenPixel0** [microg/GmsCore#1828]
**Describe the bug**
I want to add an account. When I enter my email and click on "Next", I get a crush.

**To Reproduce**
1. Go to the microg settings.
2. Click on "Add Google account.
3. Enter your email.
4. Click on "Next".

**Expected behavior**
Log in an account.

**System**
Android Version: 12
Custom ROM: CipherOS v3.8

**Comment by ale5000-git** [comment]
The was a bug in microG GmsCore that is already fixed, you can get the latest nightly build of microG GmsCore here: https://microg.org/dl/core-nightly.apk

**Comment by Ahmed0002** [comment]
I sign in to Google account and Google play successfully
But can't signin to Google map , Google drive , Google translation , ... Ect

**Comment by MininxD** [comment]
> I sign in to Google account and Google play successfully But can't signin to Google map , Google drive , Google translation , ... Ect

Try LSPosed and install FakeGapps Module, this module will swap GMS into MicroG
LSPosed is an Xposed you can install trough magisk 

![Screenshot_20221127-071028_Shell](https://user-images.githubusercontent.com/70429604/204123924-0c9ebf70-3733-4689-82e3-ba3cae9acf39.png)

**Comment by ale5000-git** [comment]
@Ahmed0002
First update microG GmsCore to v0.2.26.223616] or later, the uninstall and reinstall the apps that aren't working.

**Comment by BigmenPixel0** [comment]
Should I close the issue?

**Comment by ale5000-git** [comment]
If your problem is fixed yes :)

**Comment by Ahmed0002** [comment]
@ale5000-git I will try do that and told you what happened with me

**Comment by BigmenPixel0** [comment]
I have this problem again on the latest version.
LOS 19.1

**Comment by BigmenPixel0** [comment]
Hmm. It doesn't work with Bromite WebView...

**Comment by ale5000-git** [comment]
@BigmenPixel0
Please open a new ticket.
