### ISSUE TITLE
FIDO2 fails in the new version of MicroG

### ISSUE THREAD

**Issue by DevelopingEntitiesWithFuntations** [microg/GmsCore#1829]
**Describe the bug**
YubiKey FIDO2 doesn't react to the key normally. My installed apps are Openkeychain and Yubico Authenticator.

**To Reproduce**
1. Go to Paypal.com
2. Login
3. Go to settings and start adding a security key
4. MicroG opens, tried NFC and USB - for NFC it just vibrates and nothing happens for USB it asks for permission which I allow and then also does nothing. If I think the button it goes back in the menu.

**Expected behavior**
The menu goes thru and the key gets added to the security key list.

**Screenshots**

**System**
Android Version: 13
Custom ROM: CalyxOS 4.3.0

**Additional context**

**Comment by JonnyTech** [comment]
Which build are you using? Please try the latest nightly: https://microg.org/dl/core-nightly.apk

**Comment by DevelopingEntitiesWithFuntations** [comment]
The one that's built by the CalyxOS devs. In the MicroG App it states it is 0.2.25.223616-41 (b22416d)

**Comment by ale5000-git** [comment]
This is possibly already fixed, but to be sure please post a logcat.

**Comment by DevelopingEntitiesWithFuntations** [comment]
How do I do a logcat? Any tutorial or similar link would be appreciated.

**Comment by ale5000-git** [comment]
Look here: https://wiki.lineageos.org/how-to/logcat
(ignore the part about the radio buffer)

**Comment by DevelopingEntitiesWithFuntations** [comment]
You and the tutorial forgot to mention that you need to turn on developer mode and enable USB debugging. 

I treid it but the NFC interaction doesn't seem to get logged and fofr some reason adb closes the logging instantly and writes a 4,1MB almost instantly each time...

**Comment by ale5000-git** [comment]
Inside the guide there is a link "adb installed" that link to this page: https://wiki.lineageos.org/adb_fastboot_guide#installing-adb-and-fastboot
There it explain the other things.

The fact that it losg also previous things is normal but the fact that it stop it isn't normal, it only happen when the usb connection is lost.

**Comment by DevelopingEntitiesWithFuntations** [comment]
Well I did the steps corectly it seems. Under `adb devices` I could see the device as well, needed to enable file transfer mode to see it though. What else can I try?

**Comment by ale5000-git** [comment]
The alternative is to see logcat directly in the phone with this app: https://f-droid.org/it/packages/com.dp.logcatapp/
After install and before use you should grant the permison with: `adb shell "pm grant com.dp.logcatapp android.permission.READ_LOGS && am force-stop com.dp.logcatapp"`

**Comment by DevelopingEntitiesWithFuntations** [comment]
And where does it save the output to? On the smartphone or on the screen?

I will try it tomorrow.

**Comment by ale5000-git** [comment]
If you can see directly on the screen of the smartphone, but if you choose to record it, then the file can be shared with other apps.

Please update microG GmsCore to v0.2.26.223616 before trying.

**Comment by DevelopingEntitiesWithFuntations** [comment]
Doesn't quite matter anymore since PayPal doesn't support FIDO keys on the phone :sweat:

**Comment by DevelopingEntitiesWithFuntations** [comment]
Oh setting the page to desktop mode solves the issue! I guess it was fixed with Version 0.26! Great job, thank you!
