### ISSUE TITLE
20221118 update of lineageos microG causes infinite boot loop

### ISSUE THREAD

**Issue by p2wei** [microg/GmsCore#1831]
**Describe the bug**
I was notified of a new update today and installed it from the LineageOS updating app. After the normal reboot, neither the SIM pin input nor the login came up, instead I saw the LineageOS boot animation which stopped at some point to reboot the system. This continued at least 5 times and it fully reproducible.

**To Reproduce**
1. Update to lineage-19.1-20221118-microG-kirin (the old version was probably 20221021).
2. Reboot
3. Bootup does not complete, device reboots

**Expected behavior**
Get a normal boot.

**System**
Device: Sony Xperia 10 (kirin)
Custom ROM: LineageOS 19.1 microG version

**Additional context**
After a few trials I managed to try again overwriting the update with the lineage-19.1-20221118-microG-kirin.zip file (downloaded on my laptop) using adb sideload after booting the device into recovery. That did not help.

What _did_ help is to sideload the official LineageOS without microG (lineage-19.1-20221115-nightly-kirin-signed.zip). Then the boot got as far as the pin input.
After getting back to recovery, I installed the above microG version again, with the result of getting the boot loop again.

That's why I think it must have something to do with microG and the reason of reporting this issue here.

**Comment by p2wei** [comment]
After one of the failed boot I was able to get to recovery and /sys/fs/pstore/console-ramoops-0 (seems to be missing the first ~10s) and the output of dmesg which seems complete. I'm not sure if they are any good to tell someone what's going on, but here they are:

[console-ramoops-0__failure__partial.txt](https://github.com/microg/GmsCore/files/10051015/console-ramoops-0__failure__partial.txt)

[dmesg__failure.txt](https://github.com/microg/GmsCore/files/10051024/dmesg__failure.txt)

**Comment by Hendrick42** [comment]
Same issue - same device and versions here.
Update was OTA - but also direct install after a complete wipe of lineage-19.1-20221118-microG-kirin.zip results in a bootloop.

Before i tried a dirty install of lineage-19.1-20221115-nightly-kirin-signed.zip which was booting fine.

I am not shure what version was there before, but lineage-19.1-20221021-microG-kirin.zip is working after wiping the whole device.

**Comment by p2wei** [comment]
I realized by now that of course the dmesg output that I posted above is from the recovery boot, so I guess it's useless to investigate the issue.

I do have the (complete) console-ramoops-0 of the successful boot of the non-microG installation. In case that's helpful to compare. (But I don't know what I would be looking for.)

Finally, I found at least two reports in the XDA forum (e.g. https://forum.xda-developers.com/t/lineageos-for-microg.3700997/page-126#post-87754221) discussing similar failures on other Sony devices (XA2 and XZ2 Compact).

**Comment by ale5000-git** [comment]
If it is what I think, it isn't the fault of microG.
The latest version of microG add a new privileged permission `android.permission.MANAGE_USB`, so if the ROM doesn't add it to the appropriate XML file it will bootloop.

**Comment by Hendrick42** [comment]
What I am curious about - if I read it correctly the whole partition A/B thing should be there if LOS failes to boot 3 times - switch to the other - hopefully working LOS image?
Now all my images are lost - but should this have worked here? I did not check which LOS version did a bootloop and if it switched between the two?
Would a manually switch via fastboot have help here?

**Comment by ale5000-git** [comment]
If you are good with the command line fixing is simple, simply boot in the recovery, then with abd save this file to the PC `/product/etc/default-permissions/privapp-permissions-com.google.android.gms.xml`, add [this change](https://github.com/lineageos4microg/android_vendor_partner_gms/pull/15/files#diff-39a2642a19a66da64378063f89ac95c76543e5c81810d6fe536deae56c118a84), the upload it back to the device.

**Comment by p2wei** [comment]
Thank you, @ale5000-git! You are correct that changing that file manually helped.

Two minor complications:

- I had to use "mount/unmount system" in the recovery and then found the file at `/mnt/system/system/product/etc/permissions/privapp-permissions-com.google.android.gms.xml`.
- To copy the changed file back, I needed to run mount the system read-write, i.e. run `mount -o remount,rw /mnt/system`, first (slightly scary because that output some message about "/dev/block/bootdevice/by-name/system_b").

But now my phone seems to work again!

**Comment by Hendrick42** [comment]
Okay, now i am confused:
Fresh install of lineage-19.1-20221021-microG-kirin.zip - start F-Ddroid update micro-g service core - then do an OTA upgrade to lineage-19.1-20221118-microG-kirin.zip: everything is working out of the box, no bootloop occurring.

Other thing: @p2wei can you access your userdata again? Or did you wipe anything before so everything lost? Did you try to switch images to get the other image booting agin?

Next try: Fresh install of lineage-19.1-20221021-microG-kirin.zip -  then do an OTA upgrade to lineage-19.1-20221118-microG-kirin.zip -> bootloop. So an upgrade of the Micro-g service core package _before_ the OTA to 20221118 did the trick...

When switching the  slot manually to a, with `fastboot set_active other` Recovery of 20221021 tells me `Can't load Android system. your data may be corrupt. If you continue to get this message, you may need to perform a factory data reset and erase all user data stored an this device` - which is quite heavy and not true at all?! 
So the fall back of the whole A/B partition stuff does not work at all :-/ Now i would be totally stuck, cause I have no chanche to get to my userdata... Slot A has a working system but tells me my userdata is broken - and B is in a bootloop.

So, booting into recovery - fstab is shwowing so `/dev/block/bootdevice/by-name/system_b / ext4 barrier=1 0 0` so a  `mount -o rw /dev/block/bootdevice/by-name/system_b /mnt/system` is letting me `adb push/pull` the `/mnt/system/system/product/etc/permissions/privapp-permissions-com.google.android.gms.xml` file. 

@ale5000-git - so if we do an microg gsm-core upgrade _before_ the OTA everything is working fine. If we forget this we luckyliy see your post to save us a lot of work of a reinstall :/

What i don't get till what the purpose of the whole A/B thing is if the user has to wipe everything if he follows the recommendation  (like i did yesterday...)

**Comment by ale5000-git** [comment]
@Hendrick42 Your method of update with F-Droid before OTA update isn't reliable because if you do a factory reset or wipe data you will probably end in a bootloop.

**Comment by Hendrick42** [comment]
> @Hendrick42 Your method of update with F-Droid before OTA update isn't reliable because if you do a factory reset or wipe data you will probably end in a bootloop.

Hm, i thought installing the "image" e.g. `lineage-19.1-20221115-nightly-kirin-signed.zip` brings everything to run the system. 
So does the microg update before the OTA install some files in the userdata /data which help here?

**Comment by imsodin** [comment]
Same on pioneer, will look into fixing it as described here now.

Who manages lineage.microg.org? Given this is serious and affects anyone using the OTA, pulling the latest update update would help mitigating.

**Comment by arnaudthuillier** [comment]
Thanks @ale5000-git & @p2wei ! That also fixed it for my xz2c 🎉

**Comment by eternal-sorrow** [comment]
at least remove the broken updates from the server so that it doesn't affect more people. this won't help my data unfortunately but maybe will help others.

**Comment by ale5000-git** [comment]
@eternal-sorrow
`LineageOS for microG` isn't `microG`, you should write here: https://github.com/lineageos4microg/docker-lineage-cicd/issues/360

**Comment by ale5000-git** [comment]
This is not related to microG itself and it is already fixed by this: https://github.com/lineageos4microg/android_vendor_partner_gms/pull/12
