### ISSUE TITLE
MicroG not working properly on WSA

### ISSUE THREAD

**Issue by fillwithjoy1** [microg/GmsCore#1834]
**Describe the bug**

The bug I'm facing is that microG isn't properly working in apps that require Google Play Services, although microG reports that it is ready
![image](https://user-images.githubusercontent.com/29514446/203044600-6516e9fe-e2a9-4402-80b7-71c13a2ff19b.png)
However using an app that requires Google Play Services still fails
![image](https://user-images.githubusercontent.com/29514446/203044726-c9e2c91c-78e5-477b-8bd9-4d747eac26bd.png)
And using Youtube Music simply crashes
![image](https://user-images.githubusercontent.com/29514446/203045427-f2598534-696f-4f1b-87a3-7fdc5b760768.png)

**To Reproduce**
0. Make sure you have adb tools available
1. Download the fragment from https://github.com/fillwithjoy1/WSA-Magisk/actions/runs/3514162624
2. Unzip all files and run Install.ps2 for Powershell
3. After installing Powershell, open WSA Settings > Developer > Developer Mode and connect to adb
4. Install [GmsCore ](https://github.com/microg/GmsCore/releases/tag/v0.2.25.223616)and all [other microG apps](https://microg.org/download.html) using adb install
5. Install [Riru](https://github.com/RikkaApps/Riru/releases) and flash via Magisk and reboot via adb push
6. Install [LSPosed module with Riru](https://github.com/LSPosed/LSPosed/releases/tag/v1.8.5) and reboot via adb push
7. Install a root file explorer (I installed [droid-ify](https://github.com/Iamlooker/Droid-ify) and used [Simple File Manager Pro](https://github.com/SimpleMobileTools/Simple-File-Manager)) and then /data/adb/lspd/manager.apk and copy to downloads, and then install it like usual
8. Make sure LSPosed manager is active, otherwise reboot
9. Install [FakeGApps](https://github.com/whew-inc/FakeGApps) and reboot
10. Check microG app and see that signature spoofing is on and grant all permissions
12. Use a app that requires Google Play Services
13. Die inside, realizing that it isn't working and write a report

**Expected behavior**

Literally work

**Screenshots**

**System**
Android Version: 12 (or 12L idk)
Custom ROM: Windows Subsystem for Android

**Additional context**
None

**Comment by fillwithjoy1** [comment]
I will add that if I install microG through [a Magisk module](https://github.com/nift4/microg_installer_revived) opening the microG app crashes which is why I need to rely on the normal app

**Comment by fillwithjoy1** [comment]
Logcat upon loading Youtube Music (com.google.android.apps.youtube.music)

[logcat.txt](https://github.com/microg/GmsCore/files/10061769/logcat.txt)

**Comment by Sapiosenses** [comment]
There were some microG app UI crash fixes in the latest release of GMSCore (v0.2.26.223616), some of which were related to Google account logins.

You may want to try updating to that release and see if it helps.

**Comment by fillwithjoy1** [comment]
> There were some microG app UI crash fixes in the latest release of GMSCore (v0.2.26.223616), some of which were related to Google account logins.
> 
> You may want to try updating to that release and see if it helps.

Nope, updated to that and still getting the same 'Get Google Play Services' error

**Comment by Sapiosenses** [comment]
My comment solely referred to crash fixes. If that's not the problem, then let's see: 

I have no experience trying to run microG on Windows Services for Android. It could be a problematic environment.

In step 1 of your problem description you mention downloading something for WSA that apparently has embedded Magisk. I see no reference anywhere on their repo about microG. Do you know for a fact that microG works in that Android emulator?

That repo has a discussion link. If I were you I would ask in their discussion if anyone has experience getting microG to work in that environment.

[doing a bit of research]

From what I can tell a lot of people had problems running microG on WSA, but it *might* work if you setup the virtual ROM (or whatever they call it) with SELinux in permissive mode.

Are you familiar with ROM building?

**Comment by fillwithjoy1** [comment]
I am aware of ROM building for WSA, although I'm a total noob and don't really know anything much about it

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=am95c2luZ2guanMxQGdtYWlsLmNvbQ==>

**Comment by fillwithjoy1** [comment]
And I am using a WSA + Magisk + NoGApps build which I'm using Magisk to try and install stuff

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=am95c2luZ2guanMxQGdtYWlsLmNvbQ==>

**Comment by ale5000-git** [comment]
@fillwithjoy1
The latest version of my [microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360) now support the installation via adb.

You have to extract zip-install.sh from the zip, send both zip-install.sh and the zip to the emulator then run it with:
`adb shell "sh full_path_on_the_device/zip-install.sh full_path_on_the_device/microg-unofficial-installer-v1.2.0-beta-by-ale5000-OSS-signed.zip"`

If you have any problem I can help you.

**Comment by fillwithjoy1** [comment]
> 

Hey @ale5000-git,
I've pushed it to my downloads on WSA and did the command adb shell "sh /sdcard/download/zip-install.sh /sdcard/download/microg-unofficial-installer-v1.2.0-beta-by-ale5000-OSS-signed.zip" this happens
![image](https://user-images.githubusercontent.com/29514446/212028451-2c812fc2-11f1-49df-b285-b3d96b38cf34.png)
Alright, I'll use adb shell su
![image](https://user-images.githubusercontent.com/29514446/212028547-8c8e51f0-3fb6-44eb-bbb5-d25c02b2a763.png)
Still stuck for the past 20+ minutes, probably stuck on something. Maybe this other method could help?
![image](https://user-images.githubusercontent.com/29514446/212029012-9ad0ce02-ff87-46c5-a6a6-346907adec79.png)
Also the same happens if I also execute it as root

**Comment by ale5000-git** [comment]
Have you tried to execute this?
`adb shell`
And then inside it
`su`
And then inside it
`sh /sdcard/download/zip-install.sh /sdcard/download/microg-unofficial-installer-v1.2.0-beta-by-ale5000-OSS-signed.zip`
?

**Comment by ale5000-git** [comment]
@fillwithjoy1
The new zip-install.sh will auto-root if possible.
You can get it here => https://raw.githubusercontent.com/micro5k/microg-unofficial-installer/main/zip-content/zip-install.sh

**Comment by ale5000-git** [comment]
@fillwithjoy1

Have you been able to make it working?

**Comment by fillwithjoy1** [comment]
@ale5000 <http://github.com/ale5000>

No I haven't, it's still just stuck on installing in the command prompt

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=am95c2luZ2guanMxQGdtYWlsLmNvbQ==>

**Comment by ale5000-git** [comment]
@fillwithjoy1

Please get the latest zip-install.sh from here: https://raw.githubusercontent.com/micro5k/microg-unofficial-installer/main/zip-content/zip-install.sh
Then send to the emulator, then run adb shell, then from inside adb shell run:
`cd /sdcard/download`
`sh ./zip-install.sh ./microg-unofficial-installer-v1.2.0-beta-by-ale5000-OSS-signed.zip || echo "Error code: ${?}"`

So if it fail I can know the error code.

**Comment by fillwithjoy1** [comment]
> @fillwithjoy1
> 
> Please get the latest zip-install.sh from here: https://raw.githubusercontent.com/micro5k/microg-unofficial-installer/main/zip-content/zip-install.sh Then send to the emulator, then run adb shell, then from inside adb shell run: `cd /sdcard/download` `sh ./zip-install.sh ./microg-unofficial-installer-v1.2.0-beta-by-ale5000-OSS-signed.zip || echo "Err code: ${?}"`
> 
> So if it fail I can know the error code.
> 
> **PS:** Note the running `adb shell` and then a command inside it is not the same of running `adb shell "command"` as the latter has differences and it is more likely to have problems.

![image](https://user-images.githubusercontent.com/29514446/218228395-e427735d-02e9-43e1-b40d-145b6d95e947.png)
Hopefully that helps you

**Comment by ale5000-git** [comment]
@fillwithjoy1
I have released microG unofficial installer v1.3.0 beta that hopefully fix all issues.
Coulf you please try?

It say `You must execute this as root` only if it cannot detect root (probably because is hidden).
If this is the case you can force it with FORCE_ROOT, in this way:
```
adb shell
cd /sdcard/download
unzip ./microg-unofficial-installer-v1.3.0-beta-by-ale5000-OSS-signed.zip zip-install.sh
FORCE_ROOT=1 sh ./zip-install.sh ./microg-unofficial-installer-v1.3.0-beta-by-ale5000-OSS-signed.zip || echo "Err code: ${?}"
```

**Comment by fillwithjoy1** [comment]
@ale5000-git 
Thank you for helping me with the process
Turns out the system is just mounted as a read-only directory. Tried twice

**Comment by ale5000-git** [comment]
It seems to be working at the start but exiting without giving any error, really strange.
Could you please try this (it should create a debug log)?
```
adb shell
cd /sdcard/download
DEBUG_LOG=1 FORCE_ROOT=1 sh ./zip-install.sh ./microg-unofficial-installer-v1.3.0-beta-by-ale5000-OSS-signed.zip || echo "Err code: ${?}"
```

Then post the log please.

**Comment by fillwithjoy1** [comment]
> 

Weird error now. I've checked the file names and they are identical
![image](https://user-images.githubusercontent.com/29514446/222893614-54ccd88d-021d-47f5-a8c3-f9b5c043d7f6.png)

**Comment by fillwithjoy1** [comment]
[image]

Getting this error. Do I need to replace the zip-install.sh <http://zip-install.sh> that's in the installer?

**Comment by ale5000-git** [comment]
@fillwithjoy1
Hi, I don't see any image, maybe there was a problem during the upload.

**Comment by JonnyTech** [comment]
@fillwithjoy1 please post directly to Github, replying to the notification email strips attachments and images.

**Comment by fillwithjoy1** [comment]
Alright I got it working, but now when I try to add accounts it says 'There was a problem communicating with Google servers. Try again later."

**Comment by ale5000-git** [comment]
It is probably blocked since it isn't a certified device, you have to spoof a certified device in microG settings => Device registration => Select profile => maybe try Motorola Moto G

**Comment by fillwithjoy1** [comment]
Tried both device options, Motorola Moto G and Nexus 5X and still getting the same error

**Comment by ale5000-git** [comment]
I'm not completely sure but the "block" may be cached somewhere in the server.
The best way is:
- Disable internet and wireless in Android, maybe also in the PC to be sure
- Reset data of microG GmsCore in Android settings (this will reset all microG options also the Android ID)
- Reconfigure the profile in microG settings (Motorola Moto G or Nexus)
- Reenable internet again

**Comment by fillwithjoy1** [comment]
Got it working! Thank you!

**Comment by fillwithjoy1** [comment]
Checked YouTube Music and apparently it crashes? I re-installed the app and the issue persists, even with an older apk (Dec 2022)

**Comment by ale5000-git** [comment]
@fillwithjoy1

About YouTube Music, I haven't had time to try it yet but please open a new ticket.

PS: Could you please post the file /system/build.prop from WSA?
So I can try to make microG working without the need of manually configuring the profile.

**Comment by fillwithjoy1** [comment]
[build.prop.txt](https://github.com/microg/GmsCore/files/10985317/build.prop.txt)
Packaged as .txt file since github doesn't like .prop files

**Comment by fillwithjoy1** [comment]
> @fillwithjoy1
> 
> About YouTube Music, I haven't had time to try it yet but please open a new ticket.
> 
> PS: Could you please post the file /system/build.prop from WSA? So I can try to make microG working without the need of manually configuring the profile.

I'm wondering do you know how to get the build fingerprint of Google Pixel 7 or 7 Pro series without having physical access to the device?

**Comment by ale5000-git** [comment]
The script to generate the profile is here: https://github.com/micro5k/microg-unofficial-installer/blob/main/utils/profile-generator.sh

@fillwithjoy1
Could you please run `adb shell "getprop" > myprops.txt` and the share the myprops.txt file?
I need to check some things for my script.

**Comment by fillwithjoy1** [comment]
> The script to generate the profile is here: https://github.com/micro5k/microg-unofficial-installer/blob/main/utils/profile-generator.sh
> 
> @fillwithjoy1 Could you please run `adb shell "getprop" > myprops.txt` and then share the myprops.txt file? I need to check some things for my script.

Accidentally deleted my WSA so I reinstalled it and getting error code 127

![image](https://user-images.githubusercontent.com/29514446/230844643-6e465c2d-6773-436c-8daf-7c01a4512261.png)

**Comment by ale5000-git** [comment]
Could you please run these and post the result?
```
adb shell "df -T"
adb shell "mount"
```

**Comment by ale5000-git** [comment]
@fillwithjoy1

Could you please run these and post the result?
```
adb shell "df -T"
adb shell "mount"
```

**Comment by ale5000-git** [comment]
Could you please retry with [microG unofficial installer v1.3.1 beta](https://forum.xda-developers.com/showthread.php?t=3432360)?
I have fixed the auto-rooting and now it auto set the profile.

You just need to do this:
```
adb push microg-unofficial-installer-v1.3.1-beta-by-ale5000-OSS-signed.zip /storage/emulated/0/Download/
adb shell
cd /storage/emulated/0/Download/
sh zip-install.sh microg-unofficial-installer-v1.3.1-beta-by-ale5000-OSS-signed.zip
```

**Comment by fillwithjoy1** [comment]
ahhh right now getting 526 from CloudFlare, will have to wait for the website to come online then in around 3 days

**Comment by ale5000-git** [comment]
> ahhh right now getting 526 from CloudFlare, will have to wait for the website to come online then in around 3 days

Hi, I have added a mirror in the latest post.

**Comment by fillwithjoy1** [comment]
![image](https://user-images.githubusercontent.com/29514446/236327216-18c6f1bd-4d1c-4cf5-b14b-709d2f4052cd.png)
am getting this now

**Comment by fillwithjoy1** [comment]
I AM THE BIGGEST IDIOT EVERYONE. Turns out the FakeGApps LSPosed Module needs microG services ticked
![image](https://github.com/microg/GmsCore/assets/29514446/a174f008-d29d-48cc-b661-719c99d8b20f)

That's it, and it works.
