### ISSUE TITLE
Google analytics???

### ISSUE THREAD

**Issue by sconim** [microg/GmsCore#1840]
No matter how I read this, microG does incorporate Google Analytics. Why???

![Imagepipe_0](https://user-images.githubusercontent.com/10010866/205371311-5e065d32-3919-47ac-8a95-6200752c3672.jpg)

**Comment by ale5000-git** [comment]
All the Google AD/Analytics things are just dummy classes to fake their presence, about Mapbox I don't know since it is an external dependency.

**Comment by ale5000-git** [comment]
G AdMob:
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/com/google/android/gms/ads/AdActivity.java
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/com/google/android/gms/ads/AdManagerCreatorImpl.java

G Analytics:
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/com/google/android/gms/analytics/service/AnalyticsService.java

GF Analytics:
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/kotlin/org/microg/gms/measurement/MeasurementService.kt

**Comment by ale5000-git** [comment]
Mapbox will be switched to MapLibre, I don't know the timing though.

G AdMob:
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/com/google/android/gms/ads/AdActivity.java
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/com/google/android/gms/ads/AdManagerCreatorImpl.java

G Analytics:
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/java/com/google/android/gms/analytics/service/AnalyticsService.java

GF Analytics:
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/kotlin/org/microg/gms/measurement/MeasurementService.kt

**Comment by sconim** [comment]
I appreciate the answers, thank you!

**Comment by ale5000-git** [comment]
@sconim: Just for reference, Mapbox is no longer part of microG => https://github.com/microg/GmsCore/commit/ff65c144e5e9a2eeac5cc243b42330a5ca761ccc
