### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by BlueStarOne** [microg/GmsCore#1846]
Closed

**Comment by RobertoWa** [comment]
try to install the patched google playstore

**Comment by BlueStarOne** [comment]
And where will I find it?

**Comment by BlueStarOne** [comment]
I think part of the problem is that MicroG is not up to date with Google services:
![IMG_20221212_122817.jpg](https://user-images.githubusercontent.com/120303474/207034241-40e9255e-00fd-4837-a9cf-56eb99511e3f.jpg)

**Comment by RobertoWa** [comment]
i am using https://nanolx.org/fdroid/repo/Phonesky_132.apk for purchased apps using google play libs. i cant tell u how to install it on ur system, i used https://github.com/nift4/microg_installer_revived

**Comment by ale5000-git** [comment]
@BlueStarOne
You must have FakeStore (at least v0.1.0) or Play Store installed.

**Comment by BlueStarOne** [comment]
@ale5000-git
![image2.jpg](https://user-images.githubusercontent.com/120303474/207090390-feccfca9-5b4f-45ea-b018-905832020bc6.jpg)

**Comment by BlueStarOne** [comment]
Sorry everyone, there was an error in step 1. I'm actually using a LineageOS MicroG Rom, not MinMicroG. I confused it with another phone 😅
