### ISSUE TITLE
No exposure warning on Fairphone 4 (FP4) with both CWA and CCTG (Pixel 4 has warning since days)

### ISSUE THREAD

**Issue by rugk** [microg/GmsCore#1857]
**Describe the bug**
I usually carry two devices with me. And almost always I carry _both_ with me!

One is the Fairphone 4 (FP4) and the other is Pixel 4 (flame).
_Both_ have _both_ the official Corona-Warn-App (CWA) and the fork Corona Contact Tracing Germany (CCTG). The CWA may be suspended via CalyxOS mechanism though sometimes, but that should not matter, as the data should be collected by microG IIRC.

Now, only the Pixel 4 shows red encounter warnings for _days_, while the FP4 shows _none_ (green card).

# **To Reproduce**
Use both devices with Bluetooth and microG/exposure notifications turned on. Get some red warnings on Pixel 4.

FYI, on FP4 I today (2022-12-26) also uploaded my own positive [rapid antigen test (RAT)](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#rapid-antigen-tests-result-retrieval) via the Corona-Warn-App (CWA), so possibly the other device should show that, too? Also a [PCR](https://github.com/corona-warn-app/cwa-documentation/blob/main/solution_architecture.md#pcr-tests-retrieval-of-lab-results-and-verification-process) test is already in progress on the same device/same app (i.e. FP4, CWA). 

## **Expected behavior**
Even though the Pixel 4 shows red warnings since Wednesday last week (2022-12-21), the Fairphone 4 shows none.
However, microG shows it has collected IDs and that generally also looks similar to what the Pixel 4 shows.

# **Screenshots**  
(in German, i am sorry)

Both CWA and CCTG on each device, show the same results.

## Pixel 4

![Screenshot_20221226-180621](https://user-images.githubusercontent.com/11966684/209572040-0c8b40a9-b40e-4bb6-8614-218522a889a8.png)

![Screenshot_20221226-190040](https://user-images.githubusercontent.com/11966684/209573789-742b8af5-dbc5-46aa-b84c-8afb8d122a34.png)

![Screenshot_20221226-185651](https://user-images.githubusercontent.com/11966684/209573549-daf65b1f-faf9-45be-93f0-6feeb4c7e095.png)

## Fairphone 4 (FP4)

![Screenshot_20221226-180720](https://user-images.githubusercontent.com/11966684/209572651-2b5defd8-cebe-4d48-8ec7-0b6d4e351cbb.png)

![Screenshot_20221226-180342](https://user-images.githubusercontent.com/11966684/209573065-1b4c3d54-167f-4ec2-b049-229f906515a5.png)

![Screenshot_20221226-185942](https://user-images.githubusercontent.com/11966684/209573672-15297d6c-9b6f-47a1-a781-60eec2046684.png)

# **System**
## Pixel 4

Device: Pixel 4 (flame)  
OS: Android 13, CalyxOS 4.4.0  
Build-ID: `TQ1A.221205.011.22404000`  
CWA: v2.27.2 (ENV v 1.8 [18223616000); CCL v 3.5.1)
CCTG: v2.27.2.0 (using external microG v1822361600); CCL v 3.5.1
microG: 0.2.26.223616-37 (23ae934)

## FP4

Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.3.1  
Build-ID: `TQ1A.221205.011.22404010` 
CWA: v2.28.3 (ENV v 1.8 [18223616000); CCL v 3.5.1)
CCTG: v2.28.3.1 (using external microG v18223616000); CCL v 3.5.1
microG: 0.2.26.223616-37 (23ae934)

# **Additional context**
Just confirmed self-check on both devices is all green.

**I can provide the exposure data** (that you export, i.e. exposure.db) and **logcat for both devices _upon request_** privately.

Note I am fully aware that the [exposures between apps, i.e. CCTG and CWA](https://codeberg.org/corona-contact-tracing-germany/cwa-android#cwa-shows-some-exposures-but-cctg-doesn-t-or-the-other-way-round) and so it can vary between two devices, too _somewhat_. However, there must be a bug here, because _such a high variation_ is IMHO not explanable.

**Comment by rugk** [comment]
From my evaluation of the data it seems that Pixel 4 reports _way too many exposures_ (it even has _near_ exposures at the night while I am sleeping) and FP4 does the contrasting thing, i.e. reports _no exposures at all_.

**Comment by rugk** [comment]
Uff, can I somehow filter my own self-test out of the data?

Arg, of course Pixel 4 warns about an exposure, because that is me having uploaded it on FP4. That makes sense uff, I am sorry…

**Comment by Ein-Tim** [comment]
Just so that I understand it: You warned on your FP4, thus the Pixel shows a warning. If you have not also warned on your Pixel, why should the FP4 show a warning? 😅

Maybe I'm also missing the point of the issue, sorry.

**Comment by Ein-Tim** [comment]
@rugk 

> I am sorry…

There's no need to be sorry! I hope you get well soon!

**Comment by rugk** [comment]
Thanks.
