### ISSUE TITLE
[Technical] How does the Google Push implementation work? 

### ISSUE THREAD

**Issue by BRUHItsABunny** [microg/GmsCore#1859]
Hi, I am working on [a project](https://github.com/BRUHItsABunny/go-android-firebase) to listen for incoming Google push notifications in Go (hopefully an end-to-end push notification testing suite at some point)

So this is how far I currently understand the system/apis involved:

For apps to register for push notifications, these API calls occur in order:
*  `firebaseinstallations.googleapis.com` - register installation (returns an actual JWT used later)
![image](https://user-images.githubusercontent.com/53124399/209993986-53da1f81-3122-458e-a0d0-14b27f5d1807.png)
* `android.clients.google.com` - C2DM registration (uses the JWT from previous step app certificate and Checkin android ID, returns notification token)
![image](https://user-images.githubusercontent.com/53124399/209994152-929fb8e4-e011-44f4-b07e-7d214b59f024.png)
* App specific API call to notify the backend of our notification token from the previous step
![image](https://user-images.githubusercontent.com/53124399/209993314-cce542c3-1228-4f94-8b76-6b40670fbddd.png)

For websites on chromium browsers (tested on Brave browser, because I can't turn off HSTS on Chrome....):
*  `firebaseinstallations.googleapis.com` - register installation (returns an actual JWT used later) - for the BROWSER
* `android.clients.google.com` - C2DM registration (uses the app certificate and Checkin android ID, returns notification token) - for the website
![image](https://user-images.githubusercontent.com/53124399/209993731-06bd12d2-b178-4d1b-aab3-e4398d84d2a2.png)
![image](https://user-images.githubusercontent.com/53124399/209992150-1aa986c2-3d98-4c5d-b065-c157fae36685.png)
* Website specific API call to notify backend of our notification token, and also sends `encryption data` (similar to [this](https://github.com/MatthieuLemoine/push-receiver/blob/master/src/fcm/index.js) except that is a registration directly to FCM instead)
![image](https://user-images.githubusercontent.com/53124399/209992190-705415cb-d797-4af2-950d-e3dcd00b3d7d.png)

For us to receive the notifications:
* `android.clients.google.com` Checkin API call (returns AID login auth)
* `mtalk.google.com` connection, login request
![image](https://user-images.githubusercontent.com/53124399/209993495-63e6c15e-3ef0-4754-b866-728ebb717dcc.png)
After which we now receive encrypted push notifications
![image](https://user-images.githubusercontent.com/53124399/209992684-5596d338-dba1-4b62-b82d-4bb8e441ad61.png)

Okay, so my question comes in in the comparison between apps and websites as far as push notifications go.
In both cases the notifications we receive via `mtalk.google.com` are encrypted, but only in the case of the websites do I see an actual key exchange.
How are the push notifications decrypted for regular apps? Did I miss a super secret key exchange or do the system and backend already know what the key is going to be beforehand?
Thanks for taking the time to read this.

**Comment by mar-v-in** [comment]
I don't think anything you see here is encrypted. Most Android apps don't encrypt their push notification traffic.

The data in the last screenshot is not encrypted, but just a base64-encoded protobuf. This is application specific.

**Comment by BRUHItsABunny** [comment]
Thanks for your reply, I just did a deeper dive into the data from the last screenshot and you are correct. I guess I just assumed there was encryption involved due to the browser notifications having encryption.
