### ISSUE TITLE
F-Droid: "Cannot update, are you connected to the Internet?"

### ISSUE THREAD

**Issue by fatalhalt** [microg/GmsCore#1862]
**Affected app**
Name: F-Droid

**Describe the bug**
F-Droid cannot pull metadata from repos, keeps complaining about:  "Cannot update, are you connected to the Internet?"

**System**
Custom ROM: LOS microg 19.1

**microG**
v0.2.26.223616

Some apps like shipped default browser can browse internet fine.
Also Settings->System->microG Settings->Account, attempting to add account results in: "Sorry...You don't have a network connection"

**Comment by ale5000-git** [comment]
The account is handled by microG but the metadata of F-Droid no.
So if they both fail then it means that problem is in the ROM itself or is a Firewall/VPN that is installed.

**Comment by fatalhalt** [comment]
Thanks, wiping data+caches fixed it for me, it was a clean install of ROM from lineage.microg.org (I was switching from vanilla LOS), my phone has 2 slots (A & B), I flashed ROM to both but looks like I forgot to wipe one of the slots, sorry for the noise.
