### ISSUE TITLE
Privacy: Please make Google Device Registration opt-in by default

### ISSUE THREAD

**Issue by IzzySoft** [microg/GmsCore#1868]
**Is your feature request related to a problem? Please describe.**
Currently, with a fresh installation, Google Device Registration is enabled by default. This is a privacy concern.

**Describe the solution you'd like**
Google Device Registration should be off by default (like FCM etc is). Users who want this can enable it any time – but there's no risk of data leak for those who don't want it then.

**Describe alternatives you've considered**
There is not really one. If one is aware, on first start one can disable all network connections (mobile data, WiFi) to toggle it off – but first not everyone is aware of it, and second those who are could forget that (happened to me twice already now).

**Additional context**
Some users (like me) want microG for its location services (UnifiedNlp) but don't want any Google services (I e.g. use location completely offline, only having Nominatim and the LocalGsmBackend in use). We'd prefer to avoid any Google connections – especially registering our devices with Google. So having that completely opt-in would be the best solution for all sides.

**Comment by ale5000-git** [comment]
It isn't enabled by default, but the ROM developer can enable it by default by placing default settings in this file: /system/etc/microg.xml

**Comment by IzzySoft** [comment]
> It isn't enabled by default,

sorry that I contradict this. I've just installed it on a ROM that comes without (but supports signature spoofing), and it **was** enabled by default. Then I factory-reset another device to flash it with LOS for microG, and it again **was** enabled by default. In the first case, no ROM developer was involved as microG was installed from its own repo – and in the second case, the ROM was provided by microG. Both somehow contradict your expectation :wink:

> the ROM developer can enable it by default by placing default settings in this file: `/system/etc/microg.xml`

That's good to know – let me link it to #1867 so said ROM developer (ShiftOS-L is a ROM provided by the official SHIFTPHONES channels btw) can consider that and making sure when integrating the stub, though I wouldn't wonder if he's already aware of that.

**Comment by ale5000-git** [comment]
Are you sure that there isn't /system/etc/microg.xml?
Even a ROM that doesn't include microG can still include /system/etc/microg.xml

**Comment by IzzySoft** [comment]
> Are you sure that there isn't /system/etc/microg.xml?

For the device where I installed microG as user app (SHIFT6mq running ShiftOS-L 3.9) I'd be surprised to have that. But to make sure let me check: Nope, no such file (`ls: /system/etc/microg.xml: No such file or directory`). For the other, where microG has been included with the ROM (LineageOS for microG): Sorry to disappoint you again, same error message (`ls: /system/etc/microg.xml: No such file or directory`). So yes, I am very sure.

> Even a ROM that doesn't include microG can still include /system/etc/microg.xml

Agreed, so let's make absolutely sure, shall we? `find / -name microg.xml` yields nothing on either device. And to make sure, I've been running that as root.

**Comment by mar-v-in** [comment]
It shouldn't have been enabled by default and wasn't for a long time, but that accidentally changed at some point. I'll change it to default to disabled in a minute.

**Comment by IzzySoft** [comment]
Thanks a lot, @mar-v-in!
