### ISSUE TITLE
Installing to /system/priv-app causes boot loop on CrDroid

### ISSUE THREAD

**Issue by elastic-rock** [microg/GmsCore#1869]
**Describe the bug**
When GmsCore is put into the /system/priv-app folder, the phone bootloops. When removed, the phone boots without a problem.

**To Reproduce**
1. Boot to recovery (TWRP in my case)
2. Copy GmsCore to /system/priv-app
3. Try to boot
4. Get stuck in a bootloop

**System**
Android Version: [e.g. 13]
Custom ROM: [e.g. CrDroid 9.1]
Device: ginkgo (I don't know if that helps)

I can also confirm it not working on CrDroid 8.1 so Android 12.1

**Additional context**
I am trying to make an OTA zip file to speed-up the process of installing MicroG and all it's components properly by using the [F-Droid privileged extension OTA zip](https://gitlab.com/fdroid/privileged-extension) and this [Lineage for MicroG repo](https://github.com/lineageos4microg/android_vendor_partner_gms) as a template. I have tried installing all other components except for GmsCore and no issues occur, from which I deduce that the problem is caused by GmsCore. I have no problems using the same steps on ArrowOS 12.1 and 13.

My repo is https://github.com/elastic-rock/microg-unofficial-ota-zip.

**Comment by mar-v-in** [comment]
Might be because you're missing `android.permission.MANAGE_USB` in your privapp-permission file.

**Comment by ildar** [comment]
On Sun, Jan 15, 2023 at 6:02 PM Elastic Rock wrote:

> I am trying to make an OTA zip file to speed-up the process of installing
> MicroG
>
> Do you know https://github.com/micro5k/microg-unofficial-installer/
exists?

**Comment by elastic-rock** [comment]
> Might be because you're missing `android.permission.MANAGE_USB` in your privapp-permission file.

Fixed the issue. Thanks.

**Comment by cracket** [comment]
> > Might be because you're missing `android.permission.MANAGE_USB` in your privapp-permission file.
> 
> Fixed the issue. Thanks.

Not sure how did you fixed the issue - any suggestions or link with more detailed instructions?
I'm using crDroid  (Android 10) installed. 
Issue #986 suggests I should edit file 
/system/etc/permissions/privapp-permissions-com.google.android.gms.xml

but this file is missing in my crDroid installation. Should I create it empty and put only single permission there (MANAGE_USB) ?

**Comment by ale5000-git** [comment]
The file may have any name and may be in many folders.

It maybe be in:
- /system/etc/permissions
- /product/etc/permissions
- Maybe others

The name is maybe:
privapp-permissions-ANYTHING IS FINE HERE.xml

**Comment by ale5000-git** [comment]
Maybe many devices use a common privapp-permission xml file, or it is automatically generated during build but it must exist somewhere.
You can use find to search it directly on the device (with root or recovery).

**Comment by cracket** [comment]
> Maybe many devices use a common privapp-permission xml file, or it is automatically generated during build but it must exist somewhere. You can use `find` (via adb) to search it directly on the device (with root or recovery).

Thank you for hint, tried to search both my device image, running system and available sources of crDroid, but didnt find anything related to these permissions settings. 
Currently I don't have much time to try out blindly settings or configuration from other devices so I have configured legacy NLP according to this document - https://blog.eowyn.net/unifiednlp/  and I am not capable to use microg on my crDroid by now.

**Comment by ale5000-git** [comment]
If want to do it simpler you can try [my flashable zip](https://github.com/micro5k/microg-unofficial-installer).
**PS:** Be sure to backup your data first.
