### ISSUE TITLE
MicroG not registering device anymore nor connecting to cloud messaging

### ISSUE THREAD

**Issue by Larslol140** [microg/GmsCore#1871]
**Describe the bug**
MicroG appears to not be registering itself to Google anymore.
When enabling Google device registration the status stays on "Not registered".
When enabling Cloud Messaging the status stays on "Disconnected" 

**To Reproduce**

Google device registration
1. Open MicroG
2. Open Google device registration
3. Enable Register device
4. See status

Cloud Messaging
1. Open MicroG
2. Open Cloud Messaging
3. Enable Receive push notifications
4. See status

**Expected behavior**
MicroG should register to Google and connect to Cloud Messaging.  

**Screenshots**
![Screenshot_20230121-135655_microG Services Core](https://user-images.githubusercontent.com/25729499/213867980-b4505736-12ce-412d-b928-e7240d5ef890.png)
![Screenshot_20230121-135721_microG Services Core](https://user-images.githubusercontent.com/25729499/213867986-9c58fe4a-c7aa-4917-9939-9712942c7ef2.png)
![Screenshot_20230121-135806_microG Services Core](https://user-images.githubusercontent.com/25729499/213867988-7ab9ccbe-fca5-40d1-8d67-473f41e8bab4.png)

**System**
Android Version: 13
Custom ROM: LineageOS 20.0

**Additional context**
Device: dubai
LineageOS build using [LineageOS 4 MicroG](https://github.com/lineageos4microg/docker-lineage-cicd)

**Comment by MrHaram** [comment]
Also have this issue. According to the Signature Spoofing Checker fron F-Droid, Signature Spoofing is disabled despite micro-g saying otherwise.

**Comment by MrHaram** [comment]
I also have issues not registering the device and connecting to cloud messaging. On the microg app however, it does say my device is registered and that it was last connected a few minutes ago. The spoof checker app from f-driod says that the spoofing is disabled despite what is said otherwise in the micro g app.

**Comment by Larslol140** [comment]
As far as I know when using lineageos4microg signature spoofing (when using `restricted`) will only be applied to system apps (or even only microG).
That will maybe explain why user installed apps report that signature spoofing is not active.

**Comment by MrHaram** [comment]
> As far as I know when using lineageos4microg signature spoofing (when using `restricted`) will only be applied to system apps (or even only microG). That will maybe explain why user installed apps report that signature spoofing is not active.

Yep, just found that out online. Currently trying to fix it.

**Comment by Larslol140** [comment]
Alright, details are in the README.md of the [lineageos4microg/docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd) repository the option you are looking for would be `SIGNATURE_SPOOFING=yes` when I understood it correctly.
In case you are trying to rebuild lineage with unrestricted signature spoofing I would be glad if you could share your results.

**Comment by ixalcor** [comment]
I'm having a similar issue here. all perms enabled btw. The device *is* registered but the apps themselves aren't registering except for Discord, and that one isn't getting notifications even tho it's showing up as connected.
Already uninstalled and reinstalled the apps numerous times too and until a couple days ago I was able to get notifications

**Comment by ixalcor** [comment]
I'm running stock Android 12 on a rooted A21S btw

**Comment by ixalcor** [comment]
hmm, well, all of the sudden it's sending discord notifications now... still not registering other apps but there's some progress at least

**Comment by lucafavatella** [comment]
> **Describe the bug**
> MicroG appears to not be registering itself to Google anymore.
> When enabling Google device registration the status stays on "Not registered".
> ...
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> Google device registration
>   1. Open MicroG
>   2. Open Google device registration
>   3. Enable Register device
>   4. See status
> 
> ...
>
> **Expected behavior**
> MicroG should register to Google ...

@Larslol140 May I suggest you manually check the network access permission of the microg app as per https://github.com/microg/GmsCore/issues/1861#issuecomment-1382719080

**Comment by ixalcor** [comment]
a bunch of background apps now show up as registered, wonder what's happening here :v

**Comment by Larslol140** [comment]
> > **Describe the bug**
> > MicroG appears to not be registering itself to Google anymore.
> > When enabling Google device registration the status stays on "Not registered".
> > ...
> > **To Reproduce**
> > Steps to reproduce the behavior:
> > Google device registration
> > 
> > 1. Open MicroG
> > 2. Open Google device registration
> > 3. Enable Register device
> > 4. See status
> > 
> > ...
> > **Expected behavior**
> > MicroG should register to Google ...
> 
> @Larslol140 May I suggest you manually check the network access permission of the microg app as per [#1861 (comment)](https://github.com/microg/GmsCore/issues/1861#issuecomment-1382719080)

Thanks for the hint that was indeed the root cause.
