### ISSUE TITLE
SafetyNet deprecated

### ISSUE THREAD

**Issue by huwenkai26** [microg/GmsCore#1875]
The SafetyNet Attestation API is deprecated. It is recommended to use the Play Integrity API

**Comment by paolo-caroni** [comment]
Play Integrity API is handled by play store vendor, maybe partially on play store, [someone](https://github.com/redacted-text) is working on play integrity API on [fakestore](https://github.com/microg/FakeStore/issues/36).

**Comment by paolo-caroni** [comment]
Sorry for the late reply.
Yes, with microG GmsCore + Google Play Store you can get this:
![Screenshot](https://github.com/microg/GmsCore/assets/15793015/a8000acd-4c4d-4f64-8572-9f9d32e0a22d)

_Originally posted by @ale5000-git in https://github.com/microg/GmsCore/issues/1771#issuecomment-1672982750_
           

As pointed by @ale5000-git, if you use google play store you have a fully functional play integrity API, as previously reported it will be implemented on fakestore (I hope) soon. So this issue should be closed.

**Comment by ale5000-git** [comment]
Play Integrity API is now included in microG 0.3.6.
If there are additional issues please open a new ticket.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/microg/GmsCore/issues/1875#issuecomment-2560383934

@ale5000-git, do you mean that it'll support *`STRONG`* (in addition to `BASIC`)?

**Comment by ale5000-git** [comment]
> [@ale5000-git](https://github.com/ale5000-git), do you mean that it'll support _`STRONG`_ (in addition to `BASIC`)? Additionally, do you refer to [#2599 (comment)](https://github.com/microg/GmsCore/pull/2599#event-15694657052)?

It just add support for the API, whether it pass or not still depends from the ROM (if it doesn't pass, many times it can be fixed by specific Magisk modules).

It is usually always BASIC unless there is a miracle done by Magisk modules :-)

**Comment by marbens-arch** [comment]
> > [@ale5000-git](https://github.com/ale5000-git), do you mean that it'll support _`STRONG`_ (in addition to `BASIC`)?
> 
> It just add support for the new API, whether it pass or not still depends from the ROM (if it doesn't pass, many times it can be fixed by specific Magisk modules).
> 
> It is usually always BASIC unless there is a miracle done by Magisk modules :-)
> 
> > Additionally, do you refer to [#2599 (comment)](https://github.com/microg/GmsCore/pull/2599#event-15694657052)?
> 
> Yes.

You forgot about DEVICE integrity :)

They've been passing it for a while with magisk modules.
