### ISSUE TITLE
[com.google.android.apps.*] GMail, Google productivity apps "Add account" misbehaviour

### ISSUE THREAD

**Issue by DerZc** [microg/GmsCore#1883]
**Affected app**
Name: [Google map]
Package id: [com.google.android.apps.*]

**Describe the bug**
I use the microG on Huawei mate 40 pro, I can not log in with my google account, as the system shows connection error after the password go pass. (sorry I don't know how to translate this figure to English.)
![image](https://user-images.githubusercontent.com/34330257/219401148-43688080-f9fa-4fda-a49f-2eb771a94b59.png)

But after I modify the system to LineageOs or Android 8.1.0, I can successfully log in. But I meet the error same with #1799. How can I solve this.

Can I add a configuration file to set my phone as mate 20 pro?

**System**
Android Version: harmonyos 3.0
Custom ROM: [LineageOS 17.1]

**microG**
microG Core version: [0.2.27.223616]
microG Self-Check results: [All ticked, besides the signature]

![image](https://user-images.githubusercontent.com/34330257/219400295-68fb9459-0c04-451c-a12d-6a75483db576.png)

**Comment by Iey4iej3** [comment]
You do not have root and you cannot install MicroG properly. Huawei no longer allows unlocking bootloader which makes this impossible.

**Comment by DerZc** [comment]
> You do not have root and you cannot install MicroG properly. Huawei no longer allows unlocking bootloader which makes this impossible.

Thank you very much for your reply. Do you know of any alternative solution? LightHouse can be used in Malaysia, but I bought my phone in other country. I can not use LightHouse.

**Comment by Iey4iej3** [comment]
Sigature spoofing is a must (https://github.com/microg/GmsCore/wiki/Signature-Spoofing), and if the ROM does not support that, and the manufacturer locks the bootloader, then there is basically no solution.

I do not buy Huawei devices, since they do not give official support for unlocking bootloaders.

**Comment by DerZc** [comment]
Thank you very much! I close this issue.

**Comment by illerokcob** [comment]
I suggest you to take a look at the [revanced](https://github.com/revanced) project, probably there will be a patch available for google apps to work with non-root microG in the future.
Alternatively, for Gmail, you could use K-9 Mail with IMAP enabled inside your Google settings.
