### ISSUE TITLE
[com.google.android.youtube] Video buffer when playing video for a while

### ISSUE THREAD

**Issue by cuynu** [microg/GmsCore#1888]
**Affected app**
Name: YouTube
Package id: com.google.android.youtube

**Describe the bug**
Video buffering when play for a while on original YouTube native app

**To Reproduce**
Only affected account can reproduce (Google A/B testing)
1. Login affected account to microG service core
2. Install native original YouTube app (any versions) (not ReVanced or modified YouTube app)
3. Play any YouTube videos for a while

**Expected behavior**
Video not buffering

**Screenshots**
![Screenshot_20230306-110702_YouTube](https://user-images.githubusercontent.com/90895715/223081845-d9437fec-98bf-4d56-929a-c057ceac1998.png)

![Screenshot_20230306-110740_microG Services Core](https://user-images.githubusercontent.com/90895715/223081656-7c37a060-ce8c-474e-b962-7b506a659816.png)

**System**
Android Version: 13
Custom ROM: iodeOS [LineageOS 20 based]

**microG**
microG Core version: 0.2.27.223616-iode.29

microG Self-Check results: All ticked

**Additional context**

**Comment by K1r5ch1** [comment]
I habe the same problem
![Screenshot_20230612-085102](https://github.com/microg/GmsCore/assets/58545210/ded986c7-968a-4cac-8677-dffaa8989969)

**Comment by t-m-w** [comment]
@cuynu Did you find a fix for this? I see you closed the issue.

**Comment by cuynu** [comment]
> @cuynu Did you find a fix for this? I see you closed the issue.

not yet

**Comment by ale5000-git** [comment]
I'm not sure if it is related to this problem but microG now send `X-Android-Package` and `X-Android-Cert`, see here: https://github.com/microg/GmsCore/commit/704836324005c4d8e731a18d28059eac9efece8f

If you want, you can try the [nightly build](https://microg.org/dl/core-nightly.apk) to see if there is any difference.

**Comment by t-m-w** [comment]
> If you want, you can try the [nightly build](https://microg.org/dl/core-nightly.apk) to see if there is any difference.

Thanks, I tried the nightly build 0.2.28.231657-28 (a749fe4) and didn't see a change in behavior, unfortunately (related comment: https://github.com/microg/GmsCore/issues/1835#issuecomment-1662888762)

**Comment by ale5000-git** [comment]
I'm not completely sure but I see a similar issue previously (maybe it was in yt-dlp) and they was saying that if the YouTube server see a single request without "range" then it throttle even the subsequent requests on the same connection.

**Comment by ale5000-git** [comment]
Could anyone sniff the connection (including the one about the Google account inside YouTube, removing the private data) in the two cases?
- Google Play Services + Youtube
- microG + Youtube

**Comment by ale5000-git** [comment]
I see a similar issue and they was saying that if the YouTube server see a single request without "range" then it throttle even the subsequent requests on the same connection.

More info:
https://github.com/TeamNewPipe/NewPipe/pull/9948
https://github.com/TeamNewPipe/NewPipeExtractor/pull/1084

Could anyone sniff the connection (including the one about the Google account inside YouTube but removing the private data) in the two cases?
- Google Play Services + Youtube
- microG + Youtube

**Comment by GKid94** [comment]
Same on Redmi 9
![Screenshot_2024-04-07-23-45-04-547_app revanced android youtube](https://github.com/microg/GmsCore/assets/18757054/dbc6d27e-aee3-40f4-9ec5-87cf632cbecf)

**Comment by cuynu** [comment]
> Same on Redmi 9 ![Screenshot_2024-04-07-23-45-04-547_app revanced android youtube](https://private-user-images.githubusercontent.com/18757054/320316166-dbc6d27e-aee3-40f4-9ec5-87cf632cbecf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTc2MjUsIm5iZiI6MTcxMjU1NzMyNSwicGF0aCI6Ii8xODc1NzA1NC8zMjAzMTYxNjYtZGJjNmQyN2UtYWVlMy00MGY0LTllYzUtODdjZjYzMmNiZWNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YWIzOTBmY2YyZGJhOTIxMDYzY2E2OTk1ZmIzMzZiODAxZmY1Y2QwNDEwYmVjOGYzZWUyMDQxM2MyMmIyMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RIUO6zbG6ac7nBxBaX3kSow-7F-MzHmXe2LAJBhmjdg)

but this is ReVanced, not original yt one. you are not using regular microG and this issue refer the original microG, not the one that provided by ReVanced Team.

**Comment by GKid94** [comment]
> > Same on Redmi 9 ![Screenshot_2024-04-07-23-45-04-547_app revanced android youtube](https://private-user-images.githubusercontent.com/18757054/320316166-dbc6d27e-aee3-40f4-9ec5-87cf632cbecf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTc2MjUsIm5iZiI6MTcxMjU1NzMyNSwicGF0aCI6Ii8xODc1NzA1NC8zMjAzMTYxNjYtZGJjNmQyN2UtYWVlMy00MGY0LTllYzUtODdjZjYzMmNiZWNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA2MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YWIzOTBmY2YyZGJhOTIxMDYzY2E2OTk1ZmIzMzZiODAxZmY1Y2QwNDEwYmVjOGYzZWUyMDQxM2MyMmIyMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RIUO6zbG6ac7nBxBaX3kSow-7F-MzHmXe2LAJBhmjdg)
> 
> but this is ReVanced, not original yt one. you are not using regular microG and this issue refer the original microG, not the one that provided by ReVanced Team.

I use Revanced
![Screenshot_2024-04-08-17-33-42-314_app revanced manager flutter](https://github.com/microg/GmsCore/assets/18757054/7636f315-6571-487b-9b61-411ebbca5cde)

**Comment by GKid94** [comment]
![Screenshot_2024-04-08-17-34-32-712_com miui securitycenter](https://github.com/microg/GmsCore/assets/18757054/d5e5e81d-98aa-4150-872d-00662b2e033e)

**Comment by cuynu** [comment]
Fixed with latest microG. (consider this NOT microG for ReVanced apps, its the regular one that can be used for other Google apps.)
![Screenshot_20240413-113516_microG Services](https://github.com/microg/GmsCore/assets/90895715/62ef36f7-b0d5-4584-bae5-a99049118efd)
![Screenshot_20240413-113525_Settings](https://github.com/microg/GmsCore/assets/90895715/7680eae2-b422-414c-b98e-88d4f5d66457)

**Comment by GKid94** [comment]
> Fixed with latest microG. (consider this NOT microG for ReVanced apps, its the regular one that can be used for other Google apps.) ![Screenshot_20240413-113516_microG Services](https://private-user-images.githubusercontent.com/90895715/322177436-62ef36f7-b0d5-4584-bae5-a99049118efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDIyNjIsIm5iZiI6MTcxMzA0MTk2MiwicGF0aCI6Ii85MDg5NTcxNS8zMjIxNzc0MzYtNjJlZjM2ZjctYjBkNS00NTg0LWJhZTUtYTk5MDQ5MTE4ZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDIwNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTM3Mzg3YmI0NWMwN2EzYWQ1YWMxMDQ2MDU3ZDNiZGJkYzMwOTc4NjUyNTA3ZTkyZjUyNmU3NTNhMzgzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVzba10DWUjhH7LwT87bGZ2IZulx9HTBVYN8SkhAELk) ![Screenshot_20240413-113525_Settings](https://private-user-images.githubusercontent.com/90895715/322177438-7680eae2-b422-414c-b98e-88d4f5d66457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDIyNjIsIm5iZiI6MTcxMzA0MTk2MiwicGF0aCI6Ii85MDg5NTcxNS8zMjIxNzc0MzgtNzY4MGVhZTItYjQyMi00MTRjLWI5OGUtODhkNGY1ZDY2NDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDIwNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YzhmODk3Y2QyZDA1NDIyMTY4M2I2YTk3NzRmMWE2ZmY5ODg5NDQ3YjMxZDQwOWIxNjFmN2Q5ODkzZjk1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mX_1eporgmKy3B1ZW5ovI5oIxeHUtFzTvz2B91on5LU)

And what should I use for Revanced apps? And the Revanced team said to download this one

**Comment by cuynu** [comment]
> > Fixed with latest microG. (consider this NOT microG for ReVanced apps, its the regular one that can be used for other Google apps.) ![Screenshot_20240413-113516_microG Services](https://private-user-images.githubusercontent.com/90895715/322177436-62ef36f7-b0d5-4584-bae5-a99049118efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDIyNjIsIm5iZiI6MTcxMzA0MTk2MiwicGF0aCI6Ii85MDg5NTcxNS8zMjIxNzc0MzYtNjJlZjM2ZjctYjBkNS00NTg0LWJhZTUtYTk5MDQ5MTE4ZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDIwNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTM3Mzg3YmI0NWMwN2EzYWQ1YWMxMDQ2MDU3ZDNiZGJkYzMwOTc4NjUyNTA3ZTkyZjUyNmU3NTNhMzgzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVzba10DWUjhH7LwT87bGZ2IZulx9HTBVYN8SkhAELk) ![Screenshot_20240413-113525_Settings](https://private-user-images.githubusercontent.com/90895715/322177438-7680eae2-b422-414c-b98e-88d4f5d66457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDIyNjIsIm5iZiI6MTcxMzA0MTk2MiwicGF0aCI6Ii85MDg5NTcxNS8zMjIxNzc0MzgtNzY4MGVhZTItYjQyMi00MTRjLWI5OGUtODhkNGY1ZDY2NDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDIwNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YzhmODk3Y2QyZDA1NDIyMTY4M2I2YTk3NzRmMWE2ZmY5ODg5NDQ3YjMxZDQwOWIxNjFmN2Q5ODkzZjk1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mX_1eporgmKy3B1ZW5ovI5oIxeHUtFzTvz2B91on5LU)
> 
> And what should I use for Revanced apps? And the Revanced team said to download this one

I have no idea about ReVanced, since i use original YouTube app with microG Service Core as replacement for Play Services, thats all.

**Comment by GKid94** [comment]
> > > Fixed with latest microG. (consider this NOT microG for ReVanced apps, its the regular one that can be used for other Google apps.) ![Screenshot_20240413-113516_microG Services](https://private-user-images.githubusercontent.com/90895715/322177436-62ef36f7-b0d5-4584-bae5-a99049118efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDIyNjIsIm5iZiI6MTcxMzA0MTk2MiwicGF0aCI6Ii85MDg5NTcxNS8zMjIxNzc0MzYtNjJlZjM2ZjctYjBkNS00NTg0LWJhZTUtYTk5MDQ5MTE4ZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDIwNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTM3Mzg3YmI0NWMwN2EzYWQ1YWMxMDQ2MDU3ZDNiZGJkYzMwOTc4NjUyNTA3ZTkyZjUyNmU3NTNhMzgzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVzba10DWUjhH7LwT87bGZ2IZulx9HTBVYN8SkhAELk) ![Screenshot_20240413-113525_Settings](https://private-user-images.githubusercontent.com/90895715/322177438-7680eae2-b422-414c-b98e-88d4f5d66457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDIyNjIsIm5iZiI6MTcxMzA0MTk2MiwicGF0aCI6Ii85MDg5NTcxNS8zMjIxNzc0MzgtNzY4MGVhZTItYjQyMi00MTRjLWI5OGUtODhkNGY1ZDY2NDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDIwNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YzhmODk3Y2QyZDA1NDIyMTY4M2I2YTk3NzRmMWE2ZmY5ODg5NDQ3YjMxZDQwOWIxNjFmN2Q5ODkzZjk1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mX_1eporgmKy3B1ZW5ovI5oIxeHUtFzTvz2B91on5LU)
> > 
> > 
> > And what should I use for Revanced apps? And the Revanced team said to download this one
> 
> I have no idea about ReVanced, since i use original YouTube app with microG Service Core as replacement for Play Services, thats all.

Try and test it https://revanced.app/patches?s=gms

**Comment by cuynu** [comment]
> > > > Fixed with latest microG. (consider this NOT microG for ReVanced apps, its the regular one that can be used for other Google apps.) ![Screenshot_20240413-113516_microG Services](https://private-user-images.githubusercontent.com/90895715/322177436-62ef36f7-b0d5-4584-bae5-a99049118efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDIyNjIsIm5iZiI6MTcxMzA0MTk2MiwicGF0aCI6Ii85MDg5NTcxNS8zMjIxNzc0MzYtNjJlZjM2ZjctYjBkNS00NTg0LWJhZTUtYTk5MDQ5MTE4ZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDIwNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNTM3Mzg3YmI0NWMwN2EzYWQ1YWMxMDQ2MDU3ZDNiZGJkYzMwOTc4NjUyNTA3ZTkyZjUyNmU3NTNhMzgzMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVzba10DWUjhH7LwT87bGZ2IZulx9HTBVYN8SkhAELk) ![Screenshot_20240413-113525_Settings](https://private-user-images.githubusercontent.com/90895715/322177438-7680eae2-b422-414c-b98e-88d4f5d66457.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNDIyNjIsIm5iZiI6MTcxMzA0MTk2MiwicGF0aCI6Ii85MDg5NTcxNS8zMjIxNzc0MzgtNzY4MGVhZTItYjQyMi00MTRjLWI5OGUtODhkNGY1ZDY2NDU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDIwNTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YzhmODk3Y2QyZDA1NDIyMTY4M2I2YTk3NzRmMWE2ZmY5ODg5NDQ3YjMxZDQwOWIxNjFmN2Q5ODkzZjk1M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mX_1eporgmKy3B1ZW5ovI5oIxeHUtFzTvz2B91on5LU)
> > > 
> > > 
> > > And what should I use for Revanced apps? And the Revanced team said to download this one
> > 
> > 
> > I have no idea about ReVanced, since i use original YouTube app with microG Service Core as replacement for Play Services, thats all.
> 
> Try and test it https://revanced.app/patches?s=gms

Thanks, i use "original" unmodified YouTube app.
