### ISSUE TITLE
Couldn't communicate with Google Servers

### ISSUE THREAD

**Issue by fillwithjoy1** [microg/GmsCore#1897]
**Describe the bug**
WSA Environment using microG unofficial installer by u/ale5000. I am able to successfully login and put my password into Google, which then it says
![image](https://user-images.githubusercontent.com/29514446/224669874-94d52e85-2b6a-4d0a-b6c2-89b75970f75e.png)

**To Reproduce**
1. Go to microG Settings
2. Click on add account
3. Login
4. Error

**Expected behavior**
Self-explanatory

**Screenshots**
![image](https://user-images.githubusercontent.com/29514446/224669914-be7677d9-c4c7-4f19-96d0-a739f6fd90ab.png)

**System**
Android Version: 12
Custom ROM: WSA Windows 11 with microG unofficial installer by u/ale5000

**Comment by fillwithjoy1** [comment]
Found a solution thanks to u/ale5000

**Comment by ale5000-git** [comment]
Fore reference, the fis is here => https://github.com/microg/GmsCore/issues/1834#issuecomment-1468101197

**Comment by fillwithjoy1** [comment]
I've also found that 
a) Adding a new account **before** touching other microG services fixes the issue
