### ISSUE TITLE
Recover the password of this my Google account on this my device 

### ISSUE THREAD

**Issue by 07086690109** [microg/GmsCore#1905]
**Affected app**
Name: [e.g. WhatsApp]
Package id: [e.g. com.whatsapp]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
Android Version: [e.g. 10]
Custom ROM: [e.g. LineageOS 17.1]

**microG**
microG Core version: [e.g. 0.2.13.203915]
microG Self-Check results: [e.g. All ticked]

**Additional context**

**Comment by 07086690109** [comment]
Help me too recover my lost Email

**Comment by ILoveOpenSourceApplications** [comment]
Please Google how to do that.

**Comment by ale5000-git** [comment]
This isn't an issue with microG, please follow the Google guide to reset the password: https://support.google.com/accounts/answer/41078
