### ISSUE TITLE
FIDO 2 - NOT_ALLOWED_ERR Cannot find credential in local KeyStore or Database

### ISSUE THREAD

**Issue by leocluque** [microg/GmsCore#1929]
I'm getting the following error, I registered the credential using fido2, then I updated the application and I came across this error - showing the following message in the app: no access password available

<img width="967" alt="stack" src="https://github.com/microg/GmsCore/assets/54336852/9d9af06f-3d57-45be-addc-89aada156aa6">
![Captura de Tela 2023-05-04 às 13 02 24](https://github.com/microg/GmsCore/assets/54336852/5556e938-aa2a-4ebd-8f7a-c32dbc6fd8ac)

**Comment by ale5000-git** [comment]
Duplicate of #1930
