### ISSUE TITLE
I can't view my passwords

### ISSUE THREAD

**Issue by CHUCKECHEESETubeYT** [microg/GmsCore#1931]
I forgot a password to an account that I've used before, now I can't remember that said password, and I can't view the password in microg, what should I do?

**Comment by ILoveOpenSourceApplications** [comment]
Try a password reset perhaps?

**Comment by CHUCKECHEESETubeYT** [comment]
i can't access the Gmail to said account nither! so that's no help, i think the only way to make this work is by simply adding a setting to micro g that allows you to view the account and password so that way you can sign in to your account when necessary even if you forgot you can check micro g, at least that's my method

**Comment by mar-v-in** [comment]
microG does not remember the password in cleartext (and also shouldn't do so for security reasons) and thus can't provide it. If you're still logged into the account in microG you can use the GMail app to read its emails and maybe use account settings to add a recovery method. The latter may not work though, as Google may require to reconfirm your password based on their security system.

**Comment by CHUCKECHEESETubeYT** [comment]
well that fucking sucks ass!
