### ISSUE TITLE
Problem with google recorder , cannot sign in

### ISSUE THREAD

**Issue by ziadhussain007** [microg/GmsCore#1936]
Problem with google recorder , cannot sign into google account to restore backups 
It's expected for the app to sign into google account like the other apps drive , gmail etc.... but it doesn't sign in.
I tried to toggle the visability of google account on in microg but still the same.

![Screenshot_20230520-022445](https://github.com/microg/GmsCore/assets/109599249/304bbfd9-1205-43c6-9076-4b000424c4da)

**Comment by dtisfg** [comment]
Did you solve this problem?If you solved,please tell me how to do

**Comment by ale5000-git** [comment]
@dtisfg
It should be fixed in the [latest nightly build](https://microg.org/dl/core-nightly.apk), have you tried it?

**Comment by dtisfg** [comment]
> @dtisfg
> It should be fixed in the [latest nightly build](https://microg.org/dl/core-nightly.apk), have you tried it?

thank you but I don't know about the lastest nightly build.Can you tell me something detailed information?

**Comment by dtisfg** [comment]
@ale5000-git

**Comment by ale5000-git** [comment]
Currently there are only 2 changes compared to the latest release:
- Google Recorder account fix
- Fix for some apps that may crash if the location permission isn't granted

**Comment by dtisfg** [comment]
@ale5000-git One more problem, I deleted the google address sync by mistake. Now back down, seems to be unable to use. Is there any way you can solve it?

**Comment by ale5000-git** [comment]
You can try [Google Sync Add-on](https://forum.xda-developers.com/showthread.php?t=3432360), it install the sync adapters.

**Comment by dtisfg** [comment]
@ale5000-git I'm android 12L,Can I use it?

**Comment by ale5000-git** [comment]
Currently I'm not sure because I didn't have time to test it.
It will surely work on Android 8, for the later ones it may work but I'm not sure.

**Comment by dtisfg** [comment]
Thank you very much. If you want to Update it, please tell me,I think i can t
est him.
