### ISSUE TITLE
Remove all updates and the packages in /system/priv-app of the Google Services GmsCore?

### ISSUE THREAD

**Issue by PrincessPeach457** [microg/GmsCore#195]
So I'm not exactly an expert but in the prerequisite section you have listed:
"In case you had the Google Play Services previously installed, remove all updates and the packages in /system/priv-app of the Google Services GmsCore, GoogleBackupTransport, GoogleFeedback, GoogleLoginService, GoogleOneTimeInitializer, GooglePartnerSetup, GoogleServicesFramework, Phonesky, SetupWizard and Velvet. In case you forgot to remove the GmsCore updates, you can manually remove these using adb uninstall com.google.android.gms. After that, reboot your android device - all privileged GAPPS should be removed."
How exactly do I access /system/priv-app to be able to delete it. Do I just have to go to "com.google.android.gms" using the application manager and uninstall it?
##

**Comment by ale5000-git** [comment]
You need root or a ROM that come directly without GAPPS.

**Comment by PrincessPeach457** [comment]
Thank you for your quick response I'm currently rooted how would I go about removing the GAPPS?

**Comment by ale5000-git** [comment]
- Install adb on the pc
- Connect the phone to the pc
- From command prompt run: adb root
- Then: adb remount
- Then: adb shell rm /system/priv-app/GoogleLoginService.apk
- Then: adb shell rm /system/priv-app/GoogleServicesFramework.apk
- Etc.

Be sure to make a backup first, if you remove the wrong file the phone maystuck at boot.

**Comment by PrincessPeach457** [comment]
Alright do you have a link to the adb program/installation instructions? :)

**Comment by ale5000-git** [comment]
For Windows: http://forum.xda-developers.com/showthread.php?t=2588979
For Linux something like: sudo apt-get install android-tools-adb

**Comment by PrincessPeach457** [comment]
Alright so I'm in the command prompt. I navigated to the adb directory and now every command needs to be entered as 
for example the first one adb.exe adb root
then it would be adb.exe adb remount
etc.
Correct?

**Comment by ale5000-git** [comment]
The extension is optional, you can also skip it.

**Comment by PrincessPeach457** [comment]
Ok that makes sense when I try the first command to turn on root it gives me the error adbd cannot run as root in production builds?

**Comment by ale5000-git** [comment]
On some phones also with root, adb is unrooted.
This should be able to bypass this problem: https://play.google.com/store/apps/details?id=eu.chainfire.adbd

**Comment by PrincessPeach457** [comment]
I found a forum suggesting that I run the shell command first then to type in "su"
here: http://stackoverflow.com/questions/18369144/unable-to-run-adb-root-on-a-rooted-android-phone
Could I use this as a free option? 
Does the syntax at this point change or do I continue to enter "adb remount" for example after the ":/ #"

**Comment by ale5000-git** [comment]
Not sure but probably:
- adb shell su
- mount -o rw,remount,rw /system
- rm /system/priv-app/GoogleLoginService.apk
etc.

**Comment by PrincessPeach457** [comment]
So I've run through the list and I got this
Now either I never had them to begin with, or it can't find my device. Is there a way to print the contents of a folder to test whether the command prompt is working properly?
![command prompt log](https://cloud.githubusercontent.com/assets/22460593/18856789/0666a8e8-842c-11e6-94b3-877959dfb12c.jpg)

**Comment by ale5000-git** [comment]
Unlike Windows, Android is case sensitive, so if you pick wrong case it won't work, googleloginservice.apk should be GoogleLoginService.apk
Also some files may be in /system/app instead of /system/priv-app try both.

**Comment by PrincessPeach457** [comment]
Ok I read back through what I put in and I made sure to type in commands with system/app/ProperCase.apk and system/priv-app/ProperCase.apk same result. My phone hasn't really been doing anything is that normal?

**Comment by ale5000-git** [comment]
When the command run correctly it doesn't say anything, neither "No such file or directory".
Try to restart the phone to check if Google Settings and Play Store are disappeared.

**Comment by PrincessPeach457** [comment]
Well nothing disappeared... should I just try skipping past this step and trying to install everything?

**Comment by PrincessPeach457** [comment]
So just to give some specifics I'm currently using an S4 Active. I flashed it back to Kitkat, used towelroot, used flashfire to install a deodexed OC7 rom to preserve the root & get on 5.0.1, and then used flashfire to flash a TouchWiz Xposed Framework. 
I'm new to the idea of using adb to remove system files so I thank you for all your patience and all of your help so far :)

**Comment by ale5000-git** [comment]
Depending on your version of Android the files may have different path, try this program: https://play.google.com/store/apps/details?id=com.buak.Link2SD

It should be able to remove apps, and also show path of them.

**Comment by seanrand** [comment]
@ale5000-git FYI, last I heard, installing microG to /system isn't officially supported/recommended. https://github.com/microg/android_packages_apps_GmsCore/issues/97#issuecomment-190618393

**Comment by PrincessPeach457** [comment]
I actually used the Fx file manager app with the root support add on and it let me mount and remount the folder and I could delete the .apk's in question from the different folders. They were in priv-app. I first tried X-plore but the files would just restore after reboot.

**Comment by ale5000-git** [comment]
Link2SD remove the apps without need to know the path.

**Comment by ale5000-git** [comment]
@PrincessPeach457: If you have fixed your problem please close the issue.

PS: I have created a flashable ZIP the remove [GApps](https://forum.xda-developers.com/showthread.php?t=3432360) and nstall microG.

**Comment by akaiiro** [comment]
my ot-5017a have stock rom and rw protected /system but with Aroma File Manager on TWRP I can delete, rename and move files

**Comment by WanderMax** [comment]
@ale5000-git  only need to remove the .apk file in the priv-app/*** folders?

**Comment by ale5000-git** [comment]
@WanderMax: You need to remove only the apk in Android < 5 instead you need to remove the entire app folder (like GmsCore) in Android >= 5.

**Comment by WanderMax** [comment]
@ale5000-git OK, that's great. The installation guide in wiki page lacks a lot of information, I think.
Thanks

**Comment by ale5000-git** [comment]
@PrincessPeach457: Were you able to fix your problem?

**Comment by Jonny85** [comment]
hhjhg

**Comment by ale5000-git** [comment]
@jakapongbucha
@Jonny85
@Dayday10

This is an old issue, please create a new issue explaining your problems.
