### ISSUE TITLE
Tesla Motors app crashes with GmsCore v0.2.28.231657 when accessing map features

### ISSUE THREAD

**Issue by moonshine-cc** [microg/GmsCore#1962]
**Describe the bug**
With GmsCore v0.2.28.231657 when selecting "Location" or "Summon" the Tesla Motors app (com.teslamotors.tesla) crashes.

**To Reproduce**
1. Start the Tesla Motors app
2. Click on 'Location' or ' Summon'
3. The app crashes

**Expected behavior**
With GmsCore v0.2.27.223616 is works, so when selection either option the map is shown and the app functions correctly.

**System**
Android Version: 13
Custom ROM: ArrowOS, Libre Mobile OS and crDroid with microG Installer Revived 3.3.2-0 on Magisk v26.1

**Additional context**

**Comment by Wojtaz0w** [comment]
Please capture (crash)  logs

**Comment by ale5000-git** [comment]
I'm not sure what is your crash (without logcat) but in cases it is related to location it may have been already fixed in the nightly build.

If you want you can try it directly to save time: https://microg.org/dl/core-nightly.apk

**Comment by moonshine-cc** [comment]
@Wojtaz0w @ale5000-git 

I have tried with core-nightly.apk v0.2.28.231657-2 (d56b6a0) but it shows the exact same problem.

I am currently on crDroid v9.5 (Android 13) which comes with MatLog preinstalled.

[Here](https://paste.crdroid.net/nDmxc1) is the automatic crash log upload, though that one is not complete.

If you can tell me which configuration to use with MatLog (Log Level and Filters) I can try again to provide what you need to properly analyze this.

**Comment by moonshine-cc** [comment]
@Wojtaz0w @ale5000-git 

So is this any good or do you need another log?

**Comment by mar-v-in** [comment]
This should be fixed via https://github.com/microg/GmsCore/commit/4a68aaeddf20aeed79f4f89bd55b0b5fe5863198

**Comment by ale5000-git** [comment]
Sorry to be late I didn't have time to look at it but looks like it is already fixed by mar-v-in

**Comment by moonshine-cc** [comment]
Well done, just tried with the current nightly v0.2.28.231657-28 (a749fe4) and the Tesla app isn't crashing anymore.
