### ISSUE TITLE
Please I need your support and assistance to recover my Mac book air and my IPhone 11 Pro max

### ISSUE THREAD

**Issue by MoodyJay2** [microg/GmsCore#1965]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
Android Version: [e.g. 10]
Custom ROM: [e.g. LineageOS 17.1]

**Additional context**
![image](https://github.com/microg/GmsCore/assets/134006444/5ca90631-7038-4b88-beee-85297c74b5a3)

**Comment by Wojtaz0w** [comment]
This ain't ios support u bozo
Go cry somewhere else
