### ISSUE TITLE
Disable the location provider by default

### ISSUE THREAD

**Issue by SkewedZeppelin** [microg/GmsCore#1970]
**Is your feature request related to a problem? Please describe.**
The other features are opt-in and UnifiedNlp used to be opt-in too.

**Describe the solution you'd like**
That the Mozilla provider was disabled by default.

**Comment by mar-v-in** [comment]
As other deployments will likely want it to be enabled by default, this means we need to put that into microg.xml. Also for users migrating from UnifiedNlp, we can consider the activation of the Mozilla Nlp Backend as a sign that Mozilla location service should be used.

**Comment by mar-v-in** [comment]
Done via https://github.com/microg/GmsCore/commit/47720085820a03988e99b605a387a32f81f89542
