### ISSUE TITLE
Ability for integrators to disable SafetyNet checks

### ISSUE THREAD

**Issue by SkewedZeppelin** [microg/GmsCore#1971]
**Is your feature request related to a problem? Please describe.**
I'd like to add optional opt-in unprivileged microG support to DivestOS, however SafetyNet both won't ever succeed on it nor do I want my users needlessly running the proprietary DroidGuard executables.

**Describe the solution you'd like**
An option in the microg.xml settings override to force disable and hide any function that directly downloads/executes more proprietary code.

**Comment by mar-v-in** [comment]
> I completely remove the default/stock OS fingerprints that LineageOS uses, it was a prereq for actually supporting delta/incremental OTA updates.

The device profile feature in microG can be used to spoof fingerprints to DroidGuard to pass SafetyNet when needed.

**Comment by SkewedZeppelin** [comment]
I did actually try the self test on both clark/17.1 (can't be relocked) and taimen/20.0 (relocked bootloader and verified boot enforcing) and both said "CTS profile match failed" iirc.

**Comment by mar-v-in** [comment]
I don't say it's going to work for all devices easily. Pixel devices are harder and unlocked bootloader generally doesn't work without kernel patch that hides the bootloader state (which is trivial though).

Anyway. With https://github.com/microg/GmsCore/commit/47720085820a03988e99b605a387a32f81f89542 there is now an boolean option in `microg.xml` called `droidguard_force_local_disabled` which you can set to true.

**Comment by SkewedZeppelin** [comment]
Thank you for these additions!
