### ISSUE TITLE
Is the nightly build not building / updating?

### ISSUE THREAD

**Issue by ghosting3175** [microg/GmsCore#1974]
Just wondering but it doesn't seem like the [nightly build](https://microg.org/dl/core-nightly.apk) is building.

Latest nightly is d56b6a0 while latest commit is 11a8aa7

I feel like it should've built now but I might be wrong.

**Comment by ale5000-git** [comment]
Although it is called nightly build it isn't automated, it is built manually by mar-v-in from time to time.

**Comment by ghosting3175** [comment]
Thanks for the clarification.

I'll wait for it to be updated.
