### ISSUE TITLE
Safetynet api not working

### ISSUE THREAD

**Issue by Guarmanda** [microg/GmsCore#1991]
**Describe the bug**
Testing Safetynet with any Safetynet checker will throw an error about Google play service api not sending anything. For example, YASNAC will throw this:

![IMG_20230723_075828](https://github.com/microg/GmsCore/assets/7463055/b3751333-0f20-4306-bec6-8192e3d5a838)

**To Reproduce**
1. Install latest lineageos 20 with integrated microg, from microg website
2. Root with magisk from lineage recouvert
3. Install YASNAC from aurora store
5. See error

**Expected behavior**
Yasnac should show a screen like this:

![Screenshot_20230723-080211_Aurora Store](https://github.com/microg/GmsCore/assets/7463055/6ac83aff-dfdd-40b3-8b6c-130d6a6d54c9)

Or this

![Screenshot_20230723-080204_Aurora Store](https://github.com/microg/GmsCore/assets/7463055/78ba237a-5478-47ee-89a9-b6ef702d26a6)

**System**
Android Version: 13
Custom ROM: lineage 20-20230706-microG-haydn

**Additional context**

**Comment by mar-v-in** [comment]
Have you made sure that SafetyNet / device attestation is enabled in microG settings?

**Comment by Guarmanda** [comment]
I'm blind thank you
