### ISSUE TITLE
Help a little boy..

### ISSUE THREAD

**Issue by LUCKASSs** [microg/GmsCore#200]
Hello guys and sorry for the stupid question..
I try to install GMSCORE on my Galaxy S6 rooted with CF-Auto-Root and Xposed unofficial version [(to work on GS6 with the new ART)](http://forum.xda-developers.com/xposed/unofficial-xposed-samsung-lollipop-t3180960)
But when I install the APK it said "App not installed"..
I have to erase Google Play Service first ? I have installed FakeGApps with Xposed.

_(I installed GMSCORE to have a full acess to safetynet to play at.......pokemon go.....shame on me)_

Thx !
##

**Comment by EleutheriusBliss** [comment]
Should have read the instructions first...
1 - delete all Google-related apps, not just Google Services.
2 - got signature spoofing to work?
https://github.com/microg/android_packages_apps_GmsCore/wiki/Prerequisites

**Comment by LUCKASSs** [comment]
All google-Related App ? Youtube, Inbox, etc... ??!

**Comment by seanrand** [comment]
@LUCKASSs, no - GmsCore (Play Services), GoogleLoginService, GoogleServicesFramework are the important ones. GoogleBackupTransport, GoogleFeedback, GoogleOneTimeInitializer, GooglePartnerSetup and SetupWizard can be frozen in Titanium Backup or removed from priv-apps.

**Comment by LUCKASSs** [comment]
Can I froze this app with SD Maid Pro ?

**Comment by Nutomic** [comment]
You can try, but I'm pretty sure you have to remove their apks. Which means a complete uninstall of these apps.

**Comment by EleutheriusBliss** [comment]
Seanrand answered for me. As for Youtube, works without a glitch on my phone in good terms with MicroG. Ditto for: Gmail app, Play store official app, Google voice search (some secondary functions do not work), contacts and calendar sync from Google servers, and GMaps (an old version).

**Comment by ale5000-git** [comment]
@LUCKASSs: Hi, have you been able to install it?
If yes, please close the issue.

**Comment by ale5000-git** [comment]
This should already be fixed.
