### ISSUE TITLE
Can send SMS but not recieve on LineageOS MicroG Verizon Wireless

### ISSUE THREAD

**Issue by jrvoelk** [microg/GmsCore#2001]
Trying on multiple SMS apps (default lineageOS messenger, silence, google messages) I've run into an issue where i can send SMSes but not receive incoming ones. I had this issue on initial install but installing google messages seemed to correct it temporarily (even if I was using a different SMS app.) However this morning it appears to have stopped working. Neither Force-Stopping the SMS apps nor rebooting the phone appears to help.  Calling appears to work just fine, Mobile data works fine too and i was on the phone with customer support for my carrier and it appears theres no issues on their end. All perms are enabled in the self-check for microG services core.

**System**
Android Version: 12
Custom ROM: LineageOS 19-20230315-microG-dre
Carrier: Verizon

**Comment by jrvoelk** [comment]
@Wojtaz0w whoops sorry, what would be the correct repo to put this in for future reference?

Looks like making sure the SMSC was set worked. For anybody looking at this thread in the future having my same issue:

1.  Open the Phone App
2.  Dial \*#\*#4636#\*#\* to open the Testing menu.
3.  Tap Phone Information.
4.  Scroll to the bottom to the entry for SMSC.
5.  Tap Refresh to load the current SMSC Number.

Tutorial lifted from [this page](https://www.techtarget.com/searchmobilecomputing/definition/short-message-service-center)

**Comment by Wojtaz0w** [comment]
Somewhere in LOS4microG configs, i'm not sure where tho
Please close issue @jrvoelk 🙂

**Comment by ale5000-git** [comment]
@Wojtaz0w

Hi,
this is for microG only.
Instead for LineageOS for microG you should look at there: https://github.com/lineageos4microg/docker-lineage-cicd/issues

**Comment by ale5000-git** [comment]
@jrvoelk

Hi,
this is for microG only.
Instead for LineageOS for microG you should look at there: https://github.com/lineageos4microg/docker-lineage-cicd/issues

**Comment by Wojtaz0w** [comment]
> @Wojtaz0w
> 
> Hi,
> this is for microG only.
> Instead for LineageOS for microG you should look at there: https://github.com/lineageos4microg/docker-lineage-cicd/issues

That's literally what my first message says.

**Comment by ale5000-git** [comment]
I have typed the wrong nick, the message wasn't for you sorry :)
