### ISSUE TITLE
com.hikvision.hikconnect Unable to Register for FCM Push Notifications due to Lack of forceQueryable in GSF Proxy Android Manifest

### ISSUE THREAD

**Issue by CircuitSerialKiller** [microg/GmsCore#2009]
**Affected app**
Name: Hik-Connect
Package id: com.hikvision.hikconnect
Versions: Tested with 5.3.1.0721 all the way down to version 3. Version 3 can successfully register when starting, but not version 4 and above. 

**Describe the bug**
App is unable to register for Firebase Cloud Messaging for push notifications. There are 27 other apps on the test device that have successfully registered for FCM. 

**To Reproduce**
1. Start the app. 
2. View logcat.

**Expected behavior**
Expect the app to be able to register for FCM. 

**System**
Android Version: 11
Custom ROM: OnePlus OOS Stock, De-Googled

**microG**
microG Core version: 0.2.28.231657
microG Self-Check results: All ticked

**logcat analysis**
Logcat shows package manager NameNotFoundException on com.google.android.gsf,
however, pm shows it available:
$ pm list packages -f | grep gsf
package:/system/app/MicroGGSFProxy/MicroGGSFProxy.apk=com.google.android.gsf

So, maybe some visibility issue of com.google.android.gsf? 
$dumpsys package queries does not show com.google.android.gsf as visible.

Would adding
android:forceQueryable="true"
under <application
in AndroidManifest.xml
correct this issue with visibility permissions having changed in Android version 11 and up?
https://github.com/microg/android_packages_apps_GsfProxy/blob/master/services-framework-proxy/src/main/AndroidManifest.xml

I see 
android:forceQueryable="true"
was added in GmsCore for Android 11 support, but not GsfProxy:
https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/AndroidManifest.xml

It was due to this issue:
https://github.com/microg/GmsCore/issues/1409

**logcat**
08-13 17:49:03.818   818   818 W System.err: android.content.pm.PackageManager$NameNotFoundException: com.google.android.gsf
08-13 17:49:03.818   818   818 W System.err: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:211)
08-13 17:49:03.818   818   818 W System.err: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:183)
08-13 17:49:03.818   818   818 W System.err: 	at com.hikvision.hikconnect.push.fcm.FcmPushClient.checkGoogleDevice(SourceFile:2)
08-13 17:49:03.818   818   818 W System.err: 	at com.hikvision.hikconnect.push.fcm.FcmPushClient.isSupport(SourceFile:1)
08-13 17:49:03.818   818   818 W System.err: 	at com.hikvision.hikconnect.push.client.HcPushClientManager.tryInitPushClient(SourceFile:1)
08-13 17:49:03.818   818   818 W System.err: 	at com.hikvision.hikconnect.push.client.HcPushClientManager.startDispatchClient(SourceFile:7)
08-13 17:49:03.818   818   818 W System.err: 	at com.hikvision.hikconnect.push.client.HcPushClientManager.<init>(SourceFile:14)
08-13 17:49:03.818   818   818 W System.err: 	at com.hikvision.hikconnect.push.impl.HcClientManagerImpl.initPush(SourceFile:2)
08-13 17:49:03.818   818   818 W System.err: 	at com.hikvision.hikconnect.app.App.onCreate(SourceFile:255)
08-13 17:49:03.818   818   818 W System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
08-13 17:49:03.818   818   818 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7006)
08-13 17:49:03.818   818   818 W System.err: 	at android.app.ActivityThread.access$1800(ActivityThread.java:274)
08-13 17:49:03.818   818   818 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2104)
08-13 17:49:03.818   818   818 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-13 17:49:03.818   818   818 W System.err: 	at android.os.Looper.loop(Looper.java:233)
08-13 17:49:03.818   818   818 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8030)
08-13 17:49:03.818   818   818 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-13 17:49:03.818   818   818 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
08-13 17:49:03.818   818   818 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by CircuitSerialKiller** [comment]
I confirmed this is the issue by installing GSFProxy as a user app with the --force-queryable flag:
adb install --force-queryable MicroGGSFProxy.apk
Hik-Connect is now registered and the error is no longer showing in logcat.

**Comment by CircuitSerialKiller** [comment]
Until the devs can update the code and compile a new GsfProxy apk for distribution, if you need a quick fix, you can decompile GsfProxy apk, edit AndroidManifest.xml, recompile the GSFProxy apk, and insert it into your favorite microg zip installer or however you want to install it.

The basic idea is:

Grab GsfProxy.apk from wherever you want
Download apktool.bat
Download apktool
Download uber-apk-signer.jar
Place all files in same folder

Decompile the apk:
**apktool d NameOfGsfProxy.apk**

Go in and edit AndroidManigest.apk in the newly created folder with the decompiled contents. 
The important part here is to get android:forceQueryable="true"  in the correct section like this:
`<application android:allowBackup="false" android:forceQueryable="true" android:icon="@mipmap/ic_core_service_app" android:label="@string/gsf_app_name">`

Build a new apk:
**apktool b NameOfGsfProxyFOLDER**

Sign it with a test signature:
**java -jar uber-apk-signer.jar --apks NameOfGsfProxyFOLDER\dist**

Grab your newly signed GsfProxy.apk out of the dist folder, and replace it in your microg installer zip. Reinstall using magisk (if you're using magisk)

I can confirm this works to get HikConnect push notifications working with microg, and should for any other app with similar issues.

**Comment by ale5000-git** [comment]
> ```
> com.google.android.gsf
> ```
> 
> is now listed with dumpsys package queries under foreceQueryable: $ dumpsys package queries
> 
> Queries: system apps queryable: false forceQueryable: ~ com.google.android.gsf
> 
> **Request to please add**
> 
> `android:forceQueryable="true"` under <application in AndroidManifest.xml
> 
> here https://github.com/microg/GmsCore/blob/master/play-services-core/src/main/AndroidManifest.xml and publish a new signed release.

This ticket is in the wrong repo, this repo is for: com.google.android.gms
The one referenced in this ticket (com.google.android.gsf) is here: https://github.com/microg/android_packages_apps_GsfProxy

**Comment by CircuitSerialKiller** [comment]
Closed and transferred to https://github.com/microg/android_packages_apps_GsfProxy/issues
@ale5000-git  Thank you for all your work on microG, and everyone else that's contributed to it!

**Comment by ale5000-git** [comment]
Thanks to you too for the ticket.

**Comment by ale5000-git** [comment]
Hi,
this should already be fixed but there isn't a new version of GsfProxy yet.
