### ISSUE TITLE
WebAuthn.io demo authentication fails

### ISSUE THREAD

**Issue by relan** [microg/GmsCore#2021]
**Describe the bug**
Cannot pass WebAuth.io demo authentication with Firefox 117.0, microG 0.2.27 and YubiKey 5C Nano.

**To Reproduce**
1. Go to webauthn.io.
2. Enter a name.
3. Tap "Register."
4. "Use your security key with webauth.io" screen appears. Switch on the "Yes, Firefox is my trusted browser" switch. Tap "Get Started."
5. "Choose how to use your security key" screen appears. Tap "Use security key with USB".
6. Now we're on "Connect your USB security key" screen. It says "Please connect your USB security key."
7. Insert the YubiKey 5C Nano into the USB C port of the phone.
8. The YubiKey blinks briefly and "Allow microG Services Core to access YubiKey OTP" popup appears. Tap OK.
9. The "Connect your USB security key" screen still says "Please connect your USB security key." Can't advance farther.

**Expected behavior**
An invitation to press a button or touch contacts on the YubiKey should appear.

**System**
Android Version: 13
Custom ROM: LineageOS 20 with microG integrated (from https://download.lineage.microg.org/joan/lineage-20.0-20230809-microG-joan.zip)
Firefox: 117.0 (vanilla from Mozilla)

**Additional context**
Didn't have a chance to test this YubiKey with Google Play Services.
[logcat.zip](https://github.com/microg/GmsCore/files/12522596/logcat.zip)

**Comment by ale5000-git** [comment]
Probably it doesn't change but have you tried the latest [nightly build](https://microg.org/dl/core-nightly.apk)?
Since you have microG GmsCore already installed you can update it by installing the apk as normal app.

**Comment by relan** [comment]
> Probably it doesn't change but have you tried the latest [nightly build](https://microg.org/dl/core-nightly.apk)?

No luck with yesterday's nightly.

**Comment by mar-v-in** [comment]
Can confirm here.

The issue seems to be that Firefox sets an empty string for icon in rp and user. The spec says that the icon must be an URI if present, so the Yubikey rightfully errors. I suspect Google's implementation will filter out those empty strings and make them unset, so I'll do the same (For the same request, Chrome does not set an icon, so Firefox behavior is also not correct, but we can handle this from our side)

Also we don't have transports information yet, so even with that fixed, Firefox would crash after successful registration. See my comment on #2022 about that.

**Comment by CoelacanthusHex** [comment]
> Can confirm here.
> 
> The issue seems to be that Firefox sets an empty string for icon in rp and user. The spec says that the icon must be an URI if present, so the Yubikey rightfully errors (and our error handling currently does not include any user-visible feedback). I suspect Google's implementation will filter out those empty strings and make them unset, so I'll do the same (For the same request, Chrome does not set an icon, so Firefox behavior is also not correct, but we can handle this from our side

@relan may be able to report it to Firefox as well.

> Also we don't have transports information yet, so even with that fixed, Firefox would crash after successful registration. See my comment on #2022 about that.

**Comment by relan** [comment]
Confirming that WebAuthn.io demo now works with Firefox 117.0 and yesterday's GmsCore nightly. Thanks!
