### ISSUE TITLE
Implement ResidentKeyRequirement

### ISSUE THREAD

**Issue by relan** [microg/GmsCore#2022]
**Is your feature request related to a problem? Please describe.**
`org.microg.gms:play-services-fido` does not have [ResidentKeyRequirement](https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/api/common/ResidentKeyRequirement). It's needed to replace `com.google.android.gms:play-services-fido` in Firefox. See the use in [GeckoView](https://hg.mozilla.org/releases/mozilla-release/file/27de51e74c19186044da535125895c96fc3a0f23/mobile/android/geckoview/src/main/java/org/mozilla/geckoview/WebAuthnTokenManager.java#l196).

**Describe the solution you'd like**
Add ResidentKeyRequirement and related stuff (including [builder method](https://developers.google.com/android/reference/com/google/android/gms/fido/fido2/api/common/AuthenticatorSelectionCriteria.Builder#setResidentKeyRequirement(com.google.android.gms.fido.fido2.api.common.ResidentKeyRequirement))).

**Describe alternatives you've considered**
Made a patch to remove ResidentKeyRequirement but didn't have a chance to test it:
```diff
@@ -192,16 +191,13 @@
     final String residentKey = authenticatorSelection.getString("residentKey", "");
     if (residentKey.equals("required")) {
       selBuild
-          .setRequireResidentKey(true)
-          .setResidentKeyRequirement(ResidentKeyRequirement.RESIDENT_KEY_REQUIRED);
+          .setRequireResidentKey(true);
     } else if (residentKey.equals("preferred")) {
       selBuild
-          .setRequireResidentKey(false)
-          .setResidentKeyRequirement(ResidentKeyRequirement.RESIDENT_KEY_PREFERRED);
+          .setRequireResidentKey(false);
     } else if (residentKey.equals("discouraged")) {
       selBuild
-          .setRequireResidentKey(false)
-          .setResidentKeyRequirement(ResidentKeyRequirement.RESIDENT_KEY_DISCOURAGED);
+          .setRequireResidentKey(false);
     }
     final AuthenticatorSelectionCriteria sel = selBuild.build();
 
```

**Comment by mar-v-in** [comment]
Nightly is also updated with those changes.

**Comment by ale5000-git** [comment]
Good, thanks :)

**Comment by relan** [comment]
GeckoView builds fine with org.microg.gms:play-services-fido compiled from 666361a1fdb3fc48b110fd10f144e133a91f5163. Thanks!
