### ISSUE TITLE
Update build instruction from sources

### ISSUE THREAD

**Issue by 0x00x0** [microg/GmsCore#2026]
Hello
Could you update build instructions, as my result build is twice less in size than published on github  in releases section and map related functionality is not working?

**Comment by ale5000-git** [comment]
It is correct, because my recent PR (already merged) enable library compression so it halve size.

**Comment by 0x00x0** [comment]
@ale5000-git do you know, why maps are not loaded(empty tiles) in apps, which are using it, like bolt or glovo?

**Comment by ale5000-git** [comment]
You must set api keys for many things to work; in the main folder of the repo you downloaded create a file named `local.properties` and you need to set values of these:
```
safetynet.key=
recaptcha.siteKey=
recaptcha.secret=
recaptchaEnterpreise.projectId=
recaptchaEnterpreise.siteKey=
recaptchaEnterpreise.apiKey=
ichnaea.key=
mapbox.key=
stadia.key=
```

They aren't obligatory.
For maps you mainly need: mapbox.key

**Comment by 0x00x0** [comment]
@ale5000-git without mentioned keys, corresponded functionality won't work?
In such case, where I can get those keys?


Also, regarding to mapbox key, I can get it from here
[https://account.mapbox.com/access-tokens](https://account.mapbox.com/access-tokens)?
Or there is different service for it need?

**Comment by ale5000-git** [comment]
Yes, it is probably that the required functionality doesn't work without them.

Although I help and follow microG from a lot of time I have started compiling it myself just recently and I have found these things myself but I don't know all the details.
