### ISSUE TITLE
Nearby Share works with MicroG?

### ISSUE THREAD

**Issue by DaGuyComensal** [microg/GmsCore#2027]
Installed microG along with a [YouTube ReVanced v18.36.33 MOD APK (Premium, No ADS)](https://liteapks.com/youtube-revanced.html) and found out the Nearby Share? I am on lineageos.

***Planning on switching to PixelExperience , but still, I want an answer.***

**Comment by Wojtaz0w** [comment]
> Installed microG along with a [YouTube ReVanced v18.36.33 MOD APK (Premium, No ADS)](https://liteapks.com/youtube-revanced.html) and found out the Nearby Share? I am on lineageos.
> 
> ***Planning on switching to PixelExperience , but still, I want an answer.***

**ReVanced Team does not officially distribute apk
They only provide code and tools for patching, and officially the ReVanced Team recommends patching yourself. **
Also Revanced Extended has more features. Plus liteapks is very sketchy. If you really cant patch yourself get apk from rvx_lite or mmt on telegram.
