### ISSUE TITLE
"WebAuthn isn't supported" after building Firefox with org.microg.gms:play-services-fido

### ISSUE THREAD

**Issue by relan** [microg/GmsCore#2034]
**Describe the bug**
WebAuthn.io demo reports that WebAuthn is not supported in a custom build of Firefox 117.0 compiled with `org.microg.gms:play-services-fido-0.2.28.233013-87 (666361a)` instead of `com.google.android.gms:play-services-fido`.

**To Reproduce**
1. Build custom Firefox using F-Droid tools with https://gitlab.com/relan/fennecbuild/-/tree/microg?ref_type=heads
2. Install and start the app on an Android device.
3. Open webauthn.io site.
4. See "WebAuthn isn't supported" message.

**Expected behavior**
There should be a field to enter a user name and buttons to Register and Authenticate.

**System**
Android Version: 13
Custom ROM: LineageOS 20 with microG integrated (from https://download.lineage.microg.org/joan/lineage-20.0-20230809-microG-joan.zip) with yesterday's nightly
Custom Firefox 117.0 build (APK: https://mega.nz/file/75dmjLoZ#5IbyuIcTMAmZDXf5fsFS-9tbuafOybO7kyI6iuEwFes)

**Additional context**
WebAuthn.io demo works fine with vanilla Firefox 117.0 on this device.
GeckoView has this patch applied: https://gitlab.com/relan/fennecbuild/-/blob/microg/gecko-liberate.patch?ref_type=heads

**Comment by mar-v-in** [comment]
Hi. I tried your APK and it gives the following exception:
```logcat
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: Failed to launch activity: 
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: java.lang.IllegalStateException: No delegate attached
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at org.mozilla.geckoview.GeckoRuntime.startActivityForResult(GeckoRuntime.java:48)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at org.mozilla.geckoview.WebAuthnTokenManager.lambda$makeCredential$2(WebAuthnTokenManager.java:5)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at org.mozilla.geckoview.WebAuthnTokenManager.$r8$lambda$lxV1Gw97OXmWk5F1S1TWNMYm1hg(WebAuthnTokenManager.java:1)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at org.mozilla.geckoview.WebAuthnTokenManager$$ExternalSyntheticLambda0.onSuccess(R8$$SyntheticClass:5)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at org.microg.gms.tasks.SuccessExecutor$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:21)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at android.os.Handler.handleCallback(Handler.java:938)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at android.os.Looper.loop(Looper.java:223)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at java.lang.reflect.Method.invoke(Native Method)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
09-15 09:07:25.985 15324 15324 W WebAuthnTokenManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

I checked the source code of GeckoView to figure out what the issue is. The delegate is not attached because the WebAuthnFeature in Fenix is not activated for non official builds, see https://github.com/mozilla-mobile/firefox-android/blob/24ee592ea61ac3cf9c170aa0ca039fb5f4cc80c4/fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt#L835-L844

**Comment by relan** [comment]
> I checked the source code of GeckoView to figure out what the issue is. The delegate is not attached because the WebAuthnFeature in Fenix is not activated for non official builds

Good catch, thanks!

I removed this limitation ([patch](https://gitlab.com/relan/fennecbuild/-/commit/bca8d4c87a13670a79eb0d8465b2a52bfa773730) but result is the same. This time I can see nothing relevant in logcat. Also checked other occurrences of BuildConfig.MOZILLA_OFFICIAL, nothing caught my eye.

I'm currently out of ideas. APK for those who would like to check out: https://mega.nz/file/K5shmS5T#vVU1yoosFp1IOM6XCunSX6F6UBUJ3cY-LTKgjP-A5W8

**Comment by mar-v-in** [comment]
I figured that Proguard seemed to have deleted some code. I did a bunch of changes that should cause it to not remove it. Unfortunately I could not get Fennec to build on my machine, can you try a new build (and/or provide some build instructions). Thanks.

**Comment by relan** [comment]
> can you try a new build (and/or provide some build instructions)

Sure! Will do in two weeks when I'm back from vacation, I have no access to my PC from here.

Thanks a lot for your help!

**Comment by relan** [comment]
> can you try a new build (and/or provide some build instructions)

Sure! Will do in two weeks when I'm back from vacation, I have no access to my PC from here.

Thanks a lot for your help!

**Comment by bblacher** [comment]
@relan Any updates?

**Comment by relan** [comment]
> Any updates?

I built Fennec with microG and minification off, but the result is the same (WebAuthn.io demo says WebAuthn is not supported). Some Gecko debugging is needed, I guess.

**Comment by relan** [comment]
I finally figured out that I missed two places where WebAuthn must be enabled in Gecko.

Works for me now!
