### ISSUE TITLE
After updating to the latest gmscore, Location accuracy is horrendous

### ISSUE THREAD

**Issue by DavidRLTG** [microg/GmsCore#2046]
**Describe the bug**
Basically, I updated the app to the latest ver and saw that it no longer supports your own location services, which I disapprove of but oh well
And then I tried using my maps app, and they COULD NOT find me, they barely found my country or my city. Terrible.
**To Reproduce**
1. Use latest gmscore
2. Open your maps app
3. Suffer

**Expected behavior**
Location accuracy being equal to before the update or better

**Screenshots**
Cant really show that

**System**
Android Version: 13
Custom ROM: ArrowOS

**Additional context**
I used to use basically every possible location service on fdroid at once to get the best accuracy

**Comment by ale5000-git** [comment]
Have you enabled the new location options in microG settings?

**Comment by DavidRLTG** [comment]
No, it just came there by default. Is there some way to disable it?

**Comment by 3ri4nG0ld** [comment]
+1, currently seen in Canary Islands-Spain, but it always locates me in Galicia-Spain which is not even close.
I have also tried disabling the wifi location and the mobile network location and it gives the same result (for some reason the GPS location works worse).

**Comment by 3ri4nG0ld** [comment]
> +1, currently seen in Canary Islands-Spain, but it always locates me in Galicia-Spain which is not even close.
> I have also tried disabling the wifi location and the mobile network location and it gives the same result (for some reason the GPS location works worse).

In fact I would like to mention that this used to happen in the same way, but I could use Local NLP Backend (https://f-droid.org/es/packages/helium314.localbackend/) and Apple Unified NLP (https://f-droid.org/packages/org.microg.nlp.backend.apple/) to make it work correctly.
Traducido con DeepL https://www.deepl.com/app/?utm_source=android&utm_medium=app&utm_campaign=share-translation

**Comment by ale5000-git** [comment]
@DavidRLTG: Everything is disabled by default unless you have enabled it before.

**Comment by DavidRLTG** [comment]
I swear, I never enabled the new options menu. I dunno how to. it just came when I updated. And it didnt support my custom locations anymore. @ale5000-git

**Comment by ArchangeGabriel** [comment]
@DavidRLTG What @ale5000-git is trying to tell you is that by default no backend is enabled, so you don’t get any location (location itself is enabled, but will only work with locally collected data — that is none when you’ve just installed the app). If you want to get something out of it, you need to enable backends.

**Comment by DavidRLTG** [comment]
I enabled everything in Location, what else do I do? there is no option for backends or anything

**Comment by DavidRLTG** [comment]
Issue closed, After restarting my phone it finally worked okay, though I do wish we had a feature to use custom location modules again or to download cell tower locations for countries.
