### ISSUE TITLE
Is FakeStore as separate app no longer required?

### ISSUE THREAD

**Issue by sysxda** [microg/GmsCore#2047]
Hi . Since recently FakeStore merged into GmsCore repo ,  FakeStore as a separate application no longer required?

**Comment by mar-v-in** [comment]
FakeStore (now rebranded as microG Companion) still needs to be installed for most of microG functionality and will continue to be required. The app can also be built from the source code in GmsCore repository.

**Comment by sysxda** [comment]
Thanks for answer

**Comment by mar-v-in** [comment]
Version of microG Companion will have the same as microG Services, except for the 4th part (which will be the version of Play Store that is announced by that version of companion)

**Comment by hmtheboy154** [comment]
Hi, will the new microG companion app supports license verification for paid apps such as PowerAMP ? Currently I can't be able to use FakeStore because of this.....

**Comment by mar-v-in** [comment]
Not immediately, but generally yes, that's the plan. It's meant to move from just being a fake placeholder to support license verification, in app ourchases, play integrity, split package and asset provider...

**Comment by BurhanBudak** [comment]
The app still needs to be a system app to circumvent some DRM apps use. I use dto use the FakeStore2PlayStore module but it's not needed for most apps. But bumping the minimum API should be done.
