### ISSUE TITLE
microG settings icon inside Android settings is missing on Nougat

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#2057]
The icon of `microG Settings embedded in System Settings on SDK 23` is missing on Nougat.

![Screenshot_20230922-180320](https://github.com/microg/GmsCore/assets/15793015/f480c344-83e7-427d-911b-41bc43aeded3)

---

In the past it was like this:
![microg-settings](https://github.com/microg/GmsCore/assets/15793015/cd8dd577-9e8a-463e-9696-5a3f8673f954)

**Comment by Daviteusz** [comment]
SDK:33 (Android 13, crDroid)

![obraz](https://github.com/microg/GmsCore/assets/11527277/549e6dfd-d399-4fe5-9cb6-835c4ecaa8d8)
![obraz](https://github.com/microg/GmsCore/assets/11527277/d26a1633-e127-470c-9295-aee54b0f95f2)

**Comment by ale5000-git** [comment]
@Daviteusz
You issue is diffrent, please post it here: #2059
