### ISSUE TITLE
MicroG settings icon in settings is always light mode and it's out of place. 

### ISSUE THREAD

**Issue by Wojtaz0w** [microg/GmsCore#2059]
**Describe the bug**
The icon of microG in device settings is almost invisible when dark theme is on. 

**To Reproduce**
1. Go to settings
2. (Don't) see the broken icon. 

**Expected behavior**
Icon respects device theme. 

**Screenshots**
![Screenshot_20230923-203435_Ustawienia.png](https://github.com/microg/GmsCore/assets/104674625/6ea67d18-094c-4bd0-a8e8-c5296e06e65a)

![Screenshot_20230923-203423_Ustawienia.png](https://github.com/microg/GmsCore/assets/104674625/57d5c95c-9e0a-4f59-bf20-5a8fa0e11cb1)

**System**
Android Version: 13 (TQ3C.230805.001.A4) 
Custom ROM: risingOS 1.3

**Comment by Turbolqk** [comment]
Imo it the setting it self should be moved to the general settings menu, where google play services normally stay.

**Comment by ale5000-git** [comment]
This issue was already fixed some time ago but I don't remember the exact version so I'm closing this.
In case you still have the issue with the latest version, please comment here.
