### ISSUE TITLE
DroidGuard Helper For Barclays Banking App

### ISSUE THREAD

**Issue by rjawaid** [microg/GmsCore#206]
Hi,
I wan't to try DroidGuard Helper to see if Barclays Mobile Banking App works with it.  I couldn't find instructions for installing and using it.  I'm using omnirom with microg services running with blankstore.  Any help would be appreciated.  Thanks.

**Comment by ArchangeGabriel** [comment]
If you’re using OmniRom, it shouldn’t be too hard. Just install DroidGuard Helper (1.0 or latest snapshot), and make sure you’re using latest MicroG snapshot (-20).

You can check with https://play.google.com/store/apps/details?id=com.scottyab.safetynet.sample that you’re fine, but your Banking app should be working.

**Comment by rjawaid** [comment]
![tmp_26353-screenshot_20161004-032417156606910](https://cloud.githubusercontent.com/assets/22422207/19060734/90fbf1e6-89e2-11e6-9548-f55951052688.png)
![tmp_26353-screenshot_20161004-032500-2081538828](https://cloud.githubusercontent.com/assets/22422207/19060737/95527e86-89e2-11e6-854d-22d1fe66ec5a.png)
![tmp_26353-screenshot_20161004-032531-591377882](https://cloud.githubusercontent.com/assets/22422207/19060740/98fb62aa-89e2-11e6-90d7-b277d9acf2fa.png)

Thanks for your help. This is what I'm getting.  What could be the reason?

**Comment by ArchangeGabriel** [comment]
What’s your microG version? Self-check status?

**Comment by rjawaid** [comment]
microg services core version is 0.2.4 as it can also be seen in above images.  I assume it's the latest one.  Self-check status is all green ticks.

**Comment by ale5000-git** [comment]
@rjawaid: 0.2.4 is the latest release build and it will NOT work, you must use the latest preview build (currently 0.2.4-22).

**Comment by rjawaid** [comment]
sorry my apologies I'm using 0.2.4-22.  That's the most latest available on f-droid.

**Comment by ale5000-git** [comment]
DroidGuardHelper is no longer needed, in addition now microG pass SafetyNet.
