### ISSUE TITLE
So I backed up a Google wallet app from a rooted Gapps phone, transfered it to my MicroG enabled phone and I got this error message.

### ISSUE THREAD

**Issue by BurhanBudak** [microg/GmsCore#2088]
Here is the screenshot from my phone when I press the wallet enabled app:
![Screenshot_20231111-161336_microG Services](https://github.com/microg/GmsCore/assets/43676158/5a9ac862-6879-4ddd-b286-23f49ef2a2b1)

**Comment by BurhanBudak** [comment]
I got the idea to test it after I successfully added a RCS enabled Messages app to my MicroG phone. I thought it was worth a try.

If its not possible, would a remote controlled Wallet phone be a option? Isn't it what Tasker is for?

**Comment by Idcrafter** [comment]
it would be more secure and faster if you pay with the second phone while keeping the first phone in your pocket, and you would need to root that second phone  and hide that root to re-route the NFC data via p2p wifi or Bluetooth.

**Comment by BurhanBudak** [comment]
> it would be more secure and faster if you pay with the second phone while keeping the first phone in your pocket, and you would need to root that second phone  and hide that root to re-route the NFC data via p2p wifi or Bluetooth.

Both are rooted. I was thinking that the rooted minimal Gapps phone can stay at home and be remotely controlled from the rooted microG phone. Its like the time when Airmessage was a thing.

**Comment by Wojtaz0w** [comment]
> I got the idea to test it after I successfully added a RCS enabled Messages app to my MicroG phone. I thought it was worth a try.
> 
> If its not possible to use Payment apps with MivroG, would a remote controlled Wallet phone be a option? Isn't it what Tasker is for?

I know it is OT, but could you let me know how to enable RCS in Messages on phone with microG? How'd you get them to work?

**Comment by BurhanBudak** [comment]
> > I got the idea to test it after I successfully added a RCS enabled Messages app to my MicroG phone. I thought it was worth a try.
> > 
> > If its not possible to use Payment apps with MivroG, would a remote controlled Wallet phone be a option? Isn't it what Tasker is for?
> 
> I know it is OT, but could you let me know how to enable RCS in Messages on phone with microG? How'd you get them to work? For me it says that device doesn't support.

Look up my other post on this repo. 

You need two phones, both must be rooted.

I just transferred a RCS enabled app to a MicroG phone. Its still not possible to enable it woth RCS but my example should give hints on how it works.
