### ISSUE TITLE
Some (but not all) apps not working with GCM/FCM

### ISSUE THREAD

**Issue by osmarks** [microg/GmsCore#2092]
**Describe the bug**
Some of the apps I have installed (Signal, ProtonMail, WhatsApp Business) aren't connecting to GCM/FCM and are complaining about lack of Play Services. However, others (Firefox, Instagram) are, and work fine. microG reports signature spoofing as working. I don't know if this is actually a microG issue or something weirder but I don't know how else to report this.

**To Reproduce**
I don't know.

**Expected behavior**
Apps should think they have Google Play Services and FCM/GCM should work.

**Screenshots**
![Screenshot_20231116-122741](https://github.com/microg/GmsCore/assets/10486993/438a7a2c-89c8-4d2b-9c45-00b3df8f3249)
![Screenshot_20231116-122007_1](https://github.com/microg/GmsCore/assets/10486993/68956b02-5529-486f-9aeb-e16df63a5040)

There are various errors in `adb logcat` about Google Play Services but I don't know how to interpret them.

![screenshot-20231116-12h22m20s](https://github.com/microg/GmsCore/assets/10486993/4c0525f5-126e-4407-849f-fce10dcc261e)
![screenshot-20231116-12h22m10s](https://github.com/microg/GmsCore/assets/10486993/34a0caa1-d70c-47ed-8467-1eb588f2da33)

**System**
Android Version: 13
Custom ROM: Stock ROM on Sony Xperia 10 V (68.0.A.0.797)
I installed microG with https://github.com/whew-inc/FakeGApps and https://github.com/nift4/microg_installer_revived via Magisk.

**Additional context**
Some of the apps I tried using were restored from a backup on a previous device. I tried wiping them and signing in again, and this didn't fix it, however.

**Comment by osmarks** [comment]
I have no idea what the actual problem was but reflashing the device and reinstalling everything from scratch seems to have fixed it.

**Comment by RobertoWa** [comment]
some apps need to be installed over playstore to get working (my experience)
