### ISSUE TITLE
nonk

### ISSUE THREAD

**Issue by amingge789** [microg/GmsCore#2093]
**Affected app**
Name: [e.g. WhatsApp]
Package id: [e.g. com.whatsapp]

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
Android Version: [e.g. 10]
Custom ROM: [e.g. LineageOS 17.1]

**microG**
microG Core version: [e.g. 0.2.13.203915]
microG Self-Check results: [e.g. All ticked]

**Additional context**

**Comment by amingge789** [comment]
1.fu:/^quCYkpfnQq^eyJwMSI6IjEwMzkyODFrIiwicDIiOiIiLCJwMyI6IjEwMzkyODFpIiwicDQiOiJ7XCJicm93c2VyaWRcIjpcIlwiLFwiYmFpZHVpZFwiOlwiNTlCQURCNUQyMDQ3RDgwODVGRDdDRjVBOTIzQ0M4NzVcIn0iLCJzY2hlbWUiOiJ2MS9icm93c2VyL29wZW4/dXJsPXNlYXJjaCUzQSUyRiUyRiUyNUU2JTI1QjIlMjVCOSUyNUU3JTI1QUUlMjVBMSUyNUU1JTI1OTAlMjVBRiUyNUU1JTI1OEElMjVBOCUyNUU0JTI1QjglMjU4RCUyNUU0JTI1QkElMjU4NmFwcCZycWlkPTk3MTAzNzkzNDY0NjU0MTQ2NTgmdXBncmFkZT0xJmZyb213aXNlPTEmbmV4dD1iYWlkdWJveGFwcCUzQSUyRiUyRnYxJTJGYnJvd3NlciUyRm9wZW4lM0Z1cmwlM0RodHRwcyUyNTNBJTI1MkYlMjUyRm0uYmFpZHUuY29tJTI1MkZzJTI1M0Z3b3JkJTI1M0QlMjUyNUU2JTI1MjVCMiUyNTI1QjklMjUyNUU3JTI1MjVBRSUyNTI1QTElMjUyNUU5JTI1MjVBNiUyNTI1OTYlMjUyNUU2JTI1MjVBQyUyNTI1QTElMjUyNUU0JTI1MjVCOCUyNTI1OEIlMjUyNUU4JTI1MjVCRCUyNTI1QkQlMjUyNnNhJTI1M0R0YiUyNTI2dHMlMjUzRDAlMjUyNnRfa3QlMjUzRDAlMjUyNmllJTI1M0R1dGYtOCUyNTI2cnN2X3QlMjUzRDFhYzFxVGdVclhFd0Q3bWVFQnVlbVNqSXBRd0VldVZubWZWJTI1MjUyNTJCdTVrVFdxUTBFR3F5OHhYSCUyNTI2cnN2X3BxJTI1M0Q5NzEwMzc5MzQ2NDY1NDE0NjU4JTI1MjZzcyUyNTNEMTEwJTI1MjZzdWdpZCUyNTNEOTQ4MjMxNjkzNzk1NDMlMjUyNnJmcm9tJTI1M0QxMDM5MjgxaSUyNTI2cmNoYW5uZWwlMjUzRDEwMzkyODFrJTI1MjZycWlkJTI1M0Q5NzEwMzc5MzQ2NDY1NDE0NjU4JTI2c2ltcGxlJTNEMSUyNmZyb213aXNlJTNEMSUyNnVnX3BhcmFtcyUzRCUyNTdCJTI1MjJhcHAlMjUyMiUyNTNBJTI1MjJ1cyUyNTIyJTI1MkMlMjUyMnNjZW5lJTI1MjIlMjUzQSUyNTIydXMydnVpJTI1MjIlMjUyQyUyNTIycG9zJTI1MjIlMjUzQTE2JTI1MkMlMjUyMnNpZCUyNTIyJTI1M0ElMjUyMmFsbCUyNTIyJTI1MkMlMjUyMmJyb3dzZXJpZCUyNTIyJTI1M0ElMjUyMjI5JTI1MjIlMjUyQyUyNTIyYmFpZHVpZCUyNTIyJTI1M0ElMjUyMjU5QkFEQjVEMjA0N0Q4MDg1RkQ3Q0Y1QTkyM0NDODc1JTI1MjIlMjUyQyUyNTIydG9rZW50aW1lJTI1MjIlMjUzQTE3MDAyNjUzNzglMjUyQyUyNTIyaXNUb2tlblNoYXJlJTI1MjIlMjUzQTAlMjU3RCZuZWVkbG9nPTEmbG9nYXJncz0lN0IlMjJzb3VyY2UlMjIlM0ElMjIxMDM5MjgxaSUyMiUyQyUyMmZyb20lMjIlM0ElMjJtY3BzZGslMjIlMkMlMjJwYWdlJTIyJTNBJTIyZmlyZWZveCUyMiUyQyUyMnR5cGUlMjIlM0ElMjIlMjIlMkMlMjJ2YWx1ZSUyMiUzQSUyMiUyMiUyQyUyMmNoYW5uZWwlMjIlM0ElMjIxMDM5MjgxayUyMiUyQyUyMmV4dGxvZyUyMiUzQSU3QiUyMmV4dF9jb250ZW50JTIyJTNBJTdCJTIyZnJvbSUyMiUzQSUyMiUyMiUyQyUyMmJyb3dzZXJpZCUyMiUzQSUyMiUyMiUyQyUyMnFpZCUyMiUzQSUyMiUyMiUyQyUyMnFpZHNpZHMlMjIlM0ElMjIxMTAwODVfMjY1ODgzXzI2MzYxOF8yNzU3MzNfMjU5NjQyXzI1NjczOV8yNzQ5NDhfMjc5ODc4XzI3ODQxNF8yODA4OThfMjgwNjM2XzI4MTE5MF8yODEyMzNfMjgxODEwXzI3NzQ2OF8yODE4NjVfMjgxODkyXzI4MTY4M18yODE4MjdfMjgwNjUwXzI3NTA5NV8yNzU2MjlfMjgxMTgxXzI3OTAxMF8yODE4MTVfMjgyNTIwXzI4MjU2OF8yODI2MjhfMjgyNzYxXzI4MDI3Ml8yODA4MTBfMjgyODQ5XzI3MjQ3M18yNTMwMjJfMjc4OTU0XzI4MjQwMl8yODI5OTdfMjgzMDc0XzIzNjMxMl8yODMxNTRfMjgxOTk0XzI4MDcyM18yODMzNTRfMjgzMjIzXzI1MTk3Ml8yODMzNjRfMjgzNTk2XzI4MzQ5N18yODM2MzJfMjgzNjYxXzI4MTcwNF8yODEwNTNfMjgzNzI0XzI4MzQ0NF8yODM3MThfMjgyODg3XzI1NjIyM18yNzk2MTBfMjgzNzY1XzI4Mzg2Nl8yODM4NjdfMjgzNzgyXzI4Mzg5Nl8yODM5MjVfMjgzODkzXzI4MzM3NF8yODM5ODFfMjg0MDA0XzI4NDAyNF8yODM5NzdfMjc4Mzg4XzI4NDEwMF8yODM5NDlfMjg0MTMxXzI4Mzk0NF8yODQxOTZfMjczMjQ4XzI4MTgzOF8yODQyODJfMjg0Mjg1XzI4NDI1OV84MDAwMDcyXzgwMDAxMjZfODAwMDEzNV84MDAwMTQ5XzgwMDAxNTlfODAwMDE2M184MDAwMTcyXzgwMDAxNzhfODAwMDE3Nl84MDAwMjA0XzgwMDAyMDklMjIlMkMlMjJ0aW1lc3RhbXAlMjIlM0ExNzAwMjY1NDU4NzY5JTdEJTdEJTJDJTIyYmFpZHVJZCUyMiUzQSUyMjU5QkFEQjVEMjA0N0Q4MDg1RkQ3Q0Y1QTkyM0NDODc1JTIyJTdEIn0=

**Comment by amingge789** [comment]
djwiifigig

**Comment by amingge789** [comment]
djdocjjywifkipqhfj

**Comment by hmtheboy154** [comment]
is this some kind of encrypted message ?

**Comment by ale5000-git** [comment]
It is just spam.
