### ISSUE TITLE
Is microG Service (Lighthouse) related to microG?

### ISSUE THREAD

**Issue by samleong123** [microg/GmsCore#2106]
Hi, I've noticed that there's a post in Facebook state that the Lighthouse (For Huawei Malaysia devices to use GMS) has been "upgraded" to microG Service. 
Is this "microG Service" certified and related to microG or it's a 3rd party using microG framework and renamed as "microG Service"?

Translate : MicroG Service is the upgraded version of Lighthouse. After installing microG Service, users can expect an enhanced GMS experience, replacing the Lighthouse app. Huawei is not affiliated with microG. microG Service is certified, akin to GBox, for release on the Huawei App Gallery.

https://web.archive.org/web/20231203032548/https://www.facebook.com/groups/1449543988677424/permalink/2720199218278555/
![image](https://github.com/microg/GmsCore/assets/58818070/7bc02d64-ada4-4814-9b24-9fd0e6463198)

**Comment by mar-v-in** [comment]
Lighthouse users on Huawei devices are currently migrated to official microG. The microG version currently available to some Huawei users in Malaysia and Thailand does not match the microG version for other users yet, but is an officially supported release. As Lighthouse included some changes that are not reflected in official microG yet, only a future update will make microG in AppGallery match the releases on the microg.org website and GitHub.
