### ISSUE TITLE
FIDO2 pin support / feature-parity with google play services

### ISSUE THREAD

**Issue by Yannik** [microg/GmsCore#2127]
**Is your feature request related to a problem? Please describe.**
Google play services now support using FIDO2 with pin:
https://www.rprna.com/news/google-play-system-fido2-pin-support/

It would be great to have this supported in microg too.

**Describe the solution you'd like**

Something similar to the flow with google play services:

![image](https://github.com/microg/GmsCore/assets/801996/d310b22c-1041-440e-97f2-82b0991a4af3)

![image](https://github.com/microg/GmsCore/assets/801996/51eda383-103a-4d39-bac6-34c3babf7e64)

**Comment by ale5000-git** [comment]
The PR has been merged so it will be in the next version.

**Comment by CoelacanthusHex** [comment]
> The PR has been merged so it will be in the next version.

It has been released.
https://github.com/microg/GmsCore/releases/tag/v0.3.3.240913

**Comment by mu88** [comment]
> > The PR has been merged so it will be in the next version.
> 
> It has been released. https://github.com/microg/GmsCore/releases/tag/v0.3.3.240913

...with a regression:

> A bug in this release prevents network location access to apps that do not use the fused location provider API. See https://github.com/microg/GmsCore/issues/2564 for details. If you run apps that rely on this functionality, it is suggested to stay on [v0.3.2.240913](https://github.com/microg/GmsCore/releases/tag/v0.3.2.240913) until next release.

**Comment by CoelacanthusHex** [comment]
> > > The PR has been merged so it will be in the next version.
> > 
> > 
> > It has been released. [`v0.3.3.240913` (release)](https://github.com/microg/GmsCore/releases/tag/v0.3.3.240913)
> 
> ...with a regression:
> 
> > A bug in this release prevents network location access to apps that do not use the fused location provider API. See [#2564](https://github.com/microg/GmsCore/issues/2564) for details. If you run apps that rely on this functionality, it is suggested to stay on [v0.3.2.240913](https://github.com/microg/GmsCore/releases/tag/v0.3.2.240913) until next release.

Has been fixed in 0.3.4
