### ISSUE TITLE
0.3.0.233516-lh Strava unable to log in

### ISSUE THREAD

**Issue by Wizit38** [microg/GmsCore#2137]
**Affected app**
Name: Strava
Package id: com.strava

**Describe the bug**
Unable to login to strava account. After input credentials, you have a please wait message but nothing happens

**To Reproduce**
1. Go to Strava
2. Click on Log in at the start screen
3. Input credentials and password
4. See Please wait message

**Expected behavior**
Expect to log in and get to user home page

**Screenshots**

**System**
Android Version: [e.g. 10]
Custom ROM: Harmony OS v 3.0.0.156

**microG**
microG Core version: 0.3.0.233516-lh
microG Self-Check results: All ticked except permission to find accounts

**Additional context**
[Log_2023-12-29_14-52-47.txt](https://github.com/microg/GmsCore/files/13791511/Log_2023-12-29_14-52-47.txt)

**Comment by bbbxyz** [comment]
Do you have SafetyNet enabled when attempting to sign in?

**Comment by Wizit38** [comment]
I don't think so but how do i check this?

**Comment by bbbxyz** [comment]
Google SafetyNet inside microg settings. Try enabling it and testing reCaptcha

**Comment by Wizit38** [comment]
Google safetynet was already on. I tried toggling off then on, but strava login is still showing spinning wait without movement..

Also, i have tested with reCaptcha. It's working

**Comment by Wizit38** [comment]
Not sure why but after device reset and using the version from Huawei app store, strava is working fine
