### ISSUE TITLE
 com.google.android.projection.gearhead - "install failed, please try again"

### ISSUE THREAD

**Issue by daniu-de** [microg/GmsCore#2138]
**Affected app**
Name: android auto
Package id: see above

**Describe the bug**
I tried several versions of android auto with microg. The only version that got me beyond a red screen was version 10.2.633224-release.
However it only offers to finalize installation by pressing "update" which results in the error message: "install failed, please try again"

I got a logreader app but don't know how to find the needle in the haystack ...

1. Install microg (version 0.3.0.233515) + android auto as mentioned above 
2. Plug in USB cable connected to an android auto capable car
3. Press update button (internet connection is available, android auto has ALL available permissions)

**Expected behavior**
Android auto showing up in car screen

**Screenshots**
![Screenshot_20231231-124022_Trebuchet](https://github.com/microg/GmsCore/assets/7965004/6f212c6f-f260-4475-9df0-fb0193086763)
![Screenshot_20231231-124005_Trebuchet](https://github.com/microg/GmsCore/assets/7965004/e2279f64-c569-4560-8557-9d63f5e01050)

**System**
Android Version: 13
Custom ROM: lineage_hawao-userdebug 13 TQ3A.230901.001 52fec5a91f (Motorola g42)

**microG**
microG Core version: 0.3.0.233515 (systemized with app systemizer)
microG Self-Check results: All ticked

**Additional contex**
-

**Comment by daniu-de** [comment]
After writing this I started to play around with systemize and the android auto app. Not sure if privacy or normal but android auto was somehow systemized. After playing around I cannot even get to the mentioned screens.

I had read the long thread about android auto and like to read that some people got android auto to work with microg - unfortunately I don't and do not understand everything written in the thread about how to get it running.

**Comment by ItsJustSomeDude** [comment]
Here's a repo with a lot of info and tools for running Auto on microG.  It's setup for Magisk, so might need to be tweaked if you're not using it.  https://github.com/sn-00-x/aa4mg

**Comment by daniu-de** [comment]
That was a great advice. Works on the spot was described

THANK YOU!

**Comment by daniu-de** [comment]
That was a great advice. Works on the spot as described

THANK YOU!
