### ISSUE TITLE
Android auto - pairing phase issue (Location permissions)

### ISSUE THREAD

**Issue by rickard-505** [microg/GmsCore#2151]
Name: Andoid Auto
![2024-01-17 19 26 26](https://github.com/microg/GmsCore/assets/6882401/cecd49d1-c71d-4188-980d-d31ddb703681)

Not sure if this is the right place to report or ask questions, but I have this issue when trying to use Android auto, 
I have google maps installed and it's working totally fine on the phone, 

Google maps has rights to location at any time / background, same for microG and same for Android Auto
microG self check - everything checked except permission to draw over other apps.

Phone is P60 Pro,

**Comment by rickard-505** [comment]
Tried to all ALL permission in Google Maps (where the settings button is leading me) - but still cant pass this screen / get working Android Auto.

**Comment by curbengh** [comment]
microg doesn't support Android Auto natively, you need [aa4mg](https://github.com/sn-00-x/aa4mg) module.

**Comment by ale5000-git** [comment]
This is fixed by this: https://github.com/microg/GmsCore/commit/0dab96ff6ed08c38349c5d9611f73aa8e6dab962
The new version (not yet released) will contains the fix.
