### ISSUE TITLE
Huawei apparently presenting microG as if it's an official Huawei product

### ISSUE THREAD

**Issue by Sapiosenses** [microg/GmsCore#2157]
Someone just alerted me to this post on the Huawei forums.

Curious what @mar-v-in has to say about this. 

https://consumer.huawei.com/my/community/details/MicroG-2024-Update-your-Lighthouse-to-the-microG-Service/topicId_171840/

EDIT: 
They in fact admit it is from a "3rd party provider" in their FAQ but they also characterize it as an "upgrade" of another app on their app gallery "Lighthouse". Which is apparently also written by a 3rd-party.

They do not link to any of the official microG websites/pages.

https://consumer.huawei.com/my/community/details/FAQ-of-micro-GService-and-micro-GCompanion/topicId_166413/

**Comment by paolo-caroni** [comment]
This is a shame, it's not the first time that FOSS is deliberately "stolen", TiVo hardware for example.
Also I would not install their version, wich modification have made on the source code? How can be verified?
I think that there is all the motivations for a legal move.

**Comment by mar-v-in** [comment]
There is no stealing going on here. All the code is [published open source](https://github.com/DaVinci9196/GmsCore), code is [contributed back upstream](https://github.com/microg/GmsCore/pulls?q=is%3Apr+author%3ADaVinci9196+) bit by bit and I'm personally involved with the release process in AppGallery. However it's still considered a beta functionality, only available in some countries and for some devices through AppGallery.

**Comment by hmtheboy154** [comment]
> There is no stealing going on here. All the code is [published open source](https://github.com/DaVinci9196/GmsCore), code is [contributed back upstream](https://github.com/microg/GmsCore/pulls?q=is%3Apr+author%3ADaVinci9196+) bit by bit and I'm personally involved with the release process in AppGallery. However it's still considered a beta functionality to them, only available in some countries and for some devices through AppGallery.

I apology if this question is too personal  but does that mean @DaVinci9196 is a developer from Huawei or he's the team (maybe leader ?) behind the port for the AppGallery version that maybe not officially endorsed but allowed by Huawei ?

**Comment by mar-v-in** [comment]
To be precise: *I* am uploading the release to AppGallery, the file uploaded to AppGallery is exactly the -hw file also published here on GitHub.

There previously was an app called LightHouse in AppGallery that was a fork of microG. The changes of the fork is now merged back into upstream. For all I know, Huawei was not directly involved with the development of LightHouse, nor are they directly involved with development of microG now.

As I published it in AppGallery, as per the terms of AppGallery, Huawei is allowed to advertise microG to its users and as a feature of their phones at their discretion. I'm not involved with any of those.

**Comment by UnrealKaraulov** [comment]
> To be precise: I am uploading the release to AppGallery, the file uploaded to AppGallery is exactly the -hw file also published here on GitHub.
> 
> There previously was an app called LightHouse in AppGallery that was a fork of microG. The changes of the fork are now merged back into upstream. For all I know, Huawei was not directly involved with the development of LightHouse, nor are they directly involved with development of microG now.
> 
> As I published it in AppGallery, as per the terms of AppGallery, Huawei is allowed to advertise microG to its users and as a feature of their phones at their discretion. I'm not involved with any of those.

How to bypass your sanctions against Belarus and install microg for BY region from appgallery?
