### ISSUE TITLE
Wiki outdated: should compile with JDK 17.

### ISSUE THREAD

**Issue by Piervit** [microg/GmsCore#2177]
The wiki building page https://github.com/microg/GmsCore/wiki/Building says: 

` It currently works with Java 8, newer versions might cause exceptions.`

but in Java 8 I got issues while in Java 17, it compiles well. Moreover https://github.com/microg/GmsCore/blob/master/.github/workflows/build.yml uses java 17.

**Comment by ale5000-git** [comment]
This was correct with older version of Gradle, but now Java 17 is the correct one; the compiled app still run under Java 8.
I have changed the version in the wiki.

**Comment by Piervit** [comment]
Yes, I understand. 
Thanks for the update.
