### ISSUE TITLE
Hello.  When will a new HW version be released?  I hope it comes out globally and helps remove the WhatsApp message (you need the official app)

### ISSUE THREAD

**Issue by OREMOR305** [microg/GmsCore#2200]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mar-v-in** [comment]
It's up to Huawei to decide which devices in which countries can use signature spoofing. There's nothing we can do from here.
