### ISSUE TITLE
Signature spoofing not working HW version

### ISSUE THREAD

**Issue by cattlinggunz** [microg/GmsCore#2201]
The latest HW of microg doesn't work because it says signature spoofing is not enabled, my phone is a nova 9 emui 13 I have seen it work with emui 13.1 I have no idea what's wrong

**Comment by ale5000-git** [comment]
@cattlinggunz
It doesn't work under all devices, more info here: https://github.com/microg/GmsCore/issues/2141
Try also the LH version to see if it works.

@ildar 
The HW verison is the one specific fo Huawei, in that case it doesn't need to be in `/system/priv-app` but it doesn't work under all phones.

**Comment by cattlinggunz** [comment]
@ale5000-git sadly the lh version also does not work, I'll wait and see if get the 13.1 update eventually

**Comment by mar-v-in** [comment]
It's up to Huawei to decide which devices can use signature spoofing. There's nothing we can do from here.

**Comment by fatenjs** [comment]
any idea how to install microg in Samsung phones

**Comment by ale5000-git** [comment]
Unlock the bootloader, path for signature spoofing and flash a microG installer to have full features.

You can also install microG as user app but it will be limited especially if you can't get signature spoofing.
