### ISSUE TITLE
Gray out or remove "System grants signature spoofing permission" when unneeded

### ISSUE THREAD

**Issue by TinfoilSubmarine** [microg/GmsCore#2207]
**Is your feature request related to a problem? Please describe.**
With the new LineageOS patch supporting signature spoofing, I noticed that even though everything is working correctly, I have one check failing (System grants signature spoofing permission):
![Screenshot_20240226-132556_microG Services](https://github.com/microg/GmsCore/assets/19600707/d8a292e9-3fe2-48e3-82d6-ccf282500df3)

**Describe the solution you'd like**
Since this could be confusing for users since they are probably used to making sure that everything is checked here, this check could be de-emphasized, i.e. by graying it out, or even completely removing it.

**Comment by zelleb** [comment]
https://github.com/LineageOS/android_frameworks_base/commit/6b793fa98a40dd6c2d6eb02988161ed123439428

**Comment by ArchangeGabriel** [comment]
> What I know is that official LineageOS doesn't support signature spoofing (forks or unofficial ROM don't count).
> 
> Do you have any link for this?

It’s not like I told you about it [here](https://github.com/microg/GmsCore/pull/2188#issuecomment-1963018551) and you even answered me. :p

**Comment by ale5000-git** [comment]
> It’s not like I told you about it https://github.com/microg/GmsCore/pull/2188#issuecomment-1963018551 and you even answered me. :p

Well, I interpreted "major ROM" as generic and I didn't look yet at the link :D

**Comment by TinfoilSubmarine** [comment]
I should note that this is only reproducible if MicroG is installed as user app(s). When I install it into system by e.g. using a Magisk module, this box is checked.
