### ISSUE TITLE
[com.google.android.apps.maps] Google Maps not working anymore

### ISSUE THREAD

**Issue by Master0ne** [microg/GmsCore#2209]
**Affected app**
Name: Google Maps
Package id: com.google.android.apps.maps

**Describe the bug**
When trying to start the app it claims "Reinstall Maps - An error occurred during the installation of Maps. Please uninstall the app and then install it again."

**To Reproduce**
1. Install the latest version 11.116.0101 (1067392642)
2. Launch the app
3. Error is shown
4. Clicking on OK launches the app store

**Expected behavior**
Maps to start as usual.

**System**
Android Version: 13
Custom ROM: crDROID 9.10

**microG**
microG Core version: 0.3.0.233515
microG Self-Check results: All ticked

**Additional context**
Downgrading Google Maps to v11.103.0101 (1067237107) made it work again (there may be newer versions that still work, but that's the only version number that I could determine to be working)

**Comment by mar-v-in** [comment]
This is likely already fixed by 37dd2b59e4d14c75625a3b10c801115e08bcfbff. If you want you can try upgrading to the latest nightly from https://microg.org/dl/core-nightly.apk

**Comment by hannes386** [comment]
Thanks for sharing the nightly version, @mar-v-in! I'm running CalyxOS and I'm unable to install this version: "App not installed as package appears to be invalid". Do you might have a hint for me? Many thanks!

**Comment by mar-v-in** [comment]
@hannes386 Nightly cannot be installed on CalyxOS or /e/OS.

**Comment by Guarmanda** [comment]
I have another bug with the new version, many microg users also report it on Reddit: maps actually not load the Map anymore and we cannot find places anymore
