### ISSUE TITLE
Regularly appearing "microG Services keeps stopping" window

### ISSUE THREAD

**Issue by mks-h** [microg/GmsCore#2213]
**Describe the bug**
I keep getting "microG Services keeps stopping" window, even as I have the microG app open and fully working.
Today, I just installed microG on a relatively fresh LineageOS in Magisk using [microG Installer Revived][microg-installer-revived]. Between installing Lineage, Magisk, and microG, I only installed a few apps. 

**To Reproduce**
1. Install LineageOS 21
2. Install Magisk
3. Install [microG Installer Revived][microg-installer-revived]
4. Reboot
5. Try using your phone, you will be getting "microG Services keeps stopping" error regularly.

**Expected behavior**
No "microG Services keeps stopping" window appearing.

**System**
Android Version: 14
Custom ROM: LineageOS 21

**Additional context**
Yesterday, I had the same issue on the previously installed LineageOS 20 (Android 13) after updating the [microG Installer Revived][microg-installer-revived] Magisk module. I don't know which version of microG was used previously. The previous OS also had signature spoofing set up, while the current one doesn't yet.

[microg-installer-revived]: https://github.com/nift4/microg_installer_revived

**Comment by Wojtaz0w** [comment]
You have rooted phone, so please use an app such as logfox (on f-droid) to capture crash log. Otherwise your report is useless, as I can't reproduce despite also using a14 and microg magisk module

**Comment by mks-h** [comment]
Thanks, I was just wondering how to capture useful logs. I'll get back to it tomorrow, I think.

**Comment by ale5000-git** [comment]
This doesn't even require root: https://github.com/darshanparajuli/LogcatReader

**Comment by MillionsToOne** [comment]
Neither does Logfox

**Comment by mks-h** [comment]
The crashes stop if I give microG Servies app location permissions. I'm not sure why it didn't have them, and I don't remember denying them.

**Comment by ale5000-git** [comment]
You have missed the most important thing, we need to know the version of microG installed.
In the app list hold down the "microG settings" app icon and then press the info icon, you should find the version at the bottom of the page that appears.

**Comment by mks-h** [comment]
It is version 0.3.0.233515

**Comment by ale5000-git** [comment]
Now it should no longer creash even if the permission isn't granted.
