### ISSUE TITLE
No more sync for YouTube historic 

### ISSUE THREAD

**Issue by masnsen2nd** [microg/GmsCore#2217]
**Describe the bug**
I have no more sync between my YouTube watched videos and my YouTube history

**To Reproduce**
I could watch any YouTube video in revanced Extended. I have connected my account through mMicroG version 
0.2.27.231613. I noticed that no more added video to history or any other playlist like "to be watched later" or "favorite". 
Down issue of the bug is that YouTube is thinking I've not watched those videos and still recommanding me those same videos again and again in my feed. 
This behavior isn't there when using official YouTube Android app

**Expected behavior**
Syncing account playlists

**Screenshots**

**System**
Android Version: 14
Phone : Samsung Galaxy S23 plus 

**Additional context**

**Comment by Vavun** [comment]
Not a microG bug
https://github.com/ReVanced/revanced-patches/issues/2779
