### ISSUE TITLE
HMS setTag NullPointerException

### ISSUE THREAD

**Issue by RobotEmilio** [microg/GmsCore#2222]
**Describe the bug**
I'm opening this issue because in the app I work on, we're seeing a crash from users that has microg installed. The stack trace is this

> Fatal Exception: java.lang.NullPointerException: you should check tag,it can not be null.
>        at com.huawei.hms.common.internal.Preconditions.checkNotNull(Preconditions.java:2)
>        at com.huawei.hms.maps.model.Polyline.setTag(:2)
>        at org.microg.gms.maps.hms.model.PolylineImpl.setTag(Polyline.kt:149)
>        at com.google.android.gms.maps.model.internal.IPolylineDelegate$Stub.onTransact(IPolylineDelegate.java:399)
>        at org.microg.gms.maps.hms.model.PolylineImpl.onTransact(Polyline.kt:202)
>        at android.os.Binder.transact(Binder.java:921)
>        at com.google.android.gms.internal.maps.zza.zzc(com.google.android.gms:play-services-maps@@18.2.0:2)
>        at com.google.android.gms.internal.maps.zzah.zzz(com.google.android.gms:play-services-maps@@18.2.0:3)
>        at com.google.android.gms.maps.model.Polyline.setTag(com.google.android.gms:play-services-maps@@18.2.0:1)
>        at com.google.maps.android.compose.PolylineKt$Polyline$2.invoke(Polyline.kt:89)
>        at com.google.maps.android.compose.PolylineKt$Polyline$2.invoke(Polyline.kt:74)
>        at com.google.maps.android.compose.PolylineKt$Polyline-Ut8lOTo$$inlined$ComposeNode$1.invoke(Composables.kt:254)
>        at androidx.compose.runtime.changelist.Operation$InsertNodeFixup.execute(Operation.kt:476)
>        at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:307)
>        at androidx.compose.runtime.changelist.FixupList.executeAndFlushAllPendingFixups(FixupList.java:50)
>        at androidx.compose.runtime.changelist.Operation$InsertSlotsWithFixups.execute(Operation.kt:443)
>        at androidx.compose.runtime.changelist.Operations.executeAndFlushAllPendingOperations(Operations.kt:307)
>        at androidx.compose.runtime.changelist.ChangeList.executeAndFlushAllPendingChanges(ChangeList.kt:78)
>        at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:976)
>        at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005)
>        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1099)
>        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
>        at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(Composer.kt:3599)
>        at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633)
>        at androidx.compose.runtime.CompositionImpl.setContent(CompositionImpl.java:619)
>        at com.google.maps.android.compose.GoogleMapKt$GoogleMap$4.invokeSuspend(GoogleMap.kt:285)
>        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
>        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.android.kt:81)
>        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.android.kt:41)
>        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.android.kt:57)
>        at android.os.Handler.handleCallback(Handler.java:900)
>        at android.os.Handler.dispatchMessage(Handler.java:103)
>        at android.os.Looper.loop(Looper.java:219)
>        at android.app.ActivityThread.main(ActivityThread.java:8668)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

My thoughts is that, in Polyline.kt:setTag, the `unwrap` method is returning null and when trying to call `setTag`, Huawei's HMS does not allow for null values. Probably a null safe assignment there would solve the issue, but I don't have enough knowledge of this project to be sure.

**System**
This crash is happening in phones with Android 10, 11 and 12, and mostly in Xiaomi devices.

**Comment by bironader** [comment]
I have same issue on production for Huawei devices and xiaomi any updates ?
