### ISSUE TITLE
[com.viber.voip] Viber does not connect to Google Drive

### ISSUE THREAD

**Issue by emirvmendoza** [microg/GmsCore#2244]
**Affected app**
Name: Viber
Package id: com.viber.voip

**Describe the bug**
Viber does not connect to Google Drive.

**To Reproduce**
1. Open Viber
2. Tap More on botton-right
3. Tap Settings > Account > Viber backup
4. Tap settings below Not connected to Google Drive
5. Select account
6. Tap Backup now
7. Backing up will reach 50%
8. Select account again
9. Backing up will reach 50% again
10. Error syncing to Google Drive prompt

**Expected behavior**
Google Drive prompt (Allow Viber to access Google Drive) should show up, similar to [this](https://help.duo.com/s/article/5519?language=en_US)

**Screenshots**
![image](https://github.com/microg/GmsCore/assets/154249992/9cf3bb65-02f7-4fcb-a3c3-98d8fa6675d6)
![image](https://github.com/microg/GmsCore/assets/154249992/9703921c-591b-4ae7-9598-be85b38e593c)
![image](https://github.com/microg/GmsCore/assets/154249992/dc4aeed5-ebe3-48d1-95dd-b989340babf6)
![image](https://github.com/microg/GmsCore/assets/154249992/0ac92c80-4c40-4bf5-a6cb-abe1697d46d7)

**System**
Android Version: 9
Custom ROM: [e_vs986_usu-userdebug 9 PQEA.190801.002 eng.sfx-bo.20231223.124141 CUSTOM-release,dev-keys](https://xdaforums.com/t/todays-sec-patch-level-rom-unofficial-p-usu-non-usu-e-os-bye-google-hello-privacy.4142021/)

**microG**
microG Core version: 0.2.24.214816-12(e876375)-noen
microG Self-Check results: All ticked

**Additional context**
Extensive troubleshooting attempted on this thread, link to [first post](https://xdaforums.com/t/todays-sec-patch-level-rom-unofficial-p-usu-non-usu-e-os-bye-google-hello-privacy.4142021/post-89326293) in the series.

Both Viber and Google Drive installed from Play Store.

**Comment by Wojtaz0w** [comment]
Your version of microG is extremely outdated. Please update

**Comment by emirvmendoza** [comment]
Upgraded to [latest version for /e/ OS](https://gitlab.e.foundation/e/os/GmsCore/-/releases/e-v0.2.27.223616) using the following steps from 

1. Rename latest version ("play-services-core-withMapbox-withNearby-releaseStable.apk") to GmsCore.apk
2. Using ADB, push the renamed GmsCore.apk to /sdcard/
4. Using ADB, rename the GmsCore.apk in /system/priv-app/GmsCore/ to GmsCore_orig.apk
5. Using ADB, move /sdcard/GmsCore.apk to /system/priv-app/GmsCore/
6. Using ADB, change permission of the moved GmsCore.apk to 644
7. Reboot to recovery (TWRP) and clear dalvik-cache and cache
8. Reboot to system
9. Using ADB, push a second copy of the renamed GmsCore.apk to /sdcard/
10. Installed GmsCore.apk using the Package Installer (tapping on installer from Files)
11. Cleared data of microG Core and Google Drive
12. Granted permissions applicable from

**Comment by emirvmendoza** [comment]
> Upgraded to [latest version for /e/ OS](https://gitlab.e.foundation/e/os/GmsCore/-/releases/e-v0.2.27.223616) using the following steps from
> 
> 1. Rename latest version ("play-services-core-withMapbox-withNearby-releaseStable.apk") to GmsCore.apk
> 2. Using ADB, push the renamed GmsCore.apk to /sdcard/
> 3. Using ADB, rename the GmsCore.apk in /system/priv-app/GmsCore/ to GmsCore_orig.apk
> 4. Using ADB, move /sdcard/GmsCore.apk to /system/priv-app/GmsCore/
> 5. Using ADB, change permission of the moved GmsCore.apk to 644
> 6. Reboot to recovery (TWRP) and clear dalvik-cache and cache
> 7. Reboot to system
> 8. Using ADB, push a second copy of the renamed GmsCore.apk to /sdcard/
> 9. Installed GmsCore.apk using the Package Installer (tapping on installer from Files)
> 10. Cleared data of microG Core and Google Drive
> 11. Granted permissions applicable from

Accidentally closed, anyway:

11. Granted permissions applicable to microG Settings (except for signature spoofing, no such option from Settings > Apps > Permissions)
12. Added Google account to microG
13. Started Google Drive
14. Google Drive shows me the login page
15. Enter same Google account
16. Error: This account already exists in your device.

Steps 1 to 9 from [here](https://community.e.foundation/t/is-possible-to-upgrade-microg/46947/7) and [here](https://community.e.foundation/t/is-possible-to-upgrade-microg/46947/12)

**Comment by emirvmendoza** [comment]
After following post from steadfasterX on XDA: "have u checked the microg version after that? do not rename it to GmsCore_orig.**apk** as this will let Android still load it. rename it to GmsCore_orig.apk.disabled or so instead. atm its not clear which microg version is actually in place due to that"

This enabled signature spoofing.

1. Cleared dalvik-cache and cache again
2. Removed account from MicroG
3. Cleared data of MicroG Core
4. Cleared data of Google Drive app
5. Opened Google Drive app
6. Signed in to Google account
7. Enabled from Settings > Accounts > Google MicroG the option to "Allow apps to find accounts"
8. Closed Google Drive and Settings apps
9. Opened Viber > Settings > Accounts > Viber Backup
10. Tapped settings hyperlink
11. Account selector showed up
12. Selected Google account
13. Backed up to 50%
14. Cleared log
15. Error backing up from Google Drive showed up
16. Tapped violet back up now button again
17. Account selector showed up, or backing up to 50 percent (did not get exact sequence)
18. Error backing up from Google Drive showed up
19. Opened Google Drive app
20. After a long time loading, Google Drive opened normally
21. Without closing Google Drive app, moved back to Viber
22. Opened Viber > Settings > Accounts > Viber Backup
23. Tapped settings hyperlink
24. Account selector showed up
25. Selected Google account
26. Tapped violet back up now button
27. Nothing happened
28. Tapped violet back up now button again
29. Back up now button disappeared
30. Generated log: https://privatebin.at/?33ba30935ce1375a#DgurscgD1JwkHga4EuzuVwYYc2vLXR7kxTvRTw7z1XR
31. I then checked Play Integrity API Checker: Failed MEETS_DEVICE_INTEGRITY, Passed MEETS_BASIC_INTEGRITY

Battery drained from 17% to 9% during the process, but was plugged in via USB debugging the whole time. Battery optimization for Viber still disabled. MicroG version 0.2.27.223616-1 (4ec0d9f)

**Comment by emirvmendoza** [comment]
Given up.  Decided to cut my losses.
