### ISSUE TITLE
Cannot unlearn / update outdated network location

### ISSUE THREAD

**Issue by jejo86** [microg/GmsCore#2245]
**Describe the bug**
Almost a year ago I moved to a different city and I didn't change my router or the WiFi's SSID.

When inside, my phone still thinks I am at my former home. 

I disabled both WiFi and mobile network location services unchecking all options. I cleared both data and cache for the apps:
- Local NLP Backend
- microG Services

I had the settings disable for several weeks. Still every morning when turning on the phone, the first thing my phone does is locating me at the wrong direction, even though the network location settings are disabled.

I also tried overriding the wrong value, by enabling the setting again after around 2 weeks and standing outside on my balcony, where I temporarily get the correct location. But when no GPS and only network location is available (back inside) I am again repositioned to the former address I lived at, which is around 400 km away.

Where is the data stored, so I can delete / update it?

**Expected behavior**
When both the network locations' and GPS data is available, i.e. when I am standing on my balcony, I would expect the "location learning" (16e37cba) to eventually update the learned position.

**System**
Android Version: 13
Custom ROM: iodéOS 4.10-20240217-FP4

**Comment by ale5000-git** [comment]
New microG Services no longer support Local NLP Backend.

**Comment by LucasMZReal** [comment]
@ale5000-git Doesn't microG implement something similar to Local NLP?
Under my location settings, I see "Remember from GPS" as an option; Isn't that basically what Local NLP was?

Though I must say, I'm confused as to whether he's using the "stable" version or 0.3.
@jejo86 What version are you running, referring to microG?

**Comment by ale5000-git** [comment]
@LucasMZReal
Yes, it is similar but now everything is inside microG Services.

**Comment by jejo86** [comment]
I uninstalled _Local NLP Backend_, but that did not change anything. Apparently it was not removed automatically during an update of iodéOS.

The current version of the OS is using microG v0.3.0.233515. It is already fully integrated in iodéOS, so I have no control to install/uninstall or update it manually. At least not to my knowledge... I can only deactivate the app in the settings.

I don't suppose the position got uploaded to Mozilla and now my phone keeps downloading the data from their servers?!

Even if that were the case. It must be possible to update it, right?

Also, my phone is connected to probably several cel phone towers. Also, in my new home the SSIDs of my neighbors are different to my previous home. Why does my WiFi take precedence over all other information when evaluating the location, except actual GPS data?

I am going to keep WiFi off for a while to see whether in that case I do not get repositioned and the repositioning is really caused by the WiFi, which I am currently just assuming.

Is there any sensible way to debug this? Usually there is a huge amount of logs in catlog. Any hint for what I can search for?

**Comment by ale5000-git** [comment]
microG never upload position, but it is possible that in the past someone passed near your home with Mozilla Stumbler and uploaded it.
Also recently the Mozilla service became less precise but it don't make sense to fix it since it will be shutdown soon.

So to reset everything you should:
- Reset data (not just cache) of microG services (keep all Mozilla options inside microG disabled if it get wrong info for you)
- Update APGS data with SatStat: https://f-droid.org/it/packages/com.vonglasow.michael.satstat/
- Restart phone

**Comment by jejo86** [comment]
It appears to work now, thanks for the hints.

Now only if I enable "Fetch Wi-Fi-based location from Mozilla Location Service" I get located to my former address. So my SSID seems to have made it somehow to the Mozilla servers.

But since you mentioned that service is outdated anyways, and disabling that option now actually works, I guess my problem is solved.

I am going to observe the behavior for a while, but I feel confident enough to close the ticket.

Thanks for the support!
