### ISSUE TITLE
New strings with typos

### ISSUE THREAD

**Issue by LucasMZReal** [microg/GmsCore#2252]
Currently maintaining Portuguese (Brazil) as much as I can for microG (it was pretty much abandoned), and I noticed two semi-new strings that seem to have some slight typos:

1. https://hosted.weblate.org/translate/microg/play-services-location-core-strings/pt_BR/?checksum=0884f2bbe41b8e6d&sort_by=-priority,position

"Use location service; as part of this service, may collect location data periodically and use this data in an anonymous way to improve location accuracy and location-based services."

I'm not sure if this is indeed a typo, but it seems like it, "May" here looks out of place, I would expect "It may" or something like that. I'm actually unsure if this is correct or not. This string does sound a bit weirdly said overall anyway, it's still out of context for me.

3. https://hosted.weblate.org/translate/microg/play-services-location-core-strings/pt_BR/?checksum=922b526b3681b013&sort_by=-priority,position

"No,thanks"
Seems to missing a space after the comma, I translated according to this but I would expect this to be solved

---

Small issues, just wanted to track and make them aware if they're not; I see marvin contributes to German as well, so I would expect so :P

**Comment by mar-v-in** [comment]
Thanks, indeed those strings need to be updated, I'll try to fix them before next release.

**Comment by LucasMZReal** [comment]
Solved with https://github.com/microg/GmsCore/commit/bcb5f7cf7af87f8c3da7b9ab8af5eb49d4dc671a
