### ISSUE TITLE
[app.revanced.android.youtube] GmsCore rejects modded apps

### ISSUE THREAD

**Issue by REmerald** [microg/GmsCore#2261]
**Affected app**
Name: Youtube Revanced
Package id: app.revanced.android.youtube

**Describe the bug**
App crashes when trying to use my GmsCore.

**To Reproduce**
1. In Revanced Manager set the `GmsCore Support` patch value to `com.google`.
2. Patch the apk.
3. Install it.
4. Launch, it crashes after a second.

**Expected behavior**
No crash.

**Screenshots**
N/A

**System**
Android Version: 13
Custom ROM: LineageOS for MicroG 20, `20-20240315-microG-violet`

**microG**
microG Core version: `0.2.27.223616`
microG Self-Check results: All ticked, except `System has signature spoofing support` - "Your ROM has no native support ..." (but `System spoofs signature` - ticked)

**Additional context**
`Test SafetyNet attestation` fails: Bootloader is not locked.
Other info, such as logs, etc.: https://github.com/ReVanced/revanced-patches/issues/2904

**Comment by mar-v-in** [comment]
Revanced and patching with Revanced is not supported by upstream (neither by microG nor by YouTube). If the patched app doesn't work, but the original version does, it's an issue with the patcher, not with microG.
