### ISSUE TITLE
Support for other versions of emui 

### ISSUE THREAD

**Issue by searingsquid** [microg/GmsCore#2264]
I want to ask if you can add support for other versions of emui apart from emui 13.1

My device is a Huawei Y7a 
Android 10
Emui 10.1
I was able to log in however I can't do anything other than that And there are some features that aren't turned on and can't be turned on 
![Screenshot_20240327_193650](https://github.com/microg/GmsCore/assets/116381197/a1ed124f-a6e3-4938-ad54-0813d8ffe1d0)
![Screenshot_20240327_193546_com google android gms](https://github.com/microg/GmsCore/assets/116381197/2feddeed-ad40-4578-8f40-58b4fa11386c)
![Screenshot_20240327_193606_com android settings](https://github.com/microg/GmsCore/assets/116381197/29d1b145-abef-4827-b2ae-e1a42cc00d43)

**Comment by mar-v-in** [comment]
For technical reasons, we can't support operating systems that don't have the required feature (signature spoofing or differentiated signature). You need to request support for differentiated signature yo be ported to your device from Huawei, as they're producing the operating system.
