### ISSUE TITLE
Downloaded Gms core and can't launch it

### ISSUE THREAD

**Issue by KingAnge978** [microg/GmsCore#2265]
**Describe the bug**
I'm trying to download YouTube revanced apk and it needs GMScore so I downloaded apk but can't open it. I deleted the old revanced apps and everything. 

**To Reproduce**
1. Go to 'gms core apk'
2. Click on. 'update'
3. Error message

**Expected behavior**
App not installed as package conflicts with an existing package

**Screenshots**
![Screenshot_20240327_221300_Package installer](https://github.com/microg/GmsCore/assets/85597351/9a7117ec-b05e-4250-a393-453d0ab21219)

**System**
Android Version: 14
Custom ROM: One 6.0
Samsung Galaxy S23 Ultra 
**Additional context**
Trying to update versions for revanced. I also have twitch revanced downloaded so I don't know if it conflicts with that.

**Comment by marcdw1289** [comment]
What you need is the ReVanced version of microG, not this one.
I suggest you go to the ReVanced site and follow instructions from there.

**Comment by icynstant** [comment]
> What you need is the ReVanced version of microG, not this one.
> I suggest you go to the ReVanced site and follow instructions from there.
> 
> Also see #2261.

but why in manager it says "old"? I installed "new" micro g and deleted "old" and revanced ext youtube said micro g is not installed

**Comment by mar-v-in** [comment]
This is not a support venue for anything regarding ReVanced YouTube or ReVanced Manager. Go to their respective issue trackers or forums.

**Comment by icynstant** [comment]
> This is not a support venue for anything regarding ReVanced YouTube or ReVanced Manager. Go to their respective issue trackers or forums.

thank you, my bad
