### ISSUE TITLE
v3.1 on microg.org and F-droid repo?

### ISSUE THREAD

**Issue by Sapiosenses** [microg/GmsCore#2269]
GmsCore v0.3.1.240913 was released 4 days ago on Github.

But this release never made it to either the microg.org download page or the F-droid repo.

Can someone explain what is going on? Is it embargoed? Is there a problem with the web server?

I would like to make an official announcement in the microG group I run but I don't want to get flooded with complaints that people can't use F-droid to update, etc.

Related:
Can someone explain to me what the criteria is for a release to be flagged as "preview"? The last non-preview release was dated 2023-01-15. Was it because of the UNLP regressions?

Thanks much

**Comment by mar-v-in** [comment]
I was waiting to see if any major regression is reported before publishing on F-Droid. As this seems to not be the case, I'll push the latest release to the F-Droid repository today.

And yes, the reason for the preview flag is that we lack feature parity with the UnifiedNlp solution. In targeting to finally fix this with the next release.

**Comment by Wojtaz0w** [comment]
There is major regression - google maps are broken :(

**Comment by mar-v-in** [comment]
In 0.3.1? Google Maps app and apps using Google Maps API both work fine for me. I've seen you opened #2260 which I can't reproduce either and thus don't consider release blocking (if it only affects a minor section in settings and does not apply to all systems).

**Comment by Wojtaz0w** [comment]
> In 0.3.1? Google Maps app and apps using Google Maps API both work fine for me. I've seen you opened #2260 which I can't reproduce either and thus don't consider release blocking (if it only affects a minor section in settings and does not apply to all systems).

Hmmm. Regarding #2260, it could be be caused by microG-installer-revived. I will attempt to reinstall microG and will let you know of the results.

**Comment by mar-v-in** [comment]
Version 0.3.1 is now on F-Droid and 0.3.1 and 0.3.1-hw are linked from the website. It's still flagged as preview, for the reason explained above.
