### ISSUE TITLE
Error Google 400 with microG

### ISSUE THREAD

**Issue by emailtemptest53** [microg/GmsCore#2277]
microG services version 0.3.1.3.2490913 
What I installed, opened the app haven't touched anything about settings etc I just went to Add account > Sign in > wait a bit > Input my email > press Next it doesn't work it won't me go to next step inputting my password (I Keep pressing it still stuck image below and even wait couple of minutes still no hope)
![Screenshot_2024-03-31-01-17-16-67_4d4502106e9b52bcf4203a2f61fac539](https://github.com/microg/GmsCore/assets/165502194/ea6275fd-693c-4bd6-b92d-77d27e824efd)
But when I pressed this key on my keyboard screen (image shown)
![IMG_20240331_014023](https://github.com/microg/GmsCore/assets/165502194/e11928fa-361d-478e-8137-f5bf879f5fee)
This error given to me (image shown)
![Screenshot_2024-03-31-01-42-45-36_4d4502106e9b52bcf4203a2f61fac539](https://github.com/microg/GmsCore/assets/165502194/5b85e6fd-8756-44d7-9ca3-81a14c888849)
Tried many things
Reinstall, clear cache, clear data, restart my phone still the same error pls help me and I might missed something (I used old microG works before with Revanced app, but I reset my phone that's the reason why)

**Comment by Wojtaz0w** [comment]
Once again, incorrect repository. Please report the issue **with ReVanced's fork** there:

https://github.com/ReVanced/GmsCore

I kindly request that you  do not report bugs with **unofficial forks** on upstream repo. 
Have a blessed Easter, if you celebrate it.

**Comment by Wojtaz0w** [comment]
**If you are a Huawei user**, below you can find the fix. Please do a bit of research on your own, before bothering the creators of microG.
 https://github.com/ReVanced/GmsCore/issues/6#issuecomment-2020340735
