### ISSUE TITLE
License verification not working with iReal Pro on OnePlus 8T

### ISSUE THREAD

**Issue by deesnook** [microg/GmsCore#2278]
**Describe the bug**
I was stoked about the new license verification feature in v3.1.240913, so I immediately tried it. After updating, I installed iReal Pro through Aurora Store which I had previously bought on a different device using the regular Google Play Store. But alas, license verification on start of iReal Pro produces an error message so the app won't start. I'm not sure if this is a bug specifically relating to iReal Pro, so I put it in the generic category 

**To Reproduce**
1. Turn on Google Play Licensing in the microG settings (and Google Play Billing? I did both)
2. Log into Google account in Aurora Store
3. Install iReal Pro through Aurora Store
4. Start iReal Pro
5. See error: screenshot below

**Expected behavior**
microG handles the license verification request correctly and iReal Pro starts normally

**Screenshots**
![Screenshot_20240330-202424_iReal Pro](https://github.com/microg/GmsCore/assets/17967431/21cc6032-b2cf-433c-bcb9-1484787cd230)

**System**
Device: OnePlus 8T
Android Version: 14
Custom ROM: LineageOS for microG 21-20240319-microG-kebab
microG Services 0.3.1240913
microG Companion 0.3.140226
iReal Pro 2024.2

**Comment by ale5000-git** [comment]
Did you have updated microG Services **BEFORE** microG Companion otherwise it may not work?

**Comment by deesnook** [comment]
Thanks for the quick reply. Yes I did. And I just found out that it's just me who's stupid. I hadn't logged in to my Google Account in the microG settings (I was just logged in with Aurora Store). In that case it cannot work I guess..

Logged in, worked like a charm. Thanks a lot for implementing this feature, that was the only thing that was missing for me
