### ISSUE TITLE
[< v0.3.1.240913 Latest>] <This app bricks my phone>

### ISSUE THREAD

**Issue by tenshiism** [microg/GmsCore#2280]
**Affected app**
Name: micro g services
Package id: [e.g. com.whatsapp]

**Describe the bug**
after installing v0.3.1.240913 to install revanced youtube app per instructions, when connecting the phone to USB, the options to change the usb type (eg debugging, pictures, data etc) is all greyed out
operation

**To Reproduce**
>plug in usb
>adb devices on pc (nothing) 
> pull down notification bar 
>usb file transfer turned on (tap for more options)
>USB settings
>This whole screen is greyed out and "use usb for" cant be changed
I CANT GET FILES OFF MY PHONE ANY MORE

**Expected behavior**
>USB settings
>Use USB for 
Transferring files
USB tethering
etc

**Screenshots**

**System**
Android Version: [12]
Custom ROM: [no]

**microG**
microG Core version: [e.g. 0.2.13.203915]
microG Self-Check results: [e.g. All ticked]

**Additional context**

**Comment by Wojtaz0w** [comment]
THIS IS THE WRONG REPO
This repo is UPSTREAM microG! 
For problems with ReVanced, bother its creator.

**Comment by tenshiism** [comment]
Hi, respectfully. you are wrong.
This is the correct repo.
The problem started after installing this app. I was merely guided here by ReVanced.
There are no install instructions for this app either here on on ReVanced's site anyway. So could you provide a way to uninstall this app and revert all settings back to default, since it seems to persist with the problem even after uninstallation.

**Comment by Wojtaz0w** [comment]
The app which should be installed for ReVanced support is GMSCore from ReVanced's creator, and it is available there https://github.com/ReVanced/GmsCore

If you haven't installed using the above link, you have the incorrect version of microG installed, which should not be possible if you have Google Play Services (also known as GMS), because of it using the same package name as microG, that being com.google.android.gms , and having a different APK signature.

**Comment by Wojtaz0w** [comment]
If you have installed either the fork, or upstream microG, using regular APK installer (simply clicking on downloaded apk), the uninstallation process should be no different from a regular application.

**Comment by tenshiism** [comment]
How do i reinstall GMS? does this uninstall it? Is that way my phone can no longer change the connection method to the PC or be seen by ADB?

**Comment by Vavun** [comment]
@Wojtaz0w @mar-v-in Support please 
https://github.com/ReVanced/revanced-discussions/discussions/1035
