### ISSUE TITLE
FCM Feature API' Deprecation

### ISSUE THREAD

**Issue by piyushgarg** [microg/GmsCore#2281]
**Is your feature request related to a problem? Please describe.**
Firebase is going to deprecate FCM [API's](https://firebase.google.com/support/faq#fcm-23-deprecation)

**Additional context**
Will this impact the existing microg messaging?

**Comment by mar-v-in** [comment]
The official document only states deprecation of server-to-server APIs, that is APIs app developers use on their server to communicate to FCM. This is entirely out of our scope.

It might be that Google turns off some features on the client-to-server APIs at the same time. Unfortunately they don't do any deprecation notices or warnings about that as these APIs are not meant for consumption of third-parties - so we will only learn if something breaks at the time that it breaks. Experience from the past however shows, that Google tends to be very backwards compatible.
