### ISSUE TITLE
Please implement a "Do not show again" for the battery optimization warning at startup of Youtube Revanced

### ISSUE THREAD

**Issue by shaft17** [microg/GmsCore#2287]
Everytime I open Youtube Revanced, a popup from GMSCore pops up that an action is required, i.e. "Please disable battery optimization".

But fact is, at least in my case, Youtube Revanced works perfectly fine with GMSCore battery restricted. And I do NOT want it out of restriction, as it wakes up my device far too often.

So do me a favor and make a "Do not show this message again" for the people who know what they are doing.
Thank you very much!

**Comment by Wojtaz0w** [comment]
Wrong repo to report the issue to! 
Below is ReVanced's fork repo, which is what you have installed! You asked for a feature on UPSTREAM repo, not revanced's. On a side note, thst feature request has been denied by ReVanced developer.
https://github.com/ReVanced/GmsCore/

**Comment by shaft17** [comment]
Well ok, thanks for correcting me and thanks for the side note!
