### ISSUE TITLE
trick apps into thinking you've played an ad

### ISSUE THREAD

**Issue by 4rtemis-4rrow** [microg/GmsCore#2291]
Is your feature request related to a problem?

many games would give you rewards for watching ads, since the ads are provided by google play services, I was wondering if it'd be possible to report to the game that an ad has been played (even though it hasn't)

**Comment by Teh404Gal2** [comment]
That's a sure way to get microG sued

**Comment by 4rtemis-4rrow** [comment]
ok you make a good point ngl

I guess it could be possible for *someone* on the internet to provide a diff file wghch would add such a feature, you just have to patch the source code and build it ;)

**Comment by mar-v-in** [comment]
Ads do work even without Play Services. This is out of scope for microG. Use any existing ad blocker solution if you want to block ads.
