### ISSUE TITLE
Trouble Adding Google Account on MicroG Gmscore

### ISSUE THREAD

**Issue by AwkBoyy** [microg/GmsCore#2293]
**Problem Description**
As I've updated to the latest MicroG Gmscore version (app.revanced.android.gms-241017000), I'm encountering an issue when trying to add my Google account. Previously, on the older MicroG version, I had no trouble signing in. However, with the newest version, I'm consistently encountering the error message: "**There was a problem communicating with Google servers**." 
My device operates on a 'Pixel Experience' custom ROM. I'm unsure of the exact cause behind this. Any guidance on how to successfully add my account would be greatly appreciated.

**To Reproduce**
1. Open the newest microG Settings
2. Click on 'Google Accounts/Add Google Account'
3. Entering Google Account and Password
4. Showing error: ‘Sorry, There was a problem communicating with Google servers'

**Expected behavior**
Seamless addition of Google account on the latest MicroG Gmscore version.

**System**
Android Version: 13
Device: Xiaomi Redmi
Custom ROM: Pixel Experience

![IMG_20240403_000115](https://github.com/microg/GmsCore/assets/162299150/9237f697-ac33-4ca4-ba75-2392fefa0336)

**Comment by Vavun** [comment]
Wrong repo
https://github.com/ReVanced/GmsCore

**Comment by GivenMW** [comment]
Try removing the permission for google servers to see the devices name.
This setting is located in microG services where you choose to add account in  and it will take you to the next page
before you can click on add account, scroll down you will see an option that says "strip device name for authentication"
once you enable that it should work

it worked for me

**Comment by dud1337** [comment]
@GivenMW 's solution worked for me, after I also disabled "Authenticate with device registration."

**Comment by Maksim-Ilinskii** [comment]
Didn't work for me

**Comment by ale5000-git** [comment]
ReVanced microG is NOT microG.
