### ISSUE TITLE
telegram 

### ISSUE THREAD

**Issue by dimka40185** [microg/GmsCore#2298]
telegram with micro g does not work correctly, notifications come but without sound and banner, only the number on the telegram icon. The microg is configured correctly
![Screenshot_20240406_124339_com google android gms](https://github.com/microg/GmsCore/assets/67542372/710f26b4-71ed-416e-8ade-aebc2b02f33c)
![Screenshot_20240406_124335_com google android gms](https://github.com/microg/GmsCore/assets/67542372/15719d0f-dbbd-4305-ac66-27c7dfe8786b)
![Screenshot_20240406_124328_com google android gms](https://github.com/microg/GmsCore/assets/67542372/6335d5b9-5aad-4b93-949e-d9d8ef71c0ee)
![Screenshot_20240406_124323_com android settings](https://github.com/microg/GmsCore/assets/67542372/0121573f-9d12-48c4-b3b2-f730253fab8b)

**Comment by chpio** [comment]
How is this related to microg? Seems to me like telegram is not showing the notifications properly. Have you checked the telegram notification settings?

**Comment by dimka40185** [comment]
> How is this related to microg? Seems to me like telegram is not showing the notifications properly. Have you checked the telegram notification settings?

This is due to the Microg, as it does not wake up the telegram when a push notification is received.

**Comment by gcvl** [comment]
> Is due to the fact that Telegram does not show notifications if they are already dismissed
> 
> https://github.com/DrKLO/Telegram/blob/a906f12aaec2768969c77650a7e4b377baa6cf2a/TMessagesProj/src/main/java/org/telegram/messenger/NotificationsController.java#L3776-L3779
> 
> The problem is that microG does not forward `google.sent_time` to Telegram and so this variable is set to 0 causing the if to be always executed.

This has never been investigated so far, see #1986 .
Can you place a pull request and attempt a fix?

**Comment by Vavun** [comment]
@DaVinci9196 help please ?

> The problem is that microG does not forward `google.sent_time` to Telegram and so this variable is set to 0 causing the if to be always executed.

**Comment by matteobtt** [comment]
> This has never been investigated in nearly a decade, see #1986 . Can you place a pull request and attempt a fix?

@gcvl  Yes, #2344

**Comment by gcvl** [comment]
> > This has never been investigated in nearly a decade, see #1986 . Can you place a pull request and attempt a fix?
> 
> @gcvl Yes, #2344

Wow, grande Matteo!
