### ISSUE TITLE
Wild Rift Unknown Error -101 and Google Play Games Error

### ISSUE THREAD

**Issue by cihatozkannn** [microg/GmsCore#2302]
When I install Wild Rift and try to open it, I encounter "unknown error -101". I think I couldn't figure out how to fix this problem regarding the Google Play connection.

Similar to this, when I log into Google Play Games, I cannot open my Google Play Games account. When I go to the Settings section, it says "Some Settings could not be loaded. I am getting the error "Please try again."
![unnamed (1)](https://github.com/microg/GmsCore/assets/164739910/b43dc75c-b1ce-4fd6-a153-01817ebafaf1)
![unnamed](https://github.com/microg/GmsCore/assets/164739910/ae756f75-5ca6-4401-8380-6fb807874c58)

Device: Huawei Matepad 11.5
HarmonyOS 3.1.0.168

**Comment by cihatozkannn** [comment]
> it got fixed with [0.3.2.240913](https://github.com/microg/GmsCore/releases/tag/v0.3.2.240913)

I have a problem with the new version: I can download the game, but some sound files do not work. Some of the sound effects are missing, is that the case with you?

**Comment by cihatozkannn** [comment]
> [0.3.2.240913](https://github.com/microg/GmsCore/releases/tag/v0.3.2.240913) ile düzeltildi[](https://github.com/microg/GmsCore/releases/tag/v0.3.2.240913)

please can u help?

**Comment by egecelikci** [comment]
it seems it fixed itself after a Wild Rift update

**Comment by ale5000-git** [comment]
This problem should be fixed in microG v0.3.6.
You should update first microG Services and then microG Companion.
After that you should also enable Play Asset Delivery and Device Sync in microG settings.

If there is still something wrong, please report it.
