### ISSUE TITLE
[com.google.android.youtube] YouTube is not working

### ISSUE THREAD

**Issue by Andrew1397** [microg/GmsCore#2315]
**Affected app**
Name: YouTube
Package id: [com.google.android.youtube]

**Describe the bug**
When you open YouTube, it immediately closes with the message 
"Get Google Play services
YouTube won't run without Google Play services, which are missing from your device."

**To Reproduce**
Just open YouTube

**Screenshots**
![Screenshot_20240412-095148_crDroid Home](https://github.com/microg/GmsCore/assets/44724275/7af1eb5c-9e2b-4efc-a037-3f9e46619e55)

**System**
Android Version: 13
Custom ROM: CrDroid 9.8

**microG**
microG Core version: v0.3.1.240913
microG Self-Check results: 
![Screenshot_20240412-093659_microG Services](https://github.com/microg/GmsCore/assets/44724275/26a490c9-b1fd-43f7-80fc-d4d7881f027e)

**Additional context**
A similar problem with YouTube music, but without a message (closes immediately). Although Google Camera, Google Photos and Google Maps work fine.

**Comment by Wojtaz0w** [comment]
just switch to ReVanced. They use a fork of microG, which installs next to this one. Also it has adblocking, returned dislikes, etc. Go to revanced.app to download their manager. Here is documentation for it: https://github.com/revanced/revanced-manager/tree/main/docs

**Comment by cuynu** [comment]
works fine here

![Screenshot_20240413-113051_microG Services](https://github.com/microg/GmsCore/assets/90895715/b55fbec9-d942-47b4-8c39-02d139e2ceda)

![Screenshot_20240413-113034_YouTube](https://github.com/microg/GmsCore/assets/90895715/7584f755-07a3-4ba1-a704-4ea5bcfbda0b)

**Comment by Andrew1397** [comment]
Answer by Wojtaz0w
At the moment, I use both microGs to be able to use YouTube and Google Camera. But it would be good to run everything on one microG. So I wanted to know if it is possible and if it will work in the future? Could this be a problem on my end?

**Comment by Andrew1397** [comment]
Answer by [cuynu](https://github.com/cuynu)
What version of microG and YouTube are you using?

**Comment by cuynu** [comment]
> Answer by [cuynu](https://github.com/cuynu) What version of microG and YouTube are you using?

YouTube : 19.14.38
microG Services Core : 0.3.1.240913

**Comment by Andrew1397** [comment]
> > Answer by [cuynu](https://github.com/cuynu) What version of microG and YouTube are you using?
> 
> YouTube : 19.14.38 microG Services Core : 0.3.1.240913

Interesting
I still have "Get Google Play services..."
Did you just install and it worked?

**Comment by Wojtaz0w** [comment]
> Answer by [Wojtaz0w](https://github.com/Wojtaz0w)
> At the moment, I use both microGs to be able to use YouTube and Google Camera. But it would be good to run everything on one microG. So I wanted to know if it is possible and if it will work in the future? Could this be a problem on my end?

If your device is rooted, which I assume is true, since microG installation is very common with modules for KSU/Magisk, then you can install a magisk module installing ReVanced YT over normal YT. Please note that you need to be on a specific version of YT (19.11.38) to make the module work. Here you can find it along with instructions: https://t.me/rvx_lite/1648

**Comment by cuynu** [comment]
> > > Answer by [cuynu](https://github.com/cuynu) What version of microG and YouTube are you using?
> > 
> > 
> > YouTube : 19.14.38 microG Services Core : 0.3.1.240913
> 
> Interesting I still have "Get Google Play services..." Did you just install and it worked?

yes

**Comment by cuynu** [comment]
> > Answer by [Wojtaz0w](https://github.com/Wojtaz0w)
> > At the moment, I use both microGs to be able to use YouTube and Google Camera. But it would be good to run everything on one microG. So I wanted to know if it is possible and if it will work in the future? Could this be a problem on my end?
> 
> If your device is rooted, which I assume is true, since microG installation is very common with modules for KSU/Magisk, then you can install a magisk module installing ReVanced YT over normal YT. Please note that you need to be on a specific version of YT (19.11.38) to make the module work. Here you can find it along with instructions: https://t.me/rvx_lite/1648

this issue are completely unrelated to revanced, dont bring it in here

**Comment by Wojtaz0w** [comment]
> > > Answer by [Wojtaz0w](https://github.com/Wojtaz0w)
> > > At the moment, I use both microGs to be able to use YouTube and Google Camera. But it would be good to run everything on one microG. So I wanted to know if it is possible and if it will work in the future? Could this be a problem on my end?
> > 
> > If your device is rooted, which I assume is true, since microG installation is very common with modules for KSU/Magisk, then you can install a magisk module installing ReVanced YT over normal YT. Please note that you need to be on a specific version of YT (19.11.38) to make the module work. Here you can find it along with instructions: https://t.me/rvx_lite/1648
> 
> this issue are completely unrelated to revanced, dont bring it in here

I know, but I had similar problem and rvx module fixed it... but it might be just for me

**Comment by Andrew1397** [comment]
Sorry.
My fault.
With the help of the Lucky Patcher, I made the GmsCore a system application and now everything works. (Missed or couldn't find this step in the instructions)
But I wonder why some apps work even though GSMCORE is not a system app and some don't?

**Comment by Wojtaz0w** [comment]
Yeah, that is weird. I used to have the same issue quite some time ago, and now it just doesn't happen at all.

**Comment by Andrew1397** [comment]
Understandably
Thank you all for your help

**Comment by oSumAtrIX** [comment]
The issue is caused by GmsCore being installed incorrectly. Google apps expect GmsCore to be installed under priv-app (where System apps are apparently installed).
