### ISSUE TITLE
Message box for app push notification is barely readable

### ISSUE THREAD

**Issue by rfc2119** [microg/GmsCore#2335]
**Describe the bug**
This is a minor bug. On GmsCore 0.3.1 when configuring push notifications, the confrimation message box that allows/denies an application from receiving push notifications is barely unreadable. More specifically, the width of the message box is too low. The height seems ok

**To Reproduce**
1. Activate Google device registration
2. In "Cloud messageing", click on the three dots on the top right. Click on "confirm new apps"
3. Activate Google cloud messaging
4. Wait for a device to register or open one that register itself on startup. You will see the confirmation message box

**Expected behavior**
The width of the message box should be reasonable

**Screenshots**
N/A

**System**
Android Version: 12
Custom ROM: crDroid 9.9

**Comment by Wojtaz0w** [comment]
I have already reported on this issue!
Check open issues before opening a duplicate!
