### ISSUE TITLE
[app.revanced.android.youtube] In-car app crashes as soon as it is opened

### ISSUE THREAD

**Issue by galeondx** [microg/GmsCore#2349]
**Affected app**
Name: [ReVenced]
Package id: [app.revanced.android.youtube]

1.Install GmsCore v0.3.1.4.240913
2.Install ReVanced youtube
3.Stop battery optimization
4.login GmsCore
5.open Revenced
.....Crashing
It crashes as soon as it is opened
If there is no login to GMSCORE or it is not installed, Revencore will function normally (just without an account to log in).

Android Version: [10]

**microG**
microG Core version: [[v0.3.1.240913]
[Log_2024-05-02_00-24-16.txt](https://github.com/microg/GmsCore/files/15179721/Log_2024-05-02_00-24-16.txt)

**Comment by mar-v-in** [comment]
ReVanced is not supported here. Search on their GitHub page to find the right location to report any issues: https://github.com/ReVanced
