### ISSUE TITLE
APK Build

### ISSUE THREAD

**Issue by dimka40185** [microg/GmsCore#2350]
greetings, dear developers, could you collect releases more often in the software? or make automatic builds in Actions. There is no way to build the apk yourself, because of Huawei's signature. Need files for Huawei -hw
![Снимок экрана 2024-05-02 070323](https://github.com/microg/GmsCore/assets/67542372/1556817e-e7a9-4997-ad4c-6e71360aaa36)

**Comment by gcvl** [comment]
I second this: some usable Github's artifacts or an up-to-date core-nightly.apk (the current one is stuck at 0.3.0 thus older than the latest official release) would be great for testing.

**Comment by Benjamin-Loison** [comment]
@dimka40185 What is the reason why you closed this issue?
