### ISSUE TITLE
Cannot sync with business account

### ISSUE THREAD

**Issue by GuyCheung** [microg/GmsCore#2351]
**Describe the bug**
The microg service is working with google account normally, both Chrome, Youtebe, Gmail apps can login via it, but once I change to  my business google account, cannot work then.

**To Reproduce**
1. Go to like Gmail
2. Click on switch account (or add new account)
3. Select (or login) the business account
4. Gmail is always loading, show "Getting your messages"

**Expected behavior**
Business account can work as the normal google account

**System**
Custom ROM: Harmoney OS 4.2.0.208

**Additional context**
I can find the sync up error in the account management.
It shows "Sync is currently experiencing problems, it will be back shortly" sometimes, and may be sync correct time by time as well.

**Comment by fynngodau** [comment]
This seems to be a duplicate of https://github.com/microg/GmsCore/issues/896. We are working on a fix in #2296.

**Comment by GuyCheung** [comment]
Noted with thanks! Then i think can close this one.
