### ISSUE TITLE
0.3.2 and "custom location server endpoints"

### ISSUE THREAD

**Issue by Sapiosenses** [microg/GmsCore#2377]
I assume these must be "MLS/Ichnaea style" servers/endpoints, yes? (Something which I don't think exists yet?)

Or can one use it with OpenCellID, Google, Apple network location services and so on?

**Comment by mar-v-in** [comment]
The endpoint needs to provide the same `/v1/geolocate` API that MLS and Google use. This means using the Google endpoint with an appropriate API key there becomes is a viable option, or any other server that either is based on Mozilla's Ichnaea or uses a compatible API like the one mentioned in https://github.com/microg/GmsCore/issues/2237#issuecomment-2169193229
