### ISSUE TITLE
Wild rift Sound Effect problem

### ISSUE THREAD

**Issue by cihatozkannn** [microg/GmsCore#2380]
Some sound effects do not work. (There was no such problem when playing with the Gbox application.)
I use the latest version microg.
Devices: Huawei matepad 11.5

**Comment by AndoniH11** [comment]
Hey @cihatozkannn !

Did you find the solution for this issue?

**Comment by ale5000-git** [comment]
Is it possible that the game download sound effects at runtime and microG doesn't yet support it.
There is already a PR to implement this: #2506

**Comment by marbens-arch** [comment]
> Some sound effects do not work. (There was no such problem when playing with the Gbox application.) I use the latest version microg. Devices: Huawei matepad 11.5

Latest preview or stable?

**Comment by ale5000-git** [comment]
This problem should be fixed in microG v0.3.6.
You should update first microG Services and then microG Companion.
After that you should also enable Play Asset Delivery and Device Sync in microG settings.

If there is still something wrong, please report it.
