### ISSUE TITLE
Release type (vending, hw) descriptions

### ISSUE THREAD

**Issue by HaleTom** [microg/GmsCore#2392]
I've seen 4 different versions, with and without vending and hw in their names.

Is there a description somewhere of the differences and how to choose the appropriate one?

**Comment by mar-v-in** [comment]
- `com.android.vending` is microG Companion, previously known as FakeStore.
- `com.google.android.gms` is microG Service main app.
- versions ending in `-hw` are meant to be used on supported Huawei devices with their vendor OS. Don't use them when not on a Huawei device.

**Comment by RJK01-darkside** [comment]
This inquiry may not match the context of this question. Will the deprecation of safety net attestation and offivial use of play integrity api adversely impact microg hw?

**Comment by mar-v-in** [comment]
It's not matching at all the context of this question. Next time if you have a new questions, please don't ask it in closed and unrelated requests.

Huawei devices did not pass SafetyNet checks and they won't fully pass Play Integrity checks either, so there's no big change here.

**Comment by RJK01-darkside** [comment]
Sorry thanks for the clarification.
The concern I had was this policy.

https://www.androidauthority.com/play-integrity-upgrades-3505270/

Thanks
Rjk
