### ISSUE TITLE
[com.flightaware.android.liveFlightTracker] Satellite map crashes

### ISSUE THREAD

**Issue by xxxxme** [microg/GmsCore#2408]
**Affected app**
Name: FlightAware
Package id: com.flightaware.android.liveFlightTracker

**Describe the bug**
When opening the satellite map, the screen goes white and the app returns to the previous screen.

**To Reproduce**
1. Click either the "All" or "Airports" tab.
2. Search for an airport (ex: O'Hare ) or click a previously searched one.
3. Click the map icon in the upper right of the screen.
4. The screen turns white and the app returns to the previous tab.

**Expected behavior**
A map with the selected airport highlighted and tracked flights shown should open.

**System**
Android Version: 13
Custom ROM: LineageOS 20 (Feb 9, 2024 update) 

**microG**
microG Core version: 0.2.29.233013
microG Self-Check results: All ticked

**Additional context**
Tested with FlightAware versions 5.9.0 - 5.11.1.
[flightaware logs-2024-06-16-13-45-51.zip](https://github.com/user-attachments/files/15859414/flightaware.logs-2024-06-16-13-45-51.zip)

**Comment by ale5000-git** [comment]
@xxxxme
Hi,
it is unlikely that a report of such old version of microG will be helpful.
If possible update microG to v0.3.2.240913.

Beside that, your issue doesn't seems like a bug but a wrong installation.
This is usally what happen when you place the microG apk in the system partition without placing also the extracted libraries.

**Comment by xxxxme** [comment]
@ale5000-git
Thanks, I didn't realise I had such an old version installed. Updated to 3.2.240913 and rebooted. The same issue happens. As for installing it wrong, I flashed the zip with Magisk. I don't know how else I'd do it.

**Comment by ale5000-git** [comment]
I cannot be completely sure but it is possible that the issue is with the zip flashed with Magisk.
Have you tried to report the issue to the creator of the zip?

**Comment by xxxxme** [comment]
I will do so. However, it's nift4's microG Installer Revived (recommended in the readme of FakeGApps fork by whew-inc (recommended in the Signature Spoofing section of the MicroG/GMSCore wiki)) so I thought it should work.

I do have all boxes ticked in the Self-Check, but I had to turn on background location and receive SMS using the Uses Permissions tab of App Manager: tapping them in the Self-Check neither turns them on nor requests permission and I don't see a way to turn them on in the OS. Might this be related?
Is there a Telegram channel or another troubleshooting method that's preferred to here?

**Comment by ale5000-git** [comment]
> I will do so. However, it's nift4's microG Installer Revived (recommended in the readme of FakeGApps fork by whew-inc (recommended in the Signature Spoofing section of the MicroG/GMSCore wiki)) so I thought it should work.
> 
> I do have all boxes ticked in the Self-Check, but I had to turn on background location and receive SMS using the Uses Permissions tab of App Manager: tapping them in the Self-Check neither turns them on nor requests permission and I don't see a way to turn them on in the OS. Might this be related?

@xxxxme
It is possible that the installer doesn't correctly install the extracted libraries.
This isn't related to signature spoofing and the Self-Check cannot detect this problem.
The issue of permissions is separate.
Please try to open a ticket on the repo of nift4's microG Installer Revived.

> Is there a Telegram channel or another troubleshooting method that's preferred to here?

There are groups, but to be clear they aren't official.

**Comment by ale5000-git** [comment]
> > Please try to open a ticket on the repo of nift4's microG Installer Revived.
> 
> Honestly he's been very busy and kind of overwhelmed these days, which is why I suggested asking elsewhere.
> 
> But yeah, that works too.

I don't have time to verify but it may be a bug in the installer.
