### ISSUE TITLE
[com.riotgames.league.wildrift] IN-APP SOUND EFFECTS ISSUE

### ISSUE THREAD

**Issue by cihatozkannn** [microg/GmsCore#2410]
**Affected app**
Name: Wild Rift
Package id: https://play.google.com/store/apps/details?id=com.riotgames.league.wildrift&hl=en

**Describe the bug**
While using the application, some sound effects are missing during the game. During the game, I downloaded the loading screen without any problems, but some sound effects are missing. For example; Menu music, lack of narrator voice, skill effects.

**Expected behavior**
I think it's causing a problem while parsing the apk. I think it is related to Microg because there is no problem when I play the game with another application (Gbox).

![unnamed](https://github.com/microg/GmsCore/assets/164739910/faa49195-9cf7-430e-b7de-99e5af20b759)

There is a problem in the part of the screenshot where I left a photo. When I first install this game, the screen I see appears and it skips the screen from 0% without loading, and the screen that should appear only in the installation appears every time I enter the game and skips directly from 0% without loading. Problemin bu olduğunu düşünüyorum.

**System**
Device: Huawei Matepad 11.5 8G (BTK-W09)
Android Version:  HarmonyOS 3.1.0
Custom ROM: Stock Rom

**microG**
microG Core version: v0.3.2.240913 
microG Self-Check results: All ticked

**Additional context**

**Comment by Gaprush** [comment]
I have the same problem i have tried connecting with riot and so far no solution came from it

**Comment by flame-0** [comment]
#2302 #2380, fixed in [v0.3.6.244735](https://github.com/microg/GmsCore/releases/tag/v0.3.6.244735)

**Comment by ale5000-git** [comment]
This problem should be fixed in microG v0.3.6.
You should update first microG Services and then microG Companion.
After that you should also enable Play Asset Delivery and Device Sync in microG settings.

If there is still something wrong, please report it.
