### ISSUE TITLE
[com.att.android.tfa] <oasa telematics app crashes>

### ISSUE THREAD

**Issue by tsitsos** [microg/GmsCore#2413]
**Affected app**
Name: [oasa telematics]
Package id: [com.att.android.tfa]

**Describe the bug**
The app crashes when the user is trying to get information on a specific bus stop

**To Reproduce**
1. Go to bus locations
2. Click on any bus line number
3. Click on STOPS
4. Click on any stop
5. App crashes or sometimes goes back to initial screen

**Expected behavior**
List of bus lines and their arriving time should appear on screen

**Screenshots**

**System**
Android Version: 14
Custom ROM: Lineage 21

**microG**
microG Core version: [v0.3.2.240913]
microG Self-Check results: [e.g. All ticked]

**Additional context**
Same behavior occurs when selecting a stop either from the map (bus location) or from "Nearby Stops"

**Comment by mar-v-in** [comment]
Fixed #2421
