### ISSUE TITLE
关于中国手机安卓12的安装

### ISSUE THREAD

**Issue by fyhbauyg** [microg/GmsCore#2417]
我在尝试安装micoGgms时遇到了这个错误INSTALL_FAILED_DUPLICATE_PERMISSION: Package com.google.android.gms attempting to redeclare permission com.google.android.googleapps.permission.GOOGLE_AUTH.writely already owned by com.google.android.gsf
我试过刷入unlock cn gms的magisk模块，很遗憾毫无效果，希望开发者可以协助我解决这个问题。
我的手机已经获得内核级根权限了。
型号oppo a92s
内核4.14.168

**Comment by fyhbauyg** [comment]
我对编程技术以及对于除中文以为的语言一窍不通，如果维基已经有解决办法了请不要责怪我。

**Comment by mar-v-in** [comment]
Your system has Google's `com.google.android.gsf` package installed (typically called Google Services Framework). microG is not expected to work if parts of original Google services are installed.

**Comment by fyhbauyg** [comment]
> 你设法删除它了吗？如果有，如何？我卸载了 gsf，但在尝试安装 microg 时遇到相同的错误

no
