### ISSUE TITLE
Commits can be squashed with Weblate

### ISSUE THREAD

**Issue by lucasmz-dev** [microg/GmsCore#2474]
**Is your feature request related to a problem? Please describe.**
Weblate's commits can be quite spammy in the Git history.

**Describe the solution you'd like**
There's a plugin (at least I found it on translate.codeberg.org) that you can set up that squashes certain commits into one and rebases. (I think rebasing is another setting) (e.g. from creator or component, or language...) Per-language probably makes sense here

**Describe alternatives you've considered**

**Additional context**

**Comment by QSkill** [comment]
I think you're talking about this:
https://docs.weblate.org/en/latest/admin/addons.html#squash-git-commits
