### ISSUE TITLE
allow custom ichnaea endpoint paths

### ISSUE THREAD

**Issue by joelkoen** [microg/GmsCore#2478]
**Is your feature request related to a problem? Please describe.**

There are quite a few microG users sending requests to `/v1/geolocate/v1/geolocate` as they expect the location server field to be a complete URL.

**Describe the solution you'd like**

For simplicity, it might be better to just allow users to specify a custom path. This also makes the option easier to understand.

**Describe alternatives you've considered**

You could automatically strip `/v1/geolocate` if the user includes it when configuring.

**Comment by mar-v-in** [comment]
If we allow a custom path, we'd need to allow specify a second custom path for submission once we add support for that and require users to enter both.

Also the `/v1/geolocate` encodes the version and protocol. If we'd allow arbitrary URLs, once there exist different variants of geolocate protocols, some users likely would put a URL suitable for another protocol, resulting in similar or even more severe issues (e.g. invalid or incomplete data submissions that look valid on the server side).

However I understand your point. We already have text there saying that the `/v1/geolocate` part is appended, but I guess some people don't read. I'll add that if the path ends in `/v1/geolocate`, that will be stripped from the URL.

**Comment by joelkoen** [comment]
There also seem to be a few people appending /v2/geosubmit... that should probably stripped too.

**Comment by mar-v-in** [comment]
`/v1/geolocate/` is now (on master) automatically stripped if entered. Also the 0.3.3 release will include a online service selector that features BeaconDB, so users don't need to enter it manually anymore.
