### ISSUE TITLE
Possiblity of adding nightly build artifacts to GitHub Actions

### ISSUE THREAD

**Issue by videoman614** [microg/GmsCore#2489]
From #1974 

> Although it is called nightly build it isn't automated, it is built manually by mar-v-in from time to time.

Please add nightly apk build artifacts to the current GitHub Actions that autoruns after each master branch commit and/or pending pull requests.

This allows for users interested in testing and troubleshooting new fixes and features to be able to try them ahead of the version release.

**Comment by CoelacanthusHex** [comment]
Uploading the sign private key to GitHub may impact security since some ROMs do the signature spoof when microG is signed by @mar-v-in.

**Comment by ale5000-git** [comment]
Maybe it is possible to auto-generate an unsigned debug build, so user can still try it; at the cost of losing the app data.

**Comment by videoman614** [comment]
> Uploading the sign private key to GitHub may impact security since some ROMs do the signature spoof when microG is signed by @mar-v-in.

Ah, didn't know this. Seems like this isn't feasible.

**Comment by Benjamin-Loison** [comment]
@CoelacanthusHex
@mar-v-in

What about using [a self-hosted runner](https://docs.github.com/en/actions/concepts/runners/self-hosted-runners) having the private key? This runner would be running on open-source software ([actions/runner](https://github.com/actions/runner) for instance) on a server (either cloud (different from GitHub, OVH for instance) if don't want to trust GitHub runners, or physically owned server if not trusting cloud).

Related to #2484 and #2350.

Personal notes: [Benjamin_Loison/Google_maps/issues/5#issuecomment-12677556](https://codeberg.org/Benjamin_Loison/Google_maps/issues/5#issuecomment-12677556)

**Comment by mar-v-in** [comment]
Even when it is a GitHub private runner, GitHub effectively decides what to build and could abuse this power. Given the vibe coding and Copilot integration happening at Microsoft/GitHub these days, I don't trust them to not make a mess and allow third parties to run arbitrary code on a private runner...

**Comment by Benjamin-Loison** [comment]
@mar-v-in I understand your concern (I don't like Microsoft/GitHub either). I guess that thanks to verifying cryptographic commit signature we can avoid GitHub pushing arbitrary code to the runner. If you think that we can't even trust [actions/runner](https://github.com/actions/runner) (that I understand too), then there are open-source alternatives like [gitea/act_runner](https://gitea.com/gitea/act_runner) and [forgejo/runner](https://code.forgejo.org/forgejo/runner) using respectively Gitea and Forgejo (or GitLab), I suspect GitHub not legally allowing other runners than theirs. If not trusting such alternative runners, then we could build the app without runners to ensure the infrastructure code. If you want I can investigate or/and implement the way you prefer.
