### ISSUE TITLE
The GSF for self-examination is not checked, what needs to be installed?

### ISSUE THREAD

**Issue by Index-LibrorumProhibitorum** [microg/GmsCore#2492]
Attempting to install Google Service Framework has been unsuccessful, previously it was successful
![Screenshot_2024-08-17-15-19-42-474_com google android gms](https://github.com/user-attachments/assets/9ae1a379-33d1-4c57-bcff-2ed9ff3281d9)

**Comment by ale5000-git** [comment]
You need Services Framework Proxy here: https://microg.org/download.html

**Comment by Index-LibrorumProhibitorum** [comment]
> You need Services Framework Proxy here: https://microg.org/download.html

Thank you very much, the issue has been resolved

**Comment by leisurefire** [comment]
For HUAWEI phones, you cannot install Play Store, Contact Sync or backup directly. So most likely you won't need it for most functionality.

**Comment by ale5000-git** [comment]
@leisurefire
If you just install `microG Services` alone nothing will work, you need also `microG Companion` (this replace Play Store).
In addition some old apps also need `microG Services Framework Proxy`.

**Comment by gohanko** [comment]
> [@leisurefire](https://github.com/leisurefire) If you just install `microG Services` alone nothing will work, you need also `microG Companion` (this replace Play Store). In addition some old apps also need `microG Services Framework Proxy`.

So apparently the new version of LineageOS v22.1 don't work with GSF. I'm trying to fix an issue with WhatsApp not letting me logging in, not sure if GSF is the issue.
