### ISSUE TITLE
[Huawei MatePad 11.5] App not in Huawei launcher. (but in nova launcher, ONLY settings are shown. Companion is installed too.)

### ISSUE THREAD

**Issue by enessmr** [microg/GmsCore#2512]
**Describe the bug**
Not in Launcher. (2 apps.)

**To Reproduce**

**Expected behavior**
After install, 2 apps are shown. (No bootloader unlocked!)

**Screenshots**
![Screenshot_20240826_154858_com android settings](https://github.com/user-attachments/assets/bc56cfe1-c983-4708-a31b-ac6b5dfc358d)
![Screenshot_20240826_154856_com android settings](https://github.com/user-attachments/assets/ed954708-3f3d-4bff-9fc0-59d69634de13)

**System**
Android Version: 12.0 (HarmonyOS 3.1.0.172)
Custom ROM: no custom rom huawei stock

**Additional context**
Nothing

**Comment by enessmr** [comment]
This applies same for the store app

**Comment by enessmr** [comment]
It's installed Correctly. All the checks are ✅'ed.

**Comment by ale5000-git** [comment]
I'm not sure why you are expecting this; there isn't any graphical interface to display.
microG is only meant to be used by other apps.

microG Services have a launcher icon to display its own options, microG Companion doesn't have any launcher icon.
So the correct behaviour is to have only 1 icon.

**Comment by enessmr** [comment]
SOLVED! Using Links and Shortcut maker WORKS!

**Comment by ale5000-git** [comment]
Even if you manage to create a shortcut for microG Companion, it will still open microG Services settings so it is completely useless.
