### ISSUE TITLE
Signing key

### ISSUE THREAD

**Issue by oSumAtrIX** [microg/GmsCore#2540]
Release assets are GPG signed by you. Is there any key server I can pull your public key from? If so, this should be documented somewhere, ideally under the MicroG domain.

**Comment by mar-v-in** [comment]
The signing key pgp@microg.org / 22F796D6E62E6625A0BCEFEA7F979A66F3E08422 should now be available on [keys.openpgp.org](https://keys.openpgp.org/search?q=pgp@microg.org) and via WKD.
