### ISSUE TITLE
APK couldn't be installed - Solved, my misuse

### ISSUE THREAD

**Issue by hunhun010164** [microg/GmsCore#2543]
Update on Sep. 20th. My misuse. Can be installed when open them via embedded file explorer. Problem solved.

******************************************************************************************************************

**Describe the bug**
APK couldn't be installed

**To Reproduce**
1. Download from your official website (https://microg.org/download.html) and download stable version to my pc.
2. Copy these 3 apks to mobile phone
3. Click com.google.android.gms-223616054.apk to install it.
4. See error "Sorry, no application available".

**Expected behavior**
Successfully install the apk.

**Screenshots**
![2](https://github.com/user-attachments/assets/3ca98e48-bcf2-498b-9058-e610739315db)
.

**System**
Android Version: 13
Custom ROM: dido OS 12.0
![1](https://github.com/user-attachments/assets/7f6648a1-5e73-45e9-b9d6-a95191c6ff81)

**Additional context**
Gbox works. But I want to use yours to replace Gbox.
My phone can install all the other apks except yours. I don't know why. Please help me. Thanks.

**Comment by lucasmz-dev** [comment]
Try the AOSP file picker 

This app exposes it https://play.google.com/store/apps/details?id=com.marc.files

**Comment by hunhun010164** [comment]
> Try the AOSP file picker
> 
> This app exposes it https://play.google.com/store/apps/details?id=com.marc.files

It seems to be just a file explorer. Or I didn't realize that it has more functions to help? Could you please give me more instructions? Thanks.

**Comment by lucasmz-dev** [comment]
It's just that that error is really weird to me that it feels like it comes from the file manager you're using and it literally doesn't seem to mean anything so...

**Comment by hunhun010164** [comment]
> It's just that that error is really weird to me that it feels like it comes from the file manager you're using and it literally doesn't seem to mean anything so...
> 
> If the default android stuff said anything it could be more revealing

That is ES file explorer, APKs can be installed from this app. So I don't think it's the problem of this file explorer. Do you need any more info? I'll try my best to provide it to you. Thanks

**Comment by ILoveOpenSourceApplications** [comment]
There's a small chance that the issue could be due to ES File Explorer. Found this oneplus community [post](https://community.oneplus.com/thread/1144532). Please try the same again with another file manager and see if the issue persists.

**Comment by ale5000-git** [comment]
@hunhun010164
From a graphical interface you cannot see why it really fail.

But you can install it from adb, example:
`adb install -g ./com.google.android.gms-240913004.apk`
The apk file must be on the pc and the phone must be connected to the PC with adb enabled.

When installed in this way if it fail you see the real reason and you can fix it.

**Comment by hunhun010164** [comment]
> There's a small chance that the issue could be due to ES File Explorer. Found this oneplus community [post](https://community.oneplus.com/thread/1144532). Please try the same again with another file manager and see if the issue persists.

Yes, you are right. My misuse. Can be installed when open them via embedded file explorer. Problem solved. Thank you

**Comment by lucasmz-dev** [comment]
Close the issue
