### ISSUE TITLE
[ch.publibike.app] Crash when tapping on some map markers.

### ISSUE THREAD

**Issue by maltherd** [microg/GmsCore#2558]
**Affected app**
Name: Publibike
Package id: ch.publibike.app

**Describe the bug**
The app has a map of all stations. When clicking on a station marker, the app is supposed to show a screen with info on the bikes available at that station. Instead, the app crashes immediately.
This might be similar to https://github.com/microg/GmsCore/issues/1149.

**To Reproduce**
1. Start Publibike app
2. Ensure you select the "Map" tab (bottom left)
3. Zoom enought to see individual station markers instead of compound markers (those with numbers like "100+")
4. Click on any station marker that isn't a compound marker.
5. The app crashes.

**Expected behavior**
The app shows a screen with info on the bikes available at the selected station.

**Screenshots**
![image](https://github.com/user-attachments/assets/55e33c5c-7a93-47b6-acc4-b478591341dd)
Map screen example. When clicking on the markers with bike icons, the app crashes.

**System**
Android Version: 13
Custom ROM: /e/OS 2.3-t-20240816426372-stable-FP4

**microG**
microG Core version: 0.3.2.240913-22 (43f9740)
microG Self-Check results: All-ticked

**Additional context**

**Comment by fynngodau** [comment]
Thanks for the report. I provided a fix in #2567.
