### ISSUE TITLE
App login error

### ISSUE THREAD

**Issue by EnderNon** [microg/GmsCore#2562]
**Describe the bug**
I'm stuck in a loop for trying to log in. First time I login, it looms successful, but then the account is not actually showing in MicroG. I try again and it tells me it's already registered. Same issue as #1403. Couldn't find a fix. Surprisingly I don't encounter such an issue when using the GMSCore for Revanced.

**To Reproduce**
- Install MicroG Core
- Sign in once (sign in successful, device contacting google servers for info, then account doesn't appear in microg)
- Sign in again (when entering the email address for Google, "device already registered")

**Expected behavior**
Sign in should be successful first time.

**Screenshots**
![Screenshot_20240928-000814_microG Services Core](https://github.com/user-attachments/assets/9c22d4d1-e8e4-4934-97f0-a7c77e7c571d)

**System**
LineageOS without GApps
LOS v21 (Android 14)
Xiaomi Mi 11 Pro

**Additional context**

**Comment by ale5000-git** [comment]
Because it is the latest currently set as stable, you have to go [here](https://microg.org/download.html), then select the drop-down menu and select 0.3.3 (the latest currently)

**Comment by ale5000-git** [comment]
This is also fine but remember that if you use your own compiled version you cannot update it from F-Droid.
