### ISSUE TITLE
System network location provider does not report locations

### ISSUE THREAD

**Issue by mar-v-in** [microg/GmsCore#2564]
In v0.3.3.240913, the system network location provider would not return network locations even if bound by the system. This breaks network location in apps that only use the system network location provider and not the Google fused location provider, so this mostly affects free software apps.

**Comment by CoelacanthusHex** [comment]
It may be better to release 0.3.3.1 to include this fix since it breaks most free software.

**Comment by ale5000-git** [comment]
@mar-v-in
Isn't possible to create a branch starting at the commit [52a08ba](https://github.com/microg/GmsCore/commit/52a08bad9da51915c196a8d56a451dfc07824695) (the commit of the 0.3.3 release) and then merge only the location fix in that branch?
So you can create a tag from that branch and you can avoid the commits added after the release.

**Comment by ale5000-git** [comment]
@mar-v-in
Does the latest commit fix "network location requests staying active infinitely"?

**Comment by sconim** [comment]
> @mar-v-in Does the latest commit fix "network location requests staying active infinitely"?

Which latest commit?

**Comment by sconim** [comment]
@mar-v-in Any timeline as far as.possibly releasing the 0.3.3.1?

**Comment by ale5000-git** [comment]
@sconim
The commit `511afe8`, the commit date is last week but it was pushed today.

**Comment by lucasmz-dev** [comment]
If it would be possible/not hard to do a last pull from Weblate right before next release, even if it's a bugfix release, I'd help our work tremendously, I have no easy way of checking easily how things look in-app. Building so far hasn't worked for me and I have no idea how to change the package names. I ended up having to use things like Lucky Patcher on a new release (CalyxOS hasn't launched 0.3.3 because of this bug) which really wasn't ideal. Updates to microG are months apart, so it's complicated to get an overall pic.

**Comment by Atemu** [comment]
Hi, it's been a month, could a bugfix release be made for this?

**Comment by ale5000-git** [comment]
> I'm mostly done with that and I can backport the relevant parts to 0.3.3 to create a 0.3.3.1 version afterwards - and/or provide a nightly based on then-current master.

@mar-v-in
Please mark the new release as stable on F-Droid, there shouldn't no longer be big issues.
If it isn't marked we will continue to receive reports for v0.2.27, that it is just a waste of time.

**Comment by lucasmz-dev** [comment]
It *really is* time to get out of 0.2.27, microG has gotten amazing improvements since then and defaulting to 0.2.27 makes microG no justice, when I was using 0.2.27 it was a pretty bad exp.

**Comment by lucasmz-dev** [comment]
https://gitlab.com/CalyxOS/calyxos/-/issues/2722
Calyx sometimes bundles newer commits of microG not yet in release, but they've been waiting for this; it'd be nice to know if this is fixed in those newer commits or if there's still some more work to be done

**Comment by Atemu** [comment]
A new release is out which supposedly fixes this: https://github.com/microg/GmsCore/releases/tag/v0.3.4.240913

Thank you to everyone involved :)
