### ISSUE TITLE
Location crashing

### ISSUE THREAD

**Issue by FinGu** [microg/GmsCore#2575]
**Describe the bug**
Whenever i try to use an app with location inbuilt it fails

**To Reproduce**
Open google maps and see GMS crash

**Expected behavior**
It working

**Screenshots**
![Screenshot_20241009-221913](https://github.com/user-attachments/assets/7ac977c3-3840-4fc7-ab26-adf3c1eadc44)
![Screenshot (10 10](https://github.com/user-attachments/assets/673cb01e-deb4-4e31-987b-106c9f279b0c)

**System**
Android Version: 14
Custom ROM: None, Pixel 9 pro
MicroG Version: 0.3.3.240913

**Additional context**
0-09 21:51:53.170  1173  7991 W ActivityManager: Permission Denial: getCurrentUser() from pid=15031, uid=10292 requires android.permission.INTERACT_ACROSS_USERS
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil: Failure to get location mode via API, falling back to settings
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil: java.lang.SecurityException: Permission Denial: getCurrentUser() from pid=15031, uid=10292 requires android.permission.INTERACT_ACROSS_USERS
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at com.android.server.am.UserController.checkGetCurrentUserPermissions(UserController.java:2879)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at com.android.server.am.UserController.getCurrentUserIdChecked(UserController.java:2900)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at com.android.server.am.ActivityManagerService.getCurrentUserId(ActivityManagerService.java:17779)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at android.app.ActivityManager.getCurrentUser(ActivityManager.java:5025)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at com.android.server.wifi.util.WifiPermissionsWrapper.getCurrentUser(WifiPermissionsWrapper.java:35)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at com.android.server.wifi.util.WifiPermissionsUtil.isLocationModeEnabled(WifiPermissionsUtil.java:782)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at com.android.server.wifi.util.WifiPermissionsUtil.enforceCanAccessScanResultsForWifiScanner(WifiPermissionsUtil.java:651)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at com.android.server.wifi.scanner.WifiScanningServiceImpl.enforcePermission(WifiScanningServiceImpl.java:624)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at com.android.server.wifi.scanner.WifiScanningServiceImpl.startScan(WifiScanningServiceImpl.java:385)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at android.net.wifi.IWifiScanner$Stub.onTransact(IWifiScanner.java:288)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at android.os.Binder.execTransactInternal(Binder.java:1500)
10-09 21:51:53.170  1173  7991 E WifiPermissionsUtil:   at android.os.Binder.execTransact(Binder.java:1444)
10-09 21:51:53.171 15031 15045 D NetworkLocation: Not yet implemented: onFailure -4 Not authorized
10-09 21:51:53.180 15031 15058 D NetworkLocation: Schedule low-power scan in 9985ms
10-09 21:51:53.184 15031 15031 E SQLiteLog: (1) no such column: alt in "SELECT lat, lon, acc, alt, alt_acc, time, prec FROM cells WHERE mcc = ? AND mnc = ? AND type = ? AND lac = ? AND cid = ? AND psc = ?"
10-09 21:51:53.188 15031 15031 E AndroidRuntime: FATAL EXCEPTION: main
10-09 21:51:53.188 15031 15031 E AndroidRuntime: Process: com.google.android.gms, PID: 15031
10-09 21:51:53.188 15031 15031 E AndroidRuntime: android.database.sqlite.SQLiteException: no such column: alt (code 1 SQLITE_ERROR): , while compiling: SELECT lat, lon, acc, alt, alt_acc, time, prec FROM cells WHERE mcc = ? AND mnc = ? AND type = ? AND lac = ? AND cid = ? AND psc = ?
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.-$$Nest$smnativePrepareStatement(Unknown Source:0)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection$PreparedStatementCache.createStatement(SQLiteConnection.java:1562)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatementLI(SQLiteConnection.java:1098)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1126)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:686)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:614)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1818)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1650)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1507)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1692)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.LocationDatabase.query(LocationDatabase.kt:44)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.LocationDatabase.getCellLocation(LocationDatabase.kt:47)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.NetworkLocationService$queryCellLocationFromDatabase$2.invoke(NetworkLocationService.kt:303)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.NetworkLocationService$queryCellLocationFromDatabase$2.invoke(NetworkLocationService.kt:303)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.NetworkLocationService.queryLocationFromRetriever(NetworkLocationService.kt:315)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.NetworkLocationService.queryCellLocationFromDatabase(NetworkLocationService.kt:303)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.NetworkLocationService.queryCellLocation(NetworkLocationService.kt:421)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.NetworkLocationService.access$queryCellLocation(NetworkLocationService.kt:39)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.NetworkLocationService$onCellDetailsAvailable$3.invokeSuspend(NetworkLocationService.kt:472)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.NetworkLocationService.onCellDetailsAvailable(NetworkLocationService.kt:471)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at org.microg.gms.location.network.cell.CellDetailsSource$startScan$1.onCellInfo(CellDetailsSource.kt:31)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.telephony.TelephonyManager$4.lambda$onCellInfo$0(TelephonyManager.java:7146)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.telephony.TelephonyManager$4$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:959)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:232)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:317)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8592)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
10-09 21:51:53.188 15031 15031 E AndroidRuntime:        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@aa92237, Dispatchers.Main.immediate]
10-09 21:51:53.191 15031 15031 I Process : Sending signal. PID: 15031 SIG: 9
10-09 21:51:53.215  1173  1363 I ServiceWatcher: [network] disconnected from 10292/com.google.android.gms/org.microg.gms.location.provider.NetworkLocationProviderService@2
10-09 21:51:53.217  1173  8884 I ActivityManager: Process com.google.android.gms (pid 15031) has died: vis BTOP
10-09 21:51:53.217   813   813 I Zygote  : Process 15031 exited due to signal 9 (Killed)
10-09 21:51:53.217  1173  1363 I ServiceWatcher: [GeocoderProxy] disconnected from 10292/com.google.android.gms/org.microg.gms.location.provider.GeocodeProviderService@2
10-09 21:51:53.217   863   863 D usf_sensor_hal: rotation vector: Enter Activate. Enable = 0.
10-09 21:51:53.217  1173  1388 I libprocessgroup: Removed cgroup /sys/fs/cgroup/uid_10292/pid_15031
10-09 21:51:53.217  1173  1363 W LocationManagerService: system location request with no attribution tag
10-09 21:51:53.217  1173  1363 W LocationManagerService: java.lang.IllegalArgumentException
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.server.location.LocationManagerService.registerLocationListener(LocationManagerService.java:813)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1579)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.location.gnss.GnssOverlayLocationProvider.onSetRequest(GnssOverlayLocationProvider.java:119)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at android.location.provider.LocationProviderBase$Service.setRequest(LocationProviderBase.java:331)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.server.location.provider.proxy.ProxyLocationProvider.lambda$onSetRequest$0(ProxyLocationProvider.java:184)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.server.location.provider.proxy.ProxyLocationProvider.$r8$lambda$7VMdFID5UKJaFx-7qHYncL9kLJk(ProxyLocationProvider.java:0)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.server.location.provider.proxy.ProxyLocationProvider$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.server.servicewatcher.ServiceWatcherImpl$MyServiceConnection.runOnBinder(ServiceWatcherImpl.java:257)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.server.servicewatcher.ServiceWatcherImpl.lambda$runOnBinder$0(ServiceWatcherImpl.java:126)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.server.servicewatcher.ServiceWatcherImpl.$r8$lambda$GCGDYqQZRK7jCQUNZnY8QjXgR2Y(ServiceWatcherImpl.java:0)
10-09 21:51:53.217  1173  1363 W LocationManagerService:        at com.android.server.servicewatcher.ServiceWatcherImpl$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)

**Comment by FinGu** [comment]
> jesus christ, remove v3.3 from releases and fdroid already. such a mess. took me 3 days to make location work again and be able to revert to previous microg..

how did you fix it?

**Comment by FinGu** [comment]
unfortunately that version just doesn't open for me for some reason, thanks anyways

**Comment by mar-v-in** [comment]
Which version of microG did you use before upgrading to 0.3.3 that led to this crash?

**Comment by FinGu** [comment]
Yup, seems like reinstalling the rom and using an older version of the Installer fixed it for me. I updated it later to the latest and no issues. Thanks y'all.
