### ISSUE TITLE
Are Huawei App Store programs officially released by us?

### ISSUE THREAD

**Issue by yzyz5840** [microg/GmsCore#2609]
发现华为应用更新了版本。是不是官方发布的哦？

**Comment by yzyz5840** [comment]
Are Huawei App Store programs officially released by us?

**Comment by modelsun** [comment]
> 发现华为应用更新了版本。是不是官方发布的哦？

What is the version number?  
Never thought the app store would have this app。

**Comment by ChihyuenWang** [comment]
> > 发现华为应用更新了版本。是不是官方发布的哦？
> 
> What is the version number? Never thought the app store would have this app。

The latest version of microG Services on Huawei AppGallery is 0.3.2.240923-zh.
As of now, it looks like it's already 2 versions behind.

**Comment by ale5000-git** [comment]
@yzyz5840
In the past, when it was not called microG, it was not official, but now it has been officially released by [mar-v-in](https://github.com/mar-v-in).
Look here: #2157
