### ISSUE TITLE
[enhancement] [feature request] Implementation of "Integrity Check API"

### ISSUE THREAD

**Issue by KlausStoertebeker** [microg/GmsCore#2611]
**Is your feature request related to a problem? Please describe.**
I have some important apps which rely on the play integrity checks, for example my "CamAPS FX" app to control my insuline pump and displaying values of my continious glucose measuring system. As I couldn't get the app run under the alternative operating system "iodéOS" (which uses microg-services) I contacted the developers of the app "CamAPS FX" and they told me that they use the google play integrity checks to ensure that the app was installed from the original Google Play Store without modification and that my smartphone (in my case a "Fairphone 5") isn't rooted or has an unlocked bootloader.

After intensive search in the internet I came to the conclusion that my enhancement/feature request "**Implementation of "Integrity Check API"**" is a general issue and that there are a lot of topics/issues demanding/requesting the implementation - but I fornd no solution.

Although I saw the issue [#2050](https://github.com/microg/GmsCore/issues/2050) "Binding to the service in the play store failed . This is due to having an old play store version installed on the device", I'm not sure which status this issue has (sorry, I'm not familiar with github and moving issues...).

**Describe the solution you'd like**
Implementation of "Integrity Check API"

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by KlausStoertebeker** [comment]
Additional information:
I used the app "[Play Integrity API Checker](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck)" and it gives me the following result without executing further tests:

"**Error getting token from Google**

Binding to the service in the Play Store has failed.

This can be due to having an old Play Store version on the device."

**Comment by KlausStoertebeker** [comment]
Will this issue be solved by the pull request [#2599](https://github.com/microg/GmsCore/pull/2599) "Added Vending IntegrityService" and when will it be available to my "iodéOS"? (I know: silly question - but I really need it to migrate completly to my new smartphone...)

**Comment by fynngodau** [comment]
Play Integrity is a major topic that's generally really hard to work on; I've personally spent a week on it to little avail in the past. However, #2599 seems to be in a working state, which is quite impressive. While we cannot provide an ETA, I would personally assume it to land in an official microG release in the next few months.

We have no influence over when your custom OS will include this version in one of its releases.

**Comment by KlausStoertebeker** [comment]
Hi fynngodau,

thanks for information. Then I hope that it will be available in the (near) future and will close this issue.
Thanks for your work :-)

**Comment by marbens-arch** [comment]
> Play Integrity is a major topic that's generally really hard to work on; I've personally spent a week on it to little avail in the past. However, #2599 seems to be in a working state, which is quite impressive. While we cannot provide an ETA, I would personally assume it to land in an official microG release in the next few months.
> 
> We have no influence over when your custom OS will include this version in one of its releases.

It's expected by [December 8, 2024](https://github.com/microg/GmsCore/milestone/26). It is likely that it will be postponed by a few days, though (like what happened with 0.3.4).

**Comment by ale5000-git** [comment]
This is already implemented in #2599 and it will be avaiable in the version 0.3.6 of microG.

**Comment by marbens-arch** [comment]
> Integrity check failed on the latest version, any help on this? (I'm running an `-hw` build on EMUI 14 if that helps) ![Image](https://github.com/user-attachments/assets/9e24c60b-0210-495d-9ff6-cf588ac9280f)

Note that while it is implemented, there is no ugarantee it will pass. This does help with some applications like TextNow, which let's you through even if integrity fails, as long as it's there.

**Comment by ale5000-git** [comment]
microG just add support for the new API, whether it pass or not still depends from the ROM (if it doesn't pass, many times it can be fixed by specific Magisk modules but unfortunately on Huawei since you cannot unlock bootloader you can't use Magisk).

**Comment by maxant69** [comment]
> microG just add support for the new API, whether it pass or not still depends from the ROM (if it doesn't pass, many times it can be fixed by specific Magisk modules but unfortunately on Huawei since you cannot unlock bootloader you can't use Magisk).

So it depends on Huawei side? The only news is that with 0.3.6  now Play Integrity API Check app works (even if test fails).

**Comment by rollingmoai** [comment]
Play integrity now passes basic integrity. I wonder what changed 🤔

![Image](https://github.com/user-attachments/assets/90aa82ed-09c4-4ed0-a0ee-22d40f818a5a)

**Comment by KlausStoertebeker** [comment]
*hm*

Then I think I misunderstood the purpose of implementing the “Integrity Check API.”

I thought that implementing it would result in the app “[Play Integrity API Checker](https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck),” for example, reporting a completely positive integrity check...

Unfortunately, this implementation doesn't help me at all. As I've read in various online articles, the test checks whether the operating system installed on the smartphone has been certified as secure by Google.

And since Google only certifies its own operating system and refuses to certify other operating systems, I consider the current implementation pointless. This means that I have to root secure operating systems such as iodéOS, GrapheneOS, or LineageOS in order to pass a complete integrity check with Magisk and its modules. And rooting is known to lead to other undesirable side effects, because many banking apps then refuse to work – no matter how good Magisk's “hiding” mode may be...

What a shame...

**Comment by KlausStoertebeker** [comment]
Addendum:
My last comment was NOT intended to discredit or disparage the work of the programmers!
The result they have achieved so far seems to have been a challenge and, above all, a great achievement, and I am very grateful for that!
Unfortunately, it is just not what I had hoped for.
Please keep up the good work...
