### ISSUE TITLE
How can I find the google's login verification code on my phone?

### ISSUE THREAD

**Issue by modelsun** [microg/GmsCore#2614]
ı can not find the code.

The phone's os is harmonyOS 4.2.

![Screenshot_20241109_062709](https://github.com/user-attachments/assets/7a1e6215-ebb4-45c0-9a76-08224b58fda2)

**Comment by modelsun** [comment]
> ı can not find the code.
> 
> The phone's os is harmonyOS 4.2.
> 
> ![Screenshot_20241109_052403_com microsoft emmx](https://private-user-images.githubusercontent.com/77215718/384540726-973d5d49-ba4b-40d7-87de-347c6c9c18cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMDUwODksIm5iZiI6MTczMTEwNDc4OSwicGF0aCI6Ii83NzIxNTcxOC8zODQ1NDA3MjYtOTczZDVkNDktYmE0Yi00MGQ3LTg3ZGUtMzQ3YzZjOWMxOGNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDIyMjYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1NjA5N2ZlZjc3MTMxYjY4Mjg5MWUxOTM3NDBkMTljZjliYWM0OTRmMTUwN2NmZWYyZTI0MmIxMjgxNmQ5MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YmxBk624AI3jPOVxz13UgOsyV_Fwex3JVrElLhi8Op8)

**Comment by freechelmi** [comment]
AFAIK this is not supported by MicroG so kind of loop hole

**Comment by modelsun** [comment]
well，thanks。

**Comment by ale5000-git** [comment]
It is just not supported currently, this doesn't mean that it will never be supported.
