### ISSUE TITLE
microg gsfproxy repo receives no attention

### ISSUE THREAD

**Issue by david79111** [microg/GmsCore#2623]
although microg gsfproxy repo is not marked as public archive the issues in that repo receive no attention at all.

If that repo is dead you should mark it as public archive or update the read.me

**Comment by ale5000-git** [comment]
@david79111
It is used only by old apps, so it is still useful but not in all cases.
Also for GSF proxy there isn't any problem with signature checks, so you can also compile and sign yourself.

**Comment by Lost-Entrepreneur439** [comment]
> @david79111 It is used only by old apps, so it is still useful but not in all cases. Also for GSF proxy there isn't any problem with signature checks, so you can also compile and sign yourself.

It's currently broken on Android 15, fyi.

**Comment by david79111** [comment]
> > @david79111 It is used only by old apps, so it is still useful but not in all cases. Also for GSF proxy there isn't any problem with signature checks, so you can also compile and sign yourself.
> 
> It's currently broken on Android 15, fyi.

Well thanks for the info. I've already opened an issue about missing android 15 support on gsfproxy repo
https://github.com/microg/GsfProxy/issues/21#issue-2586277766
but since nobody answers issues in that repo I opened this issue here.

**Comment by ale5000-git** [comment]
The latest officially released version doesn't contains all the fixes in GIT, could someone try if there is still the problem with the versino compiled by me? https://github.com/micro5k/microg-unofficial-installer/raw/refs/heads/main/zip-content/origin/priv-app/GsfProxy.apk

**Comment by david79111** [comment]
yes it works on my android 15 device

**Comment by dimka40185** [comment]
> https://github.com/micro5k/microg-unofficial-installer/raw/refs/heads/main/zip-content/origin/priv-app/GsfProxy.apk

Unfortunately, this file is not downloading, could you please upload it again?

**Comment by ale5000-git** [comment]
I have renamed it, but it is still present: https://github.com/micro5k/microg-unofficial-installer/raw/refs/heads/main/zip-content/origin/priv-app/GsfProxyA5K.apk
