### ISSUE TITLE
Will there be no more special versions for Huawei after Release v0.3.4?

### ISSUE THREAD

**Issue by ChihyuenWang** [microg/GmsCore#2624]
I noticed that the latest release [v0.3.4.240913](https://github.com/microg/GmsCore/releases/tag/v0.3.4.240913), does not include a version with the "-hw" suffix specifically for Huawei users anymore.
Does this mean that Huawei users can now use the general version directly?

**Comment by dimka40185** [comment]
I am also very interested in this question, dear  @mar-v-in, please answer

**Comment by mar-v-in** [comment]
There won't be a 0.3.4-hw for Huawei (as it is effectively the same as 0.3.3-hw), but starting 0.3.5 there will be -hw builds again.

You can't use the non-hw builds on Huawei devices (and that likely will never be possible). The suggested way to install on Huawei devices is via AppGallery, where you will automatically get updates relevant to you.

**Comment by michael1900** [comment]
I had the same question! Thanks!
Hope will be a new -hw soon...
