### ISSUE TITLE
update 0.3.4.240913 from 0.3.3.240913-hw can't run youtube

### ISSUE THREAD

**Issue by PauLmaX668** [microg/GmsCore#2626]
**Describe the bug**
update 0.3.4.240913 from 0.3.3.240913-hw can't run youtube!
my phone is Huawei p50 pro 888 4G cpu
harmony os 4.2
![Screenshot_20241115_234706_com google android youtube](https://github.com/user-attachments/assets/12849b48-ec62-4146-a334-b95bb7523cbd)

**Comment by ale5000-git** [comment]
This is obvious, the version 0.3.4 isn't for Huawei so it will never works.
For Huawei you have ot use 0.3.3-hw and update to 0.3.5-hw when it will be released.

**Comment by PauLmaX668** [comment]
just wait 3.5,thanks

**Comment by ale5000-git** [comment]
On Huawei you can't never use the normal build because it lacks signature spoofing, this is why you have to use the hw builds otherwise apps will not recognize it.
