### ISSUE TITLE
[240913008 ] Latest Package is too old???

### ISSUE THREAD

**Issue by kindkains** [microg/GmsCore#2628]
Just downloaded the newest release and when I wanna install it, I get this error:

INSTALL_FAILED_VERSION_DOWNGRADE: Downgrade detected: Update version code 240913008 is older than current 244433029

**Comment by ale5000-git** [comment]
Probably what you installed before wasn't an official version.

**Comment by mar-v-in** [comment]
Either you installed an unofficial version of microG from a third-party source or you have regular play services installed (244433029 is referring to Play Services version 24.44.33 for Android 12 + arm64)
