### ISSUE TITLE
Wiki pull request

### ISSUE THREAD

**Issue by adaschma** [microg/GmsCore#2629]
I added in-app-updates to the table in implementation status. You can pull it from https://github.com/adaschma/GmsCore-wiki.git (branch: docu-in-app-updates).

I couldn't find your preferred way to make pull requests for the wiki (as github sadly doesn't support this natively).

**Comment by ale5000-git** [comment]
Can't Wiki be edited directly without pull requests?

**Comment by adaschma** [comment]
> Can't wiki be edited directly without pull requests?

According to the github docs: [only repository collaborators can edit a public repository's wiki by default](https://docs.github.com/en/communities/documenting-your-project-with-wikis/changing-access-permissions-for-wikis) and I don't see an edit button:
![image](https://github.com/user-attachments/assets/c43d9c6b-93b1-48ea-854e-049533913a60)

So I'm afraid I can't edit it directly.

**Comment by ale5000-git** [comment]
In the past it wasn't like this but it is possible that it was changed to avoid the spammers.
I will look at it when I have some time.

**Comment by adaschma** [comment]
> In the past it wasn't like this but it is possible that it was changed to avoid the spammers. I will look at it when I have some time.

Thanks. If it is easier just to copy my change into the wiki, I'm fine with that, too. I don't care about getting the attribution to the change.

**Comment by ale5000-git** [comment]
I have updated it, thanks,

**Comment by adaschma** [comment]
Thanks,
