### ISSUE TITLE
0.3.6

### ISSUE THREAD

**Issue by michael1900** [microg/GmsCore#2630]
I read about 0.3.6 version on reddit. My question is: there are some possibilities that this version will support also Google Pay?

**Comment by ale5000-git** [comment]
The latest version is 0.3.4 so everything else isn't true.

There is only a [milestone for 0.3.6](https://github.com/microg/GmsCore/milestone/26) that declare the fixes/improvements that will be included in that version but there isn't any 0.3.6 at this time.

**Comment by michael1900** [comment]
> The latest version is 0.3.4 so everything else isn't true.
> 
> There is only a [milestone for 0.3.6](https://github.com/microg/GmsCore/milestone/26) that declare the fixes/improvements that will be included in that version but there isn't any 0.3.6 at this time.

https://www.reddit.com/r/MicroG/comments/1gsfjvm/play_integrity_support_planned_to_be_added_in_036/

**Comment by ale5000-git** [comment]
It refer to the missing part of "SafetyNet" so more apps will probably works with microG, but if I remember correctly the problem of Google Pay was different.
Search the other tickets that specifically mention "Google Pay".

**Comment by mar-v-in** [comment]
Also note that sometimes the milestones also have to be adjusted, e.g. if critical issues are found in a newly added feature. The milestones merely reflect the intention to include the pull requests and corresponding features. Same goes for the due date on milestones, which reflect current plan, but might change depending on unforeseen issues.
