### ISSUE TITLE
microg-hw

### ISSUE THREAD

**Issue by michael1900** [microg/GmsCore#2631]
Question about the microg for huawei: what version is the microg-hw in Download page? Asking this because i don't see any reference about number version like with standard microg.

One of the last [commit](https://github.com/microg/GmsCore/commit/0902c75fe1bd6c67790e0cabeab549f053da7166) of november 14 i.e., refers to huawei, but this will be included in one of the next microg standard preview release or in the next microg-hw, or both?

For huawei with emui14, to spoof the sign it's necessary the -hw version or also the standard version will work?

I can't understand these 3 things. Thanks to clarify these doubts.

**Comment by mar-v-in** [comment]
The `-hw` version is built from the regular source code using the `hms` maps flavor and the `huawei` target flavor (meaning it's built using `./gradlew :play-services-core:assembleHmsHuaweiRelease` from the regular code base.

Any changes done to the regular codebase will also be reflected in the `-hw` built, except if it's a component not included in that build (e.g. the mapbox maps component or the location provider).

On Huawei devices with EMUI, you must use the `-hw` version, the regular version does not support Huawei's signature spoofing system.
