### ISSUE TITLE
Why aren't there Huawei versions for release v0.3.4.240913?

### ISSUE THREAD

**Issue by dbonner** [microg/GmsCore#2632]
Hi,
There were no Huawei versions (-hw.apk) in the assets available for download from GmsCore GitHub Release v0.3.4.240913 (released a few days ago on November 13 2024).
Is this because we can now install the base version on Huawei devices?
Or should I stick to the older Huawei version (-hw.apk) for my Huawei device?
All the best,
Daniel

**Comment by mar-v-in** [comment]
See #2624
