### ISSUE TITLE
Why is position the Default Option?

### ISSUE THREAD

**Issue by Revan335** [microg/GmsCore#2636]
Hello,

this Discussion/Article are confused my about the new Default Option for the Location (Position not Beacon).

https://community.iode.tech/t/privacy-concerns-of-the-new-location-service-positon-xyz/4936

And the Article from the first Post on this Thread: https://grapheneos.org/articles/positon-location-service

Many Thanks for your/our Work on MicroG and Answer or Resolved this Confusion!

Greetings

Rwvan335

**Comment by ale5000-git** [comment]
I don't want to enter in the discussion but these discussions you linked are mostly just flame wars and ROM authors that slander every other.

Articles that you see inside a "domain" of a certain ROM that talk about another ROM can certainly not be trusted.

**Comment by mar-v-in** [comment]
BeaconDB is indeed the long-term better option, as their server is open-source. However it's still very young and doesn't have the dataset to provide useful location results for most endusers.

Positon does have a privacy policy (that is also linked in microG). It is not verifiable (just like it was never verifiable for Mozilla or any other service) if they adhere to these terms, but there is no reason for me to assume so.

Regarding the claims made on the article on that specific ROM website: No matter what you may think of /e/OS, there is absolutely no evidence of /e/ being involved with Positon or funding it - I interacted with both parties and both claim it's untrue. /e/OS does not use Positon. Furthermore the claim that Positon is to grab market share is absurd, given that they state on their website that they plan to shutdown by end of next year when BeaconDB is good enough to be used.
