### ISSUE TITLE
Vance/Revance don't see official microg-hw

### ISSUE THREAD

**Issue by michael1900** [microg/GmsCore#2641]
Hi, hope you can help me, i have a mate 50 pro with the last microg-hw installed, the huawei version directly downloaded from the microg site.
I tried different Vanced Youtube, Revance, etc.., but every time i try to open one of them they redirect me always to a special microg github page, like they never see the microg  obviously already installed from here, huawei version. 
I need to install a second modded microg together the official one? Possible?

Thanks for help me

**Comment by michael1900** [comment]
> Use [ReVanced microG](https://github.com/ReVanced/GmsCore/releases). This official microG will not work.

Thank you! Done. Wierd that we need to have 2 Microg installed together btw....

**Comment by mar-v-in** [comment]
As they're using a Huawei device, they most likely want to also have official microG, so they can use all apps other than ReVanced. It should be a bug in ReVanced that it can't use official microG.

**Comment by michael1900** [comment]
> > > Use [ReVanced microG](https://github.com/ReVanced/GmsCore/releases). This official microG will not work.
> > 
> > 
> > Thank you! Done. Wierd that we need to have 2 Microg installed together btw....
> 
> Uninstall official one. Please close this issue now, not related to official microG.

What? I can't uninstall the official one, there is no spoof sign in the revanced microg, not only but this last is also an old version so in this case we must need to use 2 microg at same time .

**Comment by Vavun** [comment]
> It should be a bug in ReVanced that it can't use official microG.
I don't think it's a bug.
Root variants of Vanced/ReVanced apks rely on com.google.android.gms package name for register, authorization and cloud messages and works great with official microG. So if you create a Revanced patched YouTube without changing original packagename and patching "microG support" it should work with original microG. 
Problems start on non-rooted devices with pre-installed YouTube. So it is not possible to use original packagename of YouTube apk package and Google services reject working with a modified YouTube client with a changed package name. Further confusion is created by the identical name and appearance of their microG, as has already been discussed many times.

**Comment by mar-v-in** [comment]
The non-root ReVanced can't work with the official play services installed as `com.google.android.gms` and then requires a microG to be installed at another package name. It could however work with microG installed as `com.google.android.gms` and then wouldn't require a second microG. It's a bug in ReVanced that they can't handle microG being installed regularly on a non-root system.

**Comment by Vavun** [comment]
In general, what is commonly called the root version works exactly like you described with original microG. Root is not required for mod to work, root is only required for the modules that masking mod as non-mod youtube for Google services to work. If you just create a patched apk as I described above, it will (or at least should) work without problems wirh original microG.
Reveanced confusion counter +1

**Comment by michael1900** [comment]
> > It should be a bug in ReVanced that it can't use official microG.
> 
> I don't think it's a bug. Root variants of Vanced/ReVanced apks rely on com.google.android.gms package name for register, authorization and cloud messages and works great with official microG. So if you create a Revanced patched YouTube without changing original packagename and patching "microG support" it should work with original microG. **Problems start on non-rooted devices with pre-installed YouTube.** So it is not possible to use original packagename of YouTube apk package and Google services reject working with a modified YouTube client with a changed package name. Further confusion is created by the identical name and appearance of their microG, as has already been discussed many times.

But i have a Mate 50 Pro and there is not a Youtube preinstalled. I tried only Revanced Youtube.

**Comment by michael1900** [comment]
> > It should be a bug in ReVanced that it can't use official microG.
> 
> I don't think it's a bug. Root variants of Vanced/ReVanced apks rely on com.google.android.gms package name for register, authorization and cloud messages and works great with official microG. So if you create a Revanced patched YouTube without changing original packagename and patching "microG support" it should work with original microG. Problems start on non-rooted devices with pre-installed YouTube. So it is not possible to use original packagename of YouTube apk package and Google services reject working with a modified YouTube client with a changed package name. Further confusion is created by the identical name and appearance of their microG, as has already been discussed many times.



I have an error in Revanced Manager if i change the package name with the original Youtube package name:

•⁠  ⁠Device Info
RVX Manager: 1.22.2
Model: DCO-LX9
Android version: 12
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

•⁠  ⁠Patch Info
App: com.google.android.youtube v19.16.39 (Suggested: 19.16.39)
Patches version: v4.16.1
Patches added: Default
Patches removed: None
Default patch options changed: GmsCore support [Package name of YouTube: com.google.android.youtube]

•⁠  ⁠Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Remove unused library: false
Use pre-release: false
Patches source: inotia00/revanced-patches
Integration source: inotia00/revanced-integrations

•⁠  ⁠Logs
Reading APK
Decoding app manifest
Loading patches
An error occurred:
app.revanced.patcher.patch.options.PatchOptionException$ValueValidationException: The option value "com.google.android.youtube" failed validation for PackageNameYouTube
	at app.revanced.patcher.patch.options.PatchOption.assertValid(SourceFile:80)
	at app.revanced.patcher.patch.options.PatchOption.setValue(SourceFile:44)
	at app.revanced.patcher.patch.options.PatchOptions.set(SourceFile:33)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$35(SourceFile:305)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$7KobHryxqqdI5JS3uiaGATjlYU8(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:933)
