### ISSUE TITLE
About game purchase and recharge issues

### ISSUE THREAD

**Issue by wangtao99775** [microg/GmsCore#2642]
Today, I used a Huawei phone to download the game "Fifth Personality" through the Aurora Store. When recharging in-game purchases, it prompted that the recharge failed.
Is the recharge failure caused by microG not supporting the complete payment function?
Is there any good solution?
Mobile phone system: EMUI14.2.

**Comment by ale5000-git** [comment]
Try to check that you have the related options enable in microG settings.

**Comment by wangtao99775** [comment]
No problem, still can't be used.

**Comment by ale5000-git** [comment]
Could you please take a logcat and post it here?
