### ISSUE TITLE
Is there hw version for v0.3.4.240913?

### ISSUE THREAD

**Issue by crotoc** [microg/GmsCore#2653]
Hi guys, 
Thanks for the fantastic project!!
Recently Google map doesn't work and I am trying to fix it by updating Microg. But there is no hw version avaiable and anothet user suffixed version is there. Can you give some info about how to find hw version? Thanks!

**Comment by ale5000-git** [comment]
No, there isn't.
For Huawei you have to wait to 0.3.5, look here: #2624

**Comment by crotoc** [comment]
> No, there isn't. For Huawei you have to wait to 0.3.5-hw, look here: [#2624](https://github.com/microg/GmsCore/issues/2624)

Thanks very much! Happy.Thanksgiving!
