### ISSUE TITLE
[Intentionally duplicate] [Request] [Play Integrity] Please re-prioritize, fast-track and/or divulge current plans/status on Companion Play Integrity

### ISSUE THREAD

**Issue by KyunLFA** [microg/GmsCore#2655]
**Is your feature request related to a problem? Please describe.**
It has been quite a long time since basic Play Integrity support in MicroG Companion has been requested. It makes little to no sense, in my POV, to have a MicroG setup to replace Google apps, just to have to still be locked to installing Google Play Store for the sake of having working applications, since a lot of apps implement PI by now, specially banking and gaming ones. It is my opinion that, without PI in Companion, in the current Android landscape, MicroG is functionally incomplete and not a valid substitute for Google apps. I personally believe this to be serious, urgent flaw that needs to be reprioritized above other features and bug fixes.

**Describe the solution you'd like**
Please divulge, if possible: what has kept PI support in Companion in limbo until now? Lack of documentation/information about the inner workings of the Play Store's PI? Lack of developer manpower? Lack of end users to justify its inclusion? Lack of testers? Lack of funding? Lack of interest, motivation or motive? 

Please consider, according to your best judgement: Organizing goals, low hanging fruit searching, paths, development cycles, internal developer meetings and/or development workflow changes or restructuring, reassessing priorities (and whatever else deemed necessary) to attain basic PI support in Companion and thus grow MicroG's appeal.

**Describe alternatives you've considered**
Installing the Google Play Store. It defeats my purpose of deGoogling.

**Comment by ale5000-git** [comment]
It has already been implemented (#2599) and it will likely be included in version 0.3.6

**Comment by KyunLFA** [comment]
Oh, that's a pleasant surprise! Thank you very much!! I should have looked better at the PRs... Well, I'll test it this week. Cheers!

**Comment by michael1900** [comment]
@ale5000-git @KyunLFA with this fix finally app like ebay, macdonald and chgpt will work without play services error to start?

**Comment by ale5000-git** [comment]
> [@ale5000-git](https://github.com/ale5000-git) [@KyunLFA](https://github.com/KyunLFA) with this fix finally app like ebay, macdonald and chgpt will work without play services error to start?

Possible but it isn't excluded that those apps may have additional issues.
