### ISSUE TITLE
Crashed when clicking Self-check,Google Cloud Messaging,and all the colmn(with logcat)

### ISSUE THREAD

**Issue by acsway878787** [microg/GmsCore#267]
Phone: Asus Padfone S Android 4.4.4
01-13 23:04:45.253 E/AndroidRuntime(12016): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.ui.SelfCheckFragment$AsActivity}: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
01-13 23:04:45.253 E/AndroidRuntime(12016): Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
01-13 23:04:45.253 E/AndroidRuntime(12016): 	at org.microg.tools.ui.AbstractSettingsActivity.onCreate(AbstractSettingsActivity.java:21)
01-13 23:04:45.253 E/AndroidRuntime(12016): 	at org.microg.tools.ui.SwitchBar.<init>(SwitchBar.java:69)

01-13 23:04:52.895 E/AndroidRuntime(12336): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.nlp.ui.SettingsActivity}: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
01-13 23:04:52.895 E/AndroidRuntime(12336): Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
01-13 23:04:52.895 E/AndroidRuntime(12336): 	at org.microg.nlp.ui.SettingsActivity.onCreate(SettingsActivity.java:47)
01-13 23:04:52.895 E/AndroidRuntime(12336): 	at org.microg.tools.ui.SwitchBar.<init>(SwitchBar.java:69)

01-13 23:04:55.697 E/AndroidRuntime(12398): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.ui.AboutFragment$AsActivity}: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
01-13 23:04:55.697 E/AndroidRuntime(12398): Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
01-13 23:04:55.697 E/AndroidRuntime(12398): 	at org.microg.tools.ui.AbstractSettingsActivity.onCreate(AbstractSettingsActivity.java:21)
01-13 23:04:55.697 E/AndroidRuntime(12398): 	at org.microg.tools.ui.SwitchBar.<init>(SwitchBar.java:69)

**Comment by acsway878787** [comment]
By the way, is it possible to use Google Play Store with microg?

**Comment by acsway878787** [comment]
@JERW86
Can you tell me how to make it work?
I installed it in system partation,but it still crashed when i pressed install for any app.

**Comment by JERW86** [comment]
Try clearing play store data in system settings. If that doesn't work, make sure the play store app is placed in /system/priv-app and use a file manager to change the apk permissions to rw r r. Here is a screen shot of what it should like:

![screenshot_20170114-104844](https://cloud.githubusercontent.com/assets/16406776/21956384/7cb55b30-da4d-11e6-8ba6-38aa38b4e4f0.png)

**Comment by acsway878787** [comment]
@mar-v-in How about this error?
Sorry for bothering you!

**Comment by mar-v-in** [comment]
@acsway878787 can you check logcat if it has more lines referencing "org.microg.tools.ui.SwitchBar"?

**Comment by acsway878787** [comment]
@mar-v-in Here thry are.

>01-19 16:38:23.991 E/AndroidRuntime(5314): FATAL EXCEPTION: main
01-19 16:38:23.991 E/AndroidRuntime(5314): Process: com.google.android.gms, PID: 5314
01-19 16:38:23.991 E/AndroidRuntime(5314): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.ui.SelfCheckFragment$AsActivity}: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2279)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2357)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.app.ActivityThread.access$800(ActivityThread.java:139)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.os.Looper.loop(Looper.java:136)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.app.ActivityThread.main(ActivityThread.java:5249)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at dalvik.system.NativeStart.main(Native Method)
01-19 16:38:23.991 E/AndroidRuntime(5314): Caused by: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.createView(LayoutInflater.java:620)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.inflate(Native Method)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at org.microg.tools.ui.AbstractSettingsActivity.onCreate(AbstractSettingsActivity.java:21)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.app.Activity.performCreate(Activity.java:5411)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2231)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	... 12 more
01-19 16:38:23.991 E/AndroidRuntime(5314): Caused by: java.lang.reflect.InvocationTargetException
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at java.lang.reflect.Constructor.constructNative(Native Method)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.createView(LayoutInflater.java:594)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	... 26 more
01-19 16:38:23.991 E/AndroidRuntime(5314): Caused by: android.view.InflateException: Binary XML file line #21: Error inflating class TextView
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:462)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.inflate(Native Method)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at org.microg.tools.ui.SwitchBar.<init>(SwitchBar.java:69)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	... 29 more
01-19 16:38:23.991 E/AndroidRuntime(5314): Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.content.res.TypedArray.getColor(TypedArray.java:327)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.content.res.XResources$XTypedArray.getColor(XResources.java:889)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.widget.TextView.<init>(TextView.java:703)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1017)
01-19 16:38:23.991 E/AndroidRuntime(5314): 	at android.support.v7.ap

**Comment by acsway878787** [comment]
@mar-v-in So could you tell me how to solve this problem?
Thank you very much!

**Comment by acsway878787** [comment]
So any solution?
I reinstalled it but still crashed.

**Comment by acsway878787** [comment]
@mar-v-in I guess there are some incompatible code in color.xml?

**Comment by mar-v-in** [comment]
This problem does not occur in a AOSP 4.4 emulator I set up.
Can you try if setting "disable resource hooks" in Xposed settings helps?

**Comment by acsway878787** [comment]
@mar-v-in It didn't work.
Should I give SystemUI.apk to you?

**Comment by mar-v-in** [comment]
SystemUI.apk is not in any way related. I will try a few things and put them in the next preview release.

**Comment by acsway878787** [comment]
@mar-v-in It didn't fixed in 0.2.4-62.
The crash log is the same.

**Comment by acsway878787** [comment]
@mar-v-in Still crashed in 0.2.4-76 with same crash log.

**Comment by acsway878787** [comment]
@mar-v-in
Should this help?
http://stackoverflow.com/questions/19874882/android-view-inflateexception-binary-xml-file-error-inflating-class-fragment

**Comment by acsway878787** [comment]
@mar-v-in 0.2.4-79 still crashed.

**Comment by OLEG4120** [comment]
I faced same issue. Only version with old interface 0.2.4-22 works fine
Asus zenfon5, stock 5.0
