### ISSUE TITLE
Add Discussion Area in Github

### ISSUE THREAD

**Issue by ghost** [microg/GmsCore#2670]
Hey,

i would love if you could add Discussion Area to your Github Site, that we can ask Questions there, instead of needing to open an Issue. It would be nice and make it easier for us too.

**Comment by lucasmz-dev** [comment]
Questions are also marked here as 'development' questions which is ... eh
There are a few communities for microG, e.g. [this matrix channel](https://matrix.to/#/#microG:matrix.org) (which I believe mar-v-in isn't aware of)

[I've also forked the wiki from GitHub a while ago](https://github.com/lucasmz-dev/microG-wiki), though I still need to work on that and don't know everything ultimately, but it was quite outdated, so...

**Comment by lucasmz-dev** [comment]
well, that account's gone

**Comment by ale5000-git** [comment]
Having discussions enabled on GitHub only increases spam, there is already a lot of spam with just tickets.

For other things I suggest to write here: https://xdaforums.com/t/app-microg-gmscore-lightweight-free-software-clone-of-google-play-services.3217616/
