### ISSUE TITLE
[com.google.android.apps.maps] Google Maps does not work reliably in its newer versions

### ISSUE THREAD

**Issue by lucasmz-dev** [microg/GmsCore#2671]
**Affected app**
Name: Google Maps
Package id: com.google.android.apps.maps

**Describe the bug**
Most of Google Maps' seems broken ever since the last updates, e.g. logging in, using the map in anyway, etc.

**To Reproduce**
1. Open Google Maps
2. Honestly, check anything

**Expected behavior**
Google Maps login to work, map to show, reviews to show, etc.

**Screenshots**
![Image](https://github.com/user-attachments/assets/233b6837-be2e-458b-a614-e27257dc00c8)
![Image](https://github.com/user-attachments/assets/09dfaa7c-b893-4c65-a2c6-6f28a5de24d5)

**System**
Android Version: 14
Custom ROM: CalyxOS 5.14.0 (users on 6.2.0 also report this)

**microG**
microG Core version: 0.3.2
microG Self-Check results: All ticked

**Additional context**
Reported initially on the CalyxOS rooms:
[1]: https://matrix.to/#/!UlsAcjNSfQqWJPccIO:matrix.org/$lKYzzYIi_vAMTSjmIa-znotzUHqzV1EeGvMwHhWaJl4?via=calyx.dev&via=matrix.org&via=tchncs.de
[2]: https://matrix.to/#/!UlsAcjNSfQqWJPccIO:matrix.org/$OMqeymssXzU7eOdHD72oOLW674JzggxBRmsPkIjMXak?via=calyx.dev&via=matrix.org&via=tchncs.de

**Comment by lucasmz-dev** [comment]
@ale5000-git unfortunately I use Calyx so I can't update or change the microG version there, it's also on 0.3.2 for now

**Comment by lucasmz-dev** [comment]
@avbfr I see you liked the issue, do you have this issue and with what version?

**Comment by Uldiniad** [comment]
I can also reproduce this issue

only log lines I see that may relate are
```2024-12-06 18:13:33.025  4271-4271  GmsGcmRegister          com.google.android.gms               D  onBind: Intent { act=com.google.android.c2dm.intent.REGISTER pkg=com.google.android.gms }
2024-12-06 18:13:33.033  4271-4271  GmsGcmRegister          com.google.android.gms               D  handleMessage: package=com.google.android.apps.maps what=1 id=1
2024-12-06 18:13:33.134  4271-8708  GmsHttpFormClient       com.google.android.gms               D  -- Request --
                                                                                                    device=3720805207711753087&app=com.google.android.apps.maps&cert=38918a453d07199354f8b19af05ec6562ced5788&app_ver=1067814767&X-subtype=658104395416&X-app_ver=1067814767&X-osv=35&X-cliv=fiid-21.1.1&X-gmsv=240913269&X-appid=d_q0bZntTCS1ZIQcoiFjD-&X-scope=*&X-gmp_app_id=1%3A747654520220%3Aandroid%3A0000000000000000&X-firebase-app-name-hash=NN8D9lCS7f1iqmTtenFBxpSuyv4&X-app_ver_name=24.48.05.700553417&target_ver=35&sender=658104395416
2024-12-06 18:13:33.235  4271-8708  GmsHttpFormClient       com.google.android.gms               D  -- Response --
                                                                                                    Error=FIS_AUTH_ERROR```

**Comment by avbfr** [comment]
> [@avbfr](https://github.com/avbfr) I see you liked the issue, do you have this issue and with what version?

Hello, Indeed ! Unfortunately, I downgraded both Gmail (2024.11.10.702370780.Release) & Google Maps (to 11.155.003) to fix issues so I don't have the exact version. 

I think it is 24.48.07.702029101 but possibly also olders like 24.48.05.700553417.

**Comment by adrillon** [comment]
I reproduce, GMaps is also completely broken on Android Auto (black screen, crashes after a few seconds).

**Comment by js290** [comment]
Yeah, Google Maps `24.48.05.700553417` is now asking for *Google Play Services* to be installed.  I'm using `LineageOS-21-20241106-microG-coral`.

**Comment by ChickenNuggetScientist** [comment]
Use this Version 24.47.05.699977727

You can find it through apkmirror. Works on 0.2.27, i reckon will work on higher versions too.





This is not a microG issue, goolag's control is getting out of hand.

**Comment by genpfault** [comment]
> Use this Version 24.47.05.699977727
> 
> You can find it through apkmirror. Works on 0.2.27, i reckon will work on higher versions too.
> 
> This is not a microG issue, goolag's control is getting out of hand.
> 
> Whilst gmaps wv by divest OS works for now.

[Per APKMirror](https://www.apkmirror.com/apk/google-inc/maps/maps-24-47-05-699977727-release/) it looks like `24.47.05.699977727` maps to version code `1067804539` downloading manually via [Aurora Store](https://f-droid.org/en/packages/com.aurora.store/).

**Comment by devlocalhost** [comment]
> Use this Version 24.47.05.699977727
> 
> You can find it through apkmirror. Works on 0.2.27, i reckon will work on higher versions too.
> 
> This is not a microG issue, goolag's control is getting out of hand.
> 
> Whilst gmaps wv by divest OS works for now.

i can confirm this version works for me.

microg version 0.3.4.240913
rom: lineageOS 21, 21-20241204-NIGHTLY-a71

**Comment by wolftune** [comment]
Perhaps update this to be a more general Google Apps issue?

Gmail and Google Calendar both had error messages after most recent updates (saying that they needed Google Services), and downgrading via getting the previous builds (numbers found at apkmirror.com) got things working again. I expect the Maps issue is the same thing…

**Comment by ale5000-git** [comment]
@wolftune
Did you get it also with microG v0.3.5.240913?

**Comment by wolftune** [comment]
I have 0.3.2.240913-21 with CalyxOS. I have the rough impression that updating microG isn't trivial for me to do myself under CalyxOS (happy to be corrected if wrong)

**Comment by github-k8n** [comment]
Just add the microg repository to fdroid
https://microg.org/download.html

That should allow you to select the latest version.
At least it works for the microg lineageos build I use.

I also tested the latest map version  from today with 0.3.5.240913  microg and it doesn't seem to fix the issue...

**Comment by D3SOX** [comment]
Former Lineage for microG and now Calyx user here.
@github-k8n That doesn't work on CalyxOS. The microG packages use a different signature (from the Calyx team). As far as I know there is no trivial way to update other than wait for a system update that has the new version.
If you absolutely need it you would have to build your own Calyx but to install that a factory reset is required.

**Comment by chirayudesai** [comment]
We'll release a microG update for CalyxOS ASAP.

**Comment by TinfoilSubmarine** [comment]
Updated microg to 0.3.5.240913, still getting bug with `com.google.android.apps.maps version 24.49.06.703287473`.

**Comment by nafarinha** [comment]
> Per APKMirror it looks like 24.47.05.699977727 maps to version code 1067804539 for downloading manually via Aurora Store.

This version of google maps installed using the Aurora Store worked for me.

microg 0.3.5.240913
LineageOS 20-20240402-NIGHTLY-lisa

Thanks all for the help!

**Comment by lucasmz-dev** [comment]
Closing as #2680 explains this better and has more info on it
It seems to be the same issue.
