### ISSUE TITLE
MicroG app translation are broke

### ISSUE THREAD

**Issue by ruditimmermans** [microg/GmsCore#2677]
It seems on the lasted update 3.5 some translations are broke when i check the Sellf-Check options the installed packages are broke into the app

See screenshot MicroG app :

![Image](https://github.com/user-attachments/assets/52873de5-215b-48dc-8157-d383e9caba8d)

**Comment by grenadin** [comment]
it might be someone that translate don't understand the process of it.

**Comment by ruditimmermans** [comment]
> it might be someone that translate don't understand the process of it.

I have translate it myself to Dutch when i check the strings on Weblate there are a wiard English translation there, also it seems i could not found anywhere the string Permission to for some resion...

**Comment by ruditimmermans** [comment]
I found the problem
