### ISSUE TITLE
[hu.webvalto.bkkfutar] <BudapestGO> BudapestGO crashes when trying to plan a trip

### ISSUE THREAD

**Issue by Rekt3y** [microg/GmsCore#2682]
**Affected app**
Name: BudapestGO
Package id: hu.webvalto.bkkfutar

**Describe the bug**
When BudapestGO attempts to plot a trip, it crashes.
For example, if you have GPS off, it crashes after selecting a destination and a start location. If you have GPS on, it crashes immediately after selecting a destination.

**To Reproduce**
1. Go to 'Plan a journey'
2. Click on the search bar at the top
3. Pick a destination
4. Pick a start location
5. Crash

**Expected behavior**
BudapestGO should now show options to get from the starting point to the destination.

**System**
Android Version: 14
Custom ROM: LineageOS 21

**microG**
microG Core version: 0.2.27.223616
microG Self-Check results: ![Image](https://github.com/user-attachments/assets/202f9cc1-0fdb-45a0-9739-034711379e3a)

**Additional context**
I use Aurora Store, not Phonesky. It's a Galaxy A73 and it's not rooted in any way. Apparently, LineageOS supports signature spoofing for MicroG. That patch was merged 2024.02.25. I have no idea why MicroG says it doesn't support it, and then goes on to tick the checkbox.

I also haven't logged in with a Google account.

**Comment by ale5000-git** [comment]
Could you please both microG Services and microG Comanion to v0.3.5 and try again?

**Comment by Rekt3y** [comment]
I installed through F-Droid from this page: https://github.com/microg/GmsCore/wiki/Downloads
I made sure to use the microG repo.  Apparently the "suggested" version isn't the latest one. I'll get on it right away

**Comment by ale5000-git** [comment]
Although it is still marked as "suggested" the version 0.2.27 is very old and the difference is abissal.

**Comment by Rekt3y** [comment]
BudapestGO works now. Thanks for the tip. I didn't know I had to enable Beta updates for MicroG services.
