### ISSUE TITLE
Location Indicator

### ISSUE THREAD

**Issue by HaykCSec** [microg/GmsCore#2691]
I have the latest MicroG update installed, I'm noticing a strange problem, the location indicator shows that the "Settings" application is using location, but in fact location is disabled, and so on. As a temporary solution, I disabled the phone's location indicator
![Image](https://github.com/user-attachments/assets/d7d8b69d-8028-45ad-adc7-ebb54443fbf3)
![Image](https://github.com/user-attachments/assets/a11fdbe9-d487-4f0b-91bb-d233608c539c)

**Comment by mar-v-in** [comment]
Please tell which OS/ROM and version you are using. Also please check if you enabled the setting to have dark theme or night light scheduled by sunset/sunrise and try if turning them off removes the indicator.

**Comment by HaykCSec** [comment]
This is official crDroid 11.0 and MicroG verison 0.3.5.x, i disbaled and emabled location indicator from settings, still ok, cant see that issue
