### ISSUE TITLE
Fixed translation issue

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#2695]
@mar-v-in

I have fixed the issue of this:
https://hosted.weblate.org/translate/microg/play-services-core-strings/ga/?q=auth_package_override_request_title&sort_by=-priority%2Cposition
on Weblate.

Please sync it again.

**Comment by mar-v-in** [comment]
Thanks. I hadn't seen you already fixed it in weblate and fixed it directly on upstream.
