### ISSUE TITLE
How to enable the Play Integrity API?

### ISSUE THREAD

**Issue by Loweder** [microg/GmsCore#2696]
Hello. I have installed 0.3.6 version of MicroG. I was expecting to see an option to enable Play Integrity API somewhere in the settings, but I can't find it anywhere, can anyone help please?

**Comment by mar-v-in** [comment]
In microG Settings > Google SafetyNet make sure that "Allow device attestation is checked". Also make sure you have the latest version of the companion app.

**Comment by Loweder** [comment]
microG Companion is 0.3.6 as well, everything is enabled
![Image](https://github.com/user-attachments/assets/d2b2827c-57b3-4a91-9547-cab55c38300a)
![Image](https://github.com/user-attachments/assets/535c1c93-25cb-470c-b272-25385ecf6214)

**Comment by Loweder** [comment]
During further investigation, I noticed following lines in logcat:
12-24 14:06:51.422  4887  4887 W IntegrityService: requestIntegrityToken has exception:
12-24 14:06:51.422  4887  4887 D IntegrityService: requestIntegrityToken() failed for com.henrikherzig.playintegritychecker error -> java.net.UnknownHostException: Unable to resolve host "play-fe.googleapis.com": No address associated with hostname
However the output of "host play-fe.googleapis.com" is
.../files/home # host play-fe.googleapis.com
play-fe.googleapis.com has address 142.251.39.78
play-fe.googleapis.com has IPv6 address 2a00:1450:400d:80e::200e

**Comment by mar-v-in** [comment]
Are you using some ad blocker with privacy filter or DNS with filter lists? If so `play-fe.googleapis.com` might be wrongly on its block list.

**Comment by Loweder** [comment]
Well I do, but I checked the hosts file for it, wasn't present, I disabled my blocker+rebooted - same result.
Also the result of "ping" is
.../files/home # ping play-fe.googleapis.com            PING play-fe.googleapis.com (142.251.39.46) 56(84) bytes of data.                                               64 bytes from bud02s38-in-f14.1e100.net (142.251.39.46): icmp_seq=1 ttl=116 time=61.0 ms                        64 bytes from bud02s38-in-f14.1e100.net (142.251.39.46): icmp_seq=2 ttl=116 time=33.9 ms                        64 bytes from bud02s38-in-f14.1e100.net (142.251.39.46): icmp_seq=3 ttl=116 time=53.5 ms                        64 bytes from bud02s38-in-f14.1e100.net (142.251.39.46): icmp_seq=4 ttl=116 time=62.5 ms                        64 bytes from bud02s38-in-f14.1e100.net (142.251.39.46): icmp_seq=5 ttl=116 time=31.5 ms                        ^C                                                      --- play-fe.googleapis.com ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4005ms                                                  rtt min/avg/max/mdev = 31.559/48.545/62.598/13.275 ms
Which I don't think would happen if it was blocked, as the IP is registered as Google's, not my own

**Comment by D4V1D3-008** [comment]
Same issue, I use dns.adguard.com as custom dns, when it is enabled I get the error after a while, like a timeout, if I disable the dns SPIC throws the error instantly.

**Comment by mar-v-in** [comment]
Which OS do you use?

**Comment by D4V1D3-008** [comment]
LineageOS 20 on a Poco X3 Pro, I didn't update for a while, maybe that causes the issue...

**Comment by ale5000-git** [comment]
Some free DNS services block some domains on their servers (without anything on the phone), so try changing DNS.

**Comment by D4V1D3-008** [comment]
> Some free DNS services block some domains on their servers (without anything on the phone), so try changing DNS.

I said that I tried to disable it, doing so only made the error appear faster

**Comment by ale5000-git** [comment]
I really mean change, disable just use the provider DNS that may also have problems.
Just to be sure try also Cloudflare DNS (1.1.1.1)

**Comment by D4V1D3-008** [comment]
When set to cloudflare also errors after a while, like if it timeouts

**Comment by ale5000-git** [comment]
To all: I'm not sure but is it possible that there is a sort of cache that is caching failed DNS requests?

**Comment by Loweder** [comment]
> LineageOS 20 on a Poco X3 Pro, I didn't update for a while, maybe that causes the issue...

I actually also have LineageOS, but 21 and on Poco F2 Pro
I just updated it, the issue still persists.
The DNS shouldn't be the issue, other devices on this network that have Official Google's can connect just fine

**Comment by mar-v-in** [comment]
Do you have any kind of firewall or similar that bans internet access for microG Companion? Have you maybe accidentally removed network access for microG Companion via the setting in "App Info" > "Mobile data usage"?

**Comment by Loweder** [comment]
The network access was off. However I didn't remove it, it was like that by default

**Comment by D4V1D3-008** [comment]
> The network access was off. However I didn't remove it, it was like that by default

Same for me, now it works.
