### ISSUE TITLE
Pokemon Go prompts that the game is incompatible with the device

### ISSUE THREAD

**Issue by wangtao99775** [microg/GmsCore#2720]
Regarding the game problem.
System: harmony os 4.2
Version: MicroG 0.3.6-hw
After downloading Pokemon Go and logging into the game, it prompts that the game is incompatible with the device.
What is the solution?

**Comment by paolo-caroni** [comment]
Very strange.
On 0.3.6 actually I have reinstalled original pokemon go (I was using pgsharp that skip play integrity check).
Try to install "Play integrity API Checker" and see if your smartphone is at least BASIC_INTEGRITY.
If so should be supported.
If not you have to trick with magisk (I cannot help in that) or install a modded app (maybe insecure) called pgsharp (for cheater, but you can disable all cheating feature).
Obviously you can be banned by niantic in both case, using microg or a modded app is against the contract of use.

**Comment by wangtao99775** [comment]
thank you
