### ISSUE TITLE
Play integrity API is not only for proprietary apps

### ISSUE THREAD

**Issue by paolo-caroni** [microg/GmsCore#2723]
> We might want to make this more explicit and adjust the wording for Play Integrity, but in the end, if users need it, it's for a proprietary app, so users already do run proprietary code on their device anyway.

 _Originally posted by @mar-v-in in [#2050](https://github.com/microg/GmsCore/issues/2050#issuecomment-2558152378)_

---
This is not really a microg issue, maybe a freesoftwarefoundationeeurope issue, so @mar-v-in or @ale5000-git please delte or move it.

Just to clarify, sadly Play Integrity API is used by free software too.
In particular on Europe for the digital [European Wallet](https://eu-digital-identity-wallet.github.io/eudi-doc-architecture-and-reference-framework/1.4.0/arf/) (ID card, driver licence, etc.).
Actually with 0.3.6 I have the possibility to have my driver licence on the smartphone, until 0.3.5 it was not possible.
So thank you for the really important feature, but please don't consider it only for proprietary app.

**Comment by ale5000-git** [comment]
What he meant is that when you compile an app (even an opensource app) with Google libs, then the app will still contains Google libs that are proprietary (even if everything else in the app is opensource).
