### ISSUE TITLE
Location for custom SaftyNet Server (or self hosted)

### ISSUE THREAD

**Issue by Teyro** [microg/GmsCore#299]
Hi there,

The newest dev Build intregrates the SafetyNet API and far as i know there a two options the first is only for nonrooted devices the secound for rooted ?!?! Did someone know a url for that? How does it work?

best wishes from Hamburg, Germany

**Comment by ale5000-git** [comment]
As far as I know there isn't any server currently.
There is only the possibility to use a custom server but there isn't any server.

**Comment by Teyro** [comment]
ok ;) So who will implement that? And if anyone could implement a safety net custom server so microg could bypass the check? Chicken Egg like :S Sry for my bad english ... My native language is german :S

**Comment by ale5000-git** [comment]
1) I don't know
2) I think yes, it could likely not doing any check at all

**Comment by mar-v-in** [comment]
There won't be an implementation of SafetyNet Server from my side. During the SafetyNet verification process on the server, private crypto key material from Google is used, which is not publicly available. This means that the SafetyNet verification process in all cases must involve Google's original servers.

Some apps might not verify the signature properly. in this case, no verification server is required and the process can be fully done on the device. I might add such a feature to GmsCore later.
