### ISSUE TITLE
Feature request: Stop SafetyNet immediately when disabled

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#304]
I have enabled and used it.
Then I have switched off in the settings but I see that SafetyNetClientService of GmsCore is still active and also RemoteDroidGuardService of microG DroidGuard Helper is still active.

It would be nice if they are stopped immediately after disabling it.

**Comment by mar-v-in** [comment]
SafetyNetClientService is bound by apps that request safetynet results. This should not be blocked, instead the inability to use SafetyNet is reported when the app tries to do a request (which is independent from binding the service). In fact, stopping the service would be pointless as the app can just start it again.

RemoteDroidGuardService -> yes. In fact this should be closed directly after the request is done.

**Comment by ale5000-git** [comment]
Any update on this?

**Comment by ale5000-git** [comment]
Due to the departure of the separate RemoteDroidGuard I guess this is no longer a problem.
