### ISSUE TITLE
Firebase Cloud Messaging

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#313]
Is this supported? If no, please add it.

> Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features

Info are [here](https://developers.google.com/cloud-messaging/).

**Comment by RMcNeely** [comment]
So does this mean they're decoupling GCM from GMS?

**Comment by mar-v-in** [comment]
FCM shouldn't require changes in GmsCore. On Android, FCM is just a new API around GCM. I don't know how it is realized on other platforms, but that's OT here.

**Comment by ale5000-git** [comment]
For the new API to appears on Android doesn't it need to be supported in GmsCore?

**Comment by jfrederickson** [comment]
@mar-v-in's comment made it sound like FCM doesn't require changes in microG (am I understanding that correctly?) but an application I use that just switched from GCM to FCM is no longer able to register my device.

```
<yannick> i have a bug report from a nexus 5 device.
<yannick> Have a look to  GCMHelper logs
<yannick> D/GCMHelper: ## getRegistrationToken(): null
<yannick> means that the FCM registration fails.
<yannick> The latest Google play version works only with the official ROMs.
<yannick> MicroG does not seem compliant with FCM.
```

**Comment by mar-v-in** [comment]
@jfrederickson which app is that?

**Comment by jfrederickson** [comment]
Riot: https://github.com/vector-im/riot-android

Looks like this is where they switched over to FCM: https://github.com/vector-im/riot-android/commit/15bba9dce4a96e49fd4bd5132e2f60b57bdf1059

**Comment by tostercx** [comment]
I have no idea what changed but the latest version seems to have fixed it for me?

**Comment by chris42** [comment]
Please see #439

**Comment by farfromrefug** [comment]
I am a developer and was fighting to get my app to work with microg.
I was constantly hit with `SERVICE_NOT_AVAILABLE` errors.
I then used that [code](https://github.com/bbindreiter/PushNotificationTester_App) with my app id and google json file and it worked!
So what was different?
I figured it out. It is the version  of `com.google.firebase:firebase-messaging` you use to build your app.
Using `19.0.1` will work with microg. But then updating to `20.1.5`, uninstall/build/run and you will get a `SERVICE_NOT_AVAILABLE` error!

So i would guess that something changed which makes it not work anymore. We need to find what. Now it also means that any app using `com.google.firebase:firebase-messaging` later that `20.0.0` (which i would guess is the breaking point), wont work at all with microg!

**Comment by godfuture** [comment]
> So i would guess that something changed which makes it not work anymore. We need to find what. Now it also means that any app using `com.google.firebase:firebase-messaging` later that `20.0.0` (which i would guess is the breaking point), wont work at all with microg!

Same here. My banking app offered digital cards which is an alternative to Google Pay. But I get issues during registration. I found out that the "firebase messaging id" is missing. Most likely microg is missing latest API elements. Unfortunately I do not know firebase version used in the banking app.

**Comment by danielfrankcom** [comment]
Unfortunately the Fastmail app also seems to encounter a similar `SERVICE_NOT_AVAILABLE` after a fresh microG install.

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version of microG GmsCore so I close it for now.
Open a new issue if needed.
