### ISSUE TITLE
Firebase and GCM registration: Bad request

### ISSUE THREAD

**Issue by YtvwlD** [microg/GmsCore#322]
I've recently updated an app which apparently uses Firebase to sync data.
It seems to work normally, but these messages pop up in the logs:

```
W/GmsGcmRegisterSvc( 1779): java.io.IOException: Bad Request
W/GmsGcmRegisterSvc( 1779):     at org.microg.gms.common.HttpFormClient.request(HttpFormClient.java:84)
W/GmsGcmRegisterSvc( 1779):     at org.microg.gms.gcm.RegisterRequest.getResponse(RegisterRequest.java:101)
W/GmsGcmRegisterSvc( 1779):     at org.microg.gms.gcm.PushRegisterService.register(PushRegisterService.java:215)
W/GmsGcmRegisterSvc( 1779):     at org.microg.gms.gcm.PushRegisterService.register(PushRegisterService.java:77)
W/GmsGcmRegisterSvc( 1779):     at org.microg.gms.gcm.PushRegisterService.registerAndReply(PushRegisterService.java:178)
W/GmsGcmRegisterSvc( 1779):     at org.microg.gms.gcm.PushRegisterService.register(PushRegisterService.java:151)
W/GmsGcmRegisterSvc( 1779):     at org.microg.gms.gcm.PushRegisterService.onHandleIntent(PushRegisterService.java:111)
W/GmsGcmRegisterSvc( 1779):     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
W/GmsGcmRegisterSvc( 1779):     at android.os.Handler.dispatchMessage(Handler.java:110)
W/GmsGcmRegisterSvc( 1779):     at android.os.Looper.loop(Looper.java:193)
W/GmsGcmRegisterSvc( 1779):     at android.os.HandlerThread.run(HandlerThread.java:61)
D/FirebaseInstanceId(32219): background sync failed: SERVICE_NOT_AVAILABLE, retry in 10s
```

And yes, it tries again every 10 seconds.

Is this expected behaviour? What can I try to do?

**Comment by tomasz1986** [comment]
I have no logcat at the moment but I have also observed a lot of partial wakelocks related to Firebase, and FirebaseInstanceId in particular. They occur in all of the apps that rely have the FirebaseInstanceIdService implemented. The apps do seem to work normally. In order to to get rid of the wakelocks I have simply blocked their FirebaseInstanceIdService(s) completely. I am quite sure that these kind of lengthy wakelocks are not normal though.

**Comment by f03el** [comment]
Not sure if it's using Firebase, but the current version of BankID (com.bankid.bus, version 7.6.21, Swedish authentication system) fails to connect to the server, and in the log there are occurrences of "Bad Request" exceptions, see log [here](https://gist.github.com/f03el/3544ef2572b46c1a97a6498905eea661). How do I know if it's related to Firebase? Is `com.google.android.c2dm.intent.REGISTER` (seen in the log) still used with Firebase?

**Comment by ale5000-git** [comment]
Related to #313

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version of microG GmsCore so I close it for now.
Open a new issue if needed.
