### ISSUE TITLE
"Uber" crashes with the latest microG (GmsCore 0.2.4-103)

### ISSUE THREAD

**Issue by sam-kzn** [microg/GmsCore#390]
**Device:** Philips W6610i
**OS**: Android 4.2.2 (JellyBean)
**Uber version**: latest from GooglePlay (also have been tested earlier versions)
**MicroG**: latest build (2017/06/13)

[NetCat_Log.txt](https://github.com/microg/android_packages_apps_GmsCore/files/1099468/2017-06-23-22-02-35.txt)

What was done (installed):
1. LegacyNetworkLocation.apk was added by manual from [here](https://github.com/microg/android_packages_apps_UnifiedNlp#android-23---431-gingerbread--honeycomb--ice-cream-sandwich--jelly-bean)

2. framework.-res.apk was pathced (into "res/values/arrays.xml" added `<item>com.google.android.gms</item>`)

P.S.: With the latest microG the Uber on my another device on Android 6.0 works perfectly.

![jguo6rhykyy](https://user-images.githubusercontent.com/29664443/27506455-3ec6cca4-58c0-11e7-9592-4aee8a83e8d0.jpg)
![nshyesn7z2e](https://user-images.githubusercontent.com/29664443/27506456-3ed7c04a-58c0-11e7-8542-740ddd897d57.jpg)
![1wentoew028](https://user-images.githubusercontent.com/29664443/27506454-3ea51334-58c0-11e7-9e84-bd258aac265f.jpg)

**Comment by ar-lex** [comment]
Have you tried to install DroidGuard? It has fixed crashes of Uber for me (Moto X Play XT1562 with LineageOS 14.1, Android 7.1.2).

**Comment by sam-kzn** [comment]
Yes, I've install the "DroidGuard Helper" but I've not activate the "SafetyNet" option.
On my another device with Android 6.0 the "Uber" with "MicroG" works perfect.

**Comment by ale5000-git** [comment]
Maybe there is a conflict with another location provider.
My [installer](microG unofficial installer) setup everything automatically, maybe it fix your problem.

**Comment by sam-kzn** [comment]
Thank You!
I'll try it.
After I'll write the result at the topic.

**Comment by ale5000-git** [comment]
This should already be fixed, if there are other problems please open a new ticket.
