### ISSUE TITLE
Grouped points on map in Veturilo

### ISSUE THREAD

**Issue by etam** [microg/GmsCore#403]
In Veturilo (com.nextbike.veturilo) there is an option to show bike stations on the map.

It starts by showing the whole world map with points grouped into a single point with a "328" number on it.

When zooming in it should split the points, but it does not. No matter how I zoom in it always shows a "328" point.

I'm using microG 0.2.4-103-gd9e86d9.

**Comment by conrad-heimbold** [comment]
Are you sure this is an issue of microg, and not com.nextbike.veturilo's fault?

**Comment by etam** [comment]
How am I supposed to know?

On a device with google maps and services it works fine. On a device with microg it works as I described. So I think it's a problem with microg, but I don't have necessary skills to tell for sure.

**Comment by etam** [comment]
It looks like it's working now.
