### ISSUE TITLE
Which Port is required? ( Firewall )

### ISSUE THREAD

**Issue by natackx** [microg/GmsCore#408]
In my wifi the status of GCM is "not connected". As soon as i switch to mobile network it's connecting.
My suggestion is that the issue is my firewall which is only excepting very few ports.
Which port is required? Is there no fallback to a common port? (like 443)

EDIT: It seems to be the port 5228

**Comment by Catfriend1** [comment]
Tcp 5228

**Comment by utack** [comment]
How hard would it be to add the 443 fallback?  
I am in university network all day, and it cannot connect on the default ports

**Comment by ale5000-git** [comment]
GCM connect to the Google servers, I'm not sure they will accept that port.
If this is the case perhaps you could request the feature to Google (regarding the official Google Play Services), then after it is implemented in Google Play Services it won't be difficutl to do the same for microG.

**Comment by utack** [comment]
@ale5000-git according to some references I found on the internet they use it as fallback, and telnet connects just fine, so the port is open

**Comment by ale5000-git** [comment]
It is obvious that the port is open since it is the default HTTPS port but it doesn't mean it can use GCM on that port but I'm not 100% sure.
Post the references please.

**Comment by utack** [comment]
https://developers.google.com/cloud-messaging/http  
you might be right, google does not mention 443  
443 was mentioned [here](https://github.com/google/gcm/issues/110) and [here](https://stackoverflow.com/questions/23732611/google-cloud-messaging-not-working-on-4-1-2-devices-on-a-corporate-network/23784874#23784874)  
Can I just compile microG with 443, and replace my apk and try it, or does it need a certain signature to work?

**Comment by ale5000-git** [comment]
From the link the port 433 is from a different server android.googleapis.com and android.client.google.com instead of mtalk.google.com, so changing only the port isn't enough.

@mar-v-in: microG spoof signature so any signature is fine as long as you remove the old file with the signature from mar-v-in and place you own file (I'm not sure if the setting are kept or lost with this change).

**Comment by matttbe** [comment]
Hello,

First, thank you for developing and maintaining this great project!

I recently used a guest network where the "non usual ports" were blocked.

Apparently, also ports 5229 and 5230 in addition to the 5228 one can be used by FCM:

> If your organization has a firewall to restrict traffic to or from the Internet, you need to configure it to allow mobile devices to connect with FCM in order for devices on your network to receive messages. FCM typically uses port 5228, but it sometimes uses 443, 5229, and 5230.

Src: https://firebase.google.com/docs/cloud-messaging/concept-options#messaging-ports-and-your-firewall

Maybe with the recent work done by @grote in #1605, implementing a fallback to another port would be easier?

I guess the idea is to loop over different ports in the `connect()` function?

https://github.com/grote/GmsCore/blob/a830b5dd5de71fa53f9d037c210a81fb38ea3321/play-services-core/src/main/java/org/microg/gms/gcm/McsService.java#L427-L455

**Comment by matttbe** [comment]
Thank you for the confirmation!

Do you know why there are so many ports for the same protocol?
Would it be to ease testing of "experimental" version? In this case, other 52xx port would be using another version and a percentage of the users would be randomly picked to use this new backend to validate everything is OK?

For MicroG, I guess it would be "safer" to first try on port 5228, then 433, then eventually the other ones. Maybe not 5223 if it is not publicly documented?

**Comment by mar-v-in** [comment]
The protocol starts in its first byte with the version number (0x29 currently), so the port number certainly does not encode the protocol version, but may did this in the past.

5222 and 5223 are the ports originally used back in the days when they used standard XMPP (5222 is for XMPP with STARTTLS and 5223 is for XMPP with Direct TLS). All the other port numbers have probably been derived from that numbers and they probably used 5224-5227 as well at some point but deprovisioned them.

I guess we should go for first use 5228 and fallback to 443. Fallback to the other ports is probably not needed, I doubt any firewall blocks port 5228 but not 5229.
