### ISSUE TITLE
Android Pay support?

### ISSUE THREAD

**Issue by youcanaddthenameofyourorganizationlater** [microg/GmsCore#437]
Is there Android Pay support?
My payment app just shows "Sorry, something went wrong."

I would really like to see this..

**Comment by ShapeShifter499** [comment]
This is a duplicate of a issue in opened. Can you comment on that one to show support?  I already added money to BountySource for that issue.   https://github.com/microg/android_packages_apps_GmsCore/issues/361

**Comment by ShapeShifter499** [comment]
#361 duplicate. I hope this can be added one day.

**Comment by rugk** [comment]
This issue can be closed, as it is a duplicate.

**Comment by ale5000-git** [comment]
As laready said, duplicate of #361
