### ISSUE TITLE
UI crash on Zenfone phones (5.x)

### ISSUE THREAD

**Issue by sonickles9** [microg/GmsCore#463]
GmsCore crashes when selecting an item in the app's main screen. Reported to happen in Asus Zenfone lollipop stock ROMs

logcat of the crash: https://pastebin.com/cMWp6pY3

**Comment by ale5000-git** [comment]
@sonickles9: Have you tried [microG GmsCore](https://microg.org/download.html) version 0.2.4-**111**?

**Comment by sonickles9** [comment]
@ale5000-git Yes I did, the issue persists. Want me to attach a new logcat for you?

**Comment by sonickles9** [comment]
Bump? The issue persists even in the newest release. On 0.2.4 stable this issue doesn't happen due to the old UI. But downgrading isn't the best choice...

**Comment by sonickles9** [comment]
Bumping again, 0.2.6 didn't solve the issue, and the error is the same: 
E/AndroidRuntime(28627): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/org.microg.gms.ui.SelfCheckFragment$AsActivity}: android.view.InflateException: Binary XML file line #24: Error inflating class org.microg.tools.ui.SwitchBar

will attach a full logcat soon

**Comment by sonickles9** [comment]
full log of the error: https://pastebin.com/iMdVEqn8

**Comment by emv412** [comment]
Pull requests were made here - https://github.com/microg/android_external_MicroGUiTools/pulls
But I don't know if they will be included in the main repository

**Comment by ElDavoo** [comment]
This is a duplicate of #267 , please close
