### ISSUE TITLE
GCM is disconnected over longer period of time

### ISSUE THREAD

**Issue by devdan** [microg/GmsCore#490]
Sometimes, GCM is disconnected over longer period of time. If I manually reconnect GCM, it will work again. I cannot find anyhing in logcat. I'm using microg edition of Lineage OS on klte.

Is it possible to add some kind of warning if GCM is disconnected. Maybe you could show a notification if GCM is disconnected for longer than some minutes but a working network connection is available.

**Comment by firstamendment** [comment]
I used to have an issue like this - have you tried the push notification fixer from the play store? It will decrease the heartbeat interval so you won't be disconnected. You do need root though.

**Comment by godoftech** [comment]
Possible workaround:
https://github.com/microg/android_packages_apps_GmsCore/issues/631#issuecomment-429013399

**Comment by ale5000-git** [comment]
The problem should be fixed in recent versions of microG GmsCore, please try it and report back.

**Comment by ale5000-git** [comment]
Everything should already be fixed on the latest version so I close it for now.
Open a new issue if needed.
