### ISSUE TITLE
Google Cloud Messaging

### ISSUE THREAD

**Issue by sxml** [microg/GmsCore#571]
Android 7.0 ROM miui9 root

I just want to use the Google Cloud Messaging feature. Implement the googole push. Other Google stores, maps, don't need it.

Google Cloud Messaging
Need to install Xposed FakeGApps?
Need Signature Spoofing?

@ale5000-git @Jesse-V @xenithorb @Marvin W

**Comment by hockeymikey** [comment]
Yes, you need signature spoofing for gcm.

**Comment by sxml** [comment]
@hockeymikey 
No patches, why are some apps available for registration?
Wechat can't register?

Microg, I only need
Google Cloud Messaging GCM feature.
Odex ROM is very troublesome.
How to operate can not require patches, use gcm.

**Comment by hockeymikey** [comment]
Check the checklist in the app.  You need signature spoofing so maybe it doesn't have that.  All apps need to be installed AFTER microg is installed in order to register.

Either use FakeGApps or patch with say Tingle.

**Comment by godoftech** [comment]
Possible workaround:
https://github.com/microg/android_packages_apps_GmsCore/issues/631#issuecomment-429013399

**Comment by ale5000-git** [comment]
@sxml: Have you been able to fix your problems?

**Comment by sxml** [comment]
@ale5000-git I can only accept patches

**Comment by ale5000-git** [comment]
I'm closing it since it is old and unclear if it is fixed.
If still needed with latest microG GmsCore please open another issue.
