### ISSUE TITLE
SumUp: No location found

### ISSUE THREAD

**Issue by andyboeh** [microg/GmsCore#612]
I'm trying to use SumUp (a mobile card payment system using a bluetooth-connected card reader) with microg where I ran into problems: SumUp always reports "No location found. Please ensure your GPS or location services are enabled and functioning".

Permission for location requests was granted, this is what I get in the log when I try to start a payment (it's always these three lines):

```
D/SafeParcel( 2773): Unknown field num 3 in com.google.android.gms.location.LocationSettingsRequest, skipping.
D/GmsLocManagerSvcImpl( 2773): requestLocationSettingsDialog: com.google.android.gms.location.LocationSettingsRequest@48b4ac5
W/EventBus( 7512): Subscriber to unregister was not registered before: class com.sumup.merchant.controllers.PinPlusSetupController
```

Any ideas?

**Comment by chris42** [comment]
If you open microg and go to self check. What is the status of the last 4 checkmarks?

**Comment by andyboeh** [comment]
The Self-Check reports everything as checked, I should have noted that earlier, sorry.

**Comment by badgeek** [comment]
i have the same issue with MySleekr HR apps and Gojek 

Unknown field num 3 in com.google.android.gms.location.LocationSettingsRequest, skipping.

**Comment by crushv** [comment]
Same issue applies to com.tinder

**Comment by nebulade** [comment]
I got the same `SafeParcel: Unknown field num 3 in com.google.android.gms.location.LocationSettingsRequest, skipping.` for the emmy scooter app. Other apps work well for location and map display.

The last 4 status checkmarks are ticked. I am using the Mozilla location nlp backend and Nominatim for address lookup.

**Comment by miracoli** [comment]
Same issue for Polar Beat and Jodel

**Comment by dylangerdaly** [comment]
https://github.com/microg/GmsCore/pull/1484

Fixes this issue

**Comment by andyboeh** [comment]
Thanks @dylangerdaly, SumUp seems to work properly now!
