### ISSUE TITLE
crash on displaying MapFragment

### ISSUE THREAD

**Issue by thrillfall** [microg/GmsCore#618]
On LineageOS 15.1 the latest release (v3.15) of **de.numer26.android** crashes when one wants to create a cash26 request. 
To reproduce this error: In the main screen -> press **+**  symbol  -> select "CASH26" -> CRASH

The exception trace:
`09-25 10:38:45.232 21298 21298 E AndroidRuntime: Process: de.number26.android, PID: 21298
09-25 10:38:45.232 21298 21298 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at de.number26.machete.android.ui.map.MapFragment.e(MapFragment.java:118)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at de.number26.machete.android.ui.map.MapFragment.onMapReady(MapFragment.java:227)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at de.number26.machete.android.ui.cash26.Cash26Fragment.onMapReady(Cash26Fragment.java:226)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at com.google.android.gms.maps.zzac.zza(Unknown Source:7)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at com.google.android.gms.maps.internal.zzaq.onTransact(Unknown Source:38)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:627)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IOnMapReadyCallback$Stub$Proxy.onMapReady(IOnMapReadyCallback.java:79)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at org.microg.gms.maps.MapViewImpl$1.run(MapViewImpl.java:117)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
09-25 10:38:45.232 21298 21298 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**"workaround"**: if one revokes the "location" permission for the app the CASH26 request does not crash. The recurring popup (asking for location permission) can be declined.

If someone could point out which implementation is missing or needs extension i'd gladly try to fix it. But alone from the stacktrace i cannot deduct the missing parts

**Comment by ale5000-git** [comment]
@thrillfall

Is it fixed?

**Comment by thrillfall** [comment]
No. It still crashes

**Comment by ale5000-git** [comment]
@thrillfall
So is it fixed now?

**Comment by thrillfall** [comment]
Yes
