### ISSUE TITLE
Custom backup provider / Android backup service replacement?

### ISSUE THREAD

**Issue by codethief** [microg/GmsCore#640]
I know this is probably out of scope for GmsCore and it rather belongs on a wishlist but would it be feasible to develop a replacement for the Android backup service? I find it somewhat insane that this part of stock Android is not open-source and people can't choose custom backup backends. For instance, I'd love to backup all my apps and settings to my NextCloud instance or, alternatively, store the backup on my SD card in an encrypted fashion (where the SD card is automatically backed up to my server using Syncthing).

(Edit: What I'd imagine is basically that such a custom backend provider would expose the backup API to other apps and other apps such as NextCloud could then register as actual "backup provider" – provided the user gives them the permission to do so.)

**Comment by stevesoltys** [comment]
@codethief you can check out my application if you're interested. It implements a custom `BackupTransport`. However, needs to be compiled with AOSP since it uses internal APIs.

https://github.com/stevesoltys/backup

**Comment by ale5000-git** [comment]
@stevesoltys: Does it work if it isn't compiled with AOSP but installed inside `/system/priv-app`?

**Comment by stevesoltys** [comment]
@ale5000-git In theory yes - but I assume it might not work if your AOSP build has modified internal classes that it references.

This would include any changes across different versions of AOSP. For instance, there were changes made to the internal backup APIs from Nougat -> Oreo, and I assume there are some from Oreo -> Pie as well.

**Comment by ale5000-git** [comment]
@stevesoltys: The code could simply detect the feature (API in this case) and use the one present or also use "try, catch" until a one working is found.

**Comment by Lanchon** [comment]
its not that simple, javac will not compile the code because the entry points in the libraries dont exist at compile time.

but you can use reflection to find the alternative methods and when one is found, invoke it.

actually for best performance you can use the method handle api instead of reflection. and you can define different adapter method handles for different android versions, so you end up with one method handle that cross invokes to different android versions. done correctly, this is as fast and optimizable as regular java calls. on the other hand, the reflection api is slow as hell, but compatible with older VMs.

**Comment by codethief** [comment]
@stevesoltys This looks very neat, thank you! I'd be really interested in trying this out – would you mind adding instructions on how to get this running?

**Comment by stevesoltys** [comment]
@codethief I've merged in support for standalone builds and written some installation instructions here: https://github.com/stevesoltys/backup/wiki/Using-with-an-existing-AOSP-installation

**Comment by rugk** [comment]
BTW, if you come later to this issue, first have a look on **how it works**:
https://twitter.com/t_grote/status/1175070283247628291
https://twitter.com/t_grote/status/1174022555612647426

IMHO this would be an **awesome** addition to microG! 


As the app basically replaces _Google's cloud backup_ and the aim of this project/microG is to replace all built-in Google apps with free ones, IMHO, this fits into this project very well.

**Comment by rugk** [comment]
Now the technical thing. 

@stevesoltys The wiki site you've mentioned above has been deleted, as it seems. What happened?

**Comment by stevesoltys** [comment]
@rugk standalone builds are no longer possible, which @grote explains here: https://github.com/stevesoltys/backup/issues/8#issuecomment-515891338.

You need to compile the application with the operating system in the latest versions of Android, and we don't want to support backporting the application to previous versions of AOSP, as explained here: https://github.com/stevesoltys/backup/issues/8#issuecomment-516104869.

**Comment by rugk** [comment]
Okay, thanks, so it needs to be argued to possibly get this built-in into cutom ROMs.

**Comment by ArchangeGabriel** [comment]
SeedVault evolved a lot since then, and is now being integrated in LineageOS or crDroid to name a few. I think this can be closed now. ;)
