### ISSUE TITLE
Impossible to display Uber map

### ISSUE THREAD

**Issue by Freeedim** [microg/GmsCore#685]
Hi, I have been using microg since more than one year now, and it has never been possible to use Uber since the map does not display properly (Mozilla Nlp, Superman ROM based on Nougat on Samsung S7)

**Comment by oldosfan** [comment]
Mapbox resolves this

**Comment by Freeedim** [comment]
How?

**Comment by Freeedim** [comment]
OK, I guess mapbox is a new map backend. Indeed, after having updated my Uber app, it seems that the map finally works well.

**Comment by Freeedim** [comment]
Nope

**Comment by oldosfan** [comment]
It's a new version of microG that you can download from the releases section

**Comment by Freeedim** [comment]
The last version I can see is 0.2.7.17455, which I already have installed (through F-Droid). And it does not solve any thing regarding Uber map.

**Comment by ale5000-git** [comment]
@Freeedim There are 2 variant of 0.2.7.17455, have you tried both?

**Comment by Freeedim** [comment]
Nope. I just updated the app through F-Droid. Are you saying that if I download the apk from the git repository, it will be a different variant that will solve the Uber issue?

**Comment by ale5000-git** [comment]
If you look in the F-Droid app there is at the bottom of the app the possibility to select a version of the app and there there are 2 different variants of 0.2.7.17455

**Comment by Freeedim** [comment]
Yep, both are marked as recommended AND installed. So that I can't tap the mapbox version to be installed.

**Comment by ale5000-git** [comment]
It is a bug that both are displayed as installed but only one of them is installed and also the other version list "Mapbox Maps SDK for Android" in the list of libraries so noone of these things can tell you what version is installed.

**Comment by Freeedim** [comment]
Wow! Good to know. So I cannot know which version I have installed. For some reason, F-Droid fails to downgrade (so that I would re-upgrade to the right Mapbox version). I guess I am going to go on having a life without Uber...

**Comment by ale5000-git** [comment]
Try to update directly with apk files from here: https://github.com/microg/android_packages_apps_GmsCore/releases/latest

Try both and please report if one of them works.

**Comment by Freeedim** [comment]
Yeah, sorry that was pretty obvious but I was confused while doing too many things at the same time. So I did it and yay! had my first Uber course (after having had the app on my phone for 2 years)! Thanks a lot for your support and patience!

**Comment by oldosfan** [comment]
Congrats on becoming a Uber driver

**Comment by benwaffle** [comment]
You can check what version you have by going to `microG settings` > `About microG Services Core`

**Comment by Freeedim** [comment]
As mentioned previously, I already did it, but there are two variants of this last version that have exactly the save version number, and are thus impossible to differentiate.

**Comment by ale5000-git** [comment]
Close as already fixed.
