### ISSUE TITLE
whatsapp doesn't work

### ISSUE THREAD

**Issue by benoitldr** [microg/GmsCore#695]
Hello,
Above all, thanks you for your work, it's been a while that's I want to stop using opengapps (even pido mode).
I've install a fresh version of lineageos 15.1-20181107-UNOFFICIAL-athene on my moto G4 plus (athene)

Unfortunately whatsapp doesn't work and when I try to launch it (after registration), I have this error : 
> WhatsApp will not working with the google play services which is not compatible with your phone

I've activated registrating, google cloud messaging et google safetynet in microg settings.

Is anyone have this issue also ?

Thanks you,

**Comment by Nanolx** [comment]
You need to have either Play Store or Fake Store installed.

The message regarding Play Services is misleading, as it usually refers to Play Store aswell.

Despite security aspects WA fully works with microG.

**Comment by ale5000-git** [comment]
This should be already fixed, if there other other issues please open a new ticket.
