### ISSUE TITLE
Is it possible to use microg and Google Play Services at the same time?

### ISSUE THREAD

**Issue by ghost** [microg/GmsCore#701]
As a workaround for all of the bugs, it would be nice to be able to switch microG for official Google Play Services if I want to open Lyft/Uber, and then switch back to microG when I'm done.

**Comment by ale5000-git** [comment]
It isn't possible in general since microG have to use the same internal name to be able to be seen by apps.

It may be possible with a Magisk module, but this isn't directly related to microG.
