### ISSUE TITLE
Firebase Phone Auth and Google SignIn Not working

### ISSUE THREAD

**Issue by z3r0c00l-2k** [microg/GmsCore#756]
I am getting the following  logs for Phone Number Auth
> D/AutoManageHelper: starting AutoManage for client 0 false null
D/AutoManageHelper: onStart true {0=com.google.android.gms.common.api.internal.zaj$zaa@30bfafa}
E/GmsClient: unable to connect to service: com.google.android.gms.auth.api.signin.service.START on com.google.android.gms
D/AutoManageHelper: beginFailureResolution for ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
W/AutoManageHelper: Unresolved error while connecting client. Stopping auto-manage.
W/BiChannelGoogleApi: [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzam@3

And For Google Account Auth

> W/AutoManageHelper: Unresolved error while connecting client. Stopping auto-manage.
W/AuthSignInClient: Could not launch sign in Intent. Google Play Service is probably being updated...
W/LOGIN: Google sign in failed
    com.google.android.gms.common.api.ApiException: 17: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source)
        at in.ouon.travelpa.LoginActivity.onActivityResult(LoginActivity.kt:248)
        at android.app.Activity.dispatchActivityResult(Activity.java:6991)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4137)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4184)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1563)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by VictorYezhov** [comment]
The Same thing. Can`t understand what is going on

**Comment by z3r0c00l-2k** [comment]
Any way to fix this issue???

**Comment by oscfdezdz** [comment]
Same thing, on latest stable and beta.

**Comment by MrDodojo** [comment]
Might be because the latest chrome breaks the login in microG as it system app replaces the built in webview? @mar-v-in (it's like that for the Vanced Microg)

**Comment by ale5000-git** [comment]
New version released today, please try if the problem still persist.

**Comment by z3r0c00l-2k** [comment]
Yeah Sure...

**Comment by z3r0c00l-2k** [comment]
It still not working

**Comment by Zorvalt** [comment]
Hi, is there any update on this, please ?

**Comment by Romern** [comment]
Someone would have to implement FirebaseAuth, as well as the google gms ``device_key`` which is needed for generating a header (X-Goog-Spatula), which relies on Droidguard. I looked into it, but I did not get DroidGuard to work. Some resources I've collected: https://gist.github.com/Romern/e58e634e4d70b2be5b57d7abdb77f7ef

**Comment by mar-v-in** [comment]
Firebase Phone Auth is implemented as of c3bfb63f27c116d21ba7b2b87629e36573d4a59e. Google Auth is not yet available for Firebase Auth in microG.

**Comment by pigmonkey** [comment]
I'm running CalyxOS 3.5.1 on a Pixel 4a which reports microG Services Core version 0.2.24.214816-25 (fb20f8b). Here's the logcat which results when hitting the "Log in with Google" button in [Dialpad](https://play.google.com/store/apps/details?id=co.switchapp&gl=US):

```
05-12 14:07:34.109  1835  2550 I ActivityTaskManager: START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=co.switchapp cmp=co.switchapp/com.google.android.gms.auth.api.signin.internal.SignInHubActivity (has extras)} from uid 10219
05-12 14:07:34.141 27876 27876 D ClearcutLoggerService: onBind: Intent { act=com.google.android.gms.clearcut.service.START pkg=com.google.android.gms }
05-12 14:07:34.147 27876 27890 D ClearcutLoggerService: bound by: GetServiceRequest{serviceId=CLEARCUT_LOGGER, gmsVersion=221706000, packageName='com.google.android.apps.maps', extras=Bundle[{}]}
05-12 14:07:34.150 27876 27890 D SafeParcel: Unknown field id 12 in com.google.android.gms.clearcut.LogEventParcelable, skipping.
05-12 14:07:34.162 27322 27322 I FIAM.Display: Unbinding from activity: com.dialpad.login.presentation.view.LoginActivity
05-12 14:07:34.162 27322 27322 I FIAM.Headless: Removing display event component
05-12 14:07:34.168  1835  2550 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (75241190)
05-12 14:07:34.182 27876 27890 D MeasurementService: bound by: GetServiceRequest{serviceId=MEASUREMENT, gmsVersion=12451000, packageName='co.switchapp', extras=Bundle[{}]}
05-12 14:07:34.185  1835  2943 I ActivityTaskManager: START u0 {act=com.google.android.gms.auth.GOOGLE_SIGN_IN pkg=com.google.android.gms (has extras)} from uid 10219
05-12 14:07:34.186 27322 27322 W AuthSignInClient: Could not launch sign in Intent. Google Play Service is probably being updated...
05-12 14:07:34.219 27322 27322 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10219; state: DISABLED
05-12 14:07:34.226 27876 27890 D MeasurementService: f1(com.google.android.gms.measurement.internal.EventParcel@f6f1897) for AppMetadata[co.switchapp]
05-12 14:07:34.226 27876 28007 D MeasurementService: f10(0, null, null, co.switchapp)
05-12 14:07:34.228 27322 27322 I FIAM.Display: Binding to activity: com.dialpad.login.presentation.view.LoginActivity
05-12 14:07:34.228 27322 27322 I FIAM.Headless: Setting display event component
05-12 14:07:34.234  1835 19409 W InputManager-JNI: Input channel object '6d5b1fd co.switchapp/com.dialpad.login.presentation.view.LoginActivity (client)' was disposed without first being removed with the input manager!
05-12 14:07:34.249 27876 27890 D MeasurementService: f10(685774102508753908, null, LoginActivity, co.switchapp)
05-12 14:07:34.251 27876 27876 D GmsDummySvc: onBind: Intent { act=com.google.android.gms.auth.api.signin.service.START pkg=com.google.android.gms }
05-12 14:07:34.255 27876 28007 D ChimeraServiceProvider: serviceIntentCall: com.google.android.gms.auth.api.identity.service.signin.START -> Intent { act=com.google.android.gms.auth.api.identity.service.signin.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.DummyService }
05-12 14:07:34.260  1835  2092 V WindowManager: Unknown focus tokens, dropping reportFocusChanged
05-12 14:07:34.262 27876 27876 D GmsDummySvc: onBind: Intent { act=com.google.android.gms.auth.api.identity.service.signin.START pkg=com.google.android.gms cmp=com.google.android.gms/org.microg.gms.DummyService }
05-12 14:07:34.287 27876 28007 D GmsDummySvc: bound by: GetServiceRequest{serviceId=AUTH_SIGN_IN, gmsVersion=12451000, packageName='co.switchapp', extras=Bundle[{}]}
05-12 14:07:34.294 27876 28007 D GmsDummySvc: bound by: GetServiceRequest{serviceId=IDENTITY_SIGN_IN, gmsVersion=12451000, packageName='co.switchapp', extras=Bundle[{session_id=YlBa1qHkRfwv4UNsB2NlTw}]}
05-12 14:07:34.334 27876 28007 D MeasurementService: f1(com.google.android.gms.measurement.internal.EventParcel@ac6026d) for AppMetadata[co.switchapp]
```

**Comment by realsarm** [comment]
```
07-03 15:53:54.614  5657  5839 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
07-03 15:53:54.616  5657  5987 I FirebasePerformance: HTTP Method is null or invalid: <com.google.android.gms.internal.firebase-perf.zzcv$zzb@c70b6ac number=0 name=HTTP_METHOD_UNKNOWN>
07-03 15:53:54.616  5657  5987 W FirebasePerformance: Unable to process the PerfMetric due to missing or invalid values. See earlier log statements for additional information on the specific missing/invalid values.
07-03 15:53:54.679  5657  5715 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
07-03 15:53:54.682   243   256 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.clearcut.service.START pkg=com.google.android.gms } U=0: not found
07-03 15:53:54.683   243   256 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@3d850b7
07-03 15:53:54.683  5657  5843 E GmsClient: unable to connect to service: com.google.android.gms.clearcut.service.START on com.google.android.gms
07-03 15:53:54.954  5657  5715 W FirebaseRemoteConfig: No value of type 'FirebaseRemoteConfigValue' exists for parameter key 'fpr_session_max_duration_min'.
07-03 15:53:54.958   243   256 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.clearcut.service.START pkg=com.google.android.gms } U=0: not found
07-03 15:53:54.958   243   256 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@3c5024
07-03 15:53:54.959  5657  5843 E GmsClient: unable to connect to service: com.google.android.gms.clearcut.service.START on com.google.android.gms
```
Using latest microG

**Comment by ale5000-git** [comment]
Could you please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and then post a new logcat?

**Comment by girlwithnoname** [comment]
> Could you please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and then post a new logcat?

Not the OP but I stumbled upon the same issue that I can't sign in to my Google account with microg. Installed your linked nightly build and it works now. Thank you!

**Comment by ale5000-git** [comment]
For all:
It should work with the latest code (not release yet); for those that want to try there is the build compiled and signed by me: https://github.com/micro5k/microg-unofficial-installer/blob/main/zip-content/origin/priv-app/GmsCore-ale5000.apk

Since it is a different signature you can't just update but you have to remove the previous version.

**Comment by Mrugacz** [comment]
Similar issue here while running mBank

Device: Pixel 5
OS: CalyxOS 4.13.3 
microG: 0.2.29.233013-49 (1a2e94c) 

Log:
```
09-28 17:46:00.420  4025  4025 I PlayCore: UID: [10173]  PID: [4025] AppUpdateService : requestUpdateInfo(pl.mbank)
09-28 17:46:00.420  4025  4618 I PlayCore: UID: [10173]  PID: [4025] AppUpdateService : Initiate binding to the service.
09-28 17:46:00.425  4025  4618 I PlayCore: UID: [10173]  PID: [4025] AppUpdateService : Failed to bind to the service.
09-28 17:46:10.344  1893  1973 W WindowManager: Failed looking up window session=Session{af03926 4025:u0a10173} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6050 com.android.server.wm.Session.updateRequestedVisibilities:701 android.view.IWindowSession$Stub.onTransact:1075 
09-28 17:47:08.818  4025  4025 I PlayCore: UID: [10173]  PID: [4025] AppUpdateService : requestUpdateInfo(pl.mbank)
09-28 17:47:08.818  4025  4618 I PlayCore: UID: [10173]  PID: [4025] AppUpdateService : Initiate binding to the service.
09-28 17:47:08.819  4025  4618 I PlayCore: UID: [10173]  PID: [4025] AppUpdateService : Failed to bind to the service.
09-28 17:47:20.347  1893  2662 W WindowManager: Failed looking up window session=Session{af03926 4025:u0a10173} callers=com.android.server.wm.WindowManagerService.windowForClientLocked:6050 com.android.server.wm.Session.updateRequestedVisibilities:701 android.view.IWindowSession$Stub.onTransact:1075 
```

**Comment by YtvwlD** [comment]
Ingress with Google login works for me since Calyx 4.13.3

**Comment by ale5000-git** [comment]
@Mrugacz
The issue of this ticket was with: `com.google.android.gms.auth.api.signin.service.START`
Anything else is a different issue.
Please open a new ticket
