### ISSUE TITLE
Chromecast not working

### ISSUE THREAD

**Issue by Eerovil** [microg/GmsCore#818]
Cast icon does not appear. Using chromecast ultra. 

Custom built using latest nanolx-new. 

```	06-05 21:32:52.062 D/GmsChimeraSpoof(3286): query: content://com.google.android.gms.chimera/api_force_staging/com.google.android.gms.cast.framework.dynamite
06-05 21:32:52.063 W/DynamiteModule(10121): Failed to retrieve remote module version.
06-05 21:32:52.077 W/DynamiteModule(10121): IDynamite loader version < 2, falling back to getModuleVersion2
06-05 21:32:52.077 D/GmsDynamiteLoaderImpl(10121): returning temp fix module version for com.google.android.gms.cast.framework.dynamite. Cast API wil not be functional!
06-05 21:32:52.078 I/DynamiteModule(10121): Considering local module com.google.android.gms.cast.framework.dynamite:0 and remote module com.google.android.gms.cast.framework.dynamite:1
06-05 21:32:52.078 I/DynamiteModule(10121): Selected remote version of com.google.android.gms.cast.framework.dynamite, version >= 1
06-05 21:32:52.078 W/DynamiteModule(10121): Dynamite loader version < 2, falling back to createModuleContext
06-05 21:32:52.078 D/GmsDynamiteLoaderImpl(10121): unimplemented Method: createModuleContext for com.google.android.gms.cast.framework.dynamite at version 1, returning gms context
06-05 21:32:52.084 D/SafeParcel(10121): Unknown field num 6 in com.google.android.gms.cast.framework.media.CastMediaOptions, skipping.
06-05 21:32:52.085 D/SafeParcel(10121): Unknown field num 10 in com.google.android.gms.cast.framework.CastOptions, skipping.
06-05 21:32:52.098 D/SessionManagerImpl(10121): unimplemented Method: removeCastStateListener
06-05 21:32:52.098 D/SessionManagerImpl(10121): unimplemented Method: addCastStateListener
06-05 21:32:52.099 D/SessionManagerImpl(10121): unimplemented Method: addSessionManagerListener
06-05 21:32:52.109 D/GmsCastDeviceControllerSvc(3286): onBind: Intent { act=com.google.android.gms.cast.service.BIND_CAST_DEVICE_CONTROLLER_SERVICE pkg=com.google.android.gms }
06-05 21:32:52.186 D/GmsMeasureSvcImpl(3286): onTransact [unknown]: 1, android.os.Parcel@ed27361, 16
06-05 21:32:52.186 D/GmsMeasureSvcImpl(3286): onTransact [unknown]: 10, android.os.Parcel@2e47200, 16```

**Comment by Eerovil** [comment]
Update: This is app-specific. Plex app works with chromecast just fine.

**Comment by armills** [comment]
What app is it?

**Comment by Eerovil** [comment]
Oh, sorry. I've tried CMore and Yle Areena. These probably don't work without an account (and areena outside Finland).

Perhaps the issue is related the the one with Netflix?

**Comment by mnair69** [comment]
Netflix app shows the cast icon but clicking on it does not work. At the same time Chromecast cast issue was fixed and works perfectly with the latest fix.

**Comment by Emgalai** [comment]
@Eerovil Yle Areena does not require an account for Chromecast use.

**Comment by Emgalai** [comment]
I am not seeing Chromecast icon either. I did see it when I installed _LineageOS for microG_, and casting to Chromecast worked, but something made the icon disappear.

**Comment by calvinbui** [comment]
Samsung Galaxy S10+ on Pie with microg 0.28

Not working:
YouTube
Pocket Casts
Oculus

Working:
Plex
VLC

**Comment by sbaconnais** [comment]
Same here. I can see the icon but can't cast.

**Comment by SakiiCode** [comment]
YouTube works, but you have to manually connect to your TV in the settings

**Comment by 0xlne** [comment]
Native screen mirroring not working on Samsung Galaxy Note 10+/Android 10, microg v0.2.11.202414
It works after replacing microg with bitgapps, thus suggesting the cast API implementation as the issue.

**Comment by gjimenezf** [comment]
Using YouTube Vanced on Samsung S8 android 9, chromecast device is listed but when I try to cast it doesn't connect and got a message saying Google play services needs to be updated but I am using latest stable version 21.15.15.
On normal YouTube Chromecast works well
Microg version 0.2.18.210500
YouTube Vanced 16.16.38

**Comment by ale5000-git** [comment]
Cast is currently not working but I'm closing this ticket in favor of #580
