### ISSUE TITLE
[WORKAROUND] GCM apps won't register [microG v0.2.7.17455]

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [microg/GmsCore#822]
EDIT: Dialing
`*#*#2432546#*#*`
fixed the issue. Still this seems like a bug to me.

Dear @mar-v-in,

unfortunately Telegram won't register for GCM. The service is disconected, too. Rebooting the system does not help. Everything else looks good.

Cheers,
cRaZy

**Comment by oldosfan** [comment]
Google discontinued GCM and replaced it with FCM. If you're using an outdated version of Telegram then it may not yet support FCM; try updating Telegram.

If the issue persists, please grab a logcat and upload it here. The maintainers won't be able to tell what's wrong without at least a partial logcat.

**Comment by voidstarstar** [comment]
This is a known issue.

See https://github.com/microg/android_packages_apps_GmsCore/issues/439#issuecomment-433018720 and [the last bullet point here](https://github.com/microg/android_packages_apps_GmsCore/wiki/Helpful-Information).

**Comment by ale5000-git** [comment]
This should be fixed from a lot of time; if you still have problems please update microG to the latest version and open a new ticket.
