### ISSUE TITLE
Fix Bountysource integration

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#838]
It worked in the past but something got messed up, please fix it.
Manually editing the title of all issues once a bounty is added is a bit annoying.

Ref: https://github.com/bountysource/core/issues/1387

**Comment by voidstarstar** [comment]
Is it possible that a setting was mistakenly unchecked?
https://webapps.stackexchange.com/a/84868

**Comment by ale5000-git** [comment]
@mar-v-in: Could you please check if all settings are checked?

**Comment by ale5000-git** [comment]
@mar-v-in: Please go [here](https://www.bountysource.com/tools) and if it show "You must reauthorize your GitHub account to continue" then click on Re-Authorize.

**Comment by mar-v-in** [comment]
There was a checkbox to "lock" the update. I unchecked that one and now that checkbox is gone. Maybe that helps.

**Comment by ale5000-git** [comment]
The problem seems fixed, thanks.

**Comment by ale5000-git** [comment]
Apparently, it hasn't worked again [here](https://github.com/microg/android_packages_apps_GmsCore/issues/4).

**Comment by wertzuz** [comment]
https://docs.polar.sh/issue-funding could be a useful replacement

**Comment by ale5000-git** [comment]
This ticket is very old, please open a new ticket for suggestons.
