### ISSUE TITLE
Uber - cannot login using Google

### ISSUE THREAD

**Issue by JCGoran** [microg/GmsCore#878]
I am unable to login to the Uber app (version `4.269.10004`) using a Google account.
When I click on the "Google" option, it reports "Oops! Looks as if something went wrong.", while the Facebook option properly redirects to a login screen.
I'm on LineageOS 16.0 with microG on the OnePlus 5 (downloaded from [here](https://download.lineage.microg.org/cheeseburger/), version `lineage-16.0-20190701-microG-cheeseburger`).
microG services core is version `0.2.7.17455-mapbox`, and the self check reports everything except "Battery optimization ignored" and "Geocoder provides address resolution from location" as a pass.
Logcat is as follows:
```
07-08 00:25:20.878 15805 15967 W DynamiteModule: Local module descriptor class for providerinstaller not found.
07-08 00:25:20.878 15805 15967 W DynamiteModule: IDynamite loader version < 2, falling back to getModuleVersion2
07-08 00:25:20.879 15805 15967 D GmsDynamiteLoaderImpl: unimplemented Method: getModuleVersion for providerinstaller
07-08 00:25:20.879 15805 15967 I DynamiteModule: Considering local module providerinstaller:0 and remote module providerinstaller:0
07-08 00:25:20.879 15805 15967 W ProviderInstaller: Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
07-08 00:25:20.881 15805 15967 D GmsProviderInstaller: Provider installer invoked for com.ubercab
07-08 00:25:20.882 15805 15967 E ProviderInstaller: Failed to install provider: dlopen failed: "/system/priv-app/GmsCore/GmsCore.apk!/lib/arm64-v8a/libconscrypt_jni.so" is 64-bit instead of 32-bit
07-08 00:25:21.281 15805 15935 E GmsClient: unable to connect to service: com.google.android.gms.auth.api.signin.service.START on com.google.android.gms
```
Is related to issue #844?

**Comment by voidstarstar** [comment]
Possibly related to #867, but for a different instruction set.

**Comment by ale5000-git** [comment]
@JCGoran: Could you please updat to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry?

**Comment by JCGoran** [comment]
> @JCGoran: Could you please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry?

Installed the build, but even after reinstalling the Uber app and restarting the phone, it doesn't seem to work, logcat again reports:
```
07-08 10:10:09.463  5987  6093 E GmsClient: unable to connect to service: com.google.android.gms.auth.api.signin.service.START on com.google.android.gms
```
Is there anything that I must manually enable to use this service?

**Comment by voidstarstar** [comment]
> Is there anything that I must manually enable to use this service?

The sign in API is not yet implemented in microG.  Related to #410, #756, #497, #850, #179.

Not a fix, but as a workaround, some users have suggested to use m.uber.com in the meantime.

**Comment by ale5000-git** [comment]
It should be fixed with the latest microG GmsCore, if not please open another ticket.
