### ISSUE TITLE
Thank you very much for your hard work! <3

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [microg/GmsCore#883]
Dear @mar-v-in,

thank you very much for all the work you have done and all the time you afforded to make MicroG better. It's some kind of commitment that makes the world a better place by a little bit.

Just because you dedicated so much of your life time in this good project we're able to socialize without leaking all our private data to big companies beyond good and evil.

Your recent mapbox version with the Maps API bump works VERY WELL! For example "StadtRad Hamburg" which had glitches on the map works perfect now, is very responsive and reliable.

Have a good day & please keep up the good work!
cRaZy

**Comment by be-neth** [comment]
Yes ! thanks a lot @mar-v-in and all the other contributors !

**Comment by tobru** [comment]
I want to express my thanks here as well! It's absolutely fantastic to see MicroG evolving and having @mar-v-in taking care! THANK YOU VERY MUCH!
