### ISSUE TITLE
Wallapop Google sign in

### ISSUE THREAD

**Issue by ZJaume** [microg/GmsCore#888]
Can't sign in with google (existing account) to wallapop. On 0.2.6 it was working.

All checks passed and device registration is enabled. Also google account working on google music.

Migrog version: 0.2.8.1778-mapbox
Android version: Lineage Microg 16.0 (Android 9.0)
Log: https://pastebin.com/nXpvg4DS

**Comment by ale5000-git** [comment]
This is one of the problem fixed after the release.
Please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry.

**Comment by ZJaume** [comment]
Thank you, but I'll wait to f-droid or LOS update.

**Comment by ale5000-git** [comment]
It is a nightly build, it will never appears on F-Droid.
For F-Droid release you will have to wait 0.2.9 that will probably take a lot.

**Comment by ZJaume** [comment]
Ok, I have tried it but still npt logued in. Also when try two tomes in a row, microg crashes

**Comment by ale5000-git** [comment]
Please post a new logcat with the latest build.

**Comment by jslawler** [comment]
> Please update to [this build](https://microg.org/dl/GmsCore-v0.2.8.17785-4-06c8b76.apk) and retry.

Some added info on this one.
Wallapop does work with a Google login on 1778 and 17785 on my device (OnePlus 6/OmniROM).
It appears this is an isolated issue somewhat.

@ZJaume 
Checking out your logs I see that Wallapop is a WebView application, this can be the cause for a lot of crashes on microG on some systems when using Bromite it seems.

This issue was picked up on Nanolx's NanoDroid readme. I take no credit for this if it fixes it.

See [Applications crash when using WebView (BromiteWebView package)](https://github.com/Nanolx/NanoDroid/#other) for more information.

**Comment by ZJaume** [comment]
@ale5000-git here you have: https://pastebin.com/YFZXZHHL

**Comment by TheElf01** [comment]
Hi! any solution to this problem? wallapop still cant login using microg

thanks!

**Comment by catfluoride** [comment]
I have the same issue. Which was also reported by a Reddit user:

https://old.reddit.com/r/MicroG/comments/uo220m/problem_with_inapp_recaptcha/

Relevant logs:

https://pastebin.com/5kajmWNg

**Comment by d-vs** [comment]
I'm unable to sign into Wallapop after registering via my Google account. I choose my Google account, it redirects to the page, asks me again to sign in, I click the button it verifies the account, then starts back from square one again! In effect, the site is unusable.

**Comment by ZJaume** [comment]
Email login was also broken and with the latest version is working now. I no longer have a Google account, so cannot check. Closing, as it is solved for me.

**Comment by catfluoride** [comment]
> Email login was also broken and with the latest version is working now. I no longer have a Google account, so cannot check. Closing, as it is solved for me.

I hate to say that, but login with email still isn't working for me. Microg installed using 

https://github.com/nift4/microg_installer_revived

and updated using official microG apk on top of it.
