### ISSUE TITLE
SafetyNet attestation: not yet available

### ISSUE THREAD

**Issue by moritztk** [microg/GmsCore#968]
How can I try the safetynet attestation? It's always greyed out for me and says "not yet available".
Running Lineage16+MicroG on a Nexus 6.

**Comment by Nanolx** [comment]
The test is not implemented, as stated. If you use Magisk, Magisk Manager can check, else use a tool like [SafetyNet Test](https://play.google.com/store/apps/details?id=org.freeandroidtools.safetynettest&hl=en_IN).

Anyway, SafetyNet attestation is known not to work currently:

https://github.com/microg/android_packages_apps_RemoteDroidGuard/issues/24

**Comment by ale5000-git** [comment]
Latest microG GmsCore pass SafetyNet.
