### ISSUE TITLE
Uber and Yandex Taxi crashes

### ISSUE THREAD

**Issue by jpransxdev** [microg/GmsCore#987]
Uber crashes at launch after signing in. Yandex taxi shows map but crashes when i want to log in. Bolt doesn't even install I think because safetynet woes... So basically switching back to gapps because none of the taxi apps work.

ROM is havoc 3.0, android 10.

[logcat.txt](https://github.com/microg/android_packages_apps_GmsCore/files/3940899/logcat.txt)

**Comment by kolya-ay** [comment]
Can confirm. Neither yandex.taxi neither uber work for me (official microg-linageos 16). I have to workaround it using web versions. However this is way not that convenient.

**Comment by selurvedu** [comment]
Regarding Uber, see https://github.com/microg/android_packages_apps_GmsCore/issues/994#issuecomment-579020011

**Comment by ale5000-git** [comment]
Could some of you please update microG GmsCore and tell me if it is fixed?

**Comment by ildar** [comment]
Yandex Taxi works great, tested on AOSP 6, Android 7(LA) and AOSP 12.

**Comment by ale5000-git** [comment]
@jpransxdev
It should be fixed with the latest microG GmsCore, if not please open another ticket.

**Comment by ildar** [comment]
+ someone plz fix the wiki page
