### ISSUE TITLE
New Uber update crashes.

### ISSUE THREAD

**Issue by arch-btw** [microg/GmsCore#994]
**Uber version:** 4.293.10003
**Lineage MicroG:** lineage-16.0-20191206-microG-x2.zip
**Android Model:** https://wiki.lineageos.org/devices/x2

> 12-20 00:24:35.395 18990 18990 E AndroidRuntime: FATAL EXCEPTION: main
12-20 00:24:35.395 18990 18990 E AndroidRuntime: Process: com.ubercab, PID: 18990
12-20 00:24:35.395 18990 18990 E AndroidRuntime: io.reactivex.exceptions.OnErrorNotImplementedException: Inferred subscribe point: njo.a(:266247)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at com.ubercab.rx2.java.stackelementtagging.TaggingObserver.onError(:237862)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.a(:139675)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.e(:139693)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(:139750)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.android.schedulers.AsyncHandlerScheduler$ScheduledRunnable.run(:256443)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6718)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
12-20 00:24:35.395 18990 18990 E AndroidRuntime: Caused by: com.mapbox.mapboxsdk.q.a: Map interactions should happen on the UI thread. Method invoked from wrong thread is latLngForPixel.
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.NativeMapView.f(Unknown Source:53)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.NativeMapView.a(Unknown Source:2)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at com.mapbox.mapboxsdk.maps.w.a(Unknown Source:2)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at org.microg.gms.maps.mapbox.ProjectionImpl.fromScreenLocation(Unknown Source:17)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at com.google.android.gms.maps.internal.IProjectionDelegate$Stub.onTransact(Unknown Source:97)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at android.os.Binder.transact(Binder.java:667)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at cpi.a(:240256)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at dit.a(:241556)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at dia.a(:241444)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at hha.fromScreenLocation(:123834)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at njf.a(:266044)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at njf.a(:266053)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at -$$Lambda$njf$XnEnBj5IX9rzICBwhj9mHA7tGgE8.apply(Unknown Source:44)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.internal.operators.flowable.FlowableMap$MapSubscriber.onNext(:132778)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.g(:132997)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(:132843)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.internal.schedulers.ScheduledRunnable.run(:144310)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at io.reactivex.internal.schedulers.ScheduledRunnable.call(:144293)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at -$$Lambda$gvh$WntKdu3NGlhy_S71wZzZG1W9lzY.run(Unknown Source:7)
12-20 00:24:35.395 18990 18990 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)

**Comment by hamiltonrn** [comment]
Uber and Uber Eats crashes.

**Comment by anonimou0** [comment]
What was the latest version that worked?

So I can download on aurora?

**Comment by anonimou0** [comment]
Uber seems to be working again on latest update.

**Comment by Torvin** [comment]
@anonimou0 it still doesn't work for me. which version works for you? I tried `4.293.10007`

**Comment by anonimou0** [comment]
`4.298.10006.61012`

**Comment by selurvedu** [comment]
@anonimou0 @Torvin I can confirm it works, thanks for letting us know!

**Comment by Torvin** [comment]
@anonimou0 thanks... I can't yet see this version in Aurora though

**Comment by selurvedu** [comment]
@Torvin I updated via Aurora.

**Comment by selurvedu** [comment]
>  I can't yet see this version in Aurora though

@Torvin
I decided to check and now I see that currently the suggested version is `4.293.10007.60964`. When I updated last time it was `4.298.10006.61012`, so current version number is lower than the one I installed.

You can try this:

1) Open Uber in Aurora Store
2) Select "Manual download" from the menu in the upper right corner
3) Enter version code `61012`

I was able to download the right version this way a few minutes ago.

**Comment by paulolieuthier** [comment]
> version code `61012`

Confirmed, thanks!

**Comment by Torvin** [comment]
@selurvedu thanks, I know about this trick, but the last time I tried it - it failed with "corrupted apk" error. I tried it again today and it worked, so thank you!

**Comment by selurvedu** [comment]
@mar-v-in I think this ticket can be closed. Uber has been working fine ever since they released version >= `4.298.10006.61012`.

BTW, since I didn't find a more relevant issue:
Thanks to your commit https://github.com/microg/GmsCore/commit/9ef9f29940fa93c0447df582c625c604fe55cfb6 the payment options screen is finally working again (THANK YOU!!!), so instead of going to their website, logging in via SMS and going through a few screens to change the active option I can just simply _tap twice_. You saved me a lot of nerves. :sweat_smile:
